### PR TITLE
Pin pnpm@7 in CI

### PR DESCRIPTION
**Pull request by pan3793**
## Purpose of the pull request

This PR pins pnpm@7 in CI since the recent published pnpm 8.x is not compatible w/ existing lockfile.

```
added 1 package, and audited 2 packages in 722ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
 ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the version of the lockfile is incompatible with this version of pnpm

Try either:
1. Aligning the version of pnpm that generated the lockfile with the version that installs from it, or
2. Migrating the lockfile so that it is compatible with the newer version of pnpm, or
3. Using "pnpm install --no-frozen-lockfile".
Note that in CI environments, this setting is enabled by default.
```

## Brief change log

Pin pnpm@7 in CI

## Verify this pull request

Recover broken frontend CI

### CODE REVIEW

**Comment by pan3793** [comment]
kindly ping @SbloodyS

**Review by kezhenxu94 — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by SbloodyS** [comment]
dead-link check failed. PTAL @zhongjiajie

**Comment by zhongjiajie** [comment]
It seem is a true deadline here in https://github.com/apache/dolphinscheduler/blob/4e2701b57ef55c93f1f14f348e96a2f7c5fd2177/docs/docs/en/guide/alert/slack.md#L29-L28

**Pull request merged**
