### PR TITLE
[Bug-8067][LogServer] LoggerRequestProcessor incorrect word and improper use of StringBuilder

### LINKED ISSUE #8067: [Bug][LogServer] LoggerRequestProcessor incorrect word and improper use of StringBuilder
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Describe the question:** 

`org.apache.dolphinscheduler.server.log.LoggerRequestProcessor#process`

on line 72, it  has Dangling Javadoc comment and misspelling the word request
```java
/**
 * reuqest task log command type
 */
```
Replace with the following
```java
//request task log command type
```
on line 97, string concatenation as argument to 'StringBuilder.append()' call
```java
for (String line : lines) {
    builder.append(line + "\r\n");
}
```
Replace with the following
```java
for (String line : lines) {
    builder.append(line).append("\r\n");
}
```
on line 109, type status can be primitive
```java
Boolean status = true;
```
Replace with the following
```java
boolean status = true;
```

`org.apache.dolphinscheduler.server.log.LoggerRequestProcessor#getFileContentBytes`

on line 131, misspelling the word download, and `@throws Exception` is redundant
```java
/**
 * get files content bytes，for down load file
 *
 * @param filePath file path
 * @return byte array of file
 * @throws Exception exception
 */
```
Replace with the following
```java
/**
 * get files content bytes for download file
 *
 * @param filePath file path
 * @return byte array of file
 */
```

### What you expected to happen

Obvious code exception

### How to reproduce

In the latest dev branch
module: dolphinscheduler-log-server
class: org.apache.dolphinscheduler.server.log.LoggerRequestProcessor

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hongshuboy**
fix improper use of StringBuilder
fix code format and fix spelling errors
close #8067

## Purpose of the pull request

LoggerRequestProcessor incorrect word and improper use of StringBuilder

## Brief change log

fix improper use of StringBuilder
fix code format and fix spelling errors

## Verify this pull request

This pull request is already covered by existing tests, such as *(org.apache.dolphinscheduler.server.log.LoggerRequestProcessorTest)*.

### CODE REVIEW

**Comment by hongshuboy** [comment]
https://github.com/apache/dolphinscheduler/issues/8067

**Comment by yimaixinchen** [comment]
LGTM

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhuangchong** [comment]
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by hongshuboy** [comment]
@zhuangchong thank you very much, i really need a deeper understanding for dolphinscheduler

**Pull request merged**
