### PR TITLE
[ci] Fix flaky test in e2e user

### LINKED ISSUE #7656: [Bug] [ci] CI is unstable and will random failure
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

CI is unstable and will fail @zhongjiajie 

### What you expected to happen

It may be a configuration problem

### How to reproduce

Submit code to request detection when merging

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
Close: #7656

### CODE REVIEW

**Comment by zhongjiajie** [comment]
commit 7f62cf4 test E2E success one time in https://github.com/apache/dolphinscheduler/actions/runs/1661991386/attempts/1

**Comment by zhongjiajie** [comment]
> E2E success one time in [7f62cf4](https://github.com/apache/dolphinscheduler/commit/7f62cf4af6fb00400f16c08efb3d91b57a85fd20)

Success the second times

**Comment by zhongjiajie** [comment]
> commit [7f62cf4](https://github.com/apache/dolphinscheduler/commit/7f62cf4af6fb00400f16c08efb3d91b57a85fd20) test E2E success one time in https://github.com/apache/dolphinscheduler/actions/runs/1661991386/attempts/1

Success the second time in https://github.com/apache/dolphinscheduler/actions/runs/1661991386/attempts/2

**Comment by zhongjiajie** [comment]
> > commit [7f62cf4](https://github.com/apache/dolphinscheduler/commit/7f62cf4af6fb00400f16c08efb3d91b57a85fd20) test E2E success one time in https://github.com/apache/dolphinscheduler/actions/runs/1661991386/attempts/1
> 
> Success the second time in https://github.com/apache/dolphinscheduler/actions/runs/1661991386/attempts/2

The third time in https://github.com/apache/dolphinscheduler/actions/runs/1661991386/attempts/3

**Comment by zhongjiajie** [comment]
image
Why mergeable sometime remove label what I just add?

**Comment by zhongjiajie** [comment]
05eda56 Success in https://github.com/apache/dolphinscheduler/actions/runs/1662242264/attempts/1

**Comment by zhongjiajie** [comment]
> [05eda56](https://github.com/apache/dolphinscheduler/commit/05eda5633a0272429883bcd32b781dc02411d07b) Success in https://github.com/apache/dolphinscheduler/actions/runs/1662242264/attempts/1

Success in https://github.com/apache/dolphinscheduler/actions/runs/1662242264/attempts/2

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
