### PR TITLE
[Improvement][ApiServer]Task defination list paging sorted by updateTime not effect

### LINKED ISSUE #12621: [Improvement] [ApiServer] Task defination list paging sorted by updateTime not effect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

List task defination and sorted  by update time not effect

### What you expected to happen

List task defination and sorted by update time

### How to reproduce

List task defination and look

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tracehh**
fix #12621 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Please resolve the conflicts.

**Comment by tracehh** [comment]
>

**Comment by tracehh** [comment]
> Please resolve the conflicts.

**Comment by tracehh** [comment]
> Please resolve the conflicts.

resolved，please review again，thanks very much @ruanwenjun

**Review by ruanwenjun — APPROVED** [review]

**Pull request merged**
