### PR TITLE
[Feature][Authenticator] Add OAuth2 authenticator 

### LINKED ISSUE #11242: [Feature][Authenticator] Support OAuth as an authenticator
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* `OAuth` is widely used for WEB authentication without explicit password. 
* We could support `OAuth` as an authenticator in Dolphin Scheduler.
* More about `OAuth`, see: https://en.wikipedia.org/wiki/OAuth

### Use case

* Already described above.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Still WIP, just a draft, a few things need to be fixed.

* This PR closes: #11242 

## Brief change log

* Add OAuth2 authenticator 

## Verify this pull request

* WIP

### CODE REVIEW

**Comment by EricGao888** [comment]
Hello, I'm trying to add a new authenticator for DS to support OAuth2.0. Currently I'm blocked by some kind of cookie missing issue. After calling `http://localhost:12345/dolphinscheduler/testlogin/google`, I get successfully redirected to google login page and completedthe OAuth process. I could see the `sessionId` in browser.
image
However, if I try to visit `http://localhost:12345/dolphinscheduler/ui/projects`, the `sessionId` is missing and I get blocked by `LoginHandlerInterceptor`. I'm wondering whether it is caused by the wrong path or some other stuff related to cookie since I haven't implemented the front-end part of `/testlogin/google`

So I have two questions:

1. Am I supposed to handle the cookie path in front-end part so that the cookie added by back-end could be sent to /ui/**?
2. Since Spring Boot has its default interceptor for OAuth2.0, should I disabled `ds LoginHandlerInterceptor` when using OAuth2.0?

https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-ui/src/views/login/index.tsx#L35-L52

Related information:

After authentication, ds will put `sessionId` into cookies and check the `sessionId` in `preHandle` method of `LoginHandlerInterceptor`, as shown below:
https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java#L82-L100

https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LoginHandlerInterceptor.java#L69-L74

As we could see in `LoginController`, the url for login is `/login` and will be mapped to `/ui/login` https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java#L83

But in my test code, I added a new url for login which is `/testlogin/google` without front-end. And it could not be mapped to `/ui/testlogin/google`.
image

@kezhenxu94 @devosend Could u plz help take a look when available? Thanks!

**Comment by EricGao888** [comment]
> Hello, I'm trying to add a new authenticator for DS to support OAuth2.0. Currently I'm blocked by some kind of cookie missing issue. After calling `http://localhost:12345/dolphinscheduler/testlogin/google`, I get successfully redirected to google login page and completedthe OAuth process. I could see the `sessionId` in browser. image However, if I try to visit `http://localhost:12345/dolphinscheduler/ui/projects`, the `sessionId` is missing and I get blocked by `LoginHandlerInterceptor`. I'm wondering whether it is caused by the wrong path or some other stuff related to cookie since I haven't implemented the front-end part of `/testlogin/google`
> 
> So I have two questions:
> 
> 1. Am I supposed to handle the cookie path in front-end part so that the cookie added by back-end could be sent to /ui/**?
> 2. Since Spring Boot has its default interceptor for OAuth2.0, should I disabled `ds LoginHandlerInterceptor` when using OAuth2.0?
> 
> https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-ui/src/views/login/index.tsx#L35-L52
> 
> Related information:
> 
> After authentication, ds will put `sessionId` into cookies and check the `sessionId` in `preHandle` method of `LoginHandlerInterceptor`, as shown below:
> 
> https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java#L82-L100
> 
> https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LoginHandlerInterceptor.java#L69-L74
> 
> As we could see in `LoginController`, the url for login is `/login` and will be mapped to `/ui/login`
> 
> https://github.com/apache/dolphinscheduler/blob/53340fc07b1e7b6d5f76aeb015fc36eb661e4a32/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java#L83
> 
> But in my test code, I added a new url for login which is `/testlogin/google` without front-end. And it could not be mapped to `/ui/testlogin/google`. image
> 
> @kezhenxu94 @devosend Could u plz help take a look when available? Thanks!

Problems solved, thanks for the help : )

**Comment by EricGao888** [comment]
@songjianet @devosend @Amy0104 Currently we have some logic in front-end `handleLogin` like calling `getUserInfo()`. Once we support `OAuth2` login, user will no more get redirected to Username / Password login page, this `handlLogin` will not get triggered and that causes some issues, such as users cannot create projects. May I ask whether there are solutions to this? 

image

https://github.com/apache/dolphinscheduler/blob/7d0e2cbbb9fcd2e1543f5166f0518eda03afae89/dolphinscheduler-ui/src/views/login/use-login.ts#L35-L44

**Comment by devosend** [comment]
> @songjianet @devosend @Amy0104 Currently we have some logic in front-end `handleLogin` like calling `getUserInfo()`. Once we support `OAuth2` login, user will no more get redirected to Username / Password login page, this `handlLogin` will not get triggered and that causes some issues, such as users cannot create projects. May I ask whether there are solutions to this?
> 
> image
> 
> https://github.com/apache/dolphinscheduler/blob/7d0e2cbbb9fcd2e1543f5166f0518eda03afae89/dolphinscheduler-ui/src/views/login/use-login.ts#L35-L44



> @songjianet @devosend @Amy0104 Currently we have some logic in front-end `handleLogin` like calling `getUserInfo()`. Once we support `OAuth2` login, user will no more get redirected to Username / Password login page, this `handlLogin` will not get triggered and that causes some issues, such as users cannot create projects. May I ask whether there are solutions to this?
> 
> image
> 
> https://github.com/apache/dolphinscheduler/blob/7d0e2cbbb9fcd2e1543f5166f0518eda03afae89/dolphinscheduler-ui/src/views/login/use-login.ts#L35-L44

You can add a new blank page on the front end to call `getUserInfo`.

**Comment by EricGao888** [comment]
@Abingcbc Since the credentials differentiate a lot from LDAP / PASSWORD when integrated with OAuth2.0, we may abstract `AbstractLoginCredentials` to keep things unified like the way in this draft PR. WDYT?

**Comment by EricGao888** [comment]
Considering @Abingcbc has been working on integrating DS with `OAuth2.0` since March 5th, I think a better choice is to follow up with #8706 and help it get merged. Therefore, I'm closing this PR temporarily. If there are more things to do after #8706 merged, I will reopen this PR. Thanks : )

**Pull request closed without merging**
