### PR TITLE
[Feature-14421][K8S Task] Configurable image pull policy

### LINKED ISSUE #14421: [Feature][K8S Task] Configurable image pull policy
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, image pull policy is `Always` and can not be changed.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- This PR closes https://github.com/apache/dolphinscheduler/issues/14421

## Brief change log
- Support to select image pull policy from `IfNotPresent`, `Always`, `Never`.

## Verify this pull request
image

### CODE REVIEW

**Review by qingwli — COMMENTED** [review]
We have defined `Always` and `Never` in here:
https://github.com/apache/dolphinscheduler/blob/f186cd5dab609ff5adbbe0d8b9088b69a273ab67/dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java#L482-L483

Can we add a new constant `IfNotPresent` here and return a select list from API replace defined this in the UI module?

**Comment by Radeity** [comment]
> Can we add a new constant IfNotPresent here and return a select list from API replace defined this in the UI module?

Hi, @qingwli , thanks for your comment. I think image pull policies are relative static options, and it's still possible that user define a k8s task with wrong image pull policy by openAPI. In addition, we have already defined many option list in front-end codes, maybe for simplicity. Thus, considering interaction through UI page, do we have to make this change?

**Review by rickchengx — APPROVED** [review]
LGTM

**Comment by Radeity** [comment]
Hi, @qingwli , do you have any other suggestions?

**Comment by qingwli** [comment]
I agree with you @Radeity

**Pull request merged**
