### PR TITLE
[Feature-#3805][server-master] Task parameter transfer

### LINKED ISSUE #3805: [Feature][DICUSSION] The implement of passing variables between tasks
Discussion on the implement of passing variables between tasks

There are three possible solutions :

1. make global variables customizable, used to pass variables between tasks

2. increase the local variables in the taskflow. Someone has already implemented it, but it has not been merged. #3659

3. The first task is output to a specified path, and then the content in this path is read in the second step;The log is uniformly output to the standard error, the result of the task is output to the standard output, and the second task directly obtains the standard output content of the first task. @rockxsj 

----

关于Task之间的变量传递特性的讨论

目前有如下三个可能的方案

1. 将全局变量改为可自定义，用来传递Task之间的变量
2. 增加工作流内部的局部变量， @guyinyou 已经实现了，但是还未合并，具体实现细节见 #3659
3. @rockxsj  提出的方案：第一个task的输出指定输出到一个路径，然后第二步读取这个路径里面的内容；日志统一输出到标准错误，task的结果输出到标准输出，第二个task直接获取第一个task的标准输出内容。 

大家可以直接留言选出你觉得好的方案，如果有其他实现方案也欢迎交流

### PR DESCRIPTION
**Pull request by wangxj3**
[Feature-#3805][server-master] global params for task of sub_process
The function of global params has three parts,This part is the last one for task of sub_process.
The subprocess node passes in variables, and the subprocess can receive params values
About subprocess node: judge whether there is parameter passing when generating subprocess command. If there is parameter passing, the parameter will be written into the command table.When master read one command ,master will check command params .If there are params of fatherParams ,master will set the params to processInstance globalParams.
[bug-#5085][server-master] if global Param of out is a number, throw format exception
make the of all out param to String

this closes #3805 , #5085

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by luojieio** [comment]
为什么我用最新的1.3.8的发行版本也没有这个功能？请问题如何使用这个功能，万分感谢？实在找不到相关文档了。急
我是使用K8s的方式部署的

---
Why is this feature not available when I use the latest 1.3.8 release version?  how to use this function, thanks a lot? I can't find the relevant documents. urgent，
my deployment is base k8s
---

**Comment by luojieio** [comment]
image

**Comment by wangxj3** [comment]
> 
> 
> 为什么我用最新的1.3.8的发行版本也没有这个功能？请问题如何使用这个功能，万分感谢？实在找不到相关文档了。急
> 我是使用K8s的方式部署的
> ## Why is this feature not available when I use the latest 1.3.8 release version? how to use this function, thanks a lot? I can't find the relevant documents. urgent，
> my deployment is base k8s

This function execit in dev ,and the doc link is this one.
https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/globalParams.html

**Pull request merged**
