### PR TITLE
when use list as out property in sql tasks, if sql result has only one row, still wrap result in a list

### PR DESCRIPTION
**Pull request by HouSong**
## Purpose of the pull request

when use list as out property in sql tasks, if sql result has only one row, there will be an exception. 
In this PR, when use list as out property in sql tasks, if sql result has only one row, this result will be wrapped in a list; if sql result has no row, use property value as default and wrap it in a list (if property value exists) .

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — CHANGES_REQUESTED** [review]
Please change your target branch to `dev` and link this PR to your issue.

**Comment by HouSong** [comment]
> Please change your target branch to `dev` and link this PR to your issue.

I haven't created an issue for this PR. Is it required?

**Comment by ruanwenjun** [comment]
Please rebase latest dev.

**Comment by wangxj3** [comment]
There seems to be some conflict, please pull the upstream dev code.

**Pull request closed without merging**
