### PR TITLE
[Improvement-16552] Directly use Quartz replase api to bootstrap a schedule

### LINKED ISSUE #16552: [Improvement][Quartz] Optimize the scheduler code in quartz plugin, use quartz replace API to insert/update trigger and job.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Optimize the scheduler code in quartz plugin, use quartz replace API to insert/update trigger and job.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

Optimize the scheduler code in quartz plugin, use quartz replace API to insert/update trigger and job.

close #16552

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by qingwli** [comment]
It's ok to remove lock when build job details and schedule?

**Comment by ruanwenjun** [comment]
> It's ok to remove lock when build job details and schedule?

We don't need to use lock here, and quartz will use db lock when dealing with job/trigger.

**Review by qingwli — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
