### PR TITLE
[BUG] Fix positive integer judgment

### PR DESCRIPTION
**Pull request by jxeditor**
## Purpose of the pull request

Fix  positive integer judgment

## Brief change log

Repair regular matching rules

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by jxeditor — COMMENTED** [review]
Now there's no problem with the regularity

**Review by jxeditor — COMMENTED** [review]
1

**Comment by jxeditor** [comment]
@caishunfeng 
@zhuangchong

**Comment by zhuangchong** [comment]
Is there a related issue?

**Comment by jxeditor** [comment]
> Is there a related issue?

image
There is no way to select 0 when using the dataX plug-in.

In my opinion, regular expressions are wrong.
image

**Comment by jxeditor** [comment]
Although I don't quite understand why selectors need regular matching,this should not be necessary,we cannot modify it manually.

@zhuangchong

**Comment by zhuangchong** [comment]
@songjianet 
please help review, and whether next-ui needs to be modified.

**Comment by songjianet** [comment]
> @songjianet please help review, and whether next-ui needs to be modified.

In fact, there are many places in the old and new UI that have not been verified for positive integers, but if they are used normally, there will be basically no problems. Since time is relatively short, I plan to put this on the subsequent optimization and uniformly handle this in the project. problem, but will only be dealt with in the new UI

**Pull request closed without merging**
