### PR TITLE
[Fix] Fix k8sTaskExecutionContext setting configYaml

### LINKED ISSUE #15114: [Bug] K8sTaskExecutionContext incorrectly set configYaml
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```java

private KubernetesClient getClient(KubernetesApplicationManagerContext kubernetesApplicationManagerContext) {
        K8sTaskExecutionContext k8sTaskExecutionContext =
                kubernetesApplicationManagerContext.getK8sTaskExecutionContext();
        k8sTaskExecutionContext
                .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
        return cacheClientMap.computeIfAbsent(kubernetesApplicationManagerContext.getLabelValue(),
                key -> new KubernetesClientBuilder()
                        .withConfig(Config.fromKubeconfig(k8sTaskExecutionContext.getConfigYaml())).build());
    }
```

```java
 k8sTaskExecutionContext
                .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
```

We can not directly change this. For normal task, like `spark` on k8s, `k8sTaskExecutionContext` is constructed by `TaskExecutionContextFactory`, when they call `getClient`, `connectionParams` is `null`.

### What you expected to happen

set configYaml during K8S task initialization

### How to reproduce

run `spark` task

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xdu-chenrj**
close https://github.com/apache/dolphinscheduler/issues/15114
Fix k8sTask ExecutionContext setting configYaml

### CODE REVIEW

**Comment by xdu-chenrj** [comment]
I fixed this issue using other methods, but there may be other issues. Please review :D

**Comment by Radeity** [comment]
Hi @xdu-chenrj , I don't understand how you fix it. Actually, there's nothing wrong with K8S task, but for Spark on K8S, `k8sTaskExecutionContext.getConnectionParams()` is null. 

In addition, for other types of task which use `K8sTaskExecutionContext`, like `Kubeflow`, you should better replace the current way to declare the Kubernetes cluster with your connection center.

**Comment by xdu-chenrj** [comment]
> Hi @xdu-chenrj , I don't understand how you fix it. Actually, there's nothing wrong with K8S task, but for Spark on K8S, k8sTaskExecutionContext.getConnectionParams() is null.
> 
> In addition, for other types of task which use K8sTaskExecutionContext, like Kubeflow, you should better replace the current way to declare the Kubernetes cluster with your connection center.

I will use the Spark task to further correct my fix

**Comment by Radeity** [comment]
> I will use the Spark task to further correct my fix

I thought you mainly fix it in this PR, and why `setting configYaml` is relevant to the bug description in issue?

**Comment by xdu-chenrj** [comment]
> > I will use the Spark task to further correct my fix
> 
> I thought you mainly fix it in this PR, and why `setting configYaml` is relevant to the bug description in issue?



we need to fix all tasks that use the k8s namespace, such as the Spark task. i didn't get what you meant before. i just looked at some parameters required to create the Spark task. the namespace selected for the previous spark task was created in the cluster management of the security center. now, the Spark task needs to select the k8s connection created in the connection center. we need to refactor other tasks that use the k8s namespace, just like we refactor the k8s task, what do you think?

**Comment by Radeity** [comment]
> we need to fix all tasks that use the k8s namespace, such as the Spark task. i didn't get what you meant before. i just looked at some parameters required to create the Spark task. the namespace selected for the previous spark task was created in the cluster management of the security center. now, the Spark task needs to select the k8s connection created in the connection center. we need to refactor other tasks that use the k8s namespace, just like we refactor the k8s task, what do you think?

For Spark on K8S, `connectionParams` in `k8sTaskExecutionContext` is null, cuz `k8sTaskExecutionContext` is constructed in Master, and don't set any value during construction which will cause NPE.
```java
k8sTaskExecutionContext
                .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
```

**Comment by xdu-chenrj** [comment]
> > we need to fix all tasks that use the k8s namespace, such as the Spark task. i didn't get what you meant before. i just looked at some parameters required to create the Spark task. the namespace selected for the previous spark task was created in the cluster management of the security center. now, the Spark task needs to select the k8s connection created in the connection center. we need to refactor other tasks that use the k8s namespace, just like we refactor the k8s task, what do you think?
> 
> For Spark on K8S, `connectionParams` in `k8sTaskExecutionContext` is null, cuz `k8sTaskExecutionContext` is constructed in Master, and don't set any value during construction which will cause NPE.
> 
> ```java
> k8sTaskExecutionContext
>                 .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
> ```

I have made this modification to the current code

**Comment by Radeity** [comment]
> I have made this modification to the current code

I'm still confused, you should modify this part to avoid NPE
```java
k8sTaskExecutionContext
                .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
```

**OR**
 
replace original way to use K8S cluster in other tasks(Spark, KUBEFLOW) with your connection way.

In current PR, I don't get how you solve the problem.

**Comment by xdu-chenrj** [comment]
> > I have made this modification to the current code
> 
> I'm still confused, you should modify this part to avoid NPE
> 
> ```java
> k8sTaskExecutionContext
>                 .setConfigYaml(JSONUtils.getNodeString(k8sTaskExecutionContext.getConnectionParams(), "kubeConfig"));
> ```
> 
> **OR**
> 
> replace original way to use K8S cluster in other tasks(Spark, KUBEFLOW) with your connection way.
> 
> In current PR, I don't get how you solve the problem.

I think the current solution to this problem can only be achieved by adding special judgments until the Spark and Kubelow tasks are refactored

**Review by Radeity — DISMISSED** [review]
LGTM

**Comment by Radeity** [comment]
Please run `mvn spotless:apply`.

**Comment by xdu-chenrj** [comment]
> Please run `mvn spotless:apply`.

sorry

**Review by Radeity — APPROVED** [review]

**Pull request merged**
