### PR TITLE
[Feature][worker]Implement worker server independent  of the database

### LINKED ISSUE #9283: [Feature][worker] make workers completely independent of the database
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

IMO, the worker server is independent of the database.
ATM is dependent.
Besides TaskPluginManager, are there any other functions that depend on the database?
If the specific task is not dependent, the changes will not be too much.

### Use case

make workers completely independent of the database

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huagetai**
## Purpose of the pull request

Implement worker server completely independent of the database

## Brief changelog

- move the following from dolphinscheduler-service to dolphinscheduler-server
  - org.dolphinscheduler.service.alert.AlertClientService
  - org.dolphinscheduler.service.alert.AlertClientServiceTest
  - org.dolphinscheduler.service.bean.*
  - org.dolphinscheduler.service.exceptions.*
  - org.dolphinscheduler.service.log.*
  - org.dolphinscheduler.service.registry.*
- adjust pom.xml of dolphinscheduler-service
  - add dolphinscheduler-server dependency
- adjust pom.xml of dolphinscheduler-server
  - add dolphinscheduler-registry-zookeeper dependency
  - add dolphinscheduler-remote dependency
- adjust the code of dolphinscheduler-worker
  - copy org.dolphinscheduler.service.task.TaskPluginManager from dolphinscheduler-service and remove AlertDao related code
  - adjust the TaskPluginManager related code
  - exclude datasource autoconfiguration
  - remove daos of TaskCallbackServiceTestConfig
- adjust pom.xml of dolphinscheduler-worker
  - remove dolphinscheduler-service dependency
  - extents  dolphinscheduler-service dependency

This close #9283 #9292
## Verify this pull request

This pull request is already covered by existing tests
  - *org.dolphinscheduler.service.alert.AlertClientServiceTest*
  - *org.dolphinscheduler.service.log.LogClientServiceTest*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by zhuangchong** [comment]
please check ui test.

**Comment by SbloodyS** [comment]
Please check ut failed and e2e failed.

**Comment by zhongjiajie** [comment]
FYI @huagetai E2E still failed

**Comment by kezhenxu94** [comment]
@huagetai hi, i'd really like to see this PR gets merged, are you going to continue the work to make CI passed?

**Comment by ruanwenjun** [comment]
@huagetai Are there any progress?

**Comment by caishunfeng** [comment]
- I close this pr due to #13242

**Pull request closed without merging**
