### PR TITLE
[deploy] Make install.sh as executable script

### LINKED ISSUE #7860: [Bug] [deploy] Shell script install.sh in not executable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I build dev branch and find our script `install.sh` is not executable script, I have to run commend `chmod a+x install.sh` before run it

### What you expected to happen

ATT

### How to reproduce

ATT

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
When I build dev branch and find our script install.sh is not executable script, I have to run commend chmod a+x install.sh before run it

After this patch, script permission like that 
image

fix: #7860

### CODE REVIEW

**Review by zhuangchong — COMMENTED** [review]
I recommend setting file permissions when using maven to build package

For example like this:
```
        <fileSet>
            <directory>${basedir}/../script</directory>
            <outputDirectory>bin</outputDirectory>
            <fileMode>0755</fileMode>
            <directoryMode>0755</directoryMode>
        </fileSet>

```

**Comment by zhongjiajie** [comment]
I test locally, it is success although I revert commit 86deec8. So I think it is ready to go now.
BTW, I perfer to keep commit 86deec8 to ensure it work when user copy-paste form our source code
image

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks for reviewing

**Pull request merged**
