### PR TITLE
[Improvement-15009][Parameter] Change project parameter value to text

### LINKED ISSUE #15009: [Improvement][Parameter] Change project parameter value to text
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Change project parameter value form varchar to text

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

* close: #15009

## Brief change log

Change project parameter value form varchar to text

### CODE REVIEW

**Comment by Radeity** [comment]
Hi @rickchengx , please add upgrade script.

**Review by SbloodyS — DISMISSED** [review]
LGTM

**Comment by rickchengx** [comment]
> Hi @rickchengx , please add upgrade script.

Sure

**Review by zhongjiajie — CHANGES_REQUESTED** [review]
3.2.0 had released, could we migration to 3.2.1 and add upgrade statement?

**Comment by rickchengx** [comment]
> 3.2.0 had released, could we migration to 3.2.1 and add upgrade statement?

Sure. It seems that CI has errors (mysql schema check) that are not caused by this PR change. I am not familiar with this part.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by Radeity — DISMISSED** [review]

**Review by fuchanghai — APPROVED** [review]
LGTM

**Comment by fuchanghai** [comment]
@Radeity @ruanwenjun

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
