### PR TITLE
cherry-pick Allow execute task in workflow instance (#13103) 

### LINKED ISSUE #14805: [Bug] [API] Modify deleted task will write twice version log
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

modify deleted task will write twice version table.

image
image

If run this task, will cycle throw sql exception, 10min print 1.5G log.

image

### What you expected to happen

modify deleted task only write one version table.

### How to reproduce

1. create a workflow contain two task: TaskA, TaskB. You will get workflow version 1.
2. delete TaskA in Task Definition page. You will get workflow version 2.
3. switch workflow to version 1.
4. edit TaskA in workflow DAG page.  You will get workflow version 3 and **two** TaskA version 2.

don't run this workflow, unless you know how to clear through database.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HomminLee**
## Purpose of the pull request

Allow to execute task in workflow instance.

close #14805

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by qingwli** [comment]
Is this issue fixed in dev branch?

**Comment by HomminLee** [comment]
> Is this issue fixed in dev branch?

Yes, this pr is cherry pick from dev.

**Comment by qingwli** [comment]
It looks like a feature, in 3.1.x version, we only fix bugs. WDYT @zhuangchong

**Comment by zhuangchong** [comment]
> It looks like a feature, in 3.1.x version, we only fix bugs. WDYT @zhuangchong

@qingwli You are right. It is not recommended to merge feature into the 3.1.x branch, as this may cause other problems.

@HomminLee Thanks for your contribution, I will close this PR.

**Pull request closed without merging**
