### PR TITLE
[improvement-#12416] Use CollectionUtils.isEmpty judge the collection isEmpty to avoid NPE

### LINKED ISSUE #12416: [Improvement][All] for avoid NPE , improvement some codes
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- use ```CollectionUtils.isNotEmpty``` to instead of ```list.size=0``` and ``` list.isEmpty```
- use ```MapUtils.isNotEmpty``` to instead of ```map.size=0``` and ``` map.isEmpty```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
close:#12416
## Purpose of the pull request
- use ```CollectionUtils.isNotEmpty``` to instead of ```list.size=0``` and ``` list.isEmpty```
- use ```MapUtils.isNotEmpty``` to instead of ```map.size=0``` and ``` map.isEmpty```
- close #12416 
avoid NPE

## Verify this pull request
This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by ruanwenjun** [comment]
@fuchanghai Could you please rebase the upstream and use `./mvnw spotless:apply` to fix the code style

**Comment by fuchanghai** [comment]
> ./mvnw spotless:apply

thx for your recommend,i will fix it

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
