### PR TITLE
[Doc-16732][Development] development-environment-setup improvement

### LINKED ISSUE #16732: [Doc][Development] development-environment-setup improvement
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

development-environment-setup improvement

### Documentation Links

development-environment-setup.md

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

close #16732

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by caishunfeng — COMMENTED** [review]
It's better to add the reason why developer need to add this options.

**Comment by SbloodyS** [comment]
> It's better to add the reason why developer need to add this options.

This is the guidance document for starting the development environment. I don't quite understand why we should add reasons since this is not a code interpretation document...

**Comment by caishunfeng** [comment]
> > It's better to add the reason why developer need to add this options.
> 
> This is the guidance document for starting the development environment. I don't quite understand why we should add reasons since this is not a code interpretation document...

fine, just nip.

**Review by caishunfeng — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
+1

**Pull request merged**
