### PR TITLE
[Fix-14806][dolphinscheduler-dao] The syntax for changing this feature is not supported by PostgreSQL.

### LINKED ISSUE #14806: [sql syntax][dolphinscheduler-dao] DqRuleInputEntryMapper.xml exists postgresql does not support `
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

企业微信截图_16928561733863

### What you expected to happen

sql syntax error

### How to reproduce

connect postgresql

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GaoHu1997**
image
postgresql does not support `

Closes #14806

### CODE REVIEW

**Comment by CallMeKingsley97** [comment]
LGTM

**Review by CallMeKingsley97 — APPROVED** [review]
LGTM

**Comment by qingwli** [comment]
Related #14717

**Review by fuchanghai — APPROVED** [review]
LGTM ,if pass CI

**Pull request closed without merging**
