### PR TITLE
Fix missing Kyuubi type in UI

### PR DESCRIPTION
**Pull request by zhaohehuhu**
## Purpose of the pull request
Fix missing Kyuubi datasource in UI as the screen shown.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`
Screenshot 2023-10-20 at 10 07 41

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@zhaohehuhu Thanks for your pr, can you provide screenshots for this change?

**Review by songjianet — APPROVED** [review]

**Comment by zhaohehuhu** [comment]
> @zhaohehuhu Thanks for your pr, can you provide screenshots for this change?

Added. Thanks.

**Review by ruanwenjun — APPROVED** [review]
+1

**Comment by ruanwenjun** [comment]
Merged, thanks for your pr.

**Pull request merged**
