### PR TITLE
[Fix-16629][UI][Workflow Instance] fix status display error

### LINKED ISSUE #16629: [Bug] [Workflow Instance] Status display error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What you expected to happen

Not displayed correctly

### How to reproduce

Look at the illustration above

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sdhzwc**
image
image

fix #16629
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by sdhzwc** [comment]
@SbloodyS cc

**Review by SbloodyS — APPROVED** [review]
LGTM.

Please follow the pull request notice next time.

**Review by ruanwenjun — APPROVED** [review]
+1

**Comment by ruanwenjun** [comment]
In fact, there are some status is never used, and some statuses are not belong to workflow instance, it would be better if you can fix these together.

**Pull request merged**
