### PR TITLE
[Improvement] Create RollViewLogRequestCommandTest.java

### PR DESCRIPTION
**Pull request by QuakeWang**
## Purpose of the pull request
Add a test case about RollViewLogRequestCommand

### CODE REVIEW

**Comment by CalvinKirs** [comment]
It seems that  forgot to add this test file in the parent pom

**Comment by QuakeWang** [comment]
> It seems that forgot to add this test file in the parent pom

Thanks for the review，I have added the test file to the pom file, please check it

**Review by zhuangchong — APPROVED** [review]
LGTM.

You can submit more fixes in a PR.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
