### PR TITLE
[Improvement][api-server] Update the project owner

### LINKED ISSUE #5326: [Bug][api-server] delete the user ,when query the project by join the table of t_ds_user will return null.
delete the user ,when query the project by join the table of t_ds_user will return null.
Suggested that  [
from t_ds_project p
        join t_ds_user u on p.user_id = u.id
]changed  to  [
from t_ds_project p
       left  join t_ds_user u on p.user_id = u.id
]

### PR DESCRIPTION
**Pull request by ruanwenjun**
When editing a project, we can modify the owner of the project.
fix #5326

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@wangxj3 please take a look.thx

**Review by wangxj3 — CHANGES_REQUESTED** [review]
I think this issue should have another part .When admin delete the user ,check this user is the owner or not .If is the owner,should't delete  this user.Then prompts the administrator to modify the owner of the project.And show the projects which should change the owner.

**Comment by ruanwenjun** [comment]
> I think this issue should have another part .When admin delete the user ,check this user is the owner or not .If is the owner,should't delete this user.Then prompts the administrator to modify the owner of the project.And show the projects which should change the owner.

Yes, I will complete soon.

**Comment by ruanwenjun** [comment]
@wangxj3 Please help me review again, thanks.

**Review by wangxj3 — COMMENTED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
