### PR TITLE
[Improvement-6540][server] Optimize the code related to the processInstanceExecMaps object

### PR DESCRIPTION
**Pull request by eye-gu**
## Purpose of the pull request

Optimize the code related to the processInstanceExecMaps object

## Brief change log

* add ProcessInstanceExecCacheManager
* change processInstanceExecMaps object related class

## Verify this pull request

*Added ProcessInstanceExecCacheManagerImplTest

### CODE REVIEW

**Review by ruanwenjun — DISMISSED** [review]
LGTM.
But the code coverage is 0, could you please add some UT?

**Comment by eye-gu** [comment]
@ruanwenjun  I add the UT, but code coverage is still 0.

**Comment by ruanwenjun** [comment]
@ououtt Add new test class in pom.xml.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
