### PR TITLE
[Improvement]Add Unit Test for CloudController (#13695)

### LINKED ISSUE #13695: [Improvement] [dolphinscheduler-api] The UT coverage of CloudController is zero
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The UT coverage of CloudController  is zero

### What you expected to happen

The UT coverage of CloudController  is 100%

### How to reproduce

Run test with coverage

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by beatCao**
[Improvement]Add Unit Test for CloudController (close #13695)

### CODE REVIEW

**Comment by beatCao** [comment]
@caishunfeng Hello, I want to ask for help on merge. I want to add a UT, but an error is reported, saying that the label is fail. What is the reason?

**Comment by rickchengx** [comment]
Hi, @beatCao You can ignore the `Mergeable label check`, which requires a committer to add for this PR.

**Comment by beatCao** [comment]
Hi, @rickchengx Thank you very much, because the progress of the PR is stagnant, I just need to wait for a commit to add, right?
image

**Comment by rickchengx** [comment]
Hi, @beatCao DS uses `spotless` to fix the code style, could you please run `./mvnw spotless apply` before committing the code.

FYI: https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/contribute/development-environment-setup

**Comment by zhongjiajie** [comment]
> Hi, @beatCao DS uses `spotless` to fix the code style, could you please run `./mvnw spotless apply` before committing the code.
> 
> FYI: https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/contribute/development-environment-setup

Can we run spotless apply in our ci and fix the code style issue by bot instead of by hand, for our contributors? @rickchengx @EricGao888

**Comment by EricGao888** [comment]
> > Hi, @beatCao DS uses `spotless` to fix the code style, could you please run `./mvnw spotless apply` before committing the code.
> > FYI: https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/contribute/development-environment-setup
> 
> Can we run spotless apply in our ci and fix the code style issue by bot instead of by hand, for our contributors? @rickchengx @EricGao888

@zhongjiajie No. `Spotless` cannot convert wildcard imports `import *` into specific imports automatically at this moment. Also, we have rules to ban `powermock`, `junit4` with `Spotless`. If the CI automatically runs `apply` , it will remove those stuff and cause compilation failure.

**Comment by beatCao** [comment]
@EricGao888 please check again，Thank you

**Review by SbloodyS — COMMENTED** [review]
UT failed. Please check it.

**Pull request closed without merging**
