### PR TITLE
[python] Fix f-strings variable error

### PR DESCRIPTION
**Pull request by zhongjiajie**
This patch correct create workflow in batch mode I just add in #6659  . I use wrong variable for python f-strings

### CODE REVIEW

**Comment by zhongjiajie** [comment]
CI failed but it unrelated to this PR

**Comment by zhongjiajie** [comment]
PTAL @lenboo @CalvinKirs

**Review by lenboo — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
