### PR TITLE
[Improvement-15260][dolphinscheduler-datasource-hana] add hana  related dependencies

### PR DESCRIPTION
**Pull request by xujiaqiang**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

> [Feature][dolphinscheduler-datasource-hana] add hana related dependencies #15259

### CODE REVIEW

**Comment by fuchanghai** [comment]
same with #15127

**Comment by xujiaqiang** [comment]
> [与#15127](https://github.com/apache/dolphinscheduler/pull/15127)相同[](https://github.com/apache/dolphinscheduler/pull/15127)

>This feature was developed by me, but not the PR I submitted. I may be clearer on how to modify it. If you need to merge #15127 [](https://github.com/apache/dolphinscheduler/pull/15127) , please merge it into the dev branch as soon as possible. My #15146 [](https://github.com/apache/dolphinscheduler/pull/15146) requires this modification item

**Comment by fuchanghai** [comment]
> > [与#15127](https://github.com/apache/dolphinscheduler/pull/15127)相同
> 
> > This feature was developed by me, but not the PR I submitted. I may be clearer on how to modify it. If you need to merge #15127  , please merge it into the dev branch as soon as possible. My #15146  requires this modification item

cc @caishunfeng

**Comment by davidzollo** [comment]
image
test use in the wrong place

**Review by davidzollo — APPROVED** [review]
+1
LGTM

**Pull request merged**
