### PR TITLE
Remove Intellij code style

### LINKED ISSUE #6428: [Bug] [dev] Code style different between review dog and Intellij configure
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Following the [submit guide][1], I run formatter by using `Ctrl+L` in Intellij and push to upsteam, the commit is https://github.com/apache/dolphinscheduler/pull/6269/commits/bb9f050fdf87c91f1dfe8ad6d9e91f3875475abe, but it failed in our reviewdog CI, see [ci run][2].

It means that our auto formatter and reviewdog checker have different rule. what reivewdog accept format is 

```java
@ComponentScan(value = "org.apache.dolphinscheduler", excludeFilters = {
    @ComponentScan.Filter(type = FilterType.REGEX, pattern = {
        "org.apache.dolphinscheduler.server.master.*",
        "org.apache.dolphinscheduler.server.worker.*",
        "org.apache.dolphinscheduler.server.monitor.*",
        "org.apache.dolphinscheduler.server.log.*"
    })
})
```

but our auto formatter is

```java
@ComponentScan(value = "org.apache.dolphinscheduler", excludeFilters = {
        @ComponentScan.Filter(type = FilterType.REGEX, pattern = {
                "org.apache.dolphinscheduler.server.master.*",
                "org.apache.dolphinscheduler.server.worker.*",
                "org.apache.dolphinscheduler.server.monitor.*",
                "org.apache.dolphinscheduler.server.log.*"
        })
})
```

[1]: https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
[2]: https://github.com/apache/dolphinscheduler/actions/runs/1287112918

### What you expected to happen

Auto formatter and reviewdog should in the same rule

### How to reproduce

Create new java code contain `@ComponentScan(value = "org.apache.dolphinscheduler"` and create new PR

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
closes: #6428 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Would mark as **ready for review** after agree in the mailing-list.

**Comment by zhongjiajie** [comment]
Should also change our document section **Pull Request Code Style** in https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

**Review by ruanwenjun — COMMENTED** [review]
Since the code style between code-style and check-style is different, if we plan to delete the code style, do we need to update the check-style file?

What I have found so far is the continuation indent is different.
https://github.com/apache/dolphinscheduler/blob/4fbee7dc4b178b13c4a795fa848a86ec94c5cd27/style/checkstyle.xml#L181-L188
We may need to modify the `lineWrappingIndentation` to 8, otherwise, there are a lot of files may need to reformat.(PS: I think `lineWrappingIndentation` 4 is great).
```xml
<property name="lineWrappingIndentation" value="8"/>
```

**Comment by zhongjiajie** [comment]
> Would mark as **ready for review** after agree in the mailing-list.

Mailing-list address is https://lists.apache.org/thread.html/rbbf7b4473cda0bce66b4d4b475e6347fa09fd8a278dbdfc80cdf81fb%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by zhongjiajie** [comment]
@ruanwenjun I agree with you, I think `lineWrappingIndentation=4` It great, and I think reformat code is acceptable and we have to do this.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by zhongjiajie** [comment]
I'm going to reformat codebase base on `checkstyle.xml`

**Comment by ruanwenjun** [comment]
@zhongjiajie Hi, it might be better to add some new PRs to format the code, this PR just remove the code style file.

**Comment by zhongjiajie** [comment]
> @zhongjiajie Hi, it might be better to add some new PRs to format the code, this PR just remove the code style file.

OK, I think it better to separate PR cause it's unrelated and it's a little big for this.

**Comment by zhongjiajie** [comment]
I remove this format code, PTAL @ruanwenjun

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by davidzollo — APPROVED** [review]
+1

**Pull request merged**
