### PR TITLE
[Fix-6792] resolve API and alert port conflicts (#6792)

### LINKED ISSUE #6792: [Bug] [alert] NettyRemotingServer bind 50052 fail
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

NettyRemotingServer bind fail bind(..) failed: Address already in use, exit
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

--dev

### What you expected to happen

--

### How to reproduce

--

### Anything else

--

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Narcasserun**
* Multiple ApplicationRunners on classpath make SpringApplication.run() only run one

This closes #6792

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Please fix the code style and when CI passed, LGTM

**Comment by Narcasserun** [comment]
> Please fix the code style and when CI passed, LGTM

ok. ke sir

**Comment by kezhenxu94** [comment]
LGTM @CalvinKirs PTAL

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
