### PR TITLE
 [Improvement-15183][api] remove ApiException annotation #15276 

### PR DESCRIPTION
**Pull request by zhengkezhou1**
## Purpose of the pull request

the **@ApiException** is no need
this pull request slove https://github.com/apache/dolphinscheduler/issues/15183

## Brief change log

- change **org/apache/dolphinscheduler/api/exceptions** 
- change **org/apache/dolphinscheduler/api/controller**  
- change **org/apache/dolphinscheduler/api/controller/v2**
- change **test/org/apache/dolphinscheduler/api/exceptions**
## Verify this pull request

This pull request is already covered by existing tests, such as **unit test**

### CODE REVIEW

**Comment by zhengkezhou1** [comment]
screenshot-github com-2023 12 17-23_10_30
@ruanwenjun These are test cases for **@ApiException** that I think can be removed

**Comment by ruanwenjun** [comment]
> screenshot-github com-2023 12 17-23_10_30
> @ruanwenjun These are test cases for **@ApiException** that I think can be removed

Yes, we can remove this test case.

**Comment by kezhenxu94** [comment]
Hi @zzzk1 , are you still working on this?

**Comment by zhengkezhou1** [comment]
> Hi @zzzk1 , are you still working on this?

yes

**Pull request closed without merging**
