### PR TITLE
[Refactor][UI Next]Reconstructing the Log Component

### LINKED ISSUE #9537: [Feature][UI Next][V1.0.0-Beta] Style the log component in a unified project

### PR DESCRIPTION
**Pull request by labbomb**
## Purpose of the pull request
Please refer to the main `issue`  [#9537](https://github.com/apache/dolphinscheduler/issues/9537).

## Brief change log
image
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by songjianet** [comment]
image

**Comment by songjianet** [comment]
image

**Review by devosend — APPROVED** [review]
LGTM

**Review by Amy0104 — APPROVED** [review]
LGTM.

**Review by Amy0104 — APPROVED** [review]
LGTM.

**Pull request merged**
