### PR TITLE
[Improvement-#9680][task-plugin] add hive sql log listener, print MapReduce progress log and obtain application_id allows developers to better track tasks

### PR DESCRIPTION
**Pull request by fengjian1129**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by fengjian1129** [comment]
@EricGao888 plz close this pull request.

**Comment by EricGao888** [comment]
> @EricGao888 plz close this pull request.

May I ask why you want to close this pull request? BTW, why did u close #11562 and open a new one? You could directly update the PR.

**Comment by fengjian1129** [comment]
@EricGao888 There is a code conflict. The conflict is completely different from my previous code

**Comment by fengjian1129** [comment]
@EricGao888 hi bro,I have submitted the code, can you help me look at it。

**Comment by EricGao888** [comment]
> @EricGao888 There is a code conflict. The conflict is completely different from my previous code

FYI you could resolve the conflicts by rebasing your code, see: https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git:-Fork,-Branching,-Commits,-and-Pull-Request

**Pull request closed without merging**
