### PR TITLE
[Improvement] [Doc] Put default task parameters in a new file

### LINKED ISSUE #11687: [Doc][Task Plugin] Put default task parameters in a new file
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently we have the description for default task parameters in every task plugin, which is hard to maintain and could result in inconsistency. We may put it in one file for better maintainability.
* Besides, we could polish the description for default task parameters for better readability.
image

### Documentation Links

https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/guide/task/shell.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Put the docs for task plugin default parameters in a separate file for better maintainability.
* Polish related docs.
* This PR closes: #11687 

## Brief change log

* Already described above.

## Verify this pull request

This pull request is docs cleanup without any test coverage.

### CODE REVIEW

**Review by zhongjiajie — APPROVED** [review]
LGTM overall, and this may be the best way we can do it currently, but if we migrate our doc template to docusaurus, we can using `.mdx` file to show general parameter into each task docs instead of hyper link, you can see some example in https://stackoverflow.com/a/70702778/7152658 (I can not find in docusaurus official website, So I use SO link here)

**Comment by zhongjiajie** [comment]
Does @SbloodyS have other idea?

**Comment by SbloodyS** [comment]
> Does @SbloodyS have other idea?

Nope. That's great.

**Comment by zhongjiajie** [comment]
@caishunfeng This PR also needs to cherry pick to 3.1.0, thanks

**Comment by caishunfeng** [comment]
> @caishunfeng This PR also needs to cherry pick to 3.1.0, thanks

OK, and this is the improvement, should this pr cherry-pick to 3.0.1?  @zhongjiajie @EricGao888

**Comment by zhongjiajie** [comment]
> > @caishunfeng This PR also needs to cherry pick to 3.1.0, thanks
> 
> OK, and this is the improvement, should this pr cherry-pick to 3.0.1? @zhongjiajie @EricGao888

maybe only 3.1.0, cherry-pick to 3.0.1 may cause many conflict

**Comment by EricGao888** [comment]
> > > @caishunfeng This PR also needs to cherry pick to 3.1.0, thanks
> 
> > 
> 
> > OK, and this is the improvement, should this pr cherry-pick to 3.0.1? @zhongjiajie @EricGao888
> 
> 
> 
> maybe only 3.1.0, cherry-pick to 3.0.1 may cause many conflict

+1，this PR is for better maintainability, it is unnecessary to pick it into 3.0.1.

**Pull request merged**
