### PR TITLE
[e2e] Add new test of security environment

### PR DESCRIPTION
**Pull request by zhongjiajie**
ref: #7281

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @caishunfeng @songjianet @janeHe13

**Review by caishunfeng — COMMENTED** [review]
LGTM

**Review by songjianet — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]

**Comment by zhongjiajie** [comment]
thanks

**Pull request merged**
