### PR TITLE
[Fix-13438] fix breadcrumb navigation and directory visit bugs in reso…

### LINKED ISSUE #13438: [Bug] [UI] Breadcrumb navigation is not available and return unexpected error message in resource management
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After refactoring resource center, some front-end logic have not been updated.

- Step into directory will return error message.
- Breadcrumb navigation display bug.

image

### What you expected to happen

No error message and breadcrumb navigation is available.

### How to reproduce

In resource management, visit directory.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- This PR closes: https://github.com/apache/dolphinscheduler/issues/13438

## Brief change log
- Add new api `/resource/base-dir` for querying base resource dir which add constraint that breadcrumb navigation can only visit resources or files under tenant's resource paths.

- Refactor some breadcrumb navigation related codes in front-end.

image

## Verify this pull request

- Add some UT for back-end parts.
- Manually test front-end parts.

## FINALLY, Happy Lunar New Year 🐇 you all!

### CODE REVIEW

**Comment by Radeity** [comment]
PTAL @Amy0104 @songjianet, this PR mainly fixes front-end bug, thx!

**Review by SbloodyS — APPROVED** [review]
LGTM. Would you please resolve the conflicts? Thanks. @Radeity

**Comment by Radeity** [comment]
> LGTM. Would you please resolve the conflicts? Thanks. @Radeity

Sure! And it's been a while, i'll double check everything is alright tomorrow : )

**Comment by Radeity** [comment]
@SbloodyS It seems that front-end codes have been modified in https://github.com/apache/dolphinscheduler/pull/11203 😓,  also solve breadcrumb navigation bug, however, we can keep the other change of this pr
> Add new api /resource/base-dir for querying base resource dir which add constraint that breadcrumb navigation can only visit resources or files under resource paths.

I will close this one and create another pr later today.

**Pull request closed without merging**
