### PR TITLE
[DSIP-67] Use command to trigger workflow instance rather generate workflow instance

### LINKED ISSUE #16485: [DSIP-67] Use command to trigger workflow instance rather generate workflow instance
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Right now once we trigger or backfill a workflow, the logic will be like below

image

1. We will send a request to the API server
2. The API server will generate a trigger command to the DB
3. The Master will fetch the command from DB and fire them
4. If fire success, then will generate a workflow instance, if fire failed will move the command to t_ds_error_command.

The workflow instance generation is async, which means once we trigger a workflow, we don't know whether the trigger is validated, maybe it will generate a workflow instance, or maybe not. It's hard for third-party integration.

### Design Detail

To solve this problem, we should make workflow instance generation sync.

image

This will change the workflow instance lifecycle, once we trigger a workflow, the API will call master to generate a workflow instance and generate a trigger command. 

The newly generated workflow instance state is SUBMITTED. 

Once the command is fired, then the workflow instance state will be RUNNING, so all commands no matter the command type, are used to fire a workflow instance.

 And once we call the API to trigger a workflow, we can get the workflow instance id from the response.

### Compatibility, Deprecation, and Migration Plan

Compatibility with current logic.

### Test Plan

Test with E2E/IT

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/16485

## Brief change log

- Add interface in master to manualTrigger/scheduleTrigger/backfillTrigger a workflow.
- Move all workflow instance construct logic to master.
- API will directly call master's api to control a workflow.
- Return workflow instance id when triggering a workflow.
- Delete `TriggerRelation`, since we can directly use workflow instance id to track workflow instance.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
CI failed. Please check it. @ruanwenjun

**Review by SbloodyS — DISMISSED** [review]
LGTM overall.

**Review by SbloodyS — APPROVED** [review]

**Review by caishunfeng — APPROVED** [review]
LGTM overall

**Comment by LiJie20190102** [comment]
Will this PR merge into section 3.1.9？

**Comment by wallfacers** [comment]
Hi, this RP will be merged into those versions, and at what point in time will the merge take place @caishunfeng @ruanwenjun

**Comment by SbloodyS** [comment]
It will be released in the 3.3.0-release. @wallfacers @LiJie20190102

**Comment by wallfacers** [comment]
Version 3.3.0 When will it be released @SbloodyS

**Comment by SbloodyS** [comment]
> Version 3.3.0 When will it be released @SbloodyS

We hope to release it in 2025.

**Pull request merged**
