### PR TITLE
Add standalone server module to make it easier to develop and run

### PR DESCRIPTION
**Pull request by kezhenxu94**
## Brief change log

- Add a new module `dolphinscheduler-standalone-server`.
- Add H2, curator testing server for embedded database and registry.
- Add H2-specific database schema.

## Verify this pull request

This pull request composes other codes that should be already covered by existing tests.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@dailidong @CalvinKirs would you please take a look and help to test?

**Comment by CalvinKirs** [comment]
You can follow this document to follow the checkstyle plugin

**Comment by kezhenxu94** [comment]
> You can follow this document to follow the checkstyle plugin

I mean, can you help to test the standalone server :) the code styles I will fix

**Comment by CalvinKirs** [comment]
> > You can follow this document to follow the checkstyle plugin
> 
> I mean, can you help to test the standalone server :) the code styles I will fix

Well, got it, I'll test it

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
UT failed due to timeout, I will fix it.

**Pull request merged**
