### PR TITLE
[Fix] Fix the jmod issues, support 11 and later versions  #10232

### LINKED ISSUE #10232: [Bug] [dolphinscheduler-datasource-hive] The java package:sun.security.krb5 is not exsist
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I started the back-end application in Standalone mode according to the steps of the official website document, Out of line this problem. It was originally a problem on my Linux. Combined with the content of the jdk package, I thought it was a problem with my openjdk, but today Had the same problem on my oraclejdk for windows. This package can be found in jdk, and the files in jdk can also be located in idea, but the compilation fails when the application is started. I guess it might be something wrong with which compile plugin in maven.
image

### What you expected to happen

The backend application in Standalone mode starts successfully

### How to reproduce

```
mkdir dolphinscheduler
cd dolphinscheduler
git clone git@github.com:apache/dolphinscheduler.git
```
Find the class `org.apache.dolphinscheduler.server.StandaloneServer` in Intellij IDEA and clikc run main function to startup.

### Anything else

Environment: jdk11, maven3.6
Version: dev & 3.0.0-alpha

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 106umao**
## Purpose of the pull request

The official website document only indicates that developers use the 1.8+ version for development, but it does not point out that the version after 1.9+ should be incompatible with jmod, so I fixed this problem and support the 11+ version. The reason why version 1.9 is not supported is because it will require developers to modify the --release parameter of IDEA configuration. I think this is not friendly to developers. It is better to suggest that they upgrade to 11 for development.

## Brief change log

Added a profile configuration to the root POM file

## Verify this pull request

This change added tests and can be verified as follows:

mvn test -Pjmod
(or)
run the application in IDEA

### CODE REVIEW

**Comment by SbloodyS** [comment]
I think we should open a discussion before adding this.

**Comment by 106umao** [comment]
> I think we should open a discussion before adding this.

You are right, because it is better to eliminate the dependency of the code in the program on the modules that are not open inside java, but the problem now is that there is such a dependency in the code, and it will cause the program to fail to compile. I think you guys can remove my pr after refactoring the code improvement, but for now I think this pr is necessary

**Comment by SbloodyS** [comment]
@kezhenxu94 PTAL

**Comment by kezhenxu94** [comment]
@106umao hi thanks for doing this, since the patch doesn't require developers' additional changes in their development process I'm OK to add this.

But did you test the compiled codes can run correctly at runtime? And can you please add a basic test for Java 11 based on our current CI?

**Comment by 106umao** [comment]
@kezhenxu94 
I have no problem running the StandaloneServer, but I haven't done CI. I'm not very clear about the CI process of the project. I don't know where to start. Can you guide the following?

**Comment by songjianet** [comment]
Please associate the corresponding issue. @106umao

**Comment by 106umao** [comment]
@kezhenxu94 
PTAL.

**Comment by kezhenxu94** [comment]
Hi @106umao , please make the CI passed

**Comment by 106umao** [comment]
@kezhenxu94 
I'm sorry, I haven't found how to fix the problem on CI for now. I'm preparing for DolphinScheduler's summer of programming project, so I can't concentrate on fixing bugs these days. Please let me keep this PR for a few days. Fix it after the project proposal is submitted.

**Comment by kezhenxu94** [comment]
> @kezhenxu94 
> 
> I'm sorry, I haven't found how to fix the problem on CI for now. I'm preparing for DolphinScheduler's summer of programming project, so I can't concentrate on fixing bugs these days. Please let me keep this PR for a few days. Fix it after the project proposal is submitted.

sure

**Comment by kezhenxu94** [comment]
The CI still failed

**Comment by 106umao** [comment]
> The CI still failed

Sorry, I'm still testing, hope you don't mind

**Comment by 106umao** [comment]
The errors seem to be getting worse, I think I should stop this pr for a while and go to the documentation to write how to develop code on jmod first...

**Comment by zhongjiajie** [comment]
> 

you should add the doc in this PR, and they will be merge together with your code

**Comment by ruanwenjun** [comment]
I can build successfully with opeanjdk 11, but in IDEA need to remove `--release` config :).

**Comment by 106umao** [comment]
Hi @ruanwenjun 
The first time I found this problem was when I started StandaloneServer with IDEA, you can try to start it, and if you don't have any problems try to use `mvn clean test` instead of `mvn clean compile`, because there are still many problems with unit tests. For details, see this pr-related issues

**Comment by caishunfeng** [comment]
Hi, any progress? Do we still need this pr?

**Pull request closed without merging**
