### PR TITLE
[fix-#13940] add  status  of ``` stop``` in class of TaskExecutionStatus

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

this close:
- #13940 

## Brief change log

add  status  of ``` stop``` in class of TaskExecutionStatus
## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by fuchanghai** [comment]
@caishunfeng @SbloodyS @zhuangchong plz run CI

**Comment by rickchengx** [comment]
May I ask whether the `READY_STOP` state also needs to be added ?

**Comment by fuchanghai** [comment]
> May I ask whether the `READY_STOP` state also needs to be added ?


Sorry for not replying to you for so long.
>我个人认为是不需要的，ready stop 不是一个finish 状态，只有subprocess 节点的流程实例finish状态才应该去更新父流程中的subprocess 任务实例的状态
>I personally think it is unnecessary, ready stop is not a finish state, only the process instance finish state of the subprocess node should update the state of the subprocess task instance in the parent process

WDYT @rickchengx @caishunfeng @ruanwenjun

**Review by zhuangchong — APPROVED** [review]
+1

**Review by rickchengx — APPROVED** [review]
LGTM

**Pull request merged**
