### PR TITLE
[Improvement-4986][Master] Remove master delete task execution script file operations and ProcessInstance processDefinition null pointer. 

### LINKED ISSUE #4986: [Improvement][Master] Remove master delete task execution script file operations and ProcessInstance processDefinition null pointer.
**Describe the question**
1.Remove master delete task execution script file operations
2.ProcessInstance processDefinition null pointer.

**Which version of DolphinScheduler:**
 -[dev]

iShot2021-03-03 13 01 32

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request
this PR close #4986 
1.Remove master delete task execution script file operations
2.ProcessInstance processDefinition null pointer.

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by chengshiwen** [comment]
@zhuangchong You should set `-Dlogging.config=classpath:logback-master.xml`, instead of doing this. or just judge the `NPE`

**Comment by chengshiwen** [comment]
You are already a very senior contributor, you can solve more difficult problems, such as issues, instead of looking for these simple problems, leave these problems to more contributors who need to get started

**Comment by zhuangchong** [comment]
@chengshiwen 
Are you sure it's related to the -Dlogging.config=classpath:logback-master.xml parameter setting?

What I'm saying is very unclear

This PR fixes two problems: 1. After receiving the result of processing the specific task, the master will execute the delete task execution script. Since the task execution script is created by the worker, I think it is unreasonable to use the master to delete it here. Therefore, this part of code has been deleted, and the plug-in of task nodes will be taken into consideration in the later work. 2. After the master sends the task and receives the processing result of the task, ProcessInstance is processed for many times. At this time, the ProcessDefinition is empty, and the Set ProcessDefinition operation after the object conversion is meaningless

—-
这个pr修复的是两个问题，1.master接受到具体任务处理完的结果后，执行删除任务执行脚本。因为任务执行脚本是worker负责创建，此处用master去删除我认为是不合理的，所以删除了这部分代码，待后期做任务节点插件化在考虑进去。2.在master发送任务到接收任务处理结果，对processInstance多次加工，此时processDefinition为空，对象转换后的set ProcessDefinition操作已无意义，所以删除了set代码，我也查找了后面的代码没有用到这个字段

**Comment by chengshiwen** [comment]
Sorry, I mistakenly thought it was another issue and gave the wrong comment

**Comment by chengshiwen** [comment]
`public static String getProcessExecDir(int projectId, int processDefineId, int processInstanceId)` also can be removed

**Comment by zhuangchong** [comment]
@chengshiwen @CalvinKirs PTAL,Thx

**Comment by CalvinKirs** [comment]
some detail I am not sure, although I think you’re right, it’s best to ask @lenboo

**Pull request closed without merging**
