### PR TITLE
[bugfix-10116]fix complement data bug

### PR DESCRIPTION
**Pull request by brave-lee**
closed by #10116

### CODE REVIEW

**Comment by JohnZp** [comment]
I find that there is a problem, at least NPE will be generated in the process . I suggest this change:
```java
        Map<String, String> result = new HashMap<>();
        switch (commandType) {
            case COMPLEMENT_DATA:
                if (runTime != null) {
                    businessDate = DateUtils.addDays(runTime, -1);
                    break;
                } else {
                    return result;
                }
```

**Comment by brave-lee** [comment]
What scenario has NNP occurred ?

**Comment by JohnZp** [comment]
> I'm sorry, my description just now is ambiguous. It's an NPE problem.

The problem is that when you define a global parameter like this and then perform the complement operation, the generated processInstance will not have a scheduleTime
Therefore, calling the following method will occur a null pointer

image

**Comment by brave-lee** [comment]
OK, please submit a new issue for your discovery

**Pull request merged**
