### PR TITLE
[Feature][jsonsplit] replace processDefinitionVersion with processDefinitionLog

### PR DESCRIPTION
**Pull request by simon824**
#4417

### CODE REVIEW

**Review by chengshiwen — CHANGES_REQUESTED** [review]
The table name alter from `t_ds_process_definition_version` to `t_ds_process_definition_log` is missing

**Comment by brave-lee** [comment]
+1

**Comment by simon824** [comment]
> The table name alter from `t_ds_process_definition_version` to `t_ds_process_definition_log` is missing

`t_ds_process_definition_version` and `t_ds_process_definition_log` are two different tables, and i will drop table `t_ds_process_definition_version`  later.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
