### PR TITLE
[Bug] [UI] Fix Delete project error

### LINKED ISSUE #6170: [Bug] [UI] Delete project error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Delete project error

### What you expected to happen

Delete workflow normally

### How to reproduce

Snipaste_2021-09-11_13-08-08

### Anything else

-dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tandoy**
·fix delete project error
·This closes #6170

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by RichardStark** [comment]
+1 meet the same issue and fixed use this method

**Comment by Tandoy** [comment]
@ruanwenjun 
Can you review this pr, if you have time. Thanks~

**Comment by brave-lee** [comment]
Please fix ut error

**Comment by Tandoy** [comment]
> Please fix ut error

@JinyLeeChina The UI error has been resolved, please review.

**Review by brave-lee — APPROVED** [review]
+1

**Pull request merged**
