### PR TITLE
[python] Add integrated test to python gateway server

### LINKED ISSUE #8035: [Feature][python] Add CI between pydolphinscheduler and pythonGatewayServer
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In #7971, we find out example in pydolphinscheduler could raise error due to some parameter with wrong value. We could surely test our example or code each time before we release our code. But I think add some tests between pydolphinscheduler and pythonGatewayServer is better than that. I make our code more stronger

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Build java code and create standalone server image in GA
* Add component start docker in python
* Run example to make sure it works to it

close: #8035

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend @jieguangzhou thanks

**Review by jieguangzhou — APPROVED** [review]
LGTM

**Review by devosend — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
