### PR TITLE
Add constants variables for StandaloneServer keyword

### PR DESCRIPTION
**Pull request by zhongjiajie**
## Purpose of the pull request

Add constant for standalone server keyword, and use constants in other codebase

### CODE REVIEW

**Comment by CalvinKirs** [comment]
please resolve conflicting files,thx

**Comment by zhongjiajie** [comment]
Fix conflict, PTAL @CalvinKirs

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Not need to change for now

**Pull request closed without merging**
