### PR TITLE
[Improvement-12333][Test] Migrate all UT cases from jUnit 4 to jUnit 5 in microbench and e2e module

### LINKED ISSUE #12333: [Migration][Test] Migrate all UT cases from jUnit 4 to jUnit 5 in microbench and e2e module
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Migrate all UT cases from jUnit 4 to jUnit 5 in microbench and e2e module.
* This issue is a sub-task of #12301 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

* close: #12333 

## Brief change log

Migrate all UT cases from jUnit 4 to jUnit 5 in microbench and e2e module

### CODE REVIEW

**Comment by rickchengx** [comment]
Hi, @kezhenxu94 , could you please help me with this e2e problem?

This PR wants to remove the junit4 api in the `e2e` module. But in `dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java`, we cannot just remove or replace the `junit4` api  since `org.testcontainers.containers.Network` is used.

截屏2022-10-13 14 22 18

It seems that `Testcontainers` is tightly coupled with the JUnit 4.x rule API, and here is the limitation of `Testcontainers` from the article below:
截屏2022-10-13 14 32 59

* https://www.testcontainers.org/test_framework_integration/junit_5/


If we want to migrate all UT cases from jUnit4 to Junit5 here, do we need to refactor the tests in `e2e` module.
Note: `Testcontainers` is also used in `dolphinscheduler-api-test` module.

cc @EricGao888

**Comment by kezhenxu94** [comment]
From the doc of testcontainers it seems impossible to remove junit4 from test classpath. But since we have spotless check to forbid usage of junit4 classes we can avoid direct use of junit4 in our codebase. Right?

Is your question about the failed tests, then?

**Comment by rickchengx** [comment]
@kezhenxu94 Thanks a lot for the comment, I agree with you. So we need to avoid the junit 4 api in our codebase.

截屏2022-10-13 14 22 18

As for the CI e2e failure, this is because I use`network = Network.newNetWork()` instead of `network = new NetWork()` and override the methods of `getId()`, `close()` and `apply()`.

The reason I made this change was to avoid the import of `org.junit.runner.Description` and `org.junit.runners.model.Statement`. But `network = Network.newNetWork()` now cannot return the `networkId` and cause the CI failure.

Now I have tried to use `network = Network.builder().id(networkId).build();`. I am not sure whether this could pass the CI.

Maybe we could wait for the CI results before deciding what to do next.

**Comment by rickchengx** [comment]
Hi @kezhenxu94 It seems that the CI cannot pass because of the `network` below, would you please help me with this CI failure?

截屏2022-10-14 14 26 35

image

**Comment by rickchengx** [comment]
Rollback `DolphinschedulerExtension.java` to verify it is the reason of the CI failure.

**Comment by rickchengx** [comment]
I have a clue, WIP

**Comment by EricGao888** [comment]
@rickchengx FYI, we also have a junit import in microbench module, see: https://github.com/apache/dolphinscheduler/blob/3bef85f546e5ebb9d4c91e48c515756286631069/dolphinscheduler-microbench/src/main/java/org/apache/dolphinscheduler/microbench/base/AbstractBaseBenchmark.java#L23

**Comment by rickchengx** [comment]
> @rickchengx FYI, we also have a junit import in microbench module, see:
> 
> https://github.com/apache/dolphinscheduler/blob/3bef85f546e5ebb9d4c91e48c515756286631069/dolphinscheduler-microbench/src/main/java/org/apache/dolphinscheduler/microbench/base/AbstractBaseBenchmark.java#L23

Hi @EricGao888 Thanks for the comment. I've noticed this.
image

**Comment by rickchengx** [comment]
Hi, @EricGao888 , I have refactored `DolphinschedulerExtension` in e2e module to remove the junit4 api and It seems that the CI is passed, : )

cc @kezhenxu94

**Comment by EricGao888** [comment]
Seems good to me. But I'm not familiar with this module. Could u plz take a look when available? @kezhenxu94 @SbloodyS ? Thanks~

**Review by zhongjiajie — APPROVED** [review]

**Comment by zhongjiajie** [comment]
LGTM, BTW can you also fix the number format error?
image

**Review by kezhenxu94 — APPROVED** [review]

**Comment by EricGao888** [comment]
> LGTM, BTW can you also fix the number format error? image

@zhongjiajie Thanks for pointing this out. I will submit a follow-up PR to this issue to fix this, as well as remove junit4 check exclusions for these two modules. https://github.com/apache/dolphinscheduler/blob/a11892aea0dd16ea04d7a595b186a8ae1f32a9c0/pom.xml#L642-L647

**Comment by EricGao888** [comment]
> LGTM, BTW can you also fix the number format error? image

@zhongjiajie I've done it in #12450, please take a look when available, thanks : )

**Pull request merged**
