### PR TITLE
[improve][api] Support to upload file without file type suffix

### LINKED ISSUE #9502: [Improvement][Api] Support to upload file without file type suffix
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When uploading a file without file type suffix, an error will be reported as shown below, which is not the expected behavior by users.

We should support upload files without file type suffix.

image

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by exmy**
## Purpose of the pull request

This pr will close #9502 

## Brief change log

Remove the judgment that filesuffix is empty in method `verifyFile` and `upload` of `ResourcesServiceImpl`

## Verify this pull request

This change added tests and can be verified as follows:

manual test locally

### CODE REVIEW

**Comment by SbloodyS** [comment]
I don't see the reason for restricting file suffixes before. PTAL @caishunfeng

**Comment by exmy** [comment]
Can anyone review this change?

**Comment by caishunfeng** [comment]
> I don't see the reason for restricting file suffixes before. PTAL @caishunfeng

I don't know the file suffix design too, but I think it's OK without suffix.  
Do you have time to review this pr? @lenboo @QuakeWang

**Review by QuakeWang — COMMENTED** [review]
I have tested a similar situation. When uploading a file without any suffix it is not allowed. However, if the file is a *.jar, it is possible to upload it without the .jar suffix, but it will not work.

**Comment by exmy** [comment]
> I have tested a similar situation. When uploading a file without any suffix it is not allowed. However, if the file is a *.jar, it is possible to upload it without the .jar suffix, but it will not work.

In our production environment, some users do want to upload files without suffix, like binary executable file. For the case that a file is *.jar but upload without .jar suffix, i think it's best for users themselves to ensure the correctness of uploaded files.

**Comment by zhongjiajie** [comment]
I think this change is acceptable, I will merge it tomorrow if no one be opposed to this

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
