### PR TITLE
[Improvement-13835] improve mobile phone number check rule

### LINKED ISSUE #13835: [Improvement][dolphinscheduler-api] the mobile phone number check rule is too broad
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when add user, the mobile phone number check rule is too broad, can input the mobile phone number like 12345678910, but the  mobile phone number rule is start with 1,the the second number should not 2, the rule should match  regular expression "^1(3\\d|4[5-9]|5[0-3,5-9]|6[567]|7[0-8]|8\\d|9[0-3,5-9])\\d{8}$"

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huangxinan1990**
fix https://github.com/apache/dolphinscheduler/issues/13835

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by rickchengx — DISMISSED** [review]
LGTM, wait for the CI

**Comment by huangxinan1990** [comment]
@SbloodyS have modify the code format, please rerun the CI again

**Comment by huangxinan1990** [comment]
@SbloodyS @songjianet @caishunfeng @Amy0104 please help to review, thanks

**Review by xleoken — APPROVED** [review]

**Review by SbloodyS — COMMENTED** [review]
The frontend build CI failed. Please check it.

**Review by songjianet — APPROVED** [review]

**Pull request closed without merging**
