### PR TITLE
[1.3.6-prepare][Improvement][Server&UI] Update worker group ip and unify form model #4982

### PR DESCRIPTION
**Pull request by chengshiwen**
pr #4982

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by lenboo — APPROVED** [review]
+1

**Comment by CalvinKirs** [comment]
@zhuangchong @break60 please take a look(UI)

**Comment by break60** [comment]
Please solve e2e, thank you！

**Comment by chengshiwen** [comment]
> Please solve e2e, thank you！

Done

**Review by break60 — APPROVED** [review]
front end +1

**Pull request merged**
