### PR TITLE
Fix the perm setting for the process definition import function

### PR DESCRIPTION
**Pull request by alexBaiJW**
## Purpose of the pull request

Fix the perm setting for the process definition import function.

## Brief change log

Change the perm from WORKFLOW_EXPORT to WORKFLOW_IMPORT.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
Please associate this PR to your issue so that we can know which version to fix.

**Comment by alexBaiJW** [comment]
> Please associate this PR to your issue so that we can know which version to fix.

There is no issue associate with this PR, it just fix the perm setting.

**Comment by zhongjiajie** [comment]
@alexBaiJW  please run `mvn spotless:apply` to fix the style issue

**Comment by rickchengx** [comment]
LGTM, wait for CI

**Review by caishunfeng — APPROVED** [review]
LGTM

**Pull request merged**
