### PR TITLE
fix: Fix some mistakes in the datasource

### PR DESCRIPTION
**Pull request by labbomb**
## Purpose of the pull request
link [#12774 ](https://github.com/apache/dolphinscheduler/issues/12774)

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by songjianet — DISMISSED** [review]
LGTM

**Review by Amy0104 — DISMISSED** [review]
LGTM

**Review by devosend — DISMISSED** [review]
LGTM

**Comment by Tianqi-Dotes** [comment]
close https://github.com/apache/dolphinscheduler/issues/12774

**Review by Amy0104 — APPROVED** [review]
LGTM

**Pull request merged**
