### PR TITLE
[fix-11404]: make the common.properties to configurable on values.yaml

### LINKED ISSUE #11404: [Bug] [UI] Storage not enabled
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

What happened
I set values.xml
```
sharedStoragePersistence:
enabled: true
mountPath: "/opt/soft"
accessModes:
- "ReadWriteMany"
## storageClassName must support the access mode: ReadWriteMany
storageClassName: "ds-shared-nfs"
storage: "2Gi"
```
```
fsFileResourcePersistence:
enabled: true
accessModes:
- "ReadWriteMany"
## storageClassName must support the access mode: ReadWriteMany
storageClassName: "ds-file-nfs"
storage: "2Gi"
```

`DATA_BASEDIR_PATH: "/tmp/dolphinscheduler"
RESOURCE_STORAGE_TYPE: "HDFS"
RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
FS_DEFAULT_FS: "file:///"`

### What you expected to happen

It's show "Storage is not enabled" when I upload the spark-examples_2.11-2.4.7.jar.

### How to reproduce

storageClassName: "ds-shared-nfs"
storageClassName: "ds-file-nfs"
all bound 
It's use the nfs.

### Anything else

root@dolphinscheduler-api-dbcf78666-72wff:/opt/dolphinscheduler/conf# pwd
/opt/dolphinscheduler/conf
root@dolphinscheduler-api-dbcf78666-72wff:/opt/dolphinscheduler/conf# cat common.properties 
```
data.basedir.path=/tmp/dolphinscheduler
resource.storage.type=NONE
resource.upload.path=/dolphinscheduler
fs.defaultFS=file:///
```
 why?

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by itzhang89**
and set the resource.storage.type default to hdfs

## Purpose of the pull request

fix #11404(https://github.com/apache/dolphinscheduler/issues/11404)

## Brief change log

make the common.properties to configurable on values.yaml and set the default storage type to hdfs and fs.defaultFS

```yaml
conf:
  common:
    resource.storage.type: HDFS
    fs.defaultFS: file:///
```

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by aspexdaniel** [comment]
@yutianaiqingtian maybe we should replace the values in common.properties from common.configmap.* in values.yaml? 
since we already have these configs like RESOURCE_STORAGE_TYPE, FS_DEFAULT_FS, FS_S3A_ENDPOINT, 
putting everything in values.yaml is a bit redundant.

**Comment by itzhang89** [comment]
@aspexdaniel exactly It's a bit redundant. but the value the common.configmap.RESOURCE_STORAGE_TYPE is only check on the helm chart and cannot take effect by the application.   I think maybe we should split the common.configmap to two part. one is for the environment and another is for the common.properties.

**Comment by aspexdaniel** [comment]
@yutianaiqingtian this is strange though, because I tested 2.0.6 chart with common.configmap.* points to Minio , it worked. From the code I feel it's not that big different between the two version for k8s helm chart.

**Review by kezhenxu94 — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by SbloodyS** [comment]
Thanks for your contribution. This is a good beginning. Considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(SbloodyS), when mail or added, please tell me who you are. I think I can help to familiar with the Dolphinscheduler if you meet with problems. @yutianaiqingtian

**Pull request merged**
