### PR TITLE
[Doc][Architecture] Update Architecture Design Documentation

### LINKED ISSUE #13650: [Doc][architecture] Documentation bug or improvement
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Improve and supplement dolphinscheduler-master's documentation

### Documentation Links

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ouyangyewei429**
fix #13650

### CODE REVIEW

**Comment by ouyangyewei** [comment]
@zhongjiajie pls review, tks :)

**Review by EricGao888 — COMMENTED** [review]
@ouyangyewei Hi, DS uses `spotless` for style check. Could u plz run `mvn spotless:apply` to fix the formatting errors? Thx : )

**Comment by ouyangyewei429** [comment]
> @ouyangyewei Hi, DS uses `spotless` for style check. Could u plz run `mvn spotless:apply` to fix the formatting errors? Thx : )

Got it, fixed

**Comment by ouyangyewei** [comment]
@zhongjiajie pls review, tks :)

**Comment by rickchengx** [comment]
Hi, @ouyangyewei , there are some errors in CI, please fix them.
E.g. 
image

**Comment by ouyangyewei** [comment]
> 

Sry, I don't quite understand, My PR did not include this part of the changes

**Comment by ouyangyewei** [comment]
> Hi, @ouyangyewei , there are some errors in CI, please fix them. E.g. image


Sry, I don't quite understand, My PR did not include this part of the changes

**Comment by ouyangyewei429** [comment]
> Hi, @ouyangyewei , there are some errors in CI, please fix them. E.g. image

Got it, fixed

**Comment by ouyangyewei429** [comment]
@EricGao888 @zhongjiajie @rickchengx pls review again, thanks :)

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by rickchengx — APPROVED** [review]

**Pull request closed without merging**
