### PR TITLE
New doc files.

### PR DESCRIPTION
**Pull request by sneh-wha**
## Purpose of the pull request

Review of new documents

## Brief change log

Confluence pages are attached here for merging.

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @sneh-wha , could you describe why did you want to do that?

**Comment by zhongjiajie** [comment]
hi @sneh-wha you should change the doc inplace within the exist docs. for example, if you want to change `sql.md` https://github.com/apache/dolphinscheduler/pull/10598/files#diff-6e9b61686403ddb0ce8cf69a824ece20823ce299f2330602ba7f897bc4f87339 you should change base on https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/task/sql.md instead of adding the new one

**Comment by zhongjiajie** [comment]
you should:

* (main issue) Move files to exists documents, for example, you change Shell.md, than you should change file in path https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/task/shell.md instead of add new file in the root directory
* I see you use html in table instead of markdown syntax such as https://github.com/apache/dolphinscheduler/pull/10598/files#diff-a2f3a3679195de40e4b40436591ed15733a553ae41afd6d0f4453b914cd71dda setion task parameter, I think we should use makdown style, and you could see an example in https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables
* Some of of change is out of date, such as https://github.com/apache/dolphinscheduler/pull/10598/files#diff-b4d30489ff49a63af9e98e4b23eabf66802e165a446ccd2dc44c09311e09bf03 your content is still in `alert-instance01 ` but the latest in dev branch is `alert-instance01` and you change see in https://github.com/apache/dolphinscheduler/tree/dev/docs/docs/en/guide/alert
* BTW, should better submit your change in separate PR instead of the big one, which we could reveiw and merge some of them if it is ready to go.

**Comment by sneh-wha** [comment]
Submitting new PRs instead of this .

**Pull request closed without merging**
