### PR TITLE
[Fix-15787] Reuse code and solve the problem of complex SQL parsing exceptions in…

### LINKED ISSUE #15787: The sql task reports an error, and the sql parsing is incorrect.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

SQL作业使用oracle数据源类型，sql中使用union all时任务出错。
执行以下sql：
select a,b,c,b-c as d
from
(select 1 as a,2 as b,3 as c from dual)

union all
select 1 as a,2 as b,3 as c,4 as d from dual
通过查询日志，可以看到以上sql被解析为：
SELECT a, b, c, b - c AS d
FROM (
	SELECT 1 AS a, 2 AS b, 3 AS c
	FROM dual
	UNION ALL
	SELECT 1 AS a, 2 AS b, 3 AS c, 4 AS d
	FROM dual
)

### What you expected to happen

正常显示合并结果集

### How to reproduce

在SQL任务中执行以下sql：
select a,b,c,b-c as d
from
(select 1 as a,2 as b,3 as c from dual)

union all
select 1 as a,2 as b,3 as c,4 as d from dual

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinxingi**
… druid, corresponding to issue fix #15787

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM.

**Review by qingwli — DISMISSED** [review]
+1

**Review by SbloodyS — COMMENTED** [review]
@xinxingi Please fix UT.

**Review by SbloodyS — APPROVED** [review]

**Comment by xinxingi** [comment]
@qingwli @SbloodyS The UT that reports the error is meaningful. The com.alibaba.druid.sql.parser.SQLParserUtils.splitAndRemoveComment tool class does not do special processing for Oracle, which requires overall execution of PL/SQL. As a result, a complete statement will be incorrectly split. After correcting the logic of the code, I conducted unit tests on a series of PL/SQL statements and multiple compound SQL statements, and the tests all passed. But I didn't submit the code because there were too many test samples. If necessary, I will provide a comprehensive test sample in the comment area or make a git submission. I will continue to follow up on the maintenance of this data source from now on

**Comment by qingwli** [comment]
That's ok @xinxingi , This pr is merged, Thanks for your contributing

**Pull request merged**
