### PR TITLE
Remove unused try block in UT

### LINKED ISSUE #6181: Empty try block in UT
I found out we have empty try block in our UT, maybe we should just remove this block?
https://github.com/apache/dolphinscheduler/blob/e1aed5eefd26c9b447d356de6238e4b61a4d3daf/dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/plugin/AlertPluginManagerTest.java#L60-L65

### PR DESCRIPTION
**Pull request by zhongjiajie**
closes https://github.com/apache/dolphinscheduler/issues/6181

## Purpose of the pull request

closes https://github.com/apache/dolphinscheduler/issues/6181 and remove unused code

### CODE REVIEW

**Comment by CalvinKirs** [comment]
This UT needs to be modified

**Comment by zhongjiajie** [comment]
Got it, mean that we should not remove but make it work again. I would try to correct it

**Review by davidzollo — APPROVED** [review]
+1
good job

**Review by davidzollo — APPROVED** [review]

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
