### PR TITLE
[fix-11295] add chunjun plugin in dolphinscheduler-task-all/pom.xml

### LINKED ISSUE #11401: [Bug] [Task Plugin] can not create chunjun task in workflow definition
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error occured when create a workflow with chunjun task
lQLPJxaNogG53KzNA6TNAsmwrCVAL5w_sssC6R4XYsCJAA_713_932

lQLPJxaNob3G11bNA3nNBzWwhdPyuuoZ3IcC6R2n7kBvAA_1845_889

### What you expected to happen

save workflow succeed

### How to reproduce

As What Hadpped describes, create workflow -> config chunjun task node -> save, then error occured.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wxing89**
## Purpose of the pull request
fix config chunjun task error in workflow definition caused by chunjun task not loaded when start server

## Brief change log
add chunjun plugin in dolphinscheduler-task-all/pom.xml

## Verify this pull request

This pull request is code cleanup without any test coverage.

close: #11401

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @wxing89 ,to target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, just desc). It would not only connect issue to PR but also close issue automatically when PR is be closed.

**Comment by wxing89** [comment]
> Hi @wxing89 ,to target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, just desc). It would not only connect issue to PR but also close issue automatically when PR is be closed.

Thanks a lot.
I've submitted a issue and connected to it.

**Review by SbloodyS — DISMISSED** [review]
LGTM

**Review by EricGao888 — DISMISSED** [review]
@wxing89 Good job! Thanks.

**Comment by EricGao888** [comment]
There are conflicts to be solved. Could you please rebase your code? Thanks @wxing89

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
