### PR TITLE
Clean up third-party files that are not mentioned in LICENSE

### LINKED ISSUE #5388: [Bug] `ProcessUtils` seems to contain OpenJDK code
**Describe the bug**
It appears `org.apache.dolphinscheduler.server.utils.ProcessUtils` contains code from the OpenJDK without mentioning it, and without retaining the copyright header.
(It might also be problematic from a security standpoint since the upstream OpenJDK code has received security patches in the meanwhile.)

If you compare the [initial version of `ProcessUtils`](https://github.com/apache/dolphinscheduler/blob/5c45f92f463b5d6c4b811df1058cc712da67dd7e/escheduler-server/src/main/java/cn/escheduler/server/utils/ProcessUtils.java) with OpenJDKs [`ProcessImpl`](https://github.com/openjdk/jdk/blob/270fe13182e284f3f5d5ae116fb43e591535c2c6/jdk/src/java.base/windows/classes/java/lang/ProcessImpl.java) from a few years ago, you will notice that they in parts contain the same code (with some reformatting applied and comments removed or changed), mainly the `buildCommandStr` method and the private methods it is using.

(Though it could of course also be the case that the same author created this code for this project and for OpenJDK.)

### PR DESCRIPTION
**Pull request by kezhenxu94**
## Purpose of the pull request

Clean up third-party files that are not mentioned in LICENSE or NOTICE

## Brief change log

- Deleted methods in `org.apache.dolphinscheduler.server.utils.ProcessUtils` that were copied from openjdk, closes https://github.com/apache/dolphinscheduler/issues/5388
- Deleted `StringUtils` that is copied from `commons.apache.org:commons-lang`, and directly use `org.apache.commons.lang.StringUtils` instead.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Hey @CalvinKirs @yangyichao-mango https://github.com/apache/dolphinscheduler/pull/3368 , what is the reason not allowing to import `org.apache.commmons.lang`?

**Comment by CalvinKirs** [comment]
> Hey @CalvinKirs @yangyichao-mango #3368 , what is the reason not allowing to import `org.apache.commmons.lang`?

We can remove the restriction on org.apache.commons.lang in IllegalImport. IllegalImport restrictions should are based on our coding style and requirements.

**Comment by kezhenxu94** [comment]
> > Hey @CalvinKirs @yangyichao-mango #3368 , what is the reason not allowing to import `org.apache.commmons.lang`?
> 
> We can remove the restriction on org.apache.commons.lang in IllegalImport. IllegalImport restrictions should are based on our coding style and requirements.

Excellent, just wanted to confirm that it's not historical technical problem

**Comment by kezhenxu94** [comment]
Now should be good to go

**Comment by CalvinKirs** [comment]
> Now should be good to go

 this is awesome! PTAL @lenboo

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
