### PR TITLE
[Feature-7460][Alert] Wechat alert add send to group chat

### LINKED ISSUE #7460: [Feature][Alert] Wechat alert support send to group chat
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We only support sending to apps right now in 2.0.1-release. https://work.weixin.qq.com/api/doc/90000/90135/90236

We should add support send to appchat .And add a switch button in UI. https://work.weixin.qq.com/api/doc/90000/90135/90248

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

close #7460

### CODE REVIEW

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by lenboo** [comment]
would you please supplement some documents about the use of wechat alarm plug-in?
https://github.com/apache/dolphinscheduler-website

**Comment by SbloodyS** [comment]
> would you please supplement some documents about the use of wechat alarm plug-in? https://github.com/apache/dolphinscheduler-website

I'll add it.

**Review by lenboo — APPROVED** [review]
+1 well done

**Pull request merged**
