### PR TITLE
[Fix-13802][UI] Display english column name in resource center

### LINKED ISSUE #13802: [BUG][UI] Display english column name in resource center
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- After switching to english UI, it should display english column name, either.

image

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- This PR closes https://github.com/apache/dolphinscheduler/issues/13802

## Verify this pull request

image

### CODE REVIEW

**Comment by Radeity** [comment]
Hi, @jieguangzhou , can you help change the label to `3.2.0`? `3.1.4` doesn't have this bug, thanks a lot!

**Comment by Radeity** [comment]
Hi, @jieguangzhou, @songjianet , @Amy0104 , @devosend , would you like to help re-run failed CI and help review this front-end PR?

**Comment by jieguangzhou** [comment]
> Hi, @jieguangzhou, @songjianet , @Amy0104 , @devosend , would you like to help re-run failed CI and help review this front-end PR?

Done

**Comment by Radeity** [comment]
Hi, @jieguangzhou, @songjianet , @Amy0104 , @devosend, sorry to bother again, can you help me with the CI error? Maybe there's a bug, but i can not locate it...

**Comment by jieguangzhou** [comment]
@devosend @songjianet please help to review the code, It can not pass the ci

**Comment by songjianet** [comment]
> Hi, @jieguangzhou, @songjianet , @Amy0104 , @devosend, sorry to bother again, can you help me with the CI error? Maybe there's a bug, but i can not locate it...

image

**Comment by Radeity** [comment]
> > Hi, @jieguangzhou, @songjianet , @Amy0104 , @devosend, sorry to bother again, can you help me with the CI error? Maybe there's a bug, but i can not locate it...
> 
> image

Hi, @songjianet , thanks for your reply, can i simply add explicit type statement `any`?

**Comment by Radeity** [comment]
Thanks again for all your help @songjianet , @jieguangzhou , glad to see that all CI pass :D

**Review by songjianet — APPROVED** [review]

**Pull request merged**
