### PR TITLE
[Feature][server][backend] Add support multi main sql with semi colon separator

### LINKED ISSUE #1911: [Feature] Enhancement for Sql task
**Is your feature request related to a problem? Please describe.**
For now, there are 2 limitations of Sql task:
1. can't use variable for other part of sql command, because the limitation of PreparedStatement .
2. can't execute multiple sql command in task content.

**Describe the solution you'd like**
1. Replace variable firstly and then execute sql command with PreparedStatement .
2. Split multiple sql command one by one , and then execute them.

### LINKED ISSUE #3799: [Feature][*] Sql task extension, support multiple sql statement query
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*
**Background**
At present, the SQL task only supports the execution of one statement, that is, the `SQL Statement` in the  picture below currently only support one statement.
image

**Describe the feature**
Support multiple sql statement query
 - Design requirements:
1. Multiple SQL statements input by SQL Statement can be split into multiple statements;
2. Batch execution through jdbc
3. Support multiple data sources oracle, hive, postgresql, mysql

### LINKED ISSUE #4465: [Improvement][SQL component] support multiple lines of sql
**Describe the question**
现在sql组件值只支持单条sql，但希望支持多条（通过例如分号分割）

**What are the current deficiencies and the benefits of improvement**
这里应用场景是说，当sql比较多且联系紧密不可分割的时候，不见得希望每条sql一个流程节点。会过于繁琐。至少在开发阶段希望一起执行和测试。测完了基本功能可以考虑进行适当拆分成多个节点，但也未必到这么细的粒度。

**Which version of DolphinScheduler:**
 -[1.3.4]

**Describe alternatives you've considered**
虽然群里答复说：
"不支持啊, 因为jdbc只能执行一条sql, 如果是多个sql的话,没有办法做到精确拆分.
举例,以分号拆分";"  如果sql里面有注释, 注释里面包含分号";" 这个不是很好处理.
而且有的sql是按照 换行拆分的并不是按照sql拆分的.
这个你可以提个issue , 看看咋处理...
hive的话,推荐使用  shell 节点.  hive -e 执行....
"
但是，
1. 相比直接不支持多行，可以不支持注释，或者不支持注释里有分号，这都可以作为限制，不校验都行，反正写错了运行时就报错呗。
2. shell组件毕竟有一些不便。否则sql组件本身就没有存在的意义了

### LINKED ISSUE #4563: [Feature][SqlTask] Make main sql on sqltask with multi statement
**Describe the feature**
Currently, i saw dolphinscheduler sqltask have presql, mainsql and postsql. But only presql and postsql have multi choice and it not convenient and easy to use. 

**Describe the solution you'd like**
For example, we using pentaho and familar with sql step, it support multi statement with ";" delimeter. It makes we easily copy and paste bunch of sql code to sql step and run it all in once, maybe sqltask can be the same.

**Additional context**
image

### PR DESCRIPTION
**Pull request by brucemen711**
## What is the purpose of the pull request
This PR closes #4563 

Also close #3799, close #4465, close #1911

## Brief change log

  - Add support multi mainSql with non-query ( similar to many etl tools like pentaho, .... ) and remain for query with only one sql (org.apache.dolphinscheduler.server.worker.task.sql.SqlTask)

## Verify this pull request
  - Add multiple test cases.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
code style check fail, you can refer this docs resolve you question:https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

**Comment by brucemen711** [comment]
> code style check fail, you can refer this docs resolve you question:https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

I saw some testcase failed, maybe need retest @CalvinKirs

**Comment by CalvinKirs** [comment]
> > code style check fail, you can refer this docs resolve you question:https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
> 
> I saw some testcase failed, maybe need retest @CalvinKirs

Can you update your code and try to keep it synchronized with the upstream?

**Comment by CalvinKirs** [comment]
Does this design anyone have a question?

**Comment by davidzollo** [comment]
@lgcareer please review if you are free

**Comment by lgcareer** [comment]
If input the sql `SELECT CONCAT('11',';','33');`,use `;` as separator will not suitable.
But I don't find suitable method to avoid it,wish everyone to give the solution.

**Comment by brucemen711** [comment]
> If input the sql `SELECT CONCAT('11',';','33');`,use `;` as separator will not suitable.
> But I don't find suitable method to avoid it,wish everyone to give the solution.

Hi @lgcareer , maybe we using regex to remove invalid `;` on SQL statement. For example:
```
select concat('', ';', '');
select concat('1000', ';', '1000');
```
Then we split 2 statement:
``` select concat('', ';', '') and select concat('1000', ';', '1000') ```


I am using Hue (Cloudera) and I get the same behaviour.

**Comment by lgcareer** [comment]
> > If input the sql `SELECT CONCAT('11',';','33');`,use `;` as separator will not suitable.
> > But I don't find suitable method to avoid it,wish everyone to give the solution.
> 
> Hi @lgcareer , maybe we using regex to remove invalid `;` on SQL statement. For example:
> 
> ```
> select concat('', ';', '');
> select concat('1000', ';', '1000');
> ```
> 
> Then we split 2 statement:
> `select concat('', ';', '') and select concat('1000', ';', '1000')`
> 
> I am using Hue (Cloudera) and I get the same behaviour.

I think it's ok.

**Comment by brucemen711** [comment]
> > > If input the sql `SELECT CONCAT('11',';','33');`,use `;` as separator will not suitable.
> > > But I don't find suitable method to avoid it,wish everyone to give the solution.
> > 
> > 
> > Hi @lgcareer , maybe we using regex to remove invalid `;` on SQL statement. For example:
> > ```
> > select concat('', ';', '');
> > select concat('1000', ';', '1000');
> > ```
> > 
> > 
> > Then we split 2 statement:
> > `select concat('', ';', '') and select concat('1000', ';', '1000')`
> > I am using Hue (Cloudera) and I get the same behaviour.
> 
> I think it's ok.

I have implemented this feature with similar hue function and added some test cases. Please take a look @lgcareer @dailidong  @CalvinKirs

**Comment by davidzollo** [comment]
@brucemen711 , sorry for reply so late, can you solve the Conflicting files of SqlTask.java?  and then I will merge this PR, thx

**Comment by davidzollo** [comment]
image

**Comment by kezhenxu94** [comment]
No update for months, closing, please feel free to reopen if you want to continue

**Pull request closed without merging**
