### PR TITLE
[1.3.6-prepare][API] The API calls the workflow instance query interface and queries all the data when the time parameter is wrong #4817

### PR DESCRIPTION
**Pull request by CalvinKirs**
issue #4816
pr #4817

### CODE REVIEW

**Comment by zhuangchong** [comment]
+1

**Comment by CalvinKirs** [comment]
@zhuangchong please take a look,Thx

**Comment by chengshiwen** [comment]
@zhuangchong Why is there a **13.0% Code Duplication Rate**?

**Comment by CalvinKirs** [comment]
> @zhuangchong Why is there a **13.0% Code Duplication Rate**?

sonar check has a problem.

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
