### PR TITLE
[Fix-5904][upgrade]fix dev branch upgrade mysql sql script error

### LINKED ISSUE #5904: [Bug][upgrade]dev branch upgrade mysql sql script error
**Describe the bug**

```
IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS
                   WHERE TABLE_NAME='t_ds_datasource'
                     AND TABLE_SCHEMA=(SELECT DATABASE())
                     AND COLUMN_NAME ='t_ds_datasource_name_UN')
```
Create index type statement error

**Which version of Dolphin Scheduler:**
 -[dev]

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this close #5904 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
Best to follow the naming convention

**Comment by zhuangchong** [comment]
> Best to follow the naming convention

done.

**Comment by CalvinKirs** [comment]
> > Best to follow the naming convention
> 
> done.

seems not any change：）

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
