### PR TITLE
[python] Add mechanism cli with simple command

### LINKED ISSUE #8518: [Feature][python] Add basic components for CLI
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add basic configure for CLI, which includes:

* Third part CLI package
* Basics usage for CLI
* Document for CLI
* Verify work after installation
* Test on it

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Add basic cli mechanism with Click, for now just including
  one single subcommand `version`
* Add general and easy test class in tests/testing/cli, and
  test to version
* Add sphinx-click to general cli docs basic on click

ref: #8517 
close: #8518

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend @jieguangzhou thanks~

**Comment by zhongjiajie** [comment]
When my PR is just related to some issue instead of a directly closed issue, I prefer to use the keyword `ref: #<issue_number>` instead of `close: #<issue_number>`. Because keyword close would directly close the issue when this PR is merged. But in this situation, the target issue contains many sub-issue because it is a DSIP, I do not want to close it when this issue is merged. So I use `ref` in https://github.com/apache/dolphinscheduler/pull/8516#issue-1148917156

**Comment by zhongjiajie** [comment]
Our CI runs in GitHub Action https://github.com/features/actions, and the configured is in https://github.com/apache/dolphinscheduler/blob/f3d663a7eaf559e855971e83d593a827196a1aa0/.github/workflows/py-ci.yml. 

All you can see in CI run-time windows in this PR with the prefix `Python API` it created by https://github.com/apache/dolphinscheduler/blob/f3d663a7eaf559e855971e83d593a827196a1aa0/.github/workflows/py-ci.yml

**Comment by zhongjiajie** [comment]
> When my PR is just related to some issue instead of a directly closed issue, I prefer to use the keyword `ref: #<issue_number>` instead of `close: #<issue_number>`. Because keyword close would directly close the issue when this PR is merged. But in this situation, the target issue contains many sub-issue because it is a DSIP, I do not want to close it when this issue is merged. So I use `ref` in [#8516 (comment)](https://github.com/apache/dolphinscheduler/pull/8516#issue-1148917156)

I add new issue about this PR, so I add `close: #8518` just now. when this PR is merge, issue #8518 will auto close by github

**Comment by devosend** [comment]
LGTM

**Comment by zhongjiajie** [comment]
> LGTM

Thanks for reviewing. now we need @jieguangzhou for the double-check

**Review by jieguangzhou — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks~ ping @caishunfeng @songjianet I think this PR could be merged now, PTAL

**Comment by zhongjiajie** [comment]
I create an issue about add auto complete to CLI in #8521

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks for merging

**Pull request merged**
