### PR TITLE
[Bug-13882][Worker] Upgrade kubernetes-client version to 6.0.0

### LINKED ISSUE #13882: [Bug] [Worker] Collect incomplete pod log when pod fails
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Sometimes, we can not collect complete pod logs if pod fails and will throw an IOException.

We collect logs:
```
        ...
	[K8S-pod-log-spark-pi]: + CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
	[K8S-pod-log-spark-pi]: + exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.244.2.175 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.examples.SparkPi hdfs://10.176.24.55:9000/dolphinscheduler/wangwr/resources/spark-examples_2.13-3.2.0.jar 10
	[K8S-pod-log-spark-pi]: /opt/spa
```

Complete logs should be:
```
        ...
	[K8S-pod-log-spark-pi]: + CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
	[K8S-pod-log-spark-pi]: + exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.244.2.175 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.examples.SparkPi hdfs://10.176.24.55:9000/dolphinscheduler/wangwr/resources/spark-examples_2.13-3.2.0.jar 10
        [K8S-pod-log-spark-pi]: /opt/spark/bin/spark-class: line 71: /opt/jdk/bin/java: No such file or directory
	[K8S-pod-log-spark-pi]: /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
```

It can be seen that the last two lines of error logs are lost. <br><br>

### What you expected to happen

Collect complete pod log whether pod runs successfully or not.

### How to reproduce

**NOT ALWAYS INCOMPLETE!** It only happens when `PipedInputStream` and `PipedOutputStream` are closed before 
asynchronously write log (from response body of the last polling) into `PipedOutputStream`.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request

- This PR closes https://github.com/apache/dolphinscheduler/issues/13882
- Upgrade kubernetes-client version to 6.0.0, which solve the bug mentioned in above issue, it no longer uses `PipedInputStream` and `PipedOutputStream` which are replaced by `Channel` in new version, which can also solve other potential bugs.
## Brief change log

- Replace usages of deprecated `DefaultKubernetesClient` and build client in a recommended way.
- Clean the logic of pod log collection in `AbstractCommandExecutor`.

## Verify this pull request

- Manually tested, the same bug will never happen.

### CODE REVIEW

**Comment by Radeity** [comment]
I've tried different ways to solve this bug and keep dependency version unchanged, but all of them don't work well, such as we control the creation and close of `PipedInputStream` in DS.

In addition, here are some related change log of kubernetes-client :
```
The usage of Piped streams is no longer supported - they make assumptions about reading and writing threads, which the client no longer honors.  They should not be passed into 
the methods accepting InputStreams and OutputStreams.

ContainerResource.writingInput(PipedOutputStream in) and readingXXX(PipedInputStream out) have been removed - use the redirecting methods instead.
```
Thus, i think upgrade the version of this dependency is a better choice.

**Review by kezhenxu94 — COMMENTED** [review]
Please check the license file and you should need to update it.

**Comment by Radeity** [comment]
> Please check the license file and you should need to update it.

Thanks for the reminder, may i ask can we keep two different version of the same dependency? It seems like kubernetes-client v5.10.2 is a sub-dependency of sprint-boot.

**Comment by kezhenxu94** [comment]
> > Please check the license file and you should need to update it.
> 
> 
> 
> Thanks for the reminder, may i ask can we keep two different version of the same dependency? It seems like kubernetes-client v5.10.2 is a sub-dependency of sprint-boot.

If you upgrade the version in `bom` module, all the versions of kubernetes client should be the same version. All you need to do is to check whether the new version is compatible with the old one

**Comment by Radeity** [comment]
> If you upgrade the version in `bom` module, all the versions of kubernetes client should be the same version. All you need to do is to check whether the new version is compatible with the old one

Done.

**Comment by Radeity** [comment]
Hi, @kezhenxu94 , feel sorry that I miss some dependencies in last commit which have already been added now. In addition, i want to make sure that is it okay to add dependencies with CVEs?

**Comment by kezhenxu94** [comment]
> Hi, @kezhenxu94 , feel sorry that I miss some dependencies in last commit which have already been added now. In addition, i want to make sure that is it okay to add dependencies with CVEs?

It's OK but if possible we should not do that, consider upgrading to a version that has all known CVEs fixed

**Comment by Radeity** [comment]
> It's OK but if possible we should not do that, consider upgrading to a version that has all known CVEs fixed

Thanks for your reply, I've carefully checked that, CVE comes from sub-dependency `jackson-databind-2.13.4` which has been imported in  DS before, there's nothing wrong with `kubernetes-client-6.0.0`.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
