### PR TITLE
[Feature-10837][Task Plugin] Sqoop Task Add --split-by Parameter

### LINKED ISSUE #10837: [Feature][Task Plugin] Sqoop Task Add --split-by Parameter
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When sqoop param -m >1, we should set --split-by.

### Use case

Set sqoop parameter --split-by

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shangeyao**
## Purpose of the pull request
close #10837

### CODE REVIEW

**Comment by zhuangchong** [comment]
Please fix checkstyle and ut.

**Review by zhuangchong — APPROVED** [review]
+1

**Review by Amy0104 — APPROVED** [review]
The front end part LGTM.

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
