### PR TITLE
Add alert server into standalone-server as well and some minor polish

### PR DESCRIPTION
**Pull request by kezhenxu94**
## Purpose of the pull request

Add alert server into standalone server as well, now the standalone server should be feature-complete.

Make `AlertServer#start` non-blocking, it was blocking and the codes after `AlertServer#start` won't be executed, causing unexpected problems, now `AlertServer#start` is background thread and the shutdown hook can be registered successfully.

## Brief change log

- Add alert server to standalone server.
- Fix `.asf.yaml` invalid character.
- Some minor polish in alert server.
- Remove pointless comments.
- Reformat h2 `.sql` file.
- Remove unused util class.

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
It seem standalone server could not work correct, it work fine days ago before I rebase to dev, did I miss something or some configure? @kezhenxu94 

```log
Exception in thread "Standalone-Server" java.lang.RuntimeException: Load Alert Plugin Failed !
	at org.apache.dolphinscheduler.alert.AlertServer.initPlugin(AlertServer.java:100)
	at org.apache.dolphinscheduler.alert.AlertServer.start(AlertServer.java:119)
	at org.apache.dolphinscheduler.server.StandaloneServer.startAlertServer(StandaloneServer.java:80)
	at org.apache.dolphinscheduler.server.StandaloneServer.main(StandaloneServer.java:62)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 29999
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.readClass(DolphinPluginDiscovery.java:125)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.classInterfaces(DolphinPluginDiscovery.java:110)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.lambda$discoverPluginsFromArtifact$0(DolphinPluginDiscovery.java:77)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.discoverPluginsFromArtifact(DolphinPluginDiscovery.java:78)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoaderFromPom(DolphinPluginLoader.java:138)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoader(DolphinPluginLoader.java:123)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugin(DolphinPluginLoader.java:99)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugins(DolphinPluginLoader.java:92)
	at org.apache.dolphinscheduler.alert.AlertServer.initPlugin(AlertServer.java:98)
	... 3 more
```

**Comment by kezhenxu94** [comment]
> It seem standalone server could not work correct, it work fine days ago before I rebase to dev, did I miss something or some configure? @kezhenxu94 
> 
> 
> 
> ```log
> 
> Exception in thread "Standalone-Server" java.lang.RuntimeException: Load Alert Plugin Failed !
> 
> 	at org.apache.dolphinscheduler.alert.AlertServer.initPlugin(AlertServer.java:100)
> 
> 	at org.apache.dolphinscheduler.alert.AlertServer.start(AlertServer.java:119)
> 
> 	at org.apache.dolphinscheduler.server.StandaloneServer.startAlertServer(StandaloneServer.java:80)
> 
> 	at org.apache.dolphinscheduler.server.StandaloneServer.main(StandaloneServer.java:62)
> 
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 29999
> 
> 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
> 
> 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.readClass(DolphinPluginDiscovery.java:125)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.classInterfaces(DolphinPluginDiscovery.java:110)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.lambda$discoverPluginsFromArtifact$0(DolphinPluginDiscovery.java:77)
> 
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
> 
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> 
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
> 
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.discoverPluginsFromArtifact(DolphinPluginDiscovery.java:78)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoaderFromPom(DolphinPluginLoader.java:138)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoader(DolphinPluginLoader.java:123)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugin(DolphinPluginLoader.java:99)
> 
> 	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugins(DolphinPluginLoader.java:92)
> 
> 	at org.apache.dolphinscheduler.alert.AlertServer.initPlugin(AlertServer.java:98)
> 
> 	... 3 more
> 
> ```

I suspect you are using old versions compiled classes of the previous plugin and after rebased the classes are not correct. Maybe try to rebuild the plugins?

**Comment by CalvinKirs** [comment]
There is another situation：
using plugin.binding usually requires you to manually compile the plugin, you can try mvn complie first and then run StandaloneServer again

**Comment by zhongjiajie** [comment]
You're right, it work fine after I rebuild! THX

**Pull request merged**
