### PR TITLE
[Improvement][DataSourcePlugin]tiny optimize of datasource plugin module

### LINKED ISSUE #14541: [Improvement][DataSourcePlugin]tiny optimize of datasource plugin module
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

when I study  adding datasource plugin, i find the datasource-special constants like `COM_CLICKHOUSE_JDBC_DRIVER = "com.clickhouse.jdbc.ClickHouseDriver"` only used in ClickHouseDataSourceProcessor, so i move all related constant to the special DataSourceProcessor, it does not make too much sense, I just think it is a better format and pattern, after that, I can easily setDefaultValidationQuery to fit various datasource, which has problem using the original code.
So you can evaluate if this change is needed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by genuinner**
* move datasource-special constant like JDBC_DRIVER to DataSourceProcessor
* change the CommonDataSourceClient.setDefaultValidationQuery() to fit various datasource
* override OceanBaseDataSourceClient.setDefaultValidationQuery() cause CompatibleMode is needed
* this pr does not make too much sense, I just think it is a better pattern, it also fixes setValidationQuery problem too!

close #14541

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please link to your issue and describe why you want to do such a big change. @genuinner

**Comment by genuinner** [comment]
> 
sorry, this is my first pr, im not familiar with github and conduct

**Comment by genuinner** [comment]
[https://github.com/apache/dolphinscheduler/issues/14541](url)

**Comment by genuinner** [comment]
#14540

**Comment by genuinner** [comment]
#14541

**Comment by SbloodyS** [comment]
PTAL @ruanwenjun

**Comment by ruanwenjun** [comment]
Please resolve the conflict, move the constant is ok for me.

**Review by rickchengx — COMMENTED** [review]
Hi, @genuinner please resolve the conflicts

**Comment by SbloodyS** [comment]
Closing due to inactivity.

**Pull request closed without merging**
