### PR TITLE
[Fix-5386][Alert] Fix ERROR: relation t_ds_plugin_define does not exist

### LINKED ISSUE #5386: [Bug][Alert] ERROR: relation "t_ds_plugin_define" does not exist
**To Reproduce**
Steps to reproduce the behavior, for example:
1. Run `docker-compose up -d`
2. Run `docker logs -f dolphinscheduler-alert`
3. See error

**Expected behavior**
Bug fixed

**Screenshots**
Alert logs:
```
[INFO] 2021-04-26 00:27:39.678 org.apache.dolphinscheduler.alert.plugin.AlertPluginManager:[104] - Registering Alert Plugin 'DingTalk'
[INFO] 2021-04-26 00:27:39.681 org.apache.dolphinscheduler.alert.plugin.AlertPluginManager:[86] - -- Loaded Alert Plugin DingTalk --
[INFO] 2021-04-26 00:27:41.901 com.alibaba.druid.pool.DruidDataSource:[994] - {dataSource-1} inited
Exception in thread "main" java.lang.RuntimeException: load Alert Plugin Failed !
	at org.apache.dolphinscheduler.alert.AlertServer.initPlugin(AlertServer.java:104)
	at org.apache.dolphinscheduler.alert.AlertServer.start(AlertServer.java:145)
	at org.apache.dolphinscheduler.alert.AlertServer.main(AlertServer.java:161)
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "t_ds_plugin_define" does not exist
  Position: 23
### The error may exist in org/apache/dolphinscheduler/dao/mapper/PluginDefineMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select *         from t_ds_plugin_define         where plugin_name = ? and plugin_type = ?
### Cause: org.postgresql.util.PSQLException: ERROR: relation "t_ds_plugin_define" does not exist
  Position: 23
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "t_ds_plugin_define" does not exist
  Position: 23
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy11.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy15.queryByNameAndType(Unknown Source)
	at org.apache.dolphinscheduler.dao.PluginDao.addOrUpdatePluginDefine(PluginDao.java:67)
	at org.apache.dolphinscheduler.alert.plugin.AlertPluginManager.installPlugin(AlertPluginManager.java:111)
	at org.apache.dolphinscheduler.common.plugin.DolphinPluginLoader.loadPlugin(DolphinPluginLoader.java:111)
	at org.apache.dolphinscheduler.common.plugin.DolphinPluginLoader.loadPlugin(DolphinPluginLoader.java:99)
	at org.apache.dolphinscheduler.common.plugin.DolphinPluginLoader.loadPlugins(DolphinPluginLoader.java:85)
	at org.apache.dolphinscheduler.alert.AlertServer.initPlugin(AlertServer.java:102)
	... 2 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "t_ds_plugin_define" does not exist
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy23.query(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 14 more
End start alert-server.
2021-04-26 00:27:43,637 INFO exited: alert (exit status 0; expected)
```

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

*[Fix-5386][Alert] Fix ERROR: relation t_ds_plugin_define does not exist*

This closes #5386

## Brief change log

  - *Add `int checkTableExist()` in `PluginDefineMapper`*
  - *Add `boolean checkPluginDefineTableExist()` in `PluginDao`*
  - *Add `void checkTable()` in `AlertServer`*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by CalvinKirs** [comment]
The table does not seem to exist. In this case, the alarm will not function properly. 
Therefore, this may not be a problem.

**Comment by chengshiwen** [comment]
> The table does not seem to exist. In this case, the alarm will not function properly.
> Therefore, this may not be a problem.

@CalvinKirs In most cases, it is not a problem. In the case of **one-click deployment**, such as **docker/k8s**, the first time `alert-server` is started, it often fails because `t_ds_plugin_define` is not created. This will affect the experience of the first deployment of new users. So it would be better to add this judgment.

**Comment by zhuangchong** [comment]
@chengshiwen 

 I don't think it's a problem.If you want to improve the user experience, you should provide detection during the first deployment.

---
我认为这不是问题，表不存在创建表就行了，为什么要加每次循环都去判断表是否存在，多余的步骤，初始化一次就够了。如果想做提升用户体验，应该在首次部署提供检测。

**Comment by chengshiwen** [comment]
> I don't think it's a problem.If you want to improve the user experience, you should provide detection during the first deployment.

I have tried other ways and find out no better way. At present, it is the best way to check the table in `alert-server` and it's very simple. A good program should manage its dependencies.
I don't want to spend too much time explaining to new users why the `alert-server` will cause startup failures in **docker/k8s one-click deployment**. Just a few lines of code can solve this problem well, why are we bothered by it?
**One-click deployment** is equivalent to **the first deployment**. You can try to deploy ds by docker or k8s and tell me the better way.

**Comment by zhuangchong** [comment]
> > I don't think it's a problem.If you want to improve the user experience, you should provide detection during the first deployment.
> 
> I have tried other ways and find out no better way. At present, it is the best way to check the table in `alert-server` and it's very simple. A good program should manage its dependencies.
> I don't want to spend too much time explaining to new users why the `alert-server` will cause startup failures in **docker/k8s one-click deployment**. Just a few lines of code can solve this problem well, why are we bothered by it?
> **One-click deployment** is equivalent to **the first deployment**. You can try to deploy ds by docker or k8s and tell me the better way.

A good program should manage its dependencies. What's more, it should check all the dependencies before the program starts. If there is a problem with the dependencies, it will directly truncate and prompt the user

In order to deploy docker / k8s with one click, cycle to check whether the plugin table exists. The one click deployment is successful, and the alert function in alert server is not really started. (in order to deploy with one click, others can be hidden?) This will also cause some users to think that the deployment has been successful and they can't receive the alarm. Maybe they find that the plugin table doesn't exist because they haven't received the alarm. This is not as good as the current way. When deploying, errors will be displayed, and users will solve this problem.

---

一个好的程序是应该管理其依赖项, 那更应该做的是在程序启动前检查所有依赖项，依赖项存在问题，直接截断提示用户。

为了docker / k8s一键部署,循环检测plugin表是否存在,一键部署是成功了,alert-server内告警功能并没有真正启动，（为了可以一键部署，其他都可以隐藏？）这也会造成一部分用户认为已经部署成功，接收不到告警，也许发现plugin表不存在是因为没有收到告警。这样还不如现在的方式，在部署的时候就显示错误，用户就会解决这个问题。

**Comment by chengshiwen** [comment]
@zhuangchong Do you know what I'm talking about?

**Comment by chengshiwen** [comment]
I added the following lines:
```java
private void checkTable() {
    if (!pluginDao.checkPluginDefineTableExist()) {
        logger.error("Plugin Define Table t_ds_plugin_define Not Exist . Please Create it First !");
        System.exit(1);
    }
}
```
And I have tried to improve the unit test coverage. However, due to the small number of modified code lines and the difficulty of mocking, I do not plan to update anymore

@CalvinKirs

**Comment by zhuangchong** [comment]
When you deploy with one click of docker, the alert plugin report does not exist, which leads to the failure of the whole deployment

What you do: add a loop in the alert server startup to check whether the plugin table exists. If it does not exist, always print the warning log (I see that you just added a loop number judgment)

I don't know if I understand this issue

If I understand correctly, I reserve my opinion.

Formally, from a global perspective, I suggest that dependencies be detected before starting the program during deployment. What I don't understand is that the one click deployment is successful, but the alert server can't alarm normally because the table doesn't exist, and the service process is still there. This is to improve the user experience from a global perspective?

If there is no difference, there will be no discussion. I reserve my opinion
---

你在使用docker 一键部署的时候遇到alert plugin表报错不存在，导致整个部署失败

你的做法：在alert-server启动里面加了一个循环检查plugin表是否存在功能，如果不存在一直打印警告日志（我看你刚刚加看一个循环次数的判断）

不知道这是不是理解了这个issue

如果我理解的正确，我保留我的意见。

正式从全局角度出发，我建议是在部署过程中启动程序前去检测依赖项。我不理解的是让用户部署一键部署成功了，但是alert-server因为表不存在，不能正常告警，服务进程还在，这个就是从全局角度出发，提升了用户体验？

如果没有分歧，就不会发生讨论，我保留自己的意见。

**Comment by chengshiwen** [comment]
@zhuangchong 
**I have told you that I have tried other ways and find out no better way.**

From your statements, the following conclusions can be drawn:
- You do not know docker/k8s, and have not deployed ds by docker/k8s
- You don’t have a sense of the product, and you can’t even judge what is right and what is wrong
- You don’t know the facts and draw conclusions too early, and give people a rejected view, not a suggestion for modification
- Your engineering ability is not enough to review this code, you have given several opposite opinions in recent times, lacking credibility

Therefore, I will reject your review in the future, and no longer waste my time.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
