### PR TITLE
The sql has a syntax error, and because it is a function, the excepti…

### PR DESCRIPTION
**Pull request by uh001**
…on information will be hidden

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by zhuangchong — COMMENTED** [review]
Does the mysql ddl file need to be modified at the same time?

**Comment by uh001** [comment]
@zhuangchong Because our company uses pg, so only checked pg_ddl

**Comment by zhuangchong** [comment]
@uh001 
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Review by zhuangchong — APPROVED** [review]
+1

**Pull request merged**
