### PR TITLE
[Fix-13780][api] Fix the problem of process instance DAG can't show dependent task

### LINKED ISSUE #13780: [Bug] [API] Process instance DAG can't show dependent task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi，I found that the dependent tasks in the DAG of the process instance cannot be displayed. 
image

image

I think it should be caused by the modification of the log format in this [PR](https://github.com/apache/dolphinscheduler/pull/10593/files). 
image
In the `ProcessInstanceServiceImpl#parseLogForDependentResult` method, it appears to attempt parsing the running result of the dependent task using the `DEPENDENT_SPLIT` constant. Additionally, the running result in the log has been modified. So the parse method will not work too.

### What you expected to happen

The process instance DAG displays dependent tasks in the same way as the process definition DAG.

### How to reproduce

Create two process definitions like the following screenshots.
image
image
image

### Anything else

_No response_

### Version

3.1.4

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ralphgj**
## Purpose of the pull request

close #13780 

## Brief change log
Fix the problem of process instance DAG can't show dependent task

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — CHANGES_REQUESTED** [review]
Please change your target branch to `dev`. @ralphgj

**Comment by ralphgj** [comment]
@SbloodyS  Could you merge this pr or any other suggestions?

**Review by SbloodyS — DISMISSED** [review]
LGTM if CI passed.

**Comment by SbloodyS** [comment]
@ralphgj Please pull the latest dev code and push again.

**Comment by ralphgj** [comment]
@SbloodyS done

**Comment by fuchanghai** [comment]
@SbloodyS

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by SbloodyS** [comment]
Thanks for your contribution. This is a good beginning. Considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(SbloodyS), when mail or added, please tell me who you are. I think I can help to familiar with the Dolphinscheduler if you meet with problems. @ralphgj

**Pull request merged**
