### PR TITLE
[Docs] Modify standalone docs

### PR DESCRIPTION
**Pull request by ChrisYuan**
## Purpose of the pull request

this pr fix the main class name for standalone running environment in docs (both Chinese and English version ).

## Brief change log

No change test, only docs.

Reason refer to attached screenshot.

image

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by SbloodyS** [comment]
Hi @ChrisYuan , please describe the title in English next time.

BTW, please associate related issue.

**Comment by ChrisYuan** [comment]
OK, I didn't add a issue this time. Do I need to add issue firstly and push a pr everytime?

**Comment by ChrisYuan** [comment]
> Hi @ChrisYuan , please describe the title in English next time.
> 
> 
> 
> BTW, please associate related issue.


OK, I didn't add a issue this time. Do I need to add issue firstly and push a pr everytime?

**Comment by SbloodyS** [comment]
> OK, I didn't add a issue this time. Do I need to add issue firstly and push a pr everytime?

Yes. Usually it is necessary.

**Comment by ChrisYuan** [comment]
> Hi @ChrisYuan , please describe the title in English next time.
> 
> 
> 
> BTW, please associate related issue.

BTW, do I need to assign a CLA?

**Comment by ChrisYuan** [comment]
> > OK, I didn't add a issue this time. Do I need to add issue firstly and push a pr everytime?
> 
> 
> 
> Yes. Usually it is necessary.

Ok, got it.

**Comment by zhongjiajie** [comment]
> > Hi @ChrisYuan , please describe the title in English next time.
> > BTW, please associate related issue.
> 
> BTW, do I need to assign a CLA?

no, currently it is good

**Pull request merged**
