### PR TITLE
[doc] Correct standalone URL

### PR DESCRIPTION
**Pull request by mklzl**
Improve the browser path to the home page

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by davidzollo — APPROVED** [review]
+1
good job

**Review by zhongjiajie — COMMENTED** [review]
can you find all `http://localhost:12345/dolphinscheduler/ui` in our docs and change them in this PR?

**Comment by EricGao888** [comment]
Chinese version docs: #11309

**Comment by zhongjiajie** [comment]
> Chinese version docs: #11309

@mklzl can you combine https://github.com/apache/dolphinscheduler/pull/11309 into this PR?

**Pull request closed without merging**
