### PR TITLE
[Improvement][Service] Update the wrong comment in TaskPriorityQueueImpl.java

### PR DESCRIPTION
**Pull request by Yao-MR-zz**
## Purpose of the pull request

remove the wrong annotion

### CODE REVIEW

**Review by Technoboy- — CHANGES_REQUESTED** [review]
Coments should keep.
If the description is not accurate, try to update it, not remove.

**Review by chengshiwen — APPROVED** [review]
Update it

**Review by chengshiwen — APPROVED** [review]
+1

**Review by Technoboy- — APPROVED** [review]
+1

**Pull request merged**
