### PR TITLE
[Fix][Master] Fix Potential danger in the event of a worker failover

### LINKED ISSUE #15688: [Bug] [Master] Potential  danger in the event of a worker failover
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```java
    public void removeWorkerNodePath(String path, RegistryNodeType nodeType, boolean failover) {
        log.info("{} node deleted : {}", nodeType, path);
        try {
            String serverHost = null;
            if (!StringUtils.isEmpty(path)) {
                serverHost = registryClient.getHostByEventDataPath(path);
                if (StringUtils.isEmpty(serverHost)) {
                    log.error("server down error: unknown path: {}", path);
                    return;
                }
                if (!registryClient.exists(path)) {
                    log.info("path: {} not exists", path);
                }
            }
            // failover server
            if (failover) {
                failoverService.failoverServerWhenDown(serverHost, nodeType);
            }
        } catch (Exception e) {
            log.error("{} server failover failed", nodeType, e);
        }
    }
```
When call `removeWorkerNodePath` , if its first param named path is null, it will cause `serverHost` is null.
And it  is unacceptable when call `failoverService.failoverServerWhenDown`, because in `failoverServerWhenDown` method block , `masterFailoverService.failoverMaster` and `workerFailoverService.failoverWorker` had already been emphasized that serverHost cannot be NULL  by adding NonNull annotations

### What you expected to happen

please assign this issue to me,  I'm glad to deal with this issue

### How to reproduce

make the situation of the path is null or empty string, and call removeWorkerNodePath, it will happen.

 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ZhongJinHacker**
## Purpose of the pull request
This pull request to fix #15688 , when path is null or empty, it will cause serverhost is null, it is danger

please check the issue out for details 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Review by SbloodyS — CHANGES_REQUESTED** [review]
Please use English in commit message.

**Comment by ZhongJinHacker** [comment]
> Please use English in commit message.

fixed

**Review by SbloodyS — APPROVED** [review]

**Pull request merged**
