### PR TITLE
[Improvement][common]Task status error

### PR DESCRIPTION
**Pull request by didiaode18**
## Purpose of the pull request

[Improvement][common]When I run a spark task, the webui observation in yarn is successful, but the response result in dolphinscheduler fails. #5026

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM.
btw,It is best to provide UT for verification in each subsequent PR.

**Comment by CalvinKirs** [comment]
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by didiaode18** [comment]
> LGTM.
> btw,It is best to provide UT for verification in each subsequent PR.
Thanks for your advice,i hope to review me more in the future

**Comment by didiaode18** [comment]
Thanks for your advice,i hope to review me more in the future

**Pull request merged**
