### PR TITLE
Commented out sections of PR template

### PR DESCRIPTION
**Pull request by fredster33**
## What is the purpose of the pull request
Commented out sections of the PR template. When commented out, even if the PR creator forgets to remove the tips, they will not appear in the PR when it is submitted.

## Brief change log
Commented out various sections of the PR template

## Verify this pull request
This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
I think this is not a good solution. If you delete it, the user may not know how to write a PR description. As you can see, other projects do the same. If you want to avoid the situation you mentioned, you can ask the committer to make changes when you merge PR.

**Comment by davidzollo** [comment]
> I think this is not a good solution. If you delete it, the user may not know how to write a PR description. As you can see, other projects do the same. If you want to avoid the situation you mentioned, you can ask the committer to make changes when you merge PR.

+1, I take your point

**Comment by fredster33** [comment]
> I think this is not a good solution. If you delete it, the user may not know how to write a PR description. As you can see, other projects do the same. If you want to avoid the situation you mentioned, you can ask the committer to make changes when you merge PR.

This is only "commenting out", when the user opens a PR they will still see it, but if they forget to delete it, it's not visible. It will still be visible in the editing pane.

**Review by CalvinKirs — APPROVED** [review]
lgtm

**Pull request merged**
