### PR TITLE
[DSIP-57][Audit] Revert PR 14981 code

### LINKED ISSUE #16367: [DSIP-57][Audit] Refactor PR 14981 code
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

There are currently two ways to implement auditing. We should only keep one, and the implementation of #15554 is better, so refactor #14981 as the implementation of #15554

- Revert #14981 in #16370 since we already have #15554 to implement the audit part.
- Since the current workflow state is refactored in https://github.com/apache/dolphinscheduler/pull/16327, will add a new workflow state listener after it's merged.

### Design Detail

_No response_

### Compatibility, Deprecation, and Migration Plan

_No response_

### Test Plan

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by caishunfeng** [comment]
The pr #14981 add the alert event listener,  I think it's not same with audit log.

This pr seems to revert it, right? Please correct me if I'm wrong. 

Can add some brief change log pr description?

**Comment by SbloodyS** [comment]
> The pr #14981 add the alert event listener, I think it's not same with audit log.
> 
> This pr seems to revert it, right? Please correct me if I'm wrong.
> 
> Can add some brief change log pr description?

Yes. I've discuss it with @ruanwenjun . Since the current workflow state is refactored in #16327, will add a new workflow state listener after it's merged.

**Review by caishunfeng — APPROVED** [review]
LGTM overall

**Review by ruanwenjun — APPROVED** [review]
Do we need to revert some doc? I am not sure.

**Comment by SbloodyS** [comment]
> Do we need to revert some doc? I am not sure.

So far I have not found the relevant document...

**Pull request merged**
