### PR TITLE
[Improvement][Dao] SQL optimization - limit one piece of data #5061

### PR DESCRIPTION
**Pull request by Linkaiup**
## Purpose of the pull request
See #5061

This pull request improvement the PluginDefineMapper dao

## Brief change log

1.Change from select all data to limit one piece of data
2.Change the Test code too. 

## Verify this pull request
This pull request is already covered by existing tests, such as *(PluginDefineTest.testQueryByNameAndType)*.

### CODE REVIEW

**Comment by Linkaiup** [comment]
@CalvinKirs Looking forward to your code review!

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Comment by Linkaiup** [comment]
> LGTM

could you please approve to run workflow for this PR?@caishunfeng

**Review by CalvinKirs — DISMISSED** [review]

**Comment by davidzollo** [comment]
> > LGTM
> 
> could you please approve to run workflow for this PR?@caishunfeng

done, it's running

**Comment by Linkaiup** [comment]
I improve some code to get A rate for sonarcloud @dailidong @CalvinKirs @caishunfeng I submited the code again

**Comment by Linkaiup** [comment]
Now, I modified the PR according to sonarcloud  prompts and re-push the code~ Please review again@CalvinKirs @caishunfeng

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
thanks for your first contribution, I'm looking forward to see your deep participation, if you meet any question, please contact me through my  wechat(Kris_Evil), please tell me your github id when added

**Comment by Linkaiup** [comment]
> thanks for your first contribution, I'm looking forward to see your deep participation, if you meet any question, please contact me through my wechat(Kris_Evil), please tell me your github id when added

Thank you for your affirmation! In my spare time, I will continue to pay attention to the dynamics of the DS community and continue to contribute my own strength!

**Pull request merged**
