### PR TITLE
[Feature][Common] Add ZK distributed lock.

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

Add ZK distributed lock.

## Brief change log

related #11337 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Registry already contains a method to acquire lock.

**Comment by WangJPLeo** [comment]
> Registry already contains a method to acquire lock.

ok,thx. I'll see if the test fits the scene.

**Comment by WangJPLeo** [comment]
> > Registry already contains a method to acquire lock.
> 
> ok,thx. I'll see if the test fits the scene.

Yes, this wheel doesn't need to be rebuilt haha, thx @ruanwenjun

**Comment by WangJPLeo** [comment]
This wheel is exist.

**Pull request closed without merging**
