### PR TITLE
[Feature-10604] Task name in the copied and imported workflow without copy suffix

### LINKED ISSUE #10604: [Feature][Api] Task name in the copied workflow without copy suffix
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In most cases, the task name does not need to be changed in copied workflow ,  task name do not need add copy suffix

### Use case

copied task name without copy suffix
image

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
## Purpose of the pull request

close #10604

### CODE REVIEW

**Comment by SbloodyS** [comment]
In dev, we split the task instance from the workflow instance. After the task instance is copied, the user will query two task definitions with the same name and content, which will cause some confusion. I think we should discuss about it.

**Comment by zhuxt2015** [comment]
> In dev, we split the task instance from the workflow instance. After the task instance is copied, the user will query two task definitions with the same name and content, which will cause some confusion. I think we should discuss about it.

In my opinion, I only care about whether the tasks under my workflow are successfully executed, and I don't care much about whether the name is duplicated with other workflows. 

Instead, copy suffix  redundant, but removing the copy suffix is a waste of time for me. 

I've also encountered multiple copy suffixes in task name that caused copy failed/
image

In addition, if the user wants to avoid duplication, the task name can be modified manually.

**Comment by zhongjiajie** [comment]
It is incompatible change and we need dissuss about it. Maybe some users already have some function base on this behavior.

If we accept this, please notice that we have import function will also add suffix to it

**Comment by zhongjiajie** [comment]
BTW, it make no sence to me with your word

> In my opinion, I only care about whether the tasks under my workflow are successfully executed, and I don't care much about whether the name is duplicated with other workflows.

So the name it is not important in your cases

> Instead, copy suffix redundant, but removing the copy suffix is a waste of time for me.
> In addition, if the user wants to avoid duplication, the task name can be modified manually.

Seem are opposing viewpoints

**Comment by zhongjiajie** [comment]
> I've also encountered multiple copy suffixes in task name that caused copy failed

But we may take more care about this one

**Comment by zhongjiajie** [comment]
If we want to remove the `copy` and `import` suffix, we  should add some incompatible notice in our release note

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Did we want to add this to version 3.0.0? @SbloodyS @caishunfeng

**Comment by SbloodyS** [comment]
> Did we want to add this to version 3.0.0? @SbloodyS @caishunfeng

I'm not quite sure about it.

**Pull request merged**
