### PR TITLE
[Fix-14685] [Task] Remove override method k8sConfigYaml in ShShellInterceptorBuilder

### LINKED ISSUE #14685: [Bug] [Task] Remove override method k8sConfigYaml in ShShellInterceptorBuilder
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Set `shell.interceptor.type` to `sh`, run Spark on K8S task, do not set `k8sConfigYaml` in `ShShellInterceptorBuilder`, because there's an override method in `ShShellInterceptorBuilder` which directly return null.

### What you expected to happen

Remove this override method.

### How to reproduce

Ditto.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- close https://github.com/apache/dolphinscheduler/issues/14685

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by qingwli — APPROVED** [review]
LGTM

**Review by SbloodyS — COMMENTED** [review]
Please link to your issue and describe it.

**Comment by Radeity** [comment]
> Please link to your issue and describe it.

Sure, btw, recently, `HiveDataSourceE2ETest` and `SqlServerDataSource` fail often, do you have any idea to improve that or check the test environment?

**Comment by SbloodyS** [comment]
> > Please link to your issue and describe it.
> 
> Sure, btw, recently, `HiveDataSourceE2ETest` and `SqlServerDataSource` fail often, do you have any idea to improve that or check the test environment?

I have already noticed this issue. This is due to the low server configuration provided by Github Actions. So far, I haven't found a solution, so these two tests won't affect the final detection status of CI, causing PR to be unable to merge.

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
