### PR TITLE
[Improvement][common] Upgrade the version of fastjson from 1.2.61 to 1.2.75

### LINKED ISSUE #5706: [Improvement][common] Upgrade the version of fastjson from 1.2.61 to 1.2.75
To solve known bugs, upgrade fastjson

### PR DESCRIPTION
**Pull request by brave-lee**
this closes #5706

### CODE REVIEW

**Comment by CalvinKirs** [comment]
please resolve the license check error. you can refer to this doc(https://dolphinscheduler.apache.org/zh-cn/community/development/DS-License.html)

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
@lenboo PTAL,Thx

**Review by davidzollo — APPROVED** [review]
+1
good job

**Pull request merged**
