### PR TITLE
[Fix-13480][Resource] When downloading a file, an error will occur wh…

### PR DESCRIPTION
**Pull request by LiJie20190102**
…en uploading the file

## Purpose of the pull request

ref #13480 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

Added org.apache.dolphinscheduler.service.storage.impl.OssOperatorTest#testUpload
Added org.apache.dolphinscheduler.service.storage.impl.OssOperatorTest#testDownload

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — CHANGES_REQUESTED** [review]
Please change your target branch to dev.

BTW, it's better to describe why you do this.

**Comment by LiJie20190102** [comment]
> Please change your target branch to dev.
> 
> BTW, it's better to describe why you do this.

When I download a file from DS, if another program happens to upload the file to DS at this time, there will be a problem, even if the probability of the problem is relatively low. Taking HDFS as an example: If a program is reading a file from HDFS and another program uploads and replaces the file to HDFS, a problem will occur. I have added a testing method on #13480  to reproduce this issue。

BTW，his issue has always existed, so does 3.1. x. Do both 3.1. x and dev need to raise PR？

**Review by Radeity — CHANGES_REQUESTED** [review]
i don't think it's a good fix by using distributed lock.
- First, it's ineffective when users do not use DS api to upload and download resources. 
- Second, i think this error happens because when executing `fs.copyFromLocalFile`, resource will be overwritten, old block will be set invalid or removed, and then throw `ReplicaNotFoundException`. For HDFS, maybe we can try to download again when handling that exception. 

**Anyway, it's not a general error for all types of resources**. Like s3, if enable version control, this error will never happen. So, in this scenario, maintain such a distributed lock is meaningless.

**Comment by LiJie20190102** [comment]
@Radeity 
--“First, it's ineffective when users do not use DS api to upload and download resources.”
If there are many executing tasks reading the same resource from DS at the same time (i.e. downloading), and the DS web interface uploads the resource again, there is a possibility of problems occurring. I think this situation should be very common

--“Second, i think this error happens because when executing fs.copyFromLocalFile, resource will be overwritten, old block will be set invalid or removed, and then throw ReplicaNotFoundException. For HDFS, maybe we can try to download again when handling that exception.”
If many scheduled tasks are reading the same resource file and you update the file resource, I hope the scheduled task can obtain new or old resource files. At the very least, the task will not have any exceptions, rather than throwing exceptions to say that the file has an exception.

BTW，I currently only implement HDFS's distributed lock function. If other resource storage does not have this issue, resource locks can be ignored.

**Comment by Radeity** [comment]
Hi, @LiJie20190102 , i totally understand this exception will happen in the scenario you describe above, however, i think my points mentioned before are still reasonable, WDYT? 

The first point means that this exception will still happen when user use native HDFS api to upload resource, and the second point suggests avoid introducing such a complicated concurrent control on top of HDFS, why not directly try to download again?

**Comment by LiJie20190102** [comment]
Hi, @Radeity When downloading resources, if it is DS web downloading resources, I think it can prompt an exception. But if the workflow is running a task, it will go to HDFS to download resources, and there is an exception when downloading resources. Does this cause the task to generate an exception and stop?

**Comment by Radeity** [comment]
> Hi, @Radeity When downloading resources, if it is DS web downloading resources, I think it can prompt an exception. But if the workflow is running a task, it will go to HDFS to download resources, and there is an exception when downloading resources. Does this cause the task to generate an exception and stop?

I think if you configure to enable retry task, in next execution, it can download new resources.

**Comment by LiJie20190102** [comment]
> I think if you configure to enable retry task, in next execution, it can download new resources.
 @Radeity 
But why do we need to make an error in the task and try the task again? If the content of the resource I replaced does not affect the data execution results, but it causes an exception in the task at this time, I think this is a bit unreasonable. If an exception occurs and the task is retried, the operation and maintenance personnel will have to locate the cause of the problem, which undoubtedly increases the workload.

**Comment by Radeity** [comment]
> But why do we need to make an error in the task and try the task again? If the content of the resource I replaced does not affect the data execution results, but it causes an exception in the task at this time, I think this is a bit unreasonable. If an exception occurs and the task is retried, the operation and maintenance personnel will have to locate the cause of the problem, which undoubtedly increases the workload.

I never say we should retry the task... just answer your last question. And my points are clear at the beginning, maybe we should better not introduce this heavy distributed lock.

**Comment by LiJie20190102** [comment]
> > But why do we need to make an error in the task and try the task again? If the content of the resource I replaced does not affect the data execution results, but it causes an exception in the task at this time, I think this is a bit unreasonable. If an exception occurs and the task is retried, the operation and maintenance personnel will have to locate the cause of the problem, which undoubtedly increases the workload.
> 
> I never say we should retry the task... just answer your last question. And my points are clear at the beginning, maybe we should better not introduce this heavy distributed lock.

Okay, if we don't introduce distributed locks, what should we do if an exception occurs while the task is downloading HDFS resources

**Comment by Radeity** [comment]
> maybe we can try to download again when handling that exception

That's my personal suggestion, directly re-download, WDYT? cc @SbloodyS

**Pull request closed without merging**
