### PR TITLE
[Fix-8913][Worker]fix roll view log null exception

### LINKED ISSUE #8913: [Bug] [Worker] roll view log error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
java.lang.NullPointerException: null
	at java.lang.String.startsWith(String.java:1405)
	at java.lang.String.startsWith(String.java:1434)
	at org.apache.dolphinscheduler.server.log.LoggerRequestProcessor.checkPathSecurity(LoggerRequestProcessor.java:149)
	at org.apache.dolphinscheduler.server.log.LoggerRequestProcessor.process(LoggerRequestProcessor.java:103)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2022-03-15 12:46:54.403 org.apache.dolphinscheduler.service.log.LogClientService:[101] - roll view log error
```

### What you expected to happen

roll view log is normal

### How to reproduce

View the online log of a task

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this pr close #8913

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by EricJoy2048 — APPROVED** [review]
+1

**Comment by EricJoy2048** [comment]
can you copy it to branch:2.0.6-prepare ?

**Comment by zhuangchong** [comment]
> can you copy it to branch:2.0.6-prepare ?

ok

**Review by EricJoy2048 — APPROVED** [review]
+1

**Pull request merged**
