### PR TITLE
[Fix-13987][bom] set 3.17.2 version protobuf-java

### LINKED ISSUE #13987: [Bug] [Master] Could not find class when using etcd as the registration center
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registryClient': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 61 more

### What you expected to happen

master could use etcd as the registration center

### How to reproduce

use etcd as the registration center

### Anything else

I found `protobuf-java` in master module is 2.x version, worker module is 3.x version. So worker can start success but master failed. Maybe should use `maven-shade-plugin` in etcd module to fix it.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eye-gu**
## Purpose of the pull request

fix #13987 

## Brief change log

use shade plugin in etcd module

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
Can we set the `protobuf-java` in bom? Right now, we don't directly protobuf-java in master, could you please find out which module rely on this

**Comment by eye-gu** [comment]
> Can we set the `protobuf-java` in bom? Right now, we don't directly protobuf-java in master, could you please find out which module rely on this

Hadoop-client and hadoop-common refer to version 2.5 of protobuf-Java. Do you think best exclude version 2.5?

**Comment by ruanwenjun** [comment]
> > Can we set the `protobuf-java` in bom? Right now, we don't directly protobuf-java in master, could you please find out which module rely on this
> 
> Hadoop-client and hadoop-common refer to version 2.5 of protobuf-Java. Do you think best exclude version 2.5?

Can we set the version to `3.x` in dependentManagement?

**Comment by eye-gu** [comment]
> > > Can we set the `protobuf-java` in bom? Right now, we don't directly protobuf-java in master, could you please find out which module rely on this
> > 
> > 
> > Hadoop-client and hadoop-common refer to version 2.5 of protobuf-Java. Do you think best exclude version 2.5?
> 
> Can we set the version to `3.x` in dependentManagement?

Done. PTAL

**Review by SbloodyS — APPROVED** [review]
LGTM if CI passed.

**Pull request merged**
