### PR TITLE
[Improvement][Dao] SQL optimization - check exist #5930 #5931

### LINKED ISSUE #5930: [Improvement][Dao] SQL optimization - check exist
Describe the question
As report by #5061, we need to optimize the sql.  #5069 tried to optimize 'check exist'; however, there are more occurrences that need to be fixed.

What are the current deficiencies and the benefits of improvement
Improve the performance about check some exist with cleaner method

Which version of DolphinScheduler:
-[dev]
-[1.3.6]

### PR DESCRIPTION
**Pull request by allen1128**
Purpose of the pull request
See [#5061](https://github.com/apache/dolphinscheduler/issues/5061)
fix #5930 
### Brief change log
Using select 1 from xx limit 1 to check the record exist.
### Verify this pull request
Add Unit test for each changed mapper

### CODE REVIEW

**Comment by CalvinKirs** [comment]
deeply thanks for your contribution, You can refer to this document to solve the problem of code style
http://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
btw,You don't need to close PR, you can modify the commit on the current branch

**Comment by allen1128** [comment]
> deeply thanks for your contribution, You can refer to this document to solve the problem of code style
> http://dolphinscheduler.apache.org/en-us/community/development/pull-request.html
> btw,You don't need to close PR, you can modify the commit on the current branch

Sure, it's fixed. Please check.

**Comment by zhuangchong** [comment]
@allen1128 Please check the code style.

**Comment by allen1128** [comment]
> @allen1128 Please check the code style.

Should be good this time.

**Comment by allen1128** [comment]
resolved conflicts found after dev branch recent merges

**Comment by CalvinKirs** [comment]
hi, code style check errs, you can refer to this doc install plugin to resolve this problem.
https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

**Comment by allen1128** [comment]
> hi, code style check errs, you can refer to this doc install plugin to resolve this problem.
> https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

fixed

**Comment by allen1128** [comment]
> hi, code style check errs, you can refer to this doc install plugin to resolve this problem.
> https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html

**Comment by allen1128** [comment]
@CalvinKirs  hi, what is left for this pr to be merged?

**Pull request closed without merging**
