### PR TITLE
[python] Change name to_string to __str__ and add __repr__

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Change `yaml_parser.py` method `to_string` to magic method
  `__str__` make it more pythonic.
* Add some tests to magic method `__str__` and `__repr__`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend @jieguangzhou thanks

**Review by devosend — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
PTAL @caishunfeng @songjianet thanks

**Comment by songjianet** [comment]
> PTAL @caishunfeng @songjianet thanks

Sorry! I don't know Python.

**Comment by zhongjiajie** [comment]
> > PTAL @caishunfeng @songjianet thanks
> 
> Sorry! I don't know Python.

hi @songjianet , I need +1 approval here, @devosend already reviewed and approved

**Review by songjianet — APPROVED** [review]
LGTM

**Pull request merged**
