### PR TITLE
[Fix][Alert] Fix when auth is false and user || pwd null can't send email excection

### LINKED ISSUE #11455: [Feature][UI] hidden unnecessary mail.smtp.auth fileds, when user choose disable mail.smtp.auth
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

as the comment [https://github.com/apache/dolphinscheduler/pull/10721#issuecomment-1197870428](url) said, 
it's more friendly for user to hidden the field for mail.smtp.auth(fields in the red rectangle), when user choose disable mail.smtp.auth 

Screen Shot 2022-08-12 at 16 53 59

### Use case

hidden the field for mail.smtp.auth(fields in the red rectangle), when user choose disable mail.smtp.auth 

### Related issues

https://github.com/apache/dolphinscheduler/issues/10698

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qingwli**
- close #11455
- part of #10721
- This part fixes this error
- Feature can support auth choose false and hide user && pwd input filed, etc

### CODE REVIEW

**Comment by rickchengx** [comment]
Hi, @liqingwang , It seems that there is `connection time out` during CI
This PR LGTM

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
> Hi, @liqingwang , It seems that there is `connection time out` during CI This PR LGTM

I had rerun it.

**Comment by qingwli** [comment]
PTAL @caishunfeng

**Pull request merged**
