### PR TITLE
[Improvement][task node] task node resources improvement

### PR DESCRIPTION
**Pull request by zhutong6688**
[Improvement][task node] task node includes shell、proceduce、sql、spark、datax、sqoop、flink_stream and so on，those can not select resource file by seraching resources tree。

## Purpose of the pull request

The task node can use search filtering when selecting resources, even in the case of multi-level subdirectories, it can also use search to quickly filter resource files

## Verify this pull request

version 3.1. x

manually test result

图片

### CODE REVIEW

**Comment by zhutong6688** [comment]
This improvement will greatly improve user development efficiency when incorporated into the release version

**Comment by zhutong6688** [comment]
At present, with such problems to be improved is version 3.1. x

**Review by Amy0104 — APPROVED** [review]
LGTM

**Comment by zhutong6688** [comment]
@Amy0104 @davidzollo I accidentally clicked the “unsigned me” link, I was unintentional, now it's like this，
图片
Can you reassign me as the responsible person? Thanks very much.

**Pull request merged**
