### PR TITLE
[Feature-11582][api] search task instance by task type

### LINKED ISSUE #11582: [Feature][Task Instance] Searching task node type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

image
Maybe we can support a tiny feature that searching task node type?
User can easily search by task node type.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MichaelDeSteven**
## Purpose of the pull request

close #11582

## Brief change log

here are four task instance
image

the result num of shell task type is 2
image

## Verify this pull request
[TaskInstanceServiceTest.java](https://github.com/apache/dolphinscheduler/pull/12052/files#diff-ed4ad7ba577913cf40a1eca69dc4d5170780ea90ed064e52b35a0c7d175ecafb)
`queryTaskListPagingByTaskType` test method can help verify this pr.

### CODE REVIEW

**Comment by MichaelDeSteven** [comment]
@SbloodyS @caishunfeng @Amy0104 @songjianet PTAL

**Comment by MichaelDeSteven** [comment]
@SbloodyS @caishunfeng @Amy0104 @songjianet @EricGao888 PTAL, thx!

**Review by songjianet — APPROVED** [review]

**Review by songjianet — COMMENTED** [review]
lease resolve the conflict.

**Comment by SbloodyS** [comment]
Close due to inactivity.

**Pull request closed without merging**
