### PR TITLE
[Fix-9980] [Server] fix heartBeatTaskCount bug

### PR DESCRIPTION
**Pull request by brave-lee**
closed by #9980

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Please remove the deprecated class `HeartBeatTask`.

**Comment by brave-lee** [comment]
> Please remove the deprecated class `HeartBeatTask`.

Please check, it has been removed here

**Comment by caishunfeng** [comment]
> > Please remove the deprecated class `HeartBeatTask`.
> 
> Please check, it has been removed here

It means to remove the `org.apache.dolphinscheduler.server.registry.HeartBeatTask` class, if we no longer use it.

BTW, I think the name `MasterHeartBeatListener` and `WorkerHeartBeatListener` seems strange, because they are schedule runnable task, not listener.

**Comment by caishunfeng** [comment]
I had rerun the fail CI job.

**Review by ruanwenjun — APPROVED** [review]
LGTM, if there is not conflict.

**Pull request merged**
