### PR TITLE
[Bug][worker] task throw ConcurrentModifiedException #5528

### LINKED ISSUE #5528: [Bug][server] task instance can not run.
A task has too much log, and I can run it.  When a new  task instance starting, the console print this:

image

image

The new task state is submit or not running.

### PR DESCRIPTION
**Pull request by ruanwenjun**
related issue #5528 

Using `Iterator` of `SynchronizedList` is not thread safe.

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
there is a code smell that needs to be resolved

**Comment by ruanwenjun** [comment]
@CalvinKirs Done

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by geosmart** [comment]
with the old code
```
logger.info(" -> {}", String.join("\n\t", logs));
```

the test case is still pass 
```
    @Test
    public void testLogHandler() throws InterruptedException {
        List<String> list = Collections.synchronizedList(new ArrayList<>());
        Thread thread1 = new Thread(() -> {
            for (int i = 0; i < 10; i++) {
                list.add("test add log");
            }
        });
        Thread thread2 = new Thread(() -> {
            for (int i = 0; i < 10; i++) {
                sqoopTask.logHandle(list);
            }
        });
        thread1.start();
        thread2.start();
        thread1.join();
        thread2.join();
        // if no exception throw, assert true
        Assert.assertTrue(true);
    }
```

**Pull request merged**
