### PR TITLE
[1.3.6-prepare][Fix-#4866][common] Fix loading hdfs-site.xml #4867

### PR DESCRIPTION
**Pull request by CalvinKirs**
pr #4867 
issue #4866

### CODE REVIEW

**Review by lenboo — APPROVED** [review]
+1

**Comment by lenboo** [comment]
which issue does this pr refer to ?

**Comment by CalvinKirs** [comment]
> which issue does this pr refer to ?

pr #4867
issue #4866

**Review by chengshiwen — APPROVED** [review]
+1

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
