### PR TITLE
[Fix] Fix K8s error

### PR DESCRIPTION
**Pull request by qingwli**
- Due #12334
- K8s helm needs to change jvm home

### CODE REVIEW

**Review by kezhenxu94 — DISMISSED** [review]

**Comment by EricGao888** [comment]
@liqingwang Could u plz run `mvn spotless:apply` to fix the formatting errors? Thx : )

**Comment by qingwli** [comment]
Done @EricGao888

**Review by kezhenxu94 — APPROVED** [review]

**Comment by qingwli** [comment]
3.1.x has this bug too

**Comment by EricGao888** [comment]
> 3.1.x has this bug too

done

**Pull request merged**
