### PR TITLE
[python] Fix source and issue tracker link in PyPI

### PR DESCRIPTION
**Pull request by zhongjiajie**
This patch fix error or wrong link in
https://pypi.org/project/apache-dolphinscheduler/

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend  @jieguangzhou You could see more detail in https://pypi.org/project/apache-dolphinscheduler/
image

**Comment by devosend** [comment]
LGTM

**Comment by zhongjiajie** [comment]
PTAL @songjianet @caishunfeng . @devosend already approved this PR

**Review by caishunfeng — APPROVED** [review]
+1

**Pull request merged**
