### PR TITLE
[BUG][API]task definition reference deleted resource files.

### LINKED ISSUE #11827: task definition reference deleted resource files
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、Create a process  definiiton（flow001)  and add a shell task. The shell task references two rosource files (file1.sql and file2.sql）
2、Make flow001 offline 
3、From resource center, delete file1.sql
4、 Make flow001 online again
5、 The flow001 can not be scheduled  normally

### What you expected to happen

After delete file1.sql, I expected the flow001 can be scheduled normally

### How to reproduce

1、Create a process  definiiton（flow001)  and add a shell task. The shell task references two rosource files (file1.sql and file2.sql）
2、Make flow001 offline 
3、From resource center, delete file1.sql
4、 Make flow001 online again
5、 The flow001 can not be scheduled 

### Anything else

The resouce center reupload file is a very useful function . I suggest this function can be added back again

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hstdream**
## Purpose of the pull request

close #11827

## Brief change log
1、Create a process definiiton（flow001) and add a shell task. The shell task references two rosource files (file1.sql and file2.sql）
2、Make flow001 offline
3、From resource center, delete file1.sql
4、 Make flow001 online again
5、 The flow001 can not be scheduled normally
## Verify this pull request

1、Create a process definiiton（flow001) and add a shell task. The shell task references two rosource files (file1.sql and file2.sql）
2、Make flow001 offline
3、From resource center, delete file1.sql
4、 Make flow001 online again
5、 The flow001 can not be scheduled normally

### CODE REVIEW

**Comment by caishunfeng** [comment]
Hi @hstdream The 3.0.0 version had been released, please change the target branch to dev or 3.0.x-prepare or 3.1.x-prepare. 

Is this issue exist in 3.0.x and 3.1.x?

**Review by caishunfeng — CHANGES_REQUESTED** [review]
Target branch was wrong.

**Comment by hstdream** [comment]
3.0.x

**Comment by hstdream** [comment]
How to switch committed code to branch 3.0.x-prepare.

**Comment by caishunfeng** [comment]
> 3.0.x

This issue also exist in dev, it should target to dev. After merging, it will be cherry-pick to 3.0.x-prepare.

**Pull request closed without merging**
