### PR TITLE
[fix#12439] [Alert] fix send script alert NPE

### LINKED ISSUE #12439: [Bug] [Alert] Send script alert NPE
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[ERROR] 2022-10-19 16:41:53.938 +0800 org.apache.dolphinscheduler.alert.AlertSenderService:[272] - send alert error alert data id :48,
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.plugin.alert.script.ScriptSender.executeShellScript(ScriptSender.java:75)
        at org.apache.dolphinscheduler.plugin.alert.script.ScriptSender.sendScriptAlert(ScriptSender.java:47)
        at org.apache.dolphinscheduler.plugin.alert.script.ScriptAlertChannel.process(ScriptAlertChannel.java:35)
        at org.apache.dolphinscheduler.alert.AlertSenderService.alertResultHandler(AlertSenderService.java:252)
        at org.apache.dolphinscheduler.alert.AlertSenderService.send(AlertSenderService.java:112)
        at org.apache.dolphinscheduler.alert.AlertSenderService.run(AlertSenderService.java:79)
```
image

### What you expected to happen

can run script alert success.

### How to reproduce

add a script alert plugin without setting user params.
image

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pandong2011**
## Purpose of the pull request
this pr is used to close #12439

## Verify this pull request

Added method testUserParamsNPE of ScriptSenderTest to verify the change
Added method testPathNPE of ScriptSenderTest to verify the change
Added method testTypeIsError of ScriptSenderTest to verify the change

### CODE REVIEW

**Comment by davidzollo** [comment]
good job

@pandong2011 , please update `format violations`, you can check the following message, 

Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.27.2:check (default) on project dolphinscheduler-alert-script: The following files had format violations:
Error:      src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptAlertChannel.java
Error:          @@ -17,12 +17,13 @@
Error:           
Error:           package·org.apache.dolphinscheduler.plugin.alert.script;
Error:           
Error:          -import·org.apache.commons.collections.MapUtils;
Error:           import·org.apache.dolphinscheduler.alert.api.AlertChannel;
Error:           import·org.apache.dolphinscheduler.alert.api.AlertData;
Error:           import·org.apache.dolphinscheduler.alert.api.AlertInfo;
Error:           import·org.apache.dolphinscheduler.alert.api.AlertResult;
Error:           
Error:          +import·org.apache.commons.collections.MapUtils;
Error:          +
Error:           import·java.util.Map;
Error:           
Error:           public·final·class·ScriptAlertChannel·implements·AlertChannel·{
Error:      src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
Error:          @@ -18,11 +18,11 @@
Error:           package·org.apache.dolphinscheduler.plugin.alert.script;
Error:           
Error:           import·org.apache.dolphinscheduler.alert.api.AlertResult;
Error:          +import·org.apache.dolphinscheduler.spi.utils.StringUtils;
Error:           
Error:           import·java.io.File;
Error:           import·java.util.Map;
Error:           
Error:          -import·org.apache.dolphinscheduler.spi.utils.StringUtils;
Error:           import·org.slf4j.Logger;
Error:           import·org.slf4j.LoggerFactory;
Error:           
Error:          @@ -37,9 +37,15 @@
Error:           ····private·final·String·userParams;
Error:           
Error:           ····ScriptSender(Map<String,·String>·config)·{
Error:          -········scriptPath·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_PATH))?·config.get(ScriptParamsConstants.NAME_SCRIPT_PATH):"";
Error:          -········scriptType·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE))?·config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE):"";
Error:          -········userParams·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS))?·config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS):"";
Error:          +········scriptPath·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_PATH))
Error:          +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_PATH)
Error:          +················:·"";
Error:          +········scriptType·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE))
Error:          +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE)
Error:          +················:·"";
Error:          +········userParams·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS))
Error:          +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS)
Error:          +················:·"";
Error:           ····}
Error:           
Error:           ····AlertResult·sendScriptAlert(String·title,·String·content)·{
Error:          @@ -47,7 +53,7 @@
Error:      ... (8 more lines that didn't fit)
Error:  Run 'mvn spotless:apply' to fix these violations.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :dolphinscheduler-alert-script

**Comment by pandong2011** [comment]
> good job
> 
> @pandong2011 , please update `format violations`, you can check the following message,
> 
> Error: Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.27.2:check (default) on project dolphinscheduler-alert-script: The following files had format violations: Error: src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptAlertChannel.java Error: @@ -17,12 +17,13 @@ Error: Error: package·org.apache.dolphinscheduler.plugin.alert.script; Error: Error: -import·org.apache.commons.collections.MapUtils; Error: import·org.apache.dolphinscheduler.alert.api.AlertChannel; Error: import·org.apache.dolphinscheduler.alert.api.AlertData; Error: import·org.apache.dolphinscheduler.alert.api.AlertInfo; Error: import·org.apache.dolphinscheduler.alert.api.AlertResult; Error: Error: +import·org.apache.commons.collections.MapUtils; Error: + Error: import·java.util.Map; Error: Error: public·final·class·ScriptAlertChannel·implements·AlertChannel·{ Error: src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java Error: @@ -18,11 +18,11 @@ Error: package·org.apache.dolphinscheduler.plugin.alert.script; Error: Error: import·org.apache.dolphinscheduler.alert.api.AlertResult; Error: +import·org.apache.dolphinscheduler.spi.utils.StringUtils; Error: Error: import·java.io.File; Error: import·java.util.Map; Error: Error: -import·org.apache.dolphinscheduler.spi.utils.StringUtils; Error: import·org.slf4j.Logger; Error: import·org.slf4j.LoggerFactory; Error: Error: @@ -37,9 +37,15 @@ Error: ····private·final·String·userParams; Error: Error: ····ScriptSender(Map<String,·String>·config)·{ Error: -········scriptPath·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_PATH))?·config.get(ScriptParamsConstants.NAME_SCRIPT_PATH):""; Error: -········scriptType·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE))?·config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE):""; Error: -········userParams·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS))?·config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS):""; Error: +········scriptPath·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_PATH)) Error: +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_PATH) Error: +················:·""; Error: +········scriptType·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE)) Error: +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE) Error: +················:·""; Error: +········userParams·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS)) Error: +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS) Error: +················:·""; Error: ····} Error: Error: ····AlertResult·sendScriptAlert(String·title,·String·content)·{ Error: @@ -47,7 +53,7 @@ Error: ... (8 more lines that didn't fit) Error: Run 'mvn spotless:apply' to fix these violations. Error: -> [Help 1] Error: Error: To see the full stack trace of the errors, re-run Maven with the -e switch. Error: Re-run Maven using the -X switch to enable full debug logging. Error: Error: For more information about the errors and possible solutions, please read the following articles: Error: [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException Error: Error: After correcting the problems, you can resume the build with the command Error: mvn -rf :dolphinscheduler-alert-script

Ok, I'll do it

**Comment by pandong2011** [comment]
> good job
> 
> @pandong2011 , please update `format violations`, you can check the following message,
> 
> Error: Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.27.2:check (default) on project dolphinscheduler-alert-script: The following files had format violations: Error: src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptAlertChannel.java Error: @@ -17,12 +17,13 @@ Error: Error: package·org.apache.dolphinscheduler.plugin.alert.script; Error: Error: -import·org.apache.commons.collections.MapUtils; Error: import·org.apache.dolphinscheduler.alert.api.AlertChannel; Error: import·org.apache.dolphinscheduler.alert.api.AlertData; Error: import·org.apache.dolphinscheduler.alert.api.AlertInfo; Error: import·org.apache.dolphinscheduler.alert.api.AlertResult; Error: Error: +import·org.apache.commons.collections.MapUtils; Error: + Error: import·java.util.Map; Error: Error: public·final·class·ScriptAlertChannel·implements·AlertChannel·{ Error: src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java Error: @@ -18,11 +18,11 @@ Error: package·org.apache.dolphinscheduler.plugin.alert.script; Error: Error: import·org.apache.dolphinscheduler.alert.api.AlertResult; Error: +import·org.apache.dolphinscheduler.spi.utils.StringUtils; Error: Error: import·java.io.File; Error: import·java.util.Map; Error: Error: -import·org.apache.dolphinscheduler.spi.utils.StringUtils; Error: import·org.slf4j.Logger; Error: import·org.slf4j.LoggerFactory; Error: Error: @@ -37,9 +37,15 @@ Error: ····private·final·String·userParams; Error: Error: ····ScriptSender(Map<String,·String>·config)·{ Error: -········scriptPath·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_PATH))?·config.get(ScriptParamsConstants.NAME_SCRIPT_PATH):""; Error: -········scriptType·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE))?·config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE):""; Error: -········userParams·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS))?·config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS):""; Error: +········scriptPath·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_PATH)) Error: +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_PATH) Error: +················:·""; Error: +········scriptType·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE)) Error: +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_TYPE) Error: +················:·""; Error: +········userParams·=·StringUtils.isNotBlank(config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS)) Error: +················?·config.get(ScriptParamsConstants.NAME_SCRIPT_USER_PARAMS) Error: +················:·""; Error: ····} Error: Error: ····AlertResult·sendScriptAlert(String·title,·String·content)·{ Error: @@ -47,7 +53,7 @@ Error: ... (8 more lines that didn't fit) Error: Run 'mvn spotless:apply' to fix these violations. Error: -> [Help 1] Error: Error: To see the full stack trace of the errors, re-run Maven with the -e switch. Error: Re-run Maven using the -X switch to enable full debug logging. Error: Error: For more information about the errors and possible solutions, please read the following articles: Error: [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException Error: Error: After correcting the problems, you can resume the build with the command Error: mvn -rf :dolphinscheduler-alert-script

format verification complete

**Review by Radeity — COMMENTED** [review]
LGTM, but next time, please leave a message before coding for an issue which have already been assigned to others.

**Comment by pandong2011** [comment]
> LGTM, but next time, please leave a message before coding for an issue which have already been assigned to others.

sry,  I'll keep an eye on it next time

**Review by caishunfeng — APPROVED** [review]
+1

**Pull request merged**
