### PR TITLE
[fix][doc]: fix conditions.md cannot be previewed by markdown

### LINKED ISSUE #10126: [Bug] [doc] conditions.md'image cannot be previewed by markdown
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [doc] conditions.md'image cannot be previewed by markdown

### What you expected to happen

fix it

### How to reproduce

none

### Anything else

none

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huangchenguang123**
fix #10126

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@huangchenguang123 Hi, it is related to #9426 and we have to keep it in the old way now, othewise our document in website can not display img in the right way, I will change them and make it work on both the source markdown file and website

**Comment by zhongjiajie** [comment]
If you have time and interesting in issue #9426, and feel free to take it

**Comment by huangchenguang123** [comment]
> @huangchenguang123 Hi, it is related to #9426 and we have to keep it in the old way now, othewise our document in website can not display img in the right way, I will change them and make it work on both the source markdown file and website

Think.You mean I have to modify the script on the website to be compatible with the display of the pictures on dolphinscheduler.apache.org?

**Comment by zhongjiajie** [comment]
> > @huangchenguang123 Hi, it is related to #9426 and we have to keep it in the old way now, othewise our document in website can not display img in the right way, I will change them and make it work on both the source markdown file and website
> 
> Think.You mean I have to modify the script on the website to be compatible with the display of the pictures on dolphinscheduler.apache.org?

yeah, we have some example in apache/seatunnel, it will convert img path and make them work bot github markdown and website. https://github.com/apache/incubator-seatunnel-website/blob/104e0b815952d41ba03817c515d9613bde9c84cf/tools/build-docs.sh#L121-L137

**Comment by huangchenguang123** [comment]
close by batch fix

**Comment by zhongjiajie** [comment]
> close by batch fix

@huangchenguang123  Thanks for your contribution to `prepare_docs.sh` in repo apache/dolphinscheduler-website ❤️

**Pull request closed without merging**
