### PR TITLE
[Improvement-5172][UI]process list add Timing state add online/offlin…

### LINKED ISSUE #5172: [Improvement][process] add timing online/offline marking color
*For better global communication, please give priority to using English description, thx! *

make user better different process whether online,In order to prevent the user forget it
online ：color is green
offline：color is yellow

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the improvement is.

**What are the current deficiencies and the benefits of improvement**
- A clear and concise description of the current deficiencies and the benefits of this improvement.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

### PR DESCRIPTION
**Pull request by wanghong1314**
…e marking color
hope to 1.3.6 prepare version

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by wanghong1314** [comment]
please review

**Review by zhuangchong — COMMENTED** [review]
+1

**Review by davidzollo — APPROVED** [review]
+1
good job

**Comment by davidzollo** [comment]
thanks for your first contribution, looking forward to your deep participation!

**Pull request merged**
