### PR TITLE
[Fix-5483] [Bug][API] Can't view variables in the page of Process Instance

### PR DESCRIPTION
**Pull request by echohlne**
## Purpose of the pull request

Fix the bug #5483 

## Brief change log
`JSONUtils.toMap` can only parse the specific structure of json like {'key1':'value1', 'key2':'value2'...};
If the json str has many kinds of  value type, `JSONUtils.toMap` will return a null value, which will cause the method to throw a NPE.
Even though the `taskDefinitionLog` has a lot of fields, we're just going to focus on a single field,
So I try to introduce a new method in `JsonUtils` to get the str value of a certain key

## Verify this pull request

+ add a new UT 
+ munutal test works well, like below:
image

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
Deeply thanks for your contribution, considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by CalvinKirs** [comment]
The overall look is great, but there is one thing that needs to be fixed, the code style check fails, you can refer to this document to make changes. (https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html)
Thanks for your contribution.

**Comment by echohlne** [comment]
@CalvinKirs  code style error has fixed!
Thanks for your great effort , I've subscribed to the developer community, hoping to keep in touch with other developers.

**Comment by CalvinKirs** [comment]
> Deeply thanks for your contribution, considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

hi, Can you add my WeChat(Kris_Evil)?

**Pull request merged**
