### PR TITLE
If the database is dead and can't be connected all the time, the master is easy to fill the log and let the user decide the maximum number of failures.

### PR DESCRIPTION
**Pull request by zt-1997**
If the database is dead and can't be connected all the time, the master is easy to fill the log and let the user decide the maximum number of failures. If the number of failures is reached, the master exits. In this way, the maximum number of logs is controlled. The default number of database reconnections is 360.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, are you having any problems.

**Comment by CalvinKirs** [comment]
For related discussion, see: #4332 #4226

**Review by CalvinKirs — COMMENTED** [review]
Deeply thanks for your contribution. But on this issue, we may need more discussion:

I don’t think exit is a good solution (even if you use multiple intermittent retries).

I think the original design is better. I also have a reply in this issue #4226.

When the upstream is abnormal ( The downstream is strongly dependent on the upstream), our better approach is to adopt a circuit breaker strategy instead of directly downgrading.

The original method (sleep is actually a means of circuit breakers)

Maybe ,you can improve this, using the warning method here, or other.

**Comment by zt-1997** [comment]
> For related discussion, see: #4342 #4226

These two have been turned off

**Comment by lenboo** [comment]
-If the database fails, the master will print the log all the time

This is really unreasonable. 
If we can solve the problem of logging all the time, is there no need to quit?
I don't think quitting is a good idea.

**Comment by caishunfeng** [comment]
Hi @zt-1997 , this pr has not updated in a long time, so it wiil be closed.
If you have other questions, you can re-open it or create a new one. Thxs.

**Pull request closed without merging**
