### PR TITLE
[DSIP-70] Deprecated upgrade code of 1.x and 2.x in 3.3.0-release

### LINKED ISSUE #16543: [DSIP-70] Deprecated upgrade code of 1.x and 2.x in 3.3.0-release
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Deprecated upgrade code of 1.x and 2.x in 3.3.0-release since we no longer support direct upgrades to 3.3.0 from these versions. Users can upgrade to 3.0.0 first and then 3.3.0.

### Design Detail

_No response_

### Compatibility, Deprecation, and Migration Plan

Add to upgrade docs.

### Test Plan

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

close #16543

## Brief change log

- Deprecated upgrade code of 1.x and 2.x in 3.3.0-release since we no longer support direct upgrades to 3.3.0 from these versions. Users can upgrade to 3.0.0 first and then 3.3.0.
- Add some upgrade docs.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
Should remove the sql under dao

**Comment by SbloodyS** [comment]
> Should remove the sql under dao

Done. PTAL.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
I have a question here, why we not support upgrade 330 before 300? @SbloodyS

**Comment by SbloodyS** [comment]
> I have a question here, why we not support upgrade 330 before 300? @SbloodyS

We will uniformly name process in code as workflow in #16515 . After that, there will be some incompatible.

**Review by zhongjiajie — APPROVED** [review]
LGTM 👍

**Pull request merged**
