### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by AlleriaWindrunner**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*This pull request for Fix tips error when login with username and without password.*

## Brief change log

- *Replace isUserPassword to isUserName on the </p> label that userNameText error tip.*
Tips:
I just modify the file dolphinscheduler-ui/src/js/conf/login/App.vue, and the left 3 files:
1. sql/create/release-1.0.0_schema/mysql/dolphinscheduler_ddl.sql
2.sql/dolphinscheduler_mysql.sql
3.sql/upgrade/1.0.2_schema/mysql/dolphinscheduler_ddl.sql
are synchronize from dev-1.3.0, i am follow the CONTRIBUTING.md doc specification.

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

I have test in local environment.

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by chengshiwen** [comment]
@AlleriaWindrunner Thanks for your pr.
1. Please change the title of this pr
2. The change of frontend is ok
3. Why modify the sql?

**Review by chengshiwen — CHANGES_REQUESTED** [review]
@AlleriaWindrunner Thanks for your pr.
1. Please change the title of this pr
2. The change of frontend is ok
3. Why modify the sql?

**Comment by AlleriaWindrunner** [comment]
sorry about that, i am contribute first time, and i am following the CONTRIBUTING.md doc specification

If remote branch has a new branch DEV-1.0, you need to synchronize this branch to the local repository.
git checkout -b dev-1.0 upstream/dev-1.0
git push --set-upstream origin dev1.0

If inconvenience is caused, please understand! I'll pay attention later.>o<



At 2021-02-07 21:36:27, "Shiwen Cheng" <notifications@github.com> wrote:

@chengshiwen requested changes on this pull request.

@AlleriaWindrunner Thanks for your pr.

Please change the title of this pr
The change of frontend is ok
Why modify the sql?

**Comment by AlleriaWindrunner** [comment]
If there has any problems, close this pull request please, i'll be new later only about front code.



At 2021-02-07 21:36:27, "Shiwen Cheng" <notifications@github.com> wrote:

@chengshiwen requested changes on this pull request.

@AlleriaWindrunner Thanks for your pr.

Please change the title of this pr
The change of frontend is ok
Why modify the sql?

**Comment by AlleriaWindrunner** [comment]
I have new pull request, [Fix-4723](UI):Fix tips error when login with username and without password. close this please!

**Comment by CalvinKirs** [comment]
duplicate(#4728 )

**Pull request closed without merging**
