### PR TITLE
[Improvement][Test] Block the usage of powermock and move mockito dependencies from sub-modules to root pom

### LINKED ISSUE #11405: [Improvement][Test] Remove dependency of powermock
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* As stated in https://github.com/apache/dolphinscheduler/issues/10976#issuecomment-1207427898, `Powermock` does not and will not support `jUnit 5`. We need to remove the dependency on `Powermock`.
* One possible way is to use a high version (greater than 3.4.0) of `Mockito` to mock `static` method, see: https://wttech.blog/blog/2020/mocking-static-methods-made-possible-in-mockito-3.4.0/

- [x] Furthermore, we could use `Spotless` to block the usage of `Powermock`. #11637

### Sub-Tasks

I have split the task into six sub-tasks by workload:

- [x] Remove `Powermock` in `dolphinscheduler-api` #12144
- [x] Remove `Powermock` in `dolphinscheduler-datasource-plugin` #12179
- [x] Remove `Powermock` in `dolphinscheduler-master` #12124
- [x] Remove `Powermock` in `dolphinscheduler-common`, `dolphinscheduler-alert`, `dolphinscheduler-log-server`, `dolphinscheduler-spi`, `dolphinscheduler-worker` #12208
- [x] Remove `Powermock` in `dolphinscheduler-service`, `dolphinscheduler-server` #12155
- [x] Remove `Powermock` in `dolphinscheduler-task-plugin` #12150

### Examples

Currently we have several typical scenarios where we heavily rely on `Powermock`

1. Mock static class
2. Suppress `Static Initialization Error`
3. Access private method in UT
... (to be continued)

I will give some examples and corresponding solutions for these scenarios respectively as follows:

1. Add `mockito-inline` and use `Mockito.mockStatic` as an alternative. 
2. Simply mocking some special static classes with `Mockito.mockStatic` will cause `Static Initialization Error`. For these special cases, we need to refactor the origin class with some tricks to decouple the usage of static method.
3. Change `private` method to `protected`

For examples, see: #11588

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #11637: [Improvement][Test] Block the usage of `Powermock`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* We could block the usage of `Powermock` by `Spotless`.
* Change the pre-commit hook from `mvn spotless:apply` to `mvn spotless:check` to avoid confusing.

related: #11405 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request
* This PR closes: #11637 
* This PR also closes: #11405

## Brief change log

* Move mockito dependencies from sub-modules to root pom.
* Add a new step in `Spotless` to block the usage of powermock .

## Verify this pull request

* Verified by UT cases and manual tests.

### CODE REVIEW

**Comment by EricGao888** [comment]
Currently we use `check` in CI but `apply` in pre-commit hook as execution goal of `Spotless`, see:

https://github.com/apache/dolphinscheduler/blob/04e1b88c1c423ca9216af34539cdedf1ac405e82/pom.xml#L679-L686 

https://github.com/apache/dolphinscheduler/blob/04e1b88c1c423ca9216af34539cdedf1ac405e82/.pre-commit-config.yaml#L58-L65

I'm thinking about changing the `apply` in pre-commit hook to `check`. The reason is if I add a `regex step` to block `import org.powermock.*`, contributors may get quite confused when pre-commit hook automatically deletes the import, just the same as the `wildcard imports` we discussed before: https://github.com/apache/dolphinscheduler/pull/11458#discussion_r945087368

WDYT @kezhenxu94 @zhongjiajie

**Comment by kezhenxu94** [comment]
> I'm thinking about changing the `apply` in pre-commit hook to `check`. The reason is if I add a `regex step` to block `import org.powermock.*`, contributors may get quite confused when pre-commit hook automatically deletes the import, just the same as the `wildcard imports` we discussed before: [#11458 (comment)](https://github.com/apache/dolphinscheduler/pull/11458#discussion_r945087368)
> 
> WDYT @kezhenxu94 @zhongjiajie

Sounds good to me

**Comment by zhongjiajie** [comment]
> Currently we use `check` in CI but `apply` in pre-commit hook as execution goal of `Spotless`, see:
> 
> https://github.com/apache/dolphinscheduler/blob/04e1b88c1c423ca9216af34539cdedf1ac405e82/pom.xml#L679-L686
> 
> https://github.com/apache/dolphinscheduler/blob/04e1b88c1c423ca9216af34539cdedf1ac405e82/.pre-commit-config.yaml#L58-L65
> 
> I'm thinking about changing the `apply` in pre-commit hook to `check`. The reason is if I add a `regex step` to block `import org.powermock.*`, contributors may get quite confused when pre-commit hook automatically deletes the import, just the same as the `wildcard imports` we discussed before: [#11458 (comment)](https://github.com/apache/dolphinscheduler/pull/11458#discussion_r945087368)
> 
> WDYT @kezhenxu94 @zhongjiajie

+1 for me

**Comment by EricGao888** [comment]
PTAL when available, thx : )

**Comment by EricGao888** [comment]
PTAL when available, thx~ @kezhenxu94 @caishunfeng @ruanwenjun @SbloodyS @zhongjiajie

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
