### PR TITLE
[Fix][UI Next][V1.0.0-Alpha] Fixed a problem where safari ICONS are not displayed

### LINKED ISSUE #8656: [Bug][UI Next][V1.0.0-Alpha] edit and delete button display incorrectly in security/tenant-manage and more
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

safari
image
image

chrome
image

image

### What you expected to happen

display correctly when use safari browser

### How to reproduce

launch ui-next, visit security/tenant-manage and security/yarn-queue-manage

my computer
image

about safari version
image

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by labbomb**
## Purpose of the pull request
Please refer to the main `issue`  [#8656](https://github.com/apache/dolphinscheduler/issues/8656).

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by songjianet** [comment]
The operation buttons of other forms can also be viewed.

**Comment by labbomb** [comment]
> 

anything is ok

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by labbomb** [comment]
> The operation buttons of other forms can also be viewed.

anything is ok

**Comment by songjianet** [comment]
> > The operation buttons of other forms can also be viewed.
> 
> anything is ok

Thank you.

**Comment by labbomb** [comment]
> > > The operation buttons of other forms can also be viewed.
> > 
> > 
> > anything is ok
> 
> Thank you.

no thanks,baby

**Pull request merged**
