### PR TITLE
[Improvement][HELM] add driver-class-name

### PR DESCRIPTION
**Pull request by Gallardot**
## Purpose of the pull request
- ref: #14585

For users who use MySQL, it is necessary to specify the driver-class-name to ensure that MyBatis uses the correct driver. Otherwise, MyBatis will continue to use the PostgreSQL driver

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by Radeity — APPROVED** [review]
LGTM

**Comment by Radeity** [comment]
Just curious, we don't have helm + mysql use cases before? cc @zhongjiajie @EricGao888

**Comment by SbloodyS** [comment]
> Just curious, we don't have helm + mysql use cases before? cc @zhongjiajie @EricGao888

Perhaps other users did not contribute...

**Comment by EricGao888** [comment]
> Just curious, we don't have helm + mysql use cases before? cc @zhongjiajie @EricGao888

@Radeity I tested this case when playing with KEDA worker auto-scaler. I did not get into this kind of trouble at that time.

**Comment by qingwli** [comment]
I remember we used spring profile to control which will be used

```
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dolphinscheduler
    username: root
    password: root
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      ```

**Pull request merged**
