### PR TITLE
[Bug][Parameter Context] The problem of global parameter priority 

### PR DESCRIPTION
**Pull request by cheneychoi**
The problem of global parameter priority，globalParam>varpool>localParam
[issues-8329](https://github.com/apache/dolphinscheduler/issues/8329)

### CODE REVIEW

**Comment by cheneychoi** [comment]
@zhongjiajie I modified this problem ,checkout from  2.0.2-release and plan to merge back to 2.0.2-release after completion. Am I doing this right?

**Comment by zhongjiajie** [comment]
@cheneychoi Please change describe from Chinese to English first

**Comment by zhongjiajie** [comment]
image

**Comment by cheneychoi** [comment]
@zhongjiajie finished

**Comment by zhongjiajie** [comment]
@cheneychoi FYI, we have a discussion in https://github.com/apache/dolphinscheduler/issues/8329#issuecomment-1036163170

**Comment by caishunfeng** [comment]
> @zhongjiajie I modified this problem ,checkout from 2.0.2-release and plan to merge back to 2.0.2-release after completion. Am I doing this right?

Sorry for late review. @cheneychoi  You should fix in dev branch first, and then we will cherry-pick to next 2.0.x version. I don't understand the original design of the `parameter priority`, @wangxj3 @lenboo PTAL.

**Review by wangxj3 — DISMISSED** [review]
LGTM

**Comment by zhongjiajie** [comment]
So, is this PR ready to go now?

**Review by zhongjiajie — DISMISSED** [review]

**Comment by zhongjiajie** [comment]
Hi @cheneychoi, I change to base to dev and it seem they are lots of conflict, could you please solve it locally?

**Comment by zhongjiajie** [comment]
BTW, you should also change our docs later, thanks

**Comment by lgcareer** [comment]
@cheneychoi Hi,Why change the parameter priority.localParam>varpool>globalParam is right.

**Comment by zhongjiajie** [comment]
> @cheneychoi Hi,Why change the parameter priority.localParam>varpool>globalParam is right.

ping @cheneychoi again

**Pull request closed without merging**
