### PR TITLE
[Improvement][UI] Add default namespace to k8s datasource

### LINKED ISSUE #16082: [Improvement][UI] Add default namespace to k8s datasource
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add default namespace to k8s datasource for avoiding fulfilling each time.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pegasas**
## Purpose of the pull request

fix: https://github.com/apache/dolphinscheduler/issues/16082

## Brief change log

Add default namespace to k8s datasource for avoiding fulfilling each time.
## Verify this pull request

image

### CODE REVIEW

**Review by Radeity — APPROVED** [review]

**Comment by ruanwenjun** [comment]
I don't think we need to set the default namespace, like we don't set the default username as root in mysql.

**Comment by Radeity** [comment]
> I don't think we need to set the default namespace, like we don't set the default username as root in mysql.

Good example, agree with you. And `default` namespace will not be frequently used in production environment.

**Review by songjianet — APPROVED** [review]

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
Need discuss.

**Comment by SbloodyS** [comment]
> > I don't think we need to set the default namespace, like we don't set the default username as root in mysql.
> 
> Good example, agree with you. And `default` namespace will not be frequently used in production environment.

+1

**Pull request closed without merging**
