### PR TITLE
[Bug] [Parameter Context] The preparameter OUT is null 

### LINKED ISSUE #7887: [Bug] [Parameter Context] The preparameter OUT is null
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在首节点设定两个OUT参数，其中一个给常量，另一个以shell设置参数值传递的方式，传递到下一个节点时，其中常量的参数为null
image
image
image

### What you expected to happen

AbstractParameters中在给OUT参数设置value时，把原有的常量值设置了为null

### How to reproduce

image
image
image
image

### Anything else

每次都会发生

### Version

2.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cheneychoi**
Fixes https://github.com/apache/dolphinscheduler/issues/7887
参数传递out被下游节点置为null的问题

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Hi @cheneychoi , I received your email. That because you're the first-time contributor, ci only run if maintainer approval to. for more detail see https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors

**Comment by zhongjiajie** [comment]
I approved to run the CI just now.

**Comment by zhongjiajie** [comment]
According to your description in https://github.com/apache/dolphinscheduler/issues/7887, I think it is expected behavior. If you want your `end` task to get a variable you should set value in a global variable or use `setValue`.  Am I right? @caishunfeng @zhuangchong @lenboo

**Comment by cheneychoi** [comment]
感谢回复，确实可以用全局参数处理，我开始没有想到，然后我从origin/dev切出了新的分支修复了它这里使用不当导致参数为null的问题，然后我提交了pr，然后ci告诉我单元测试不通过，可我只修改了几行代码，希望得到您的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dolphinscheduler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dolphinscheduler] [Bug] [Parameter Context] The preparameter OUT is null  (PR #8315)





 
According to your description in #7887, I think it is expected behavior. If you want your end task to get variable you should set value in global variable or use setValue
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhongjiajie** [comment]
@cheneychoi  I restart the failed test

**Comment by zhongjiajie** [comment]
I failed due to flake test

**Comment by zhongjiajie** [comment]
ping @zhuangchong @wangxj3 could you please take a look at this PR?

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhuangchong** [comment]
Thank you very much for your contribution, this PR is very good. I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Pull request merged**
