### PR TITLE
[fix][Data Quality] Data Quality Report Display For Admin Role #10919

### LINKED ISSUE #10919: [Bug] [Data Quality] Data Quality Report Display For Admin Role
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Before we switched to LDAP login, everything was fine, but when we use LDAP to login DS, the data quality report page dosen't show properly.
Previously, admin is the only user of administrator role, and his user_id is `1`, when we switch to LDAP, admin can't be used any one and we appoint two administrator users by change database manually.
However, these two administrator users can't see any data in the data quality report page, I find out that is because only `user_id=1` can see all the data in this page, otherwise, they may only see the data they created.
image
So, I think maybe use `user_type` here is better, in case administrator user's id is not equal to 1.

### What you expected to happen

administrator users can check all the data quality data

### How to reproduce

use LDAP to login and appoint another administrator user

### Anything else

maybe this problem also exist in other place like this situation

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jackfanwan**
The permission verification of data quality query is changed from userId to userType

close: #10919

### CODE REVIEW

**Comment by jackfanwan** [comment]
@SbloodyS Hello, do I need to modify my PR

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by jackfanwan** [comment]
@SbloodyS Hello, is there anything else I need to change？

**Comment by jackfanwan** [comment]
PTAL @SbloodyS

**Comment by jackfanwan** [comment]
@caishunfeng

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
@caishunfeng We added new commit with Chinese as title to upstream/dev
image

**Comment by caishunfeng** [comment]
> @caishunfeng We added new commit with Chinese as title to upstream/dev image

Sorry, My fault, how to deal it?

**Comment by jackfanwan** [comment]
> 

sorry，Can I now rebase the commit message and force the commit？

**Comment by caishunfeng** [comment]
> sorry，Can I now rebase the commit message and force the commit？

It has been merged in dev, we should avoid it next time.

**Pull request merged**
