### PR TITLE
[Bug][Fix-10555] Fastjson has a deserialization vulnerability

### LINKED ISSUE #10555: [Bug] [pom.xml] Fastjson has a deserialization vulnerability
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Fastjson deserialization vulnerability
https://github.com/alibaba/fastjson/wiki/security_update_20220523

### What you expected to happen

Upgrade Fastjson version to 1.2.83

### How to reproduce

https://github.com/alibaba/fastjson/wiki/security_update_20220523

### Anything else

_No response_

### Version

1.3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kangyuanjia**
## Purpose of the pull request
Fix #10555 
Fix Fastjson deserialization vulnerability
https://github.com/alibaba/fastjson/wiki/security_update_20220523

## Brief change log

./pom.xml

## Verify this pull request

This pull request is code cleanup without any test coverage.

*Yes*

This pull request is already covered by existing tests, such as *(please describe tests)*.

Yes

This change added tests and can be verified as follows:

None

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @kangyuanjia , please submit to `dev` branch.

**Comment by SbloodyS** [comment]
closed due to incorrect target branch.

**Comment by kangyuanjia** [comment]
> Hi @kangyuanjia , please submit to `dev` branch.

Hi @SbloodyS , 

There is no fastjson in dev/pom.xml . 
Branch 1.3.9-release is the last version which includes fastjson.

**Comment by SbloodyS** [comment]
> > Hi @kangyuanjia , please submit to `dev` branch.
> 
> Hi @SbloodyS ,
> 
> There is no fastjson in dev/pom.xml . Branch 1.3.9-release is the last version which includes fastjson.

Then we do not need to care about it since the latest release version does not have this problem

**Pull request closed without merging**
