### PR TITLE
[TEST] fix log server related test

### PR DESCRIPTION
**Pull request by abzymeinsjtu**
## Purpose of the pull request

Case in LoggerServerTest will fail when port 8080 is already used by other process, try start with a random port instead

### CODE REVIEW

**Review by EricGao888 — DISMISSED** [review]

**Comment by EricGao888** [comment]
Looks like there are some style issues which cause CI to fail, plz run `mvn spotless:apply`.

Others LGTM

image

**Comment by abzymeinsjtu** [comment]
> Looks like there are some style issues which cause CI to fail, plz run `mvn spotless:apply`.
> 
> Others LGTM
> 
> image

fixed

**Review by EricGao888 — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1

**Review by rickchengx — APPROVED** [review]
LGTM

**Pull request merged**
