### PR TITLE
wrong word: 'WAITTING' ->'WAITING'

### PR DESCRIPTION
**Pull request by Squidyu**
## Purpose of the pull request

This pull request changed 'WAITTING' ->'WAITING'

### CODE REVIEW

**Review by brave-lee — COMMENTED** [review]
+1

**Review by davidzollo — APPROVED** [review]
good job
+1

**Comment by davidzollo** [comment]
It seems that there is no related issue for this PR, so please create an issue then associated this PR

**Comment by Squidyu** [comment]
> It seems that there is no related issue for this PR, so please create an issue then associated this PR

issue #5671

**Pull request merged**
