### PR TITLE
[Improvement][WorkerGroup]  Optimize and reduce database and zookeeper queries and replace worker address input with multiple-select

### LINKED ISSUE #5175: [Improvement][Server] Optimize and reduce worker group queries of database and zookeeper
**Describe the question**

`HostManager.select()` will call `workerGroupMapper.queryAllWorkerGroup()` or `workerGroupMapper.queryWorkerGroupByName(workerGroupName)` from database, and call `registryCenter.getRegisterOperator().get(workerGroupPath + "/" + node)` from zookeeper.

They will cause more queries, even if these queries rarely change.

**What are the current deficiencies and the benefits of improvement**
- Optimize and reduce worker group queries of database and zookeeper 

**Which version of DolphinScheduler:**
 -[1.3.5]
 -[dev]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

### LINKED ISSUE #5176: [Bug][Server] Wrong excludeFilters cause the worker server to start the master's beans and threads like LowerWeightHostManager and RefreshResourceTask
**To Reproduce**
Steps to reproduce the behavior, for example:
1. Add one line `logger.info("RefreshResourceTask: {}", workerHostWeights);` in `RefreshResourceTask#run` (Picture 1)
2. Re-run `MasterServer` and `WorkerServer`
3. See log of `MasterServer` and `WorkerServer`
4. The `LowerWeightHostManager` and `RefreshResourceTask` logs of master appear in the`WorkerServer` log (Picture 2)
5. **Other master's beans and threads will also appear in the`WorkerServer` like `MasterRegistry`, `ZookeeperNodeManager` and etc**

**Picture 1**
image

**Picture 2**
image

**Expected behavior**
Bug fixed

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

*[Improvement-5175-5176][WorkerGroup]  Optimize and reduce database and zookeeper queries and replace worker address input with multiple-select*

This PR is alos synchronized with the pr #5122

This PR closes #5175 and closes #5176

## Brief change log

  - *Add Unique for name in table t_ds_worker_group*
  - *Optimize and reduce database and zookeeper queries*
  - *Replace worker address input with multiple-select*
  - *Optimize long host to short host and long host display in k8s*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

## Detail

I made optimization to reduce the database and zookeeper queries by `ServerNodeManager`, which is evolved from `ZooKeeperNodeManager`. Please review, thanks a lot.

`ServerNodeManager` is responsible for:
- `WorkerNodeInfoAndGroupDbSyncTask`: Schedule worker node info (heartbeat info) and worker group db sync task every 10s
- `WorkerGroupNodeListener` & `MasterNodeListener`: Listen worker group node and master node and sync nodes

image

I added a new commit to replace worker address input with multiple-select as follow:

image

### CODE REVIEW

**Comment by chengshiwen** [comment]
@gaojun2048 @CalvinKirs @dailidong @lenboo @break60 
This pr is just cherry-pick optimization syncing with 1.3.6, please review, thx!

**Comment by break60** [comment]
Is it better to use element-ui with a multi-select selection box?

**Review by break60 — APPROVED** [review]
front end +1

**Comment by chengshiwen** [comment]
> Is it better to use element-ui with a multi-select selection box?

@break60 I used `vue-treeselect` in `1.3.6` and `dev` branch, and there is no `element-ui` in `1.3.6`. So for maintainability, I keep using `vue-treeselect`

**Comment by break60** [comment]
> > Is it better to use element-ui with a multi-select selection box?
> 
> @break60 I used `vue-treeselect` in `1.3.6` and `dev` branch, and there is no `element-ui` in `1.3.6`. So for maintainability, I keep using `vue-treeselect`

👌

**Review by davidzollo — APPROVED** [review]
+1
good job

**Pull request merged**
