### PR TITLE
[python] Add independent deployment for python gateway server

### LINKED ISSUE #7539: [Feature][python] Gateway deployment in production mode
For now, pythonGateway only support in standalone server, and standalone is not production env, so we have to find a better to run in production mode

### PR DESCRIPTION
**Pull request by zhongjiajie**
For now, pythonGatewayServer could only run in a standalone server, and standalone is not for the production environment, we should make pythonGatewayServer work like api-server or master-server. We should also make python gateway server work in docker/K8S enviroment.

close: #7539

### CODE REVIEW

**Comment by zhongjiajie** [comment]
We could success build and the result as below
image

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Comment by zhongjiajie** [comment]
I already test

* [x] Using `dolphinscheduler-daemon.sh start python-gateway-server` to start server
* [x] Using `./bin/install` to
  * [x] Install in single machine
  * [x] Install in multiple machine

Configure to other database **failed**, but is not related to this PR, So I think it is ready to go now

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
