### PR TITLE
[Fix-13913][Master] syncMasterNodes does not make current slot correctly after zookeeper reconnect

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- This pr closes https://github.com/apache/dolphinscheduler/issues/13913

## Brief change log
- Set initial master heartbeat.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by Radeity** [comment]
cc @zhongjiajie @ruanwenjun

**Review by fuchanghai — APPROVED** [review]
LGTM if pass CI

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
> LGTM if pass CI

some of 3.0.x-prepare ci is alway failed, like python and docs, we could just ignore it

**Comment by zhongjiajie** [comment]
Thanks @Radeity for the help

**Pull request merged**
