### PR TITLE
[python] Initiate document for pydolphinscheduler

### PR DESCRIPTION
**Pull request by zhongjiajie**
ref: #6407

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@devosend PTAL, thanks

**Review by kezhenxu94 — APPROVED** [review]
I didn't dig deeper but if you copy some files from others (like SPHINX), make sure to keep their license header and address the license

**Comment by zhongjiajie** [comment]
> I didn't dig deeper but if you copy some files from others (like SPHINX), make sure to keep their license header and address the license

Hi @kezhenxu94 , I am not copy-paste from sphinx, it just auto-generate by command `sphinx-quickstart` https://www.sphinx-doc.org/en/master/tutorial/getting-started.html#creating-the-documentation-layout . It just like a config file and I think is could directly use ASF license, WDYT?

**Comment by zhongjiajie** [comment]
Thanks~

**Comment by devosend** [comment]
The doc looks great.

**Comment by zhongjiajie** [comment]
Thanks~

> The doc looks great.

**Pull request merged**
