### PR TITLE
[fix-13492]add single quotes

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

add single quotes

- #13492

### CODE REVIEW

**Review by davidzollo — DISMISSED** [review]
+1
good job

**Review by EricGao888 — COMMENTED** [review]
@fuchanghai You need to update the related UT case in order to pass the CI.

```text
Error:  Failures: 
Error:    DataxTaskTest.testHandleNullParamsMap:118 expected: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G" -p "-DDT='DT' -DDS='DS'" /tmp/execution/app-id_job.json> but was: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G"  /tmp/execution/app-id_job.json>
Error:    DataxTaskTest.testHandleParamsMap:159 expected: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G" -p "-DDT='DT' -DDS='DS'" /tmp/execution/app-id_job.json> but was: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G" -p "-DDT=DT -DDS=DS" /tmp/execution/app-id_job.json>
```

**Comment by fuchanghai** [comment]
> @fuchanghai You need to update the related UT case in order to pass the CI.
> 
> ```
> Error:  Failures: 
> Error:    DataxTaskTest.testHandleNullParamsMap:118 expected: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G" -p "-DDT='DT' -DDS='DS'" /tmp/execution/app-id_job.json> but was: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G"  /tmp/execution/app-id_job.json>
> Error:    DataxTaskTest.testHandleParamsMap:159 expected: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G" -p "-DDT='DT' -DDS='DS'" /tmp/execution/app-id_job.json> but was: <python2.7 ${DATAX_HOME}/bin/datax.py  --jvm="-Xms1G -Xmx1G" -p "-DDT=DT -DDS=DS" /tmp/execution/app-id_job.json>
> ```

thx for you review

**Review by caishunfeng — APPROVED** [review]
LGTM

**Pull request merged**
