### PR TITLE
Feature 13165

### LINKED ISSUE #13165: [Improvement][dolphinschedule-api]  fine-grained authority management
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now in ds,the granularity of rights management is too coarse,it is difficult to meet real needs.it is nice to have feature below
1. tenent belong to project,
2. tenant has project admin(one:many)
3. warning group belong to tenant(many:one)
4. worker group belong to tenant(many:one)
5. only admin user and the project admin can edit the resource that belong to project 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mxq-151**
## Purpose of the pull request
this pr is for issue https://github.com/apache/dolphinscheduler/issues/13165

## Brief change log
1.change  rest api in dolphinscheduler-api
2.change mapper in dolphinscheduler-dao
3.add some field mysql table
4.add code in OssOperator

1.add user view
image

2.project admin view
image

3.admin user's resource view
image

4.admin user's project view 
image

5.admin user's run-job view 
image

6.project user' run-job view 
image

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please update the document too.

**Comment by mxq-151** [comment]
> Please update the document too.

I will do it later,would you guys merge this pr without doc?

**Comment by SbloodyS** [comment]
> > Please update the document too.
> 
> I will do it later,would you guys merge this pr without doc?

It is better to merge with the document.

**Comment by mxq-151** [comment]
i found authority management have been commited,it is too coarse,it's hard to use,now should i conitnue to update doc to commit this pr?
image

**Comment by mxq-151** [comment]
i found authority management have been commited,i think it's hard to use,now should i conitnue to update doc to commit this pr?

**Comment by mxq-151** [comment]
> i found authority management have been commited,it is too coarse,it's hard to use,now should i conitnue to update doc to commit this pr? image


@SbloodyS some case in use as below
1.Certain users can only access certain workers
2.it cost too much tell admin user to config alert group,alert group should manager by tenant it selft
3.it's dangerous that someone has permission to run a job（who has edit permission can run a job too）

**Comment by SbloodyS** [comment]
> i found authority management have been commited,it is too coarse,it's hard to use,now should i conitnue to update doc to commit this pr? 

You can optimize the document in this PR, or you can create a separate PR. The main purpose is that new features need to be consistent in code and documentation.

**Comment by mxq-151** [comment]
> > i found authority management have been commited,it is too coarse,it's hard to use,now should i conitnue to update doc to commit this pr?
> 
> You can optimize the document in this PR, or you can create a separate PR. The main purpose is that new features need to be consistent in code and documentation.

ok,docs will  update soon

**Comment by zhongjiajie** [comment]
Hi @mxq-151 I personally do not thing OSS project should have complex permission setting, unless the project is design for permission configurations, because each person or company have it own permission need, maybe some config we thing is useful is useless for others.

and unless we make our permission config as complete as possible, to allow user can config whatever they want, but it will cost lots of time to build and test it. And our code base will full of permission code,  when user want to add new feature will be difficult

**Comment by mxq-151** [comment]
> Hi @mxq-151 I personally do not thing OSS project should have complex permission setting, unless the project is design for permission configurations, because each person or company have it own permission need, maybe some config we thing is useful is useless for others.
> 
> and unless we make our permission config as complete as possible, to allow user can config whatever they want, but it will cost lots of time to build and test it. And our code base will full of permission code, when user want to add new feature will be difficult

it means that you guys will not accept the pr?

**Comment by zhongjiajie** [comment]
we need more discussions to judge whether we should accept or not. and maybe we will take some of them, or maybe we will merge all of them, but the point is more dicussions

**Comment by mxq-151** [comment]
> Hi @mxq-151 I personally do not thing OSS project should have complex permission setting, unless the project is design for permission configurations, because each person or company have it own permission need, maybe some config we thing is useful is useless for others.
> 
> and unless we make our permission config as complete as possible, to allow user can config whatever they want, but it will cost lots of time to build and test it. And our code base will full of permission code, when user want to add new feature will be difficult

What I have done is to delegate some authority to the project administrator to reduce the management cost of the super administrator, which should not be complicated

**Comment by mxq-151** [comment]
docs have been updated(only chinese language)，path:docs/docs/zh/guide/authority.md

**Comment by mxq-151** [comment]
> we need more discussions to judge whether we should accept or not. and maybe we will take some of them, or maybe we will merge all of them, but the point is more dicussions

@SbloodyS 
how is going about the disccussion now?

**Comment by mxq-151** [comment]
has any advise about this feature? @SbloodyS

**Pull request closed without merging**
