### PR TITLE
[Feature-4960][Spark] Add name input for Spark and improve Spark & MR args

### LINKED ISSUE #4960: [Feature][Spark] Support spark name
**Describe the feature**
Support spark name, which is common option

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I will implement this feature

### PR DESCRIPTION
**Pull request by chengshiwen**
## What is the purpose of the pull request

*Add name input for Spark and improve Spark & MR args*

This closes #4960

## Brief change log

  - *Add name input for Spark*
  - *Improve Spark & MR args*

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.

 - *dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtilsTest.java*

(or)

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

*The snapshot of name input for spark*:
image

### CODE REVIEW

**Comment by CalvinKirs** [comment]
It looks great, but you'd better create related issues.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
@break60 @zhuangchong PTAL,Thx

**Comment by zhuangchong** [comment]
+1

**Pull request merged**
