### PR TITLE
Format task parameter as pretty json

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request
Right now, the task log is not friendly, this PR is aim to format the task parameter as pretty json in task log.
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by kezhenxu94 — COMMENTED** [review]
I'm +0 to the changes, prettifying the JSON in logs is good for human beings, but it might break log collecting system like ELK, if users collect the logs to ELK stack, they have extra work to config the line breaks inside the JSON.

**Comment by ruanwenjun** [comment]
> I'm +0 to the changes, prettifying the JSON in logs is good for human beings, but it might break log collecting system like ELK, if users collect the logs to ELK stack, they have extra work to config the line breaks inside the JSON.

I got you, this is an disvantage.
in fact, we didn't support using es to store task log :), and I am not sure if es is a suitable to store the task log, since we may need to create a index for each task instance.

**Comment by kezhenxu94** [comment]
> > I'm +0 to the changes, prettifying the JSON in logs is good for human beings, but it might break log collecting system like ELK, if users collect the logs to ELK stack, they have extra work to config the line breaks inside the JSON.
> 
> I got you, this is an disvantage. in fact, we didn't support using es to store task log :), 

It doesn't need our support, ELK can be used to collect any kind of logs and we don't know whether users are using this or not. But as I said, I have no opinion on the changes, it was just a reminder, so feel free to merge this PR when it's ready

**Pull request merged**
