### PR TITLE
[Improvement][SQL] Remove unused table: t_ds_master_server and t_ds_worker_server

### PR DESCRIPTION
**Pull request by chengshiwen**
## What is the purpose of the pull request

**Remove unused table: t_ds_master_server and t_ds_worker_server**

## Brief change log

*Remove unused t_ds_master_server and t_ds_worker_server*: 

  - *`sql/create/release-1.0.0_schema/mysql/dolphinscheduler_ddl.sql`*
  - *`sql/create/release-1.2.0_schema/postgresql/dolphinscheduler_ddl.sql`*
  - *`sql/upgrade/1.2.0_schema/mysql/dolphinscheduler_ddl.sql`*
  - *`sql/dolphinscheduler_postgre.sql`*

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.

### CODE REVIEW

**Comment by davidzollo** [comment]
@lgcareer please review this PR , thx

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
I looked through the code, and some of the tables were not part of the Apache version, and some of the tables were indeed not used in the corresponding version. Please have another person review

**Comment by lgcareer** [comment]
@chengshiwen Hi, I think it not need to update the old table struct, Because the contents of create ddl under 1.0.0 or 1.2.0 need be consistant with the table struct of version 1.0.0 or 1.2.0.

**Comment by lgcareer** [comment]
@chengshiwen Hi, I think it not need to update the old table struct, Because the contents of create ddl under 1.0.0 or 1.2.0 need be consistant with the table struct of version 1.0.0 or 1.2.0.

**Comment by chengshiwen** [comment]
> @chengshiwen Hi, I think it not need to update the old table struct, Because the contents of create ddl under 1.0.0 or 1.2.0 need be consistant with the table struct of version 1.0.0 or 1.2.0.

Now all sql records are incomplete about `master_server` and `worker_server`. In summary,

The following is all the operation records of mysql:

- `sql/create/release-1.0.0_schema/mysql/dolphinscheduler_ddl.sql`:
  - create `t_escheduler_master_server` and `t_escheduler_worker_server`
- `sql/upgrade/1.2.0_schema/mysql/dolphinscheduler_ddl.sql`:
  - rename `t_escheduler_master_server` to `t_ds_master_server`
  - rename `t_escheduler_worker_server` to `t_ds_worker_server`

**But there is no record of `master_server` or `worker_server` in `sql/dolphinscheduler_mysql.sql`**

The following is all the operation records of postgresql:

- `sql/create/release-1.2.0_schema/postgresql/dolphinscheduler_ddl.sql`
  - create `t_ds_master_server` and `t_ds_worker_server`
- `sql/dolphinscheduler_postgre.sql`
  - only create `t_ds_worker_server` 

**But there is no record of `t_ds_master_server` in `sql/dolphinscheduler_postgre.sql`**

Since we did not actually use these tables, and there will be no impact on the upgrade, but all sql records are still incomplete. Therefore, **I suggest to either remove all unused tables or complete the missing sql records**.

**Pull request closed without merging**
