### PR TITLE
[Improvement][security] get-user-info API endpoint should not return the user's password in MD5 format

### LINKED ISSUE #14679: [Improvement][security] get-user-info API endpoint should not return the user's password in MD5 format
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The get-user-info API endpoint currently returns the user's password in MD5 format, which is then stored in the local storage by the web front-end. 
https://github.com/apache/dolphinscheduler/blob/37ecd262ee9a2228f0daf84e336dcfdd6f2ae9ad/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java#L447-L450

https://github.com/apache/dolphinscheduler/blob/37ecd262ee9a2228f0daf84e336dcfdd6f2ae9ad/dolphinscheduler-ui/src/views/login/use-login.ts#L44-L45

However, there is no functionality that requires the use of this password. Moreover, this password is just a simple MD5 hash, which can be easily cracked. 

https://github.com/apache/dolphinscheduler/blob/37ecd262ee9a2228f0daf84e336dcfdd6f2ae9ad/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java#L211

Therefore, I believe that get-user-info API endpoint should not return the password in MD5 format.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gallardot**
## Purpose of the pull request

- close #14679 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by Radeity** [comment]
Will it affect the display of the password in UI?

**Comment by Gallardot** [comment]
> Will it affect the display of the password in UI?

@Radeity 
I did not find any requirement to display the password in the UI, and the password is in MD5 format.

**Comment by rickchengx** [comment]
If it is in md5 format, I think it should not be decryptable

**Comment by Gallardot** [comment]
> If it is in md5 format, I think it should not be decryptable

@rickchengx 
Of course it shouldn't be decrypted. Even if it is in MD5 format, it should not be returned through the API interface, as the current system only performs one round of MD5, which can be easily cracked using an MD5 dictionary.

We can further enhance the security of the password by adding some salt to the current MD5 processing, but this would be a non-backward compatible change that would cause some trouble for version upgrades.

**Comment by qingwli** [comment]
I  agree with @Gallardot , we don't need to display the password even if it was md5 format

**Comment by Gallardot** [comment]
@Radeity @EricGao888 @SbloodyS @rickchengx PTAL.

**Review by qingwli — APPROVED** [review]
LGTM

**Review by Radeity — APPROVED** [review]
LGTM

**Review by rickchengx — APPROVED** [review]
LGTM

**Pull request merged**
