### PR TITLE
[Fix-5876][SQL] Support more resources files in the task

### PR DESCRIPTION
**Pull request by calvinjiang**
## Purpose of the pull request

This PR will fix the issue #5876 .

## Verify this pull request

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Review by zhuangchong — APPROVED** [review]
LGTM.

**Review by lenboo — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
I thinks this patch could be including to 2.0 @lenboo

**Comment by caishunfeng** [comment]
+1

**Pull request merged**
