### PR TITLE
[Fix] Fix ldap error

### PR DESCRIPTION
**Pull request by qingwli**

### CODE REVIEW

**Comment by SbloodyS** [comment]
Please also submit this to `dev` branch.

**Comment by qingwli** [comment]
The Dev branch has contained this fixed, only needs to fix 3.0.2.

**Comment by qingwli** [comment]
@SbloodyS PTAL, The Dev branch has contained this fixed, only needs to fix 3.0.2. Do not need to add 3.1.x label and 3.2.0 Milestone

**Comment by EricGao888** [comment]
> @SbloodyS PTAL, The Dev branch has contained this fixed, only needs to fix 3.0.2. Do not need to add 3.1.x label and 3.2.0 Milestone

@liqingwang  3.0.2-prepare has been frozen, you could submit a PR to 3.0.3-prepare, thanks : )

**Comment by qingwli** [comment]
Move to #12929

**Pull request closed without merging**
