### PR TITLE
[CI][Doc] Add lint for markdown document

### LINKED ISSUE #8391: [Feature][Doc] Add lint for markdown document
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For now, our website without lint, I think we should better support lint for document.

I think we should only lint laster verison and dev version of our document, maybe we should use https://github.com/markdownlint/markdownlint or some other tool to do that

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hezean**
## Purpose of the pull request

Resolves #8391

Ex. see https://github.com/HeZean/dolphinscheduler/actions/runs/2949741507

### CODE REVIEW

**Comment by hezean** [comment]
There are too many lint errors, I'll submit another PR to fix them

**Comment by EricGao888** [comment]
Sorry, I closed it by mistake just now. I've reopened it. This one is great, it could save our time for reviewing and fixing docs manually.

**Comment by hezean** [comment]
@EricGao888 can we merge this PR first, and fix the lint errors in another PR? I think that may make review easier

**Comment by EricGao888** [comment]
> @EricGao888 can we merge this PR first, and fix the lint errors in another PR? I think that may make review easier

I'm fine with it. WDYT? @SbloodyS BTW, @HeZean  could you please add the key word `related: #xxxxxxxx` in `another PR` so that we could understand what `another PR` you are referring to.

**Review by EricGao888 — APPROVED** [review]
LGTM, but I'm wondering whether there are any conflicts between `spotless flexmark step` and `lint` for markdown files? Have you experimented on it? @HeZean

**Comment by kezhenxu94** [comment]
> LGTM, but I'm wondering whether there are any conflicts between `spotless flexmark step` and `lint` for markdown files? Have you experimented on it? @HeZean 

I prefer we use a single linter (spotless) to do the linting stuffs. It's easier for developers to verify locally and don't require another learning how superlinter works

**Comment by hezean** [comment]
Thanks for the suggestion! I totally agree on it and will take a look at spotless, whereas I'm busy preparing for an important exam recently, please give me some time before I can step back to this pr.

**Comment by EricGao888** [comment]
> > LGTM, but I'm wondering whether there are any conflicts between `spotless flexmark step` and `lint` for markdown files? Have you experimented on it? @HeZean
> 
> I prefer we use a single linter (spotless) to do the linting stuffs. It's easier for developers to verify locally and don't require another learning how superlinter works

+1

**Comment by EricGao888** [comment]
> Thanks for the suggestion! I totally agree on it and will take a look at spotless, whereas I'm busy preparing for an important exam recently, please give me some time before I can step back to this pr.

@HeZean Good luck with the exam : )

**Comment by kezhenxu94** [comment]
Is this fixed by https://github.com/apache/dolphinscheduler/pull/12006?

**Comment by hezean** [comment]
closing this outdated pr as finished in #12977

**Pull request closed without merging**
