### PR TITLE
[improvement][Resources] Improve details page return to the previous list page (#14951)

### LINKED ISSUE #14951: [Improvement][Resources Project] The details page does not return to the previous list page after returning to the list page
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

version 3.1.x  、3.2.x
**Current Problems**
图片
图片
图片
When you come to the task or workflow list interface(Figure 1), click the task edit button on the specified page to enter the task details page(Figure 2). When you return, you will jump to the first page instead of the page where the original task is located(Figure 3). Very unfriendly to the user's experience.

图片
图片
图片
When you come to the list interface of the resource file, click the edit button of the resource file on the specified page to enter the details page of the resource file. When you return or save, you will jump to the first page instead of the page where the original resource file is located. It is also very unfriendly to the user's experience.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhutong6688**
## Purpose of the pull request

Current Problem Is fix #14951 in any version of 3.1.x or 3.2.x or later version
The purpose of this modification is that when we are in the resource list, we click into the resource details page, and then return to the resource list, we can still return to the original resource list。

## Brief change log
base on dev branch
add main improve code in dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
add main improve code in dolphinscheduler-ui/src/views/resource/components/resource/edit/use-edit.ts
add main improve code in dolphinscheduler-ui/src/views/resource/components/resource/table/use-table.ts
add main improve code dolphinscheduler-ui/src/views/resource/components/resource/index.tsx

## Verify this pull request

This is the test verification of this improvement for problem #14951, as follows：
1、Query resource list unconditionally
图片
图片
图片
图片

2、Query resource list conditionally
图片
图片
图片
图片
图片

As can be seen from the above, whether in the case of conditional or unconditional query of resource files, when you enter the corresponding resource details page and click Save or Return, you can smoothly return to the previous resource list, greatly improving the development efficiency. Otherwise, you will return to the home page every time and lose the query conditions, which greatly reduces the development efficiency。

### CODE REVIEW

**Comment by pinkfloyds** [comment]
@zhutong6688 Good job !

**Comment by zhutong6688** [comment]
I use pinia to store data instead of using localStorage directly

**Comment by zhutong6688** [comment]
I have applied this optimization to the dolphin scheduling used by our company, This Improvement has greatly improved the development efficiency and user experience.

**Review by songjianet — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
