### PR TITLE
[fix-11295] remove duplicate classes

### LINKED ISSUE #11295: [Improvement][common,task-api] have duplicate classes
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

image
PlaceholderUtils  PropertyPlaceholderHelper  TimePlaceholderUtils BusinessTimeUtils

maybe we can left class in task-api ,because common depends on task -api

image

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request
remove duplicate classes

## Brief change log
remove duplicate classes include PlaceholderUtils PropertyPlaceholderHelper TimePlaceHolderUtils

## Verify this pull request
This pull request is code cleanup without any test coverage.

this close #11295

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@WangJPLeo I remember some class are used in WS, we may need to add some comments or refactor this.

**Comment by fuchanghai** [comment]
> @WangJPLeo I remember some class are used in WS, we may need to add some comments or refactor this.

I marked the improvement tag for this issue. But in my newly opened maven project, the api module was introduced, because these classes with the same name caused the same name to report an error. I don't understand very well, because these names have different paths, and I haven't seen the use of @autowire, how can this error be reported。
Seeing that you want to redesign, I will tell you about the doubts I encountered before

**Comment by fuchanghai** [comment]
@ruanwenjun @caishunfeng These bugs may not be caused by the code I modified。

**Comment by caishunfeng** [comment]
> @WangJPLeo I remember some class are used in WS, we may need to add some comments or refactor this.

Yes, as wenjun said, we need to modify in WS if we cherry-pick this pr, but I think it's OK. cc @WangJPLeo

**Review by caishunfeng — APPROVED** [review]
LGTM

**Review by zhuangchong — APPROVED** [review]

**Pull request merged**
