### PR TITLE
[fix-11378] fix API-Server release response message typo

### LINKED ISSUE #11378: [Improvement] [API] API-Server release response message typo
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

### What you expected to happen

- response right message

### How to reproduce

- when an error occurs ，response right message

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

fix response message error

## Brief change log

fix response message error

## Verify this pull request

This pull request is already covered by existing tests

this close #11378

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
LGTM, some important things I want to mention.

1. This is not a Bug, this is just a typo improvement.
2. Please write the correct title of the issue and PR, "response message error" is not a good title.

**Comment by fuchanghai** [comment]
@ruanwenjun I have some different opinions，In my project group.
-  if there is a spelling error in the comment, or the documentation is wrong, these errors for internal personnel belong to improvement
- Anything shown to end users that is not what they want is a bug
That's why I tag the bug ,just my personal understanding

**Comment by ruanwenjun** [comment]
> @ruanwenjun I have some different opinions，In my project group.
> 
> * if there is a spelling error in the comment, or the documentation is wrong, these errors for internal personnel belong to improvement
> * Anything shown to end users that is not what they want is a bug
>   That's why I tag the bug ,just my personal understanding

If the error is writting online as offline, then it should be a bug...., I don't think `on line` should be a bug...

And I don't agree `Anything shown to end users that is not what they want is a bug`.

**Pull request merged**
