### PR TITLE
[Improvement][deploy] worker template persistentVolumeClaim link Improvement-11247

### LINKED ISSUE #11247: [Improvement][Deploy kubernetes] values.yaml config worker. persistentVolumeClaim
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Improvement deploy kubernetes worker template ,
in config value.yaml
image

if ".Values.worker.persistentVolumeClaim.enabled" is false,but ".Values.worker.persistentVolumeClaim.dataPersistentVolume.enabled" config item is true，the template would take a error.
The normal logic main switch is closed, and the sub-switch is turned on, it will not take effect, but the current mechanism main switch does not take effect

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
- https://github.com/apache/dolphinscheduler/pull/11248

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lishiyucn**
closes https://github.com/apache/dolphinscheduler/issues/11247
## Brief change log

Improvement deploy kubernetes worker template , 
in config value.yaml 
image
if ".Values.worker.persistentVolumeClaim.enabled"  is false,but ".Values.worker.persistentVolumeClaim.dataPersistentVolume.enabled" config item is true，the template would take a error.
The normal logic main switch is closed, and the sub-switch is turned on, it will not take effect, but the current mechanism main switch does not take effect

## Verify this pull request

The newly submitted code modifies the template to make the master switch take effect

### CODE REVIEW

**Comment by lishiyucn** [comment]
#https://github.com/apache/dolphinscheduler/issues/11247

**Comment by lishiyucn** [comment]
This commit needs to wait until when can the code review?
@kezhenxu94 @caishunfeng

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Comment by caishunfeng** [comment]
Hi @lishiyucn please resolve the conflicts.

Please use the correct title for this pr.

**Comment by lishiyucn** [comment]
@caishunfeng I revised the conflicts point and updated the title of the pr

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
