### PR TITLE
[Improvement] The newly introduced spi pugin support work in windows os.

### PR DESCRIPTION
**Pull request by echohlne**
**The newly introduced spi (#5562) can't work in windows os, it leads to the project can't be launched in windows.**

## Purpose of the pull request
git clone the latest branch of dev in windows, and try to run the entire project in windows os, but it would throws exception like below:
```markdown
Caused by: java.lang.RuntimeException: Unexpected file for main artifact: E:\workspaces\dolphinscheduler\.\dolphinscheduler-registry-plugin\dolphinscheduler-registry-zookeeper\target\classes**
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginDiscovery.discoverPluginsFromArtifact(DolphinPluginDiscovery.java:73)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoaderFromPom(DolphinPluginLoader.java:136)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.buildPluginClassLoader(DolphinPluginLoader.java:121)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugin(DolphinPluginLoader.java:97)
	at org.apache.dolphinscheduler.spi.plugin.DolphinPluginLoader.loadPlugins(DolphinPluginLoader.java:90)
	at org.apache.dolphinscheduler.service.registry.RegistryCenter.installRegistryPlugin(RegistryCenter.java:138)
	... 38 more
Disconnected from the target VM, address: '127.0.0.1:11392', transport: 'socket'
```

The code in `DolphinPluginDiscovery.java` uses hard code to test whether the dir is ok:
```java
 if (!file.getPath().endsWith("/target/classes")) {
            throw new RuntimeException("Unexpected file for main artifact: " + file);
 }
```
**but it does't consider the sperator in  windows OS is different in unix-like OS. The static vriables in `DolphinPluginDiscovery.java` also have the same problems.**

## Brief change log
Use the File.sperator to repleace the hardcode :"/"

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

anually verified the change by testing locally

### CODE REVIEW

**Comment by kyoty** [comment]
cc @zhuangchong , hi,can you help me to review this? it's a enhancement of pr #5635

**Comment by kyoty** [comment]
cc @zhuangchong , hi,can you help me to review this? it's a enhancement of pr #5635

**Comment by echohlne** [comment]
cc @CalvinKirs , hi,can you help me to review this? it's a enhancement about pr #5562

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
