### PR TITLE
[Bug] [Alert] Ignore alert not write info to db

### LINKED ISSUE #12866: [Bug] [Alert] Ignore alert not write info to db
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Alert warning type does not match instance, will ignore this alert, but not write correct into the back to DB.

### What you expected to happen

When the alert warning type does not match the instance, write the correct info to DB.

### How to reproduce

⬆️

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qingwli**
- close #12866

### CODE REVIEW

**Review by davidzollo — DISMISSED** [review]
+1
LGTM

**Review by SbloodyS — COMMENTED** [review]
Please check the failed CI.

**Comment by qingwli** [comment]
I'm not sure this code smell is a question, I have checked `alertResultHandler` method will never return a null value, but I think adding a not null check is better maybe someday somebody chaneged this method will return a null value.

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by qingwli** [comment]
This pr needs 3.1.x label too.

**Comment by zhongjiajie** [comment]
@zhuangchong Please make sure wether we can cherry pick this PR to version 3.1.2

**Pull request merged**
