### PR TITLE
[FIX-11114][improvement] [UI] Changed the background color of the task priority drop-down box to overwrite the font 

### LINKED ISSUE #11114: [Bug] [UI] Changed the background color of the task priority drop-down box to overwrite the font
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
The value is obscured by the dangling background color of the dropdown box

### What you expected to happen

Clash of styles

### How to reproduce

.n-base-select-option--pending::before{
  background-color: rgba(0,0,0,0.1) !important;
}
.n-base-select-option--pending::before{
  background-color: rgba(0,0,0,0.1) !important;
}

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TangTangGrit**
## Purpose of the pull request

Changed the background color of the task priority drop-down box to overwrite the font

fix #11114

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @TangTangGrit , please associate the issue.

**Comment by TangTangGrit** [comment]
The address of the problem,#11114
[https://github.com/apache/dolphinscheduler/issues/11114](url)

**Comment by TangTangGrit** [comment]
#11114 @SbloodyS

**Comment by SbloodyS** [comment]
> #11114 @SbloodyS

to target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, just desc). It would not only connect issue to PR but also close issue automatically when PR is be closed.

**Review by Amy0104 — CHANGES_REQUESTED** [review]
This is a bug in naive-ui. It's not suggested to change the color in global because there may be a clutter of others dropdown.

**Comment by Amy0104** [comment]
It's better to upgrade z-index of the option text.

**Comment by Amy0104** [comment]
Have you got any questions？ @TangTangGrit

**Comment by TangTangGrit** [comment]
> 你有什么问题吗？@TangTangGrit
There's nothing wrong with it. Your advice. I'm trying. I don't have any good solutions here. I asked someone else to take care of it

**Comment by TangTangGrit** [comment]
> 你有什么问题吗？@TangTangGrit

I modified the global color, which I tested did not affect the other dropdown boxes

**Comment by Amy0104** [comment]
> > 你有什么问题吗？@TangTangGrit
> > There's nothing wrong with it. Your advice. I'm trying. I don't have any good solutions here. I asked someone else to take care of it

Try to wrap the label with a span, then set the z-index of the span to 1. @TangTangGrit

**Pull request closed without merging**
