### PR TITLE
Fix shell tools for database schema cannot run

### LINKED ISSUE #6998: [Bug] [dolphin-api]  api start failed in k8s cause org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
```java
7:15:14.812 [main] ERROR org.apache.dolphinscheduler.dao.datasource.ConnectionFactory - Initializing ConnectionFactory error
java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.ibatis.mapping.Environment.<init>(Environment.java:39)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getSqlSessionFactory(ConnectionFactory.java:92)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:57)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:43)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory$ConnectionFactoryHolder.<clinit>(ConnectionFactory.java:48)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getInstance(ConnectionFactory.java:52)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.getDataSource(UpgradeDao.java:82)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.<clinit>(UpgradeDao.java:78)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initUpgradeDao(DolphinSchedulerManager.java:39)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.<init>(DolphinSchedulerManager.java:59)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:37)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getInstance(ConnectionFactory.java:52)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.getDataSource(UpgradeDao.java:82)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.<clinit>(UpgradeDao.java:78)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initUpgradeDao(DolphinSchedulerManager.java:39)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.<init>(DolphinSchedulerManager.java:59)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:37)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:61)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:43)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory$ConnectionFactoryHolder.<clinit>(ConnectionFactory.java:48)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.ibatis.mapping.Environment.<init>(Environment.java:39)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getSqlSessionFactory(ConnectionFactory.java:92)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:57)
	... 8 more

```
### What you expected to happen

api start normally

### How to reproduce
```java
7:15:14.812 [main] ERROR org.apache.dolphinscheduler.dao.datasource.ConnectionFactory - Initializing ConnectionFactory error
java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.ibatis.mapping.Environment.<init>(Environment.java:39)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getSqlSessionFactory(ConnectionFactory.java:92)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:57)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:43)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory$ConnectionFactoryHolder.<clinit>(ConnectionFactory.java:48)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getInstance(ConnectionFactory.java:52)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.getDataSource(UpgradeDao.java:82)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.<clinit>(UpgradeDao.java:78)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initUpgradeDao(DolphinSchedulerManager.java:39)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.<init>(DolphinSchedulerManager.java:59)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:37)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getInstance(ConnectionFactory.java:52)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.getDataSource(UpgradeDao.java:82)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.<clinit>(UpgradeDao.java:78)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initUpgradeDao(DolphinSchedulerManager.java:39)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.<init>(DolphinSchedulerManager.java:59)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:37)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:61)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:43)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory$ConnectionFactoryHolder.<clinit>(ConnectionFactory.java:48)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.ibatis.mapping.Environment.<init>(Environment.java:39)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getSqlSessionFactory(ConnectionFactory.java:92)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:57)
	... 8 more
```

### Anything else
```java
7:15:14.812 [main] ERROR org.apache.dolphinscheduler.dao.datasource.ConnectionFactory - Initializing ConnectionFactory error
java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.ibatis.mapping.Environment.<init>(Environment.java:39)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getSqlSessionFactory(ConnectionFactory.java:92)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:57)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:43)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory$ConnectionFactoryHolder.<clinit>(ConnectionFactory.java:48)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getInstance(ConnectionFactory.java:52)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.getDataSource(UpgradeDao.java:82)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.<clinit>(UpgradeDao.java:78)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initUpgradeDao(DolphinSchedulerManager.java:39)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.<init>(DolphinSchedulerManager.java:59)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:37)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getInstance(ConnectionFactory.java:52)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.getDataSource(UpgradeDao.java:82)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.<clinit>(UpgradeDao.java:78)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initUpgradeDao(DolphinSchedulerManager.java:39)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.<init>(DolphinSchedulerManager.java:59)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:37)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:61)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:43)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory$ConnectionFactoryHolder.<clinit>(ConnectionFactory.java:48)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Parameter 'dataSource' must not be null
	at org.apache.ibatis.mapping.Environment.<init>(Environment.java:39)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.getSqlSessionFactory(ConnectionFactory.java:92)
	at org.apache.dolphinscheduler.dao.datasource.ConnectionFactory.<init>(ConnectionFactory.java:57)
	... 8 more
```

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kezhenxu94**
Closes https://github.com/apache/dolphinscheduler/issues/6998

@zwZjut can you take a look at this?

### CODE REVIEW

**Comment by zwZjut** [comment]
> 
I have two questions:
(1) who will init class DolphinSchedulerManager by   "public DolphinSchedulerManager(DataSource dataSource, List<UpgradeDao> daos)"  ?
(2)  how to send env to datasource like "export=${DATABASE_PARAMS:-"characterEncoding=utf8"}" ?

**Comment by kezhenxu94** [comment]
> I have two questions:
> (1) who will init class DolphinSchedulerManager by "public DolphinSchedulerManager(DataSource dataSource, List daos)" ?

Spring will init this

> (2) how to send env to datasource like "export=${DATABASE_PARAMS:-"characterEncoding=utf8"}" ?

Use this environment variable to override the JDBC URL `export SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/dolphinscheduler?characterEncoding=utf8`

**Comment by zwZjut** [comment]
> > I have two questions:
> > (1) who will init class DolphinSchedulerManager by "public DolphinSchedulerManager(DataSource dataSource, List daos)" ?
> 
> Spring will init this
> 
> > (2) how to send env to datasource like "export=${DATABASE_PARAMS:-"characterEncoding=utf8"}" ?
> 
> Use this environment variable to override the JDBC URL `export SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/dolphinscheduler?characterEncoding=utf8`

how to select the type of datasource  mysql ,h2, postgresql  by env  ?

**Comment by kezhenxu94** [comment]
> how to select the type of datasource mysql ,h2, postgresql by env ?

`export dbtype=h2` / `export dbtype=mysql` / `export dbtype=postgresql`

**Comment by zwZjut** [comment]
> Use this environment variable to override the JDBC URL `export SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/dolphinscheduler?characterEncoding=utf8`

“Database”,  the part of startup-init-conf.sh also needs to be modified  , or another pr

**Comment by kezhenxu94** [comment]
> > Use this environment variable to override the JDBC URL `export SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/dolphinscheduler?characterEncoding=utf8`
> 
> “Database”, the part of startup-init-conf.sh also needs to be modified , or another pr

Updated the `dbtype` back to `DATABASE_TYPE` for compatibility

**Comment by zwZjut** [comment]
> > how to select the type of datasource mysql ,h2, postgresql by env ?
> 
> `export dbtype=h2` / `export dbtype=mysql` / `export dbtype=postgresql`

in dolphinscheduler-daemon.sh , it will be set  like this : export SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE},api,${dbtype}",
but it does not  in  create-dolphinscheduler.sh and  upgrade-dolphinscheduler.sh; create-dolphinscheduler.sh execute before  dolphinscheduler-daemon.sh ,does it mater ?

**Comment by kezhenxu94** [comment]
> > > how to select the type of datasource mysql ,h2, postgresql by env ?
> > 
> > 
> > `export dbtype=h2` / `export dbtype=mysql` / `export dbtype=postgresql`
> 
> in dolphinscheduler-daemon.sh , it will be set like this : export SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE},api,${dbtype}", but it does not in create-dolphinscheduler.sh and upgrade-dolphinscheduler.sh; create-dolphinscheduler.sh execute before dolphinscheduler-daemon.sh ,does it mater ?

Hi @zwZjut I've also updated the `dbtype` to `DATABSE_TYPE` in `dolphinscheduler-daemon.sh`

**Comment by zwZjut** [comment]
LGTM, I don't have the permission of  "+ 1", but I hope this fix  can be merged into dev as soon as possible

**Comment by kezhenxu94** [comment]
> LGTM, I don't have the permission of "+ 1", but I hope this fix can be merged into dev as soon as possible

@CalvinKirs @lenboo please take a look

**Review by CalvinKirs — DISMISSED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
