### PR TITLE
[Fix-16475][UI] Can't SET Timing successful in Workflow Definition grid

### LINKED ISSUE #16475: [Bug] [UI] Can't  SET Timing successful in Workflow Definition grid
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the workflow definition page, it is not possible to set a timer for two processes consecutively.

### What you expected to happen

On the workflow definition page, it is desired to be able to set a timer for two processes consecutively.

### How to reproduce

1. create two processes in Workflow Definition page
2. choose one process to set Timing, its successful
3. choose another process to set Timing, its failed. Response message like: schedule 42 does not exist.

Another method:
1.Open the page of  Workflow Definition, then choose two processes,  one of these have set Timing and another isn't set timing
timing0
2. Check the Timing of a process which have set timing
timing1
3. Choose another process which no timing, try to set it's Timing. And then it response message: schedule 42 does not exist.
timing2

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by topsli**
## Purpose of the pull request

close #16475

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM. Thanks for your contribution.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by SbloodyS** [comment]
Frontend build failed. Please check it. @topsli

**Comment by topsli** [comment]
I've made the updates, please review them again.
` variables.timingState = 'OFFLINE'`

**Review by SbloodyS — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]

**Pull request merged**
