### PR TITLE
[Bug] [docs] doc MinIO write wrong #15394

### PR DESCRIPTION
**Pull request by DalongZhenZ**
[Bug] [docs] doc MinIO write wrong

### CODE REVIEW

**Comment by fuchanghai** [comment]
plz don't merge ,I don't think it's right to merge the changes into the released version cc @davidzollo @zhuangchong 
 @EricGao888  WDYT

**Comment by zhuangchong** [comment]
Will merging the document into the released branch take effect? @zhongjiajie

**Comment by EricGao888** [comment]
Please DO NOT merge PR into released branch, normally we only merge PRs into `dev` branch.

**Comment by zhongjiajie** [comment]
> Please DO NOT merge PR into released branch, normally we only merge PRs into `dev` branch.

I would also add some commits about docs change to the release branch, because we use `*-release` to render our docs, and that is why we delete `*-prepare` but keep all `*-release` in our repos. which we can see the config in https://github.com/apache/dolphinscheduler-website/blob/f9875452b925d0b94e1173a1009d2d5f241c785f/scripts/conf.sh#L49-L70
So  maybe we should change the branch name from `*-release` to `*-doc` for classification, to tell user this branch only for docs rendering

Eric considers we should not change the release branch code because we do not want to break the released version code. And I think when users when to add some custom change based on specific released version, they should use a specific tag instead of `*-release` branch

**Pull request closed without merging**
