### PR TITLE
[fix] DB2 username can not be save

### PR DESCRIPTION
**Pull request by AliceXiaoLu**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by davidzollo — DISMISSED** [review]
+1
good job

**Comment by AliceXiaoLu** [comment]
@davidzollo 麻烦review了。

**Comment by AliceXiaoLu** [comment]
@caishunfeng 麻烦+2了

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Comment by caishunfeng** [comment]
image
Hi  @AliceXiaoLu please check the fail CI case

**Comment by AliceXiaoLu** [comment]
@caishunfeng +1

**Comment by AliceXiaoLu** [comment]
@caishunfeng

**Review by SbloodyS — COMMENTED** [review]
I've rerun the CI.

**Comment by AliceXiaoLu** [comment]
@SbloodyS CLI is wrong??

**Comment by AliceXiaoLu** [comment]
@caishunfeng

**Review by davidzollo — DISMISSED** [review]
+1
LGTM

**Comment by caishunfeng** [comment]
@AliceXiaoLu please check the fail CI case.

**Comment by caishunfeng** [comment]
Please link the issue or add the pr description, thanks.

**Comment by AliceXiaoLu** [comment]
@caishunfeng Sorry, Forget to change Test error。 Please retun the CI again. Thank you again.

**Comment by AliceXiaoLu** [comment]
@caishunfeng Please add label -[cicd required Label must include one or more version numbers.]； Thank you again。

**Comment by zhongjiajie** [comment]
seem mergeable can not re-run with no idea

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
