### PR TITLE
[Bug][Master] Fix taskInstance's start time might be null when dispatch failed

### PR DESCRIPTION
**Pull request by jackyyyyyssss**
## Purpose of the pull request
If there is only one work and the available resources are very low, the heartbeat will result in no available work Dispatcher method reporting an error, and calling addDispatchFailedEvent will result in an empty starttime. In this case, the task is actually a failure. When querying failed tasks in the foreground, the count is incorrect because the starttime is empty
image
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by fuchanghai — APPROVED** [review]
LGTM

**Review by fuchanghai — CHANGES_REQUESTED** [review]
hi @jackyyyyyssss  I refute the point I agreed with before, because according to the logic of the previous version, startTime is the time when the task is in the running state, and startTime in the dispatch state should be null because the task has not really started. We should solve it in another way. this problem , WDYT? cc @ruanwenjun

**Comment by jackyyyyyssss** [comment]
> hi @jackyyyyyssss I refute the point I agreed with before, because according to the logic of the previous version, startTime is the time when the task is in the running state, and startTime in the dispatch state should be null because the task has not really started. We should solve it in another way. this problem , WDYT? cc @ruanwenjun

Thank you for your feedback. It is incorrect to have a start and end time according to this method, but not setting a time will result in the loss of front-end statistical tasks

**Comment by fuchanghai** [comment]
> LGTM



> > hi @jackyyyyyssss I refute the point I agreed with before, because according to the logic of the previous version, startTime is the time when the task is in the running state, and startTime in the dispatch state should be null because the task has not really started. We should solve it in another way. this problem , WDYT? cc @ruanwenjun
> 
> Thank you for your feedback. It is incorrect to have a start and end time according to this method, but not setting a time will result in the loss of front-end statistical tasks

hi @jackyyyyyssss  can we modify the statistical's interface to fix this bug?

**Comment by jackyyyyyssss** [comment]
> > LGTM
> 
> > > hi @jackyyyyyssss I refute the point I agreed with before, because according to the logic of the previous version, startTime is the time when the task is in the running state, and startTime in the dispatch state should be null because the task has not really started. We should solve it in another way. this problem , WDYT? cc @ruanwenjun
> > 
> > 
> > Thank you for your feedback. It is incorrect to have a start and end time according to this method, but not setting a time will result in the loss of front-end statistical tasks
> 
> hi @jackyyyyyssss can we modify the statistical's interface to fix this bug?
Statistical task time is a display field. If it is empty, it may seem strange. We can take a look at the opinions of others

**Comment by fuchanghai** [comment]
> > > LGTM
> > 
> > 
> > > > hi @jackyyyyyssss I refute the point I agreed with before, because according to the logic of the previous version, startTime is the time when the task is in the running state, and startTime in the dispatch state should be null because the task has not really started. We should solve it in another way. this problem , WDYT? cc @ruanwenjun
> > > 
> > > 
> > > Thank you for your feedback. It is incorrect to have a start and end time according to this method, but not setting a time will result in the loss of front-end statistical tasks
> > 
> > 
> > hi @jackyyyyyssss can we modify the statistical's interface to fix this bug?
> > Statistical task time is a display field. If it is empty, it may seem strange. We can take a look at the opinions of others

Can you tell me which statistics interface it is? I'd be happy to take a look at it when I have free time.

**Comment by jackyyyyyssss** [comment]
> > > > LGTM
> > > 
> > > 
> > > > > hi @jackyyyyyssss I refute the point I agreed with before, because according to the logic of the previous version, startTime is the time when the task is in the running state, and startTime in the dispatch state should be null because the task has not really started. We should solve it in another way. this problem , WDYT? cc @ruanwenjun
> > > > 
> > > > 
> > > > Thank you for your feedback. It is incorrect to have a start and end time according to this method, but not setting a time will result in the loss of front-end statistical tasks
> > > 
> > > 
> > > hi @jackyyyyyssss can we modify the statistical's interface to fix this bug?
> > > Statistical task time is a display field. If it is empty, it may seem strange. We can take a look at the opinions of others
> 
> Can you tell me which statistics interface it is? I'd be happy to take a look at it when I have free time.
Display on the homepage


image

**Pull request closed without merging**
