### PR TITLE
[Fix] [Worker] Fix worker will hang if fails to start 

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

cherry-pick #10342

## Brief change log

- Change thread to daemon
- Remove memory_max,cpu_quota in TaskDefinitionMapper, since these two fields not used in 3.0.0

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@caishunfeng @devosend  Please take a look.

**Comment by caishunfeng** [comment]
I rerun the fail UT

**Comment by ruanwenjun** [comment]
The CI failed, since the version of 3.0.0-beta is not dev.

image

**Comment by caishunfeng** [comment]
> The CI failed, since the version of 3.0.0-beta is not dev.
> 
> image


Got it. I will merge this pr. 
But is there any solution to this?

**Pull request merged**
