### PR TITLE
[Improvement][pom]chore: update mysql dependency

### PR DESCRIPTION
**Pull request by Gallardot**
## Purpose of the pull request

ref: https://github.com/apache/dolphinscheduler/issues/14683

ref: https://dev.mysql.com/doc/connector-j/en/connector-j-installing-maven.html

You can link the Connector/J library to your project by adding the following dependency in your pom.xml file:
```
<dependency>
    <groupId>com.mysql</groupId>
    <artifactId>mysql-connector-j</artifactId>
    <version>x.y.z</version>
</dependency>
```

Note
For Connector/J 8.0.29 and earlier, use the following Maven coordinates:
```
groupId: mysql

artifactId: mysql-connector-java
```

now we using Connector/J 8.4.0

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by Radeity** [comment]
Dependency license check failed, and dependency `+mysql-connector-java-8.0.30.jar` appears, it's weird.

**Comment by ruanwenjun** [comment]
The link https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-installing-maven.html is 404 and it seems this pr might bring incompatible problem.

**Comment by Gallardot** [comment]
> The link https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-installing-maven.html is 404 and it seems this pr might bring incompatible problem.

@ruanwenjun 

The current 8.0.33 version also has a cve vulnerability, updated to the latest 8.4.0 version.
ref link update to https://dev.mysql.com/doc/connector-j/en/connector-j-installing-maven.html

**Comment by SbloodyS** [comment]
The current version of mysql's CVE is not higher than 7 points, we do not need to upgrade it.

**Pull request closed without merging**
