### PR TITLE
[FIX][WEBSITE-9224]fix wechat doc and wechat form display

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

fix the doc according to code changes
refer to https://github.com/apache/dolphinscheduler/pull/9225

## Verify this pull request

I have test this locally.

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
It will be more beautiful to change the screenshot to the one in markdown format. What do you think? @Tianqi-Dotes

**Comment by zhongjiajie** [comment]
Hi @Tianqi-Dotes , we should only English version screenshot in both En and Zh doc

**Comment by zhongjiajie** [comment]
> It will be more beautiful to change the screenshot to the one in markdown format. What do you think? @Tianqi-Dotes

What do you mean screenshot in markdown format?

**Comment by SbloodyS** [comment]
> > It will be more beautiful to change the screenshot to the one in markdown format. What do you think? @Tianqi-Dotes
> 
> What do you mean screenshot in markdown format?

Screenshot in markdown format just like this.

**Comment by zhongjiajie** [comment]
> > > It will be more beautiful to change the screenshot to the one in markdown format. What do you think? @Tianqi-Dotes
> > 
> > 
> > What do you mean screenshot in markdown format?
> 
> Screenshot in markdown format just like this. 

Get it, cc: @Tianqi-Dotes

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Pull request merged**
