### PR TITLE
fix-13869: add return success judge

### LINKED ISSUE #13869: [Improvement] [dolphinscheduler-api] There is no judgment whether to return to success
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

An error occurred when creating a python script, but no reason was returned

### What you expected to happen

return error reason

### How to reproduce

image

### Anything else

_No response_

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jackfanwan**
add return success judge

close: #13869

### CODE REVIEW

**Review by caishunfeng — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Review by SbloodyS — COMMENTED** [review]
Please check the failed CI.

**Comment by jackfanwan** [comment]
> Please check the failed CI.

@SbloodyS this is ci problem, please try for me

**Pull request merged**
