### PR TITLE
[Fix-6978][UI]fix token delete request 404

### LINKED ISSUE #6978: [Bug] [UI] Token delete request 404
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Token delete request 404.
```
xhr.js?b50d:178 DELETE http://localhost:8888/dolphinscheduler/access-token/3?id=3 404 (Not Found)
```

### What you expected to happen

Token delete request is normal

### How to reproduce

Delete token

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this pr close #6978 6978
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhuangchong** [comment]
@songjianet 
Please help review

**Review by songjianet — APPROVED** [review]

**Comment by songjianet** [comment]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Please cherry-pick this patch to 2.0.1 @CalvinKirs @zhuangchong @lenboo

**Comment by zhongjiajie** [comment]
Oh, I know that, I could do it by myself.

**Comment by zhongjiajie** [comment]
@CalvinKirs  Please move milestone from 2.0.2 to 2.0.1

**Pull request merged**
