### PR TITLE
[python] Add tox for out of box test

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Add `tox` for easy and complete test
* Correct package data attribute
* Add more dirs in flake8 ignore

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend @jieguangzhou thanks

**Review by devosend — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
PTAL @caishunfeng @songjianet , the failing CI is not related to this patch

**Review by songjianet — APPROVED** [review]
LGTM

**Pull request merged**
