### PR TITLE
[Improvement] Resource authority module database table unique index increased.

### LINKED ISSUE #10806: [Improvement] Project, Queue, UDF, Tenant module database tables are missing unique indexes.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Project, Queue, UDF, Tenant module database tables are missing unique indexes.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

Project、Queue、UDF、Tenant table unique add.

## Brief change log

close #10806 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM

**Review by lenboo — DISMISSED** [review]
+1

**Comment by caishunfeng** [comment]
Hi @WangJPLeo you should change the sql file too, include mysql、pgsql and h2.

**Comment by WangJPLeo** [comment]
> Hi @WangJPLeo you should change the sql file too, include mysql、pgsql and h2.
ok thx, i'll change it. @caishunfeng

**Review by caishunfeng — APPROVED** [review]
LGTM

**Pull request merged**
