### PR TITLE
[Feature-#5273][server-UI] Task node of SWITCH

### PR DESCRIPTION
**Pull request by gitofrenlu**
[Feature-#5273][server-UI] Task node of SWITCH 
Determine the nodes that need to be run based on the value of the parameter.

### CODE REVIEW

**Review by zhuangchong — COMMENTED** [review]
image

No data for branch circulation parameters?

**Comment by CalvinKirs** [comment]
hi,how it is going?

**Comment by zhuangchong** [comment]
#5939

**Comment by CalvinKirs** [comment]
> #5939

thx Chong, so,can I close it?

**Comment by zhuangchong** [comment]
I see that the functions of the two PR submissions are the same, close this pr first.

**Pull request closed without merging**
