### PR TITLE
[Fix][CI] fix the ci error of E2E-K8S-Execute

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

fix CI error
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by rickchengx** [comment]
PTAL @ruanwenjun @SbloodyS @caishunfeng @Radeity

**Comment by EricGao888** [comment]
Looks like #15922 attempted to make datasource configurable but forgot to add default values of profile in `values.yaml`, which causes CI to fail. What about add default profile values in `values.yaml`?

**Review by EricGao888 — DISMISSED** [review]

**Comment by rickchengx** [comment]
> Looks like #15922 attempted to make datasource configurable but forgot to add default values of profile in `values.yaml`, which causes CI to fail. What about add default profile values in `values.yaml`?

Sure, I've added `datasource.profile` in `values.yaml`

**Review by ruanwenjun — COMMENTED** [review]
LGTM

**Review by Radeity — DISMISSED** [review]

**Review by ruanwenjun — DISMISSED** [review]

**Comment by rickchengx** [comment]
Update `deploy/kubernetes/dolphinscheduler/README.md`

**Review by EricGao888 — APPROVED** [review]

**Comment by Radeity** [comment]
Hi @ruanwenjun , would you like to help check the failed UT?

**Review by ruanwenjun — APPROVED** [review]

**Comment by ruanwenjun** [comment]
> Hi @ruanwenjun , would you like to help check the failed UT?

This might cause by the 
```
block-until-connected: 600ms
```
is too small, I submit https://github.com/apache/dolphinscheduler/pull/16041 to fix this.

**Review by Radeity — APPROVED** [review]

**Pull request merged**
