### PR TITLE
[FIX][SERVER]9213

### LINKED ISSUE #9213: [Bug-RD][UI Next][V1.0.0-Alpha] UDF upload file error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**UDF upload file error**

error massage:create resource error

image

image

### What you expected to happen

Successfully uploaded

### How to reproduce

Click to upload UDF
Select file
Click on Confirm

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by nobolity**
## Purpose of the pull request

FIX #9213

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by lenboo** [comment]
@nobolity Thank you very much for contribution, but it would be nice to describe what you do in the title.

**Comment by caishunfeng** [comment]
Hi @nobolity Please add the right title of this pr.
BTW, UT run failed, please take a look.

**Comment by nobolity** [comment]
> @nobolity Thank you very much for contribution, but it would be nice to describe what you do in the title.
i  had marked a new pr to describe it

**Comment by nobolity** [comment]
i had marked a new pr to describe it [pr](https://github.com/apache/dolphinscheduler/pull/9319)

**Pull request closed without merging**
