### PR TITLE
Use workerNodeInfoWriteLock to update work node info

### LINKED ISSUE #15898: [Bug] [Master] Use workerGroupWriteLock to update work node info
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When executing the updateWorkerNodes method, since we need to update the workerNodeInfo list,  but we use the workerGroupWriteLock object. It is not OK !

private void updateWorkerNodes() {
        workerGroupWriteLock.lock();
        try {
            Map<String, String> workerNodeMaps = registryClient.getServerMaps(RegistryNodeType.WORKER);
            for (Map.Entry<String, String> entry : workerNodeMaps.entrySet()) {
                workerNodeInfo.put(entry.getKey(), JSONUtils.parseObject(entry.getValue(), WorkerHeartBeat.class));
            }
        } finally {
            workerGroupWriteLock.unlock();
        }
    }

### What you expected to happen

When executing the updateWorkerNodes method, since we need to update the workerNodeInfo list, we need to use the workerNodeInfoWriteLock object.

### How to reproduce

The modified code is as follows:

private void updateWorkerNodes() {
        workerNodeInfoWriteLock.lock();
        try {
            Map<String, String> workerNodeMaps = registryClient.getServerMaps(RegistryNodeType.WORKER);
            for (Map.Entry<String, String> entry : workerNodeMaps.entrySet()) {
                workerNodeInfo.put(entry.getKey(), JSONUtils.parseObject(entry.getValue(), WorkerHeartBeat.class));
            }
        } finally {
            workerNodeInfoWriteLock.unlock();
        }
    }

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DaqianLiao**
… be used. close #15898

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by DaqianLiao** [comment]
您好，您的邮件以收到，谢谢！未及时回复，请见谅。我会尽快处理。

**Review by Radeity — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
+1

**Comment by ruanwenjun** [comment]
I change this to improvement, and remove the bug label, since this will not cause a `bug`

**Comment by Radeity** [comment]
> I change this to improvement, and remove the bug label, since this will not cause a `bug`

Oops, my mistake, forgot to update commit message, will pay more attention next time.

**Pull request merged**
