### PR TITLE
[Feature-5668][UI]Add a quick search box to quickly locate the data source to be selected

### LINKED ISSUE #5668: [Feature][UI] Data source selection drop-down box optimization
图片

图片

这个下拉框去修改的时候 没有默认展示当前选中的  每次都是从第一条开始往下滑动 
能否优化为 点击下拉框时 就定位在回显的那条数据上

或者

优化修改此类下拉框支持 搜索

### PR DESCRIPTION
**Pull request by Zzm0809**
close #5668 
When the SQL node is selected , The data source list needs to scroll continuously, and the search efficiency is low ,
Add a quick search box to quickly locate the data source to be selected

### CODE REVIEW

**Comment by wangyizhi1** [comment]
LGTM

**Comment by CalvinKirs** [comment]
hi, @zhuangchong  PTAL,Thx

**Comment by wangyizhi1** [comment]
@zhu-mingye 
Thank you for your contribution!
I noticed an issue you mentioned before (#5668). Can you change the PR title to ``[Feature-5668][UI] xxx`` ?

**Comment by Zzm0809** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
    DONE!



@zhu-mingye
Thank you for your contribution!
I noticed an issue you mentioned before (#5668). Can you change the PR title to [Feature-5668][UI] xxx ?

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
