### PR TITLE
[python] Migrate pythonGatewayServer into api server

### PR DESCRIPTION
**Pull request by zhongjiajie**
Currently the size of our distribute package is up to
800MB, this patch is migrate python gateway server into
api server

The distribute package size before and after this patch is:

```sh
# before
796M   apache-dolphinscheduler-2.0.4-SNAPSHOT-bin.tar.gz

# after
647M   apache-dolphinscheduler-2.0.4-SNAPSHOT-bin.tar.gz
```

### CODE REVIEW

**Review by caishunfeng — COMMENTED** [review]
LGTM

**Review by SbloodyS — COMMENTED** [review]
+1

**Comment by zhongjiajie** [comment]
Does someone give me one single approval which make it could merge to dev branch?

**Review by SbloodyS — APPROVED** [review]

**Comment by SbloodyS** [comment]
> Does someone give me one single approval which make it could merge to dev branch?

I just followed the operation of Shunfeng and thought it had any special meaning...

**Comment by zhongjiajie** [comment]
Maybe shunfeng think it is good but needs one more opinion

**Pull request merged**
