### PR TITLE
[Improvement#6337]increase the log result prompt in SQL result

### PR DESCRIPTION
**Pull request by CalvinKirs**
issue #6337
pr #6387

### CODE REVIEW

**Review by lenboo — APPROVED** [review]
+1

**Comment by lenboo** [comment]
i think you need to format the title and refer this pr to the issue.

**Comment by CalvinKirs** [comment]
> i think you need to format the title and refer this pr to the issue.

done

**Review by brave-lee — APPROVED** [review]
+1

**Review by zhuangchong — APPROVED** [review]
+1

**Pull request merged**
