### PR TITLE
[BUG][Worker]Fix shell task ${setValue(key,value)} is not working

### LINKED ISSUE #5071: [Bug][Server] When setting value on shell script, it not working on the next task node.
**When setting value on shell script, it not working on the next task node.**
If using `${setValue(key, value)}` function in the shell task, it needs to share the `key` to the process instance. but now, it's not working.

**Which version of Dolphin Scheduler:**
 - [current dev branch]

### PR DESCRIPTION
**Pull request by mrproliu**
## Purpose of the pull request

Fix the shell task `${setValue(key,value)}` is not working.

fix #5071 

## Brief change log

Setting var pool content to the task.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by mrproliu** [comment]
Is anyone could help me to re-run the e2e? It's looks like downloading maven plugin failed.

**Comment by davidzollo** [comment]
> Is anyone could help me to re-run the e2e? It's looks like downloading maven plugin failed.

I will re-run this e2e

**Comment by mrproliu** [comment]
> > Is anyone could help me to re-run the e2e? It's looks like downloading maven plugin failed.
> 
> I will re-run this e2e

thanks

**Comment by davidzollo** [comment]
> > > Is anyone could help me to re-run the e2e? It's looks like downloading maven plugin failed.
> > 
> > 
> > I will re-run this e2e
> 
> thanks

hi, I can't find the corresponding issue,  if there is no issue, please create an issue first , thx

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
hi, deeply thanks for your contribution, can you create an issue for this pr, when created, I will merge it.

**Comment by mrproliu** [comment]
> hi, deeply thanks for your contribution, can you create an issue for this pr, when created, I will merge it.

Thanks for your response. I have created https://github.com/apache/incubator-dolphinscheduler/issues/5071, please take a look. Sorry, I'm not sure about the PR process, so I just created the PR.

**Comment by CalvinKirs** [comment]
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Pull request merged**
