### PR TITLE
[Bug] [Common] SnowFlakeUtils will generate duplicate id due to clock backward

### LINKED ISSUE #6742: [Bug] [Common] SnowFlakeUtils will generate duplicate id due to clock backward
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The SnowFlakeUtils will generate duplicate id due to clock backward.

This may be caused by we use `System.currentTimeMillis()` to get system time, this method is based on system time, will forward or backward.
https://stackoverflow.com/questions/2978598/will-system-currenttimemillis-always-return-a-value-previous-calls

### What you expected to happen

Generate duplicate Id

### How to reproduce

Hard to reproduce :)

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
close #6742

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@JinyLeeChina @zhongjiajie @CalvinKirs Please take a look.

**Comment by brave-lee** [comment]
> @JinyLeeChina @zhongjiajie @CalvinKirs Please take a look.
I tested this code through the upgrade program, and the duplicate problem is not solved here
image
image

**Review by brave-lee — APPROVED** [review]
+1

**Comment by brave-lee** [comment]
> > @JinyLeeChina @zhongjiajie @CalvinKirs Please take a look.
> > I tested this code through the upgrade program, and the duplicate problem is not solved here
> > image
> > image

Another PR solves the problem of duplication

**Comment by brave-lee** [comment]
#6744

**Pull request merged**
