### PR TITLE
[Improvement][K8S] Disable delete namespaces in the K8S cluster

### LINKED ISSUE #14593: [Improvement][K8S] Disable delete namespaces in the K8S cluster
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Managing namespaces in K8S is a critical task, and deleting a namespace can have severe consequences, especially in a production-level K8S cluster.  Typically, such operations are intercepted by a policy engine at the K8S Cluster to prevent accidental deletion of namespaces.  If a namespace is deleted in the DS, it can cause errors in the DS. 
I recommended to remove the logic that cascades the deletion of the namespace in the K8S cluster. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gallardot**
## Purpose of the pull request
- close #14593 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by Radeity — COMMENTED** [review]
You may also have to disable update operation. 

BTW, how about disable create operation, either. Replace with checking whether the namespace exists in kubernetes cluster.

**Comment by EricGao888** [comment]
> You may also have to disable update operation.
> 
> BTW, how about disable create operation, either. Replace with checking whether the namespace exists in kubernetes cluster.

+1. I always think managing K8S clusters is not the responsibility of DS.

**Comment by SbloodyS** [comment]
> You may also have to disable update operation.
> 
> BTW, how about disable create operation, either. Replace with checking whether the namespace exists in kubernetes cluster.

+1, Agreed!

**Comment by Gallardot** [comment]
@Radeity @EricGao888 @SbloodyS 
All done. PTAL.

**Review by Radeity — APPROVED** [review]
LGTM

**Review by EricGao888 — APPROVED** [review]

**Pull request merged**
