### PR TITLE
Fix the problem that the script name corresponds to the configuration file and does not match the 3.0.1 upgrade document

### PR DESCRIPTION
**Pull request by xinxingi**
Fix the problem that the script name corresponds to the configuration file and does not match the 3.0.1 upgrade document
#12212

## Purpose of the pull request

Fix the problem that the script name corresponds to the configuration file and does not match the 3.0.1 upgrade document

## Brief change log

1、修改了 `install_config.sh`的名称
2、修改了script目录下`status-all.sh`对应关联到新名称`install_config.sh`的内容
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Great! Would you please associate the issue? Thanks.

**Comment by xinxingi** [comment]
@SbloodyS OK,already adjusted

**Comment by xinxingi** [comment]
@SbloodyS Hello，The automatic code merge failed. I found the problem. Do I need to resubmit PR?

**Comment by xinxingi** [comment]
@ke4qqq @SbloodyS Hello，Auto-check is blocked

**Review by kezhenxu94 — APPROVED** [review]

**Review by zhongjiajie — COMMENTED** [review]
I am not sure whether we should change our file name or our document description

**Comment by kezhenxu94** [comment]
> I am not sure whether we should change our file name or our document description

Oh I missed this. I thought it was the documentations are changed. We should change the doc instead of the file names.

**Comment by zhongjiajie** [comment]
Yeah, I think so, we have already released three versions of dolphinscheduler above 3.0.0, many users already use `install_env.sh` as config file, so maybe change the document is the better way

**Comment by zhongjiajie** [comment]
@xinxingi Hi, are you still there? do you have time to change our document instead of code?

**Comment by zhongjiajie** [comment]
close due to #13294

**Pull request closed without merging**
