### PR TITLE
[Fix-16464] [pom] fix parent pom plugin config error

### LINKED ISSUE #16464: [Bug] [pom] parent pom plugin config error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

parent pom plugin config error

### What you expected to happen

fix parent pom plugin config error

### How to reproduce

parent pom plugin config error

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luoyize**
fix jacoco-maven-plugin instrument excludes tag config loc error  Closes #16464

### CODE REVIEW

**Comment by chenss-1** [comment]
Closes #16464

**Review by SbloodyS — COMMENTED** [review]
Can you describe what issue you have? @chenss-1

**Comment by luoyize** [comment]
> Can you describe what issue you have? @chenss-1

in idea parent pom error ，i read this plugin official doc ，find this excludes tag should place  instrument‘ configuration

**Comment by SbloodyS** [comment]
> in idea parent pom error ，i read this plugin official doc ，find this excludes tag should place instrument‘ configuration

Can you send the link to the official document you found?

**Comment by chenss-1** [comment]
I had build success in local ，this github action error is network error。

**Comment by luoyize** [comment]
> > in idea parent pom error ，i read this plugin official doc ，find this excludes tag should place instrument‘ configuration
> 
> Can you send the link to the official document you found?

https://www.jacoco.org/jacoco/trunk/doc/instrument-mojo.html
https://www.jacoco.org/jacoco/trunk/doc/restore-instrumented-classes-mojo.html

restore only support skip tag , instrument support excludes tag

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Pull request merged**
