### PR TITLE
[feat][ci] Add pre-commit for easy spotless config

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Use pre-commit to handle spotless check
* Migrate exists python pre-commit-config into dir root one
* Change related document

### CODE REVIEW

**Comment by EricGao888** [comment]
Looks cool!

**Review by EricGao888 — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
thanks

**Comment by EricGao888** [comment]
I think we will release spotless related stuff in 3.2.0, otherwise, it will be pretty painful for 3.0.x or 3.1.x users to resolve conflicts when they try to rebase their code.

**Pull request merged**
