### PR TITLE
[Improvement][Metrics] Update some metrics names in grafana-demo dashboards

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request
* Update some metrics names in `Grafana` demo dashboards which I missed in the previously PR: #10477
* Fix some minor typos in docs.

## Brief change log
* Already described above.

## Verify this pull request
* Verified by manual test.

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by kezhenxu94 — APPROVED** [review]

**Comment by SbloodyS** [comment]
I had rerun the CI.

I found that E2E is not very stable today. But I don't know what has been changed. o(╥﹏╥)o

**Comment by EricGao888** [comment]
> I had rerun the CI.
> 
> I found that E2E is not very stable today. But I don't know what has been changed. o(╥﹏╥)o

@SbloodyS Should I rebase on the dev? Will it help?

**Comment by SbloodyS** [comment]
> > I had rerun the CI.
> > I found that E2E is not very stable today. But I don't know what has been changed. o(╥﹏╥)o
> 
> @SbloodyS Should I rebase on the dev? Will it help?

Maybe not...

**Pull request merged**
