### PR TITLE
[fix-13320][server] the same name param not be replaced in sql task

### LINKED ISSUE #13320: [Bug] [server] the out param not be replaced when rerun the sql task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the out param not be replaced when rerun a workflow 

### What you expected to happen

the out param should be replaced

### How to reproduce

the sql task
image
the shell task which get the `dt` from the sql task
image
run the workflow, shell task log
```
[INFO] 2023-01-03 06:46:42.916 +0000 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/jie/8102121698688/8102143663872_1/1/2
[INFO] 2023-01-03 06:46:43.735 +0000 -  -> 2023-01-03 14:46:42
[INFO] 2023-01-03 06:46:43.751 +0000 - FINALIZE_SESSION
```
then rerun the instance after a few minutes, shell task log
```
[INFO] 2023-01-03 06:53:41.300 +0000 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/jie/8102121698688/8102143663872_1/1/4
[INFO] 2023-01-03 06:53:42.230 +0000 -  -> 2023-01-03 14:46:42
[INFO] 2023-01-03 06:53:42.236 +0000 - FINALIZE_SESSION
```
still print `2023-01-03 14:46:42`, not be replaced

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ChPi**
## Purpose of the pull request
version 3.1.2
try to fix #13320 

## Brief change log

before add a property, remove the same property.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by Radeity — COMMENTED** [review]
It's better also fix that re-run task's initial `varPool` should not contain output properties from last running (in another PR). Anyway, your fix can work, the target problem is how to handle output parameter with same name in sql task, like in https://github.com/apache/dolphinscheduler/pull/12930.

**Comment by ChPi** [comment]
> It's better also fix that re-run task's initial `varPool` should not contain output properties from last running (in another PR). Anyway, your fix can work, the target problem is how to handle output parameter with same name in sql task, like in #12930.

only fix that re-run task's initial varPool，there maybe be other cases which encounter this bug such as task failover or pass parameter ，i am not sure. 
so its better to handle output `SqlParameters` like `AbstractParameters`

**Comment by Radeity** [comment]
> only fix that re-run task's initial varPool，there maybe be other cases which encounter this bug such as task failover or pass parameter ，i am not sure. so its better to handle output `SqlParameters` like `AbstractParameters`

There's nothing wrong with your fix in this PR. It can solve the problem, although, as mentioned above, the target problem is 

> how to handle output parameter with same name in sql task

And because of this fix, rerun sql task will not have bugs any more. Maybe you can change the title to make it more clear.

**Comment by ChPi** [comment]
> > only fix that re-run task's initial varPool，there maybe be other cases which encounter this bug such as task failover or pass parameter ，i am not sure. so its better to handle output `SqlParameters` like `AbstractParameters`
> 
> There's nothing wrong with your fix in this PR. It can solve the problem, although, as mentioned above, the target problem is
> 
> > how to handle output parameter with same name in sql task
> 
> And because of this fix, rerun sql task will not have bugs any more. Maybe you can change the title to make it more clear.

Thank you for reminding me! i changed the title.

**Pull request closed without merging**
