### PR TITLE
[python] Add example about how to bulk create workflow

### PR DESCRIPTION
**Pull request by zhongjiajie**
## Purpose of the pull request

Add example to show how to bulk create workflow

## Verify this pull request

This pull request is code cleanup without any test coverage. I just an example

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL, @lenboo @CalvinKirs . I add example about how to create workflow in batch mode

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
+1

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
