### PR TITLE
Add CI test for python API

### PR DESCRIPTION
**Pull request by zhongjiajie**
Using pytest as unit test for DolphinScheduler Python API, and integrated to CI

### CODE REVIEW

**Comment by zhongjiajie** [comment]
It's ready to go now, PTAL @lenboo @CalvinKirs

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by lenboo — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks 🎉

**Pull request merged**
