### PR TITLE
[Fix-14284][DAO] update the check of Integer in equals()

### LINKED ISSUE #14284: [Bug] [DAO] update the check of Integer in equals()
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

We cannot use `!=` to compare two Integers in the `equals()` of entity

### What you expected to happen

use `Objects.equals()`

### How to reproduce

2 entities with id > 127

### Anything else

* related: #14123

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

* close: #14284 

## Brief change log

replace `!=` with `!Objects.equals()`

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by Radeity — COMMENTED** [review]
Also can fix `Project.java` and `Tenant.java` :D

**Comment by rickchengx** [comment]
> Also can fix `Project.java` and `Tenant.java` :D

* Thanks for your comment, I've fixed `Tenant` and `Project` would be fixed in #14167

**Review by Radeity — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by rickchengx** [comment]
will merge tomorrow if no more comments

**Pull request merged**
