### PR TITLE
[Feature][UI-Next]: Build a front-end refactoring project.

### LINKED ISSUE #7380: [Feature][UI Next][Create Project] Build a front-end refactoring project.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Build the project, install and configure the necessary dependencies. Specific dependencies can refer to [#7332](https://github.com/apache/dolphinscheduler/issues/7332).

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by songjianet**
## Purpose of the pull request
close [#7380](https://github.com/apache/dolphinscheduler/issues/7380)

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by wangyizhi1 — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks

**Comment by songjianet** [comment]
> Thanks

666

**Comment by labbomb** [comment]
Thanks

**Pull request merged**
