### PR TITLE
[python] Refactor structure to avoid cycle import

### PR DESCRIPTION
**Pull request by zhongjiajie**
Currently, our core and side module dependent on each others. and will cause
cycle import in our codebase, especially in issue #10905, we try to refactor
to solve this problem.

This patch do the following change:

* Rename module `side` to `models`
* Move `core/base` and `core/sidebase` to dir `modules`
* Move `configuration` and `default_config.yaml` to the root of pydolphinscheduler

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @jieguangzhou @devosend @lyleshaw

**Comment by zhongjiajie** [comment]
I think it can go now

**Review by ly1ex — APPROVED** [review]
LGTM

**Review by jieguangzhou — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]

**Pull request merged**
