### PR TITLE
[Bug][Worker] generate kill command with unknown user: default

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request

- When we generate sudo command with default tenant, we will get error: `sudo: unknown user: default`

## Brief change log
- Replace default tenant with bootstrap user.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by Radeity** [comment]
Or we can directly set `TaskExecutionContext.tenantCode` to bootstrap user. cc @ruanwenjun

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
>  Or we can directly set `TaskExecutionContext.tenantCode` to bootstrap user. cc @ruanwenjun 

I think we should not do that, the code you change currently LGTM

**Comment by fuchanghai** [comment]
+1

**Pull request merged**
