### PR TITLE
Remove unused params in SwitchTaskTest

### PR DESCRIPTION
**Pull request by zuston**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
The CI inspection results show that there are still some areas that can be modified. You can resubmit the PR to modify it

**Comment by zuston** [comment]
Thanks @CalvinKirs. If have time i will contribute to fix. 

It’s my first time to contribute dolphinscheduler. Happy to join this community!

**Comment by zhongjiajie** [comment]
Well done, you did a good job @zuston, looking forward your further contributions

**Pull request merged**
