### PR TITLE
[Improvement] Abnormal characters check

### PR DESCRIPTION
**Pull request by pinkfloyds**
## Purpose of the pull request
resource center file path illegal character check filter ,added checkFilePath() in checkFullName()

## Brief change log

 **dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java**
```java
/**
     * regex FilePath check,only use a to z ,A to Z, 0 to 9, and _./- 
     *
     * @param str     input string
     * @return true if regex pattern is right, otherwise return false
     */
    public static boolean checkFilePath(String str) {
        return regexChecks(str, Constants.REGEX_FILE_PATH);
    }
```

**dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java**

```java
// abnormal characters check
        if (!checkFilePath(fullName)){
            log.error("fullName contains illegal characters");
            throw new ServiceException(Status.ILLEGAL_RESOURCE_PATH);
        }
```

## Verify this pull request

Manually verified the change by testing locally.
Added test case testCheckFilePath in CheckUtilsTest.

### CODE REVIEW

**Review by pinkfloyds — COMMENTED** [review]
remove error log

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Review by SbloodyS — COMMENTED** [review]
Please link this pr to your issue and fix CI. @pinkfloyds

**Review by rickchengx — COMMENTED** [review]
Overall LGTM, please Run 'mvn spotless:apply' to fix the code style

**Review by SbloodyS — DISMISSED** [review]
+1

**Review by SbloodyS — APPROVED** [review]

**Pull request merged**
