### PR TITLE
[Improvement][Alert]Alert code clean

### PR DESCRIPTION
**Pull request by huagetai**
## Purpose of the pull request

Alert code cleanup.

## Brief change log
  - “ShowType.java” moved from org.apache.dolphinscheduler.alert.api to org.apache.dolphinscheduler.plugin.alert.email
  - Adjusting AlertServer only depends on AlertPluginManager、AlertRequestProcessor、AlertSender、AlertConfig，not Dao（dolphinscheduler-alert-server）
 
## Verify this pull request
This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by caishunfeng** [comment]
@huagetai please check the CI test.

**Comment by caishunfeng** [comment]
PTAL @Tianqi-Dotes

**Comment by caishunfeng** [comment]
Is this pr ready for review? It's draft now.

**Comment by caishunfeng** [comment]
Hi @huagetai This part of the code has been modified in the dev, please check it.

**Comment by retime123** [comment]
Can this code be merged?  If not, what other adjustments need to be made?

**Comment by kezhenxu94** [comment]
Long time no update. Closing. Please reopen if you want to continue.

**Pull request closed without merging**
