### PR TITLE
[imporve] Add index to table t_ds_relation_process_instance

### LINKED ISSUE #10449: [Bug] [dao] Scheduling a large number of tasks . Metadata database resource consumption is high
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用dolphinscheduler每天调度10万级工作流，上百万任务量时，使用mysql作为元数据库，mysql压力过大
如下图，开始mysql配置为2核4g，cpu占用非常多峰刺。
然后升级mysql为8核16g，很快cpu使用率就达到100%
image

### What you expected to happen

经过问题排查发现t_ds_task_instance，t_ds_process_instance，t_ds_relation_process_instance这三张表数据量过大，并且没有配置入口去删除数据。
而mysql cpu使用过高的的原因主要是大量相同语句查询t_ds_relation_process_instance表，查询语句如下：
select id, parent_process_instance_id, parent_task_instance_id, process_instance_id from t_ds_relation_process_instance where parent_process_instance_id = 667735 and parent_task_instance_id = 2454593;

这个表没有创建合适的索引，导致每次查询会扫描全表。
所以可以对此表增加索引，可以很大程度缓解mysql压力。
image

### How to reproduce

工作流、任务并行度为默认值，元数据库为mysql
每小时调度数百个工作流，每个工作流有数十个任务
执行一段时间会把mysql cpu占满

### Anything else

_No response_

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by bukeliyu**
Add index to table t_ds_relation_process_instance

This closes #10449

### CODE REVIEW

**Comment by SbloodyS** [comment]
> ⚠️ This PR do not change database DDL synchronize.

@zhongjiajie Could you please take a look at this?

**Comment by zhongjiajie** [comment]
> > ⚠️ This PR do not change database DDL synchronize.
> 
> @zhongjiajie Could you please take a look at this?

this is expected behavior, it will comment a new message if our SQL DDL does not change in the same PR to avoid contributors forget to change the files.  But as you can see some changes like index adding or deleting only will be appear in mysql or postgresql, so the message is only the hint instead of error

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks for your contribution @bukeliyu

**Comment by zhongjiajie** [comment]
> ⚠️ This PR do not change database DDL synchronize.

？

**Comment by zhongjiajie** [comment]
why are you still hint after merged?

**Pull request merged**
