### PR TITLE
[ci] mergable do not handle label

### PR DESCRIPTION
**Pull request by zhongjiajie**
mergable some time will become crazy and adding
or deleting labels in the PR. This affects the
user experience. I try to solve it in #7099 but
it is seems not affect and we should remove the
label and comment operation and only should the
result in check result.

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
👍

**Comment by zhongjiajie** [comment]
ref: #10633 #10364 #10637

**Comment by zhongjiajie** [comment]
PTAL @SbloodyS @ruanwenjun

**Comment by zhongjiajie** [comment]
In Chinese, there is a short word "I can run if I can't beat you"

**Comment by SbloodyS** [comment]
> In Chinese, there is a short word "I can run if I can't beat you"

hahahaha....

**Pull request merged**
