### PR TITLE
[Fix][UI] Add loading before file modification data is returned.

### PR DESCRIPTION
**Pull request by Amy0104**
## Purpose of the pull request

This pull request adds loading before file modification data is returned.

## Related Issue

#10033

### CODE REVIEW

**Review by labbomb — APPROVED** [review]
LGTM

**Review by devosend — APPROVED** [review]
LGTM

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Great and it make our E2E more stable 👍

**Pull request merged**
