### PR TITLE
[Fix][Issue-11579] Cannot check the application status.

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

Change status check scripts, fix issue: #11579 

## Brief change log
Modify the status-all.sh and dolphinscheduler-daemon.sh, just add each Main class name to grep command:

Why do not use jps command to check process? Because many product env do not approve to install JDK, just JRE.

Why i add a "java"? This is a double guarantee mechanism 

## Verify this pull request

Just modify the shell script

### CODE REVIEW

**Comment by ruanwenjun** [comment]
related issue #11176

**Review by ruanwenjun — APPROVED** [review]
Generally LGTM, the script is just a simple tool now, we need to develop a cli tool for this.

**Comment by DarkAssassinator** [comment]
> Generally LGTM, the script is just a simple tool now, we need to develop a cli tool for this.
I think that the current script location and naming are not very standard，tool scripts(eg. install.sh) and interactive entry scripts need to be distinguished. And start-all.sh, stop-all.sh and status-all.sh should renamed to start_cluster.sh, stop_cluster.sh and status_cluster.sh.

**Review by EricGao888 — APPROVED** [review]

**Comment by ruanwenjun** [comment]
> Generally LGTM, the script is just a simple tool now, we need to develop a cli tool for this.
> I think that the current script location and naming are not very standard，tool scripts(eg. install.sh) and interactive entry scripts need to be distinguished. And start-all.sh, stop-all.sh and status-all.sh should renamed to start_cluster.sh, stop_cluster.sh and status_cluster.sh.

Do you have a plan to optimize this? Before your work please send your idea in dev@apache.dolphinscheduler.org.

**Pull request merged**
