### PR TITLE
Split the upgrade code

### PR DESCRIPTION
**Pull request by ruanwenjun**
1. Split the upgrade code into different version
2. Log the dml/ddl sql in origin friendly format
image

3. Fix ddl of 3.0.0 and 3.1.0

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by ruanwenjun** [comment]
The `Code scanning results` seems not correct, all resource leak has been fixed.
image

**Comment by kezhenxu94** [comment]
> The `Code scanning results` seems not correct, all resource leak has been fixed.
> image

It looks correct to me, because it says these are **fixed alerts**

image

**Comment by kezhenxu94** [comment]
The reason why it fails is that, there is a new detected security issue here 

image

**Comment by ruanwenjun** [comment]
> The reason why it fails is that, there is a new detected security issue here
> 
> image

Thanks for your reminder, helps a lot.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
