### PR TITLE
[Improvement-7907][refactor] Optimization for query task instances list when build dag flow

### PR DESCRIPTION
**Pull request by jim-parsons**
## Purpose of the pull request

Optimization for query task instances list when build dag flow

## Brief change log
1. add `findTaskInstanceByIdList` in `processService`

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@tangchunbo Please resolve the conflict first.

**Comment by jim-parsons** [comment]
> @tangchunbo Please resolve the conflict first.

got it. i forgot pull the new code from dev

**Review by ruanwenjun — DISMISSED** [review]
LGTM.

But I prefer to combine selectById with selectByIds, then we can just keep one method. So you can remove selectById, if you want.

**Comment by jim-parsons** [comment]
> 

thx, i'll combine this two methods.

**Comment by jim-parsons** [comment]
> LGTM.
> 
> But I prefer to combine selectById with selectByIds, then we can just keep one method. So you can remove selectById, if you want.

do you mean this two methods ?

i checked the useage by the first method `processService#findTaskInstanceById` and it has been uesed many situations. Besides if the first method call the second method to fullfill it's function, i think i will be complicated.

what do you think, big old (大佬 LOL)

@ruanwenjun 

image

**Comment by ruanwenjun** [comment]
@tangchunbo You can just modify the method `getRecoveryTaskInstance` in `WorkflowExecuteThread`, this method only used to query one instance, you can change it to `getRecoveryTaskInstances`, this might be easy work.

**Review by ruanwenjun — APPROVED** [review]

**Pull request merged**
