### PR TITLE
fix-10131: closed

### PR DESCRIPTION
**Pull request by redamancydec**
Missing parameters added.

Is the merge request I submitted correct?

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @iamliangdi ,Could you descirbe why did you want to do that?

**Comment by redamancydec** [comment]
> 
Please check the issues description about #10131 in version 3.0.0-alpha
Missing parameter in mapper layer

**Comment by SbloodyS** [comment]
> Please check the issues description about #10131 in version 3.0.0-alpha Missing parameter in mapper layer

To target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, jus desc). It would not only connect issue to PR but also close issue automatically when PR is be closed.

BTW, your target branch should be ```dev```. Please rebase your code to ```dev``` branch and change the target branch to ```dev```

**Comment by redamancydec** [comment]
> To target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, jus desc). It would not only connect issue to PR but also close issue automatically when PR is be closed.
> 
> BTW, your target branch should be `dev`. Please rebase your code to `dev` branch and change the target branch to `dev`

Sorry, I was wrong

**Pull request closed without merging**
