### PR TITLE
[cherry-pick-2.0.6][Bug] Fix config permisson

### PR DESCRIPTION
**Pull request by EricJoy2048**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by caishunfeng** [comment]
same pr #8938

**Comment by EricJoy2048** [comment]
@caishunfeng 
 https://github.com/apache/dolphinscheduler/pull/8938 is merge to branch:dev
 This pr is need merge to branch:2.0.6-prepare.

**Comment by caishunfeng** [comment]
> @caishunfeng #8938 is merge to branch:dev This pr is need merge to branch:2.0.6-prepare.

Sorry, I get it.

**Comment by caishunfeng** [comment]
@gaojun2048 next time please associate the original pr and let others know it is a cherry-pick pr.

**Comment by EricJoy2048** [comment]
> @gaojun2048 next time please associate the original pr and let others know it is a cherry-pick pr.

Ok, I am sorry.

**Pull request merged**
