### PR TITLE
[Fix-11249] No-admin user query alert group fix.

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

1. Non-admin users can also query the alarm group info.
2. Checked other data resource modules.

Currently there are several issues:

1. Non-admin users have no right to access other pages in the Security Center except AccessToken.
2. Some data resource modules cannot be used by non-admin users. For example, WorkerGroup has only one default
3. It is recommended to establish a unified resource authorization mechanism in DS, increase authorization for unauthorized resources, and unified management after the transformation of authorization before projects and data sources.

## Brief change log

related #11249 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Hi @ruanwenjun @WangJPLeo next time please add a milestone to PR when it fix the releasing version and we are in the release process. or you can mention the release manager in this PR

**Comment by zhongjiajie** [comment]
I almost forgot cherry pick this PR

**Comment by zhongjiajie** [comment]
> Hi @ruanwenjun @WangJPLeo next time please add a milestone to PR when it fix the releasing version and we are in the release process. or you can mention the release manager in this PR

My bad, it seem 3.0.0 work correctly

**Pull request merged**
