### PR TITLE
Use docker.scarf.sh to track docker user info

### PR DESCRIPTION
**Pull request by zhongjiajie**
Add scarf gateway to track our docker user come from, PTAL @kezhenxu94 @CalvinKirs

### CODE REVIEW

**Comment by kezhenxu94** [comment]
LGTM

**Comment by zhongjiajie** [comment]
FYI, I am pretty sure I replace all `docker-compose.yml` and `docker-stack.yml` but I am not very familiar with k8s, and not pretty sure if we only need to change `value.yml`. cc : @kezhenxu94

**Comment by kezhenxu94** [comment]
> FYI, I am pretty sure I replace all `docker-compose.yml` and `docker-stack.yml` but I am not very familiar with k8s, and not pretty sure if we only need to change `value.yml`. cc : @kezhenxu94 

I can recheck those Kubernetes related places later. Feel free to merge now.

**Comment by zhongjiajie** [comment]
CI failed with

```log
Pulling dolphinscheduler (dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:ci)...
manifest for dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:ci not found: manifest unknown: manifest unknown
```
I check in my local env, is could not run with both
* `docker pull dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler:ci`
* and `docker pull apache/dolphinscheduler:ci`

**Comment by kezhenxu94** [comment]
@zhongjiajie `apache/dolphinscheduler:ci` is built on the fly in CI machine and is used locally so this cannot be changed to `scarf.sh`

**Comment by zhongjiajie** [comment]
I got your point and thank for the feedback

**Comment by kezhenxu94** [comment]
@CalvinKirs should be good now 👍

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
Do we want to release it to 2.0？ @lenboo @zhongjiajie @kezhenxu94

**Comment by kezhenxu94** [comment]
> Do we want to release it to 2.0？ @lenboo @zhongjiajie @kezhenxu94

This does no harm in terms of functionalities, it can help the community to make more sense how the project is used in the world, I think we can include this in 2.0

**Comment by zhongjiajie** [comment]
I think it should including too.

**Pull request merged**
