### PR TITLE
[fix][#6204] provide the parameter task.plugin.dir with the default value

### PR DESCRIPTION
**Pull request by jon-qj**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Hi,thx for your contribution,please don't modify irrelevant files.

**Comment by CalvinKirs** [comment]
> Hi,thx for your contribution,please don't modify irrelevant files.

hi, how is it getting?

**Comment by jon-qj** [comment]
it’s ok and you can merge it.
 
 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 9月23日 10:42，Kirs ***@***.***> 写道： 
   
   
   Hi,thx for your contribution,please don't modify irrelevant files. 
   
  hi, how is it getting? 
  —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CalvinKirs** [comment]
> it’s ok and you can merge it.
> […](#)
> -- 发自新浪邮箱客户端 在 9月23日 10:42，Kirs ***@***.***> 写道： Hi,thx for your contribution,please don't modify irrelevant files. hi, how is it getting? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

You don’t seem to understand what I mean~

**Comment by CalvinKirs** [comment]
> Hi,thx for your contribution,please don't modify irrelevant files.

cc @jon-qj

**Comment by jon-qj** [comment]
By the way, I fixed some other bugs in it . I
 t keeps some records,s
 ome irrelevant files are out-of-date and I don’t know how to delete these files.

 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 9月23日 12:10，Kirs ***@***.***> 写道： 
   
   
   Hi,thx for your contribution,please don't modify irrelevant files. 
   
  cc @jon-qj 
  —
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
