### PR TITLE
Enhancement Translation

### PR DESCRIPTION
**Pull request by RichardStark**
## Purpose of the pull request

This pull request enhanced translation work.

## Brief change log

- replaced all the single Loading... with i18n $t(Loading...)
- replaced Edit translation from '编辑' to '更新' （'编辑' feels like starting Edit, '更新' is more like done edit, equivalent to submit（提交）)

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by ruanwenjun** [comment]
There seems to be no need to change the Chinese meaning of `Edit`

**Comment by RichardStark** [comment]
really？ when I edited a form a lot, and I see a button called "编辑", I really think it will popup another form, other than finished my edit.

**Comment by RichardStark** [comment]
Like many other sys:
image

image


'编辑' means start editing.
'更新' or '保存' means finish editing.

**Comment by dailidong** [comment]
Sorry, I deleted zh_CN.js file by mistake

**Review by davidzollo — APPROVED** [review]
+1

**Comment by davidzollo** [comment]
Sorry, I found that I deleted zh_CN.js file by mistake, I will upload it again

**Comment by ruanwenjun** [comment]
Don't worry, the zh_CN.js has been uploaded by #6054

**Pull request merged**
