### PR TITLE
[Bug][Tools] Add datasource url for mysql profile in tools application.yaml

### LINKED ISSUE #10390: [Bug] [Tools] DB configurations not work for tools
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* If we set database to `mysql` in `dolphinscheduler_env.sh`, when running `upgrade-schema.sh` in `tools`, will get errors like `Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:postgresql://127.0.0.1:5432/dolphinscheduler`
* `datasource.url` is somehow deleted in PR: #10128 , causing the datasource url will not be overwritten if `mysql` profile activated. I'm confused why that line was deleted in that PR.
* https://github.com/apache/dolphinscheduler/blob/9782fe4e7cd0c9313c748bb45b5b1f2d1ddd3367/dolphinscheduler-tools/src/main/resources/application.yaml#L39-L46

image

### What you expected to happen

* Already described above.

### How to reproduce

* Already described above.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Add datasource url for mysql profile in tools application.yaml
* This PR closes: #10390 

## Brief change log
* Already described above.

## Verify this pull request

* Verified by manual test.

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
> If we set database to mysql in dolphinscheduler_env.sh, when running upgrade-schema.sh in tools, will get errors like Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:postgresql://127.0.0.1:5432/dolphinscheduler

Does it means we should also set `SPRING_DATASOURCE_URL` in `dolphinscheduler_env.sh`. you adding in this PR only a default value of database connection, if user database not in the same mechine of dolphinscheduler service it will throw error too.

**Comment by zhongjiajie** [comment]
@EricGao888  could you try it again after #10414 merged

**Comment by EricGao888** [comment]
> @EricGao888 could you try it again after #10414 merged

Sure, will check it as soon as #10414 merged

**Comment by EricGao888** [comment]
> @EricGao888 could you try it again after #10414 merged

@zhongjiajie @SbloodyS It works fine now. I'm quite curious about how you guys made it work? How did PR #10414 affect `upgrade-schema.sh`? Very interesting.

**Comment by liqingwang** [comment]
`export DATABASE=${DATABASE:-h2}` 

This field DATABASE is the key to letting the Spring choose the active profile.

And the active profile will choose the DB `driver-class-name` automatically.

`dolphinscheduler-standalone-server/src/main/bin/start.sh` miss this line. 

So you seted the MySQL URL and other information, but the DB `driver-class-name` is still PostgreSQL, So you can see the error is `Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:postgresql://127.0.0.1:5432/dolphinscheduler`

And the more detailed information about why we don't need to define URL in YAML file,  you can see https://github.com/apache/dolphinscheduler/issues/10103#issuecomment-1131238019

**Comment by EricGao888** [comment]
> `export DATABASE=${DATABASE:-h2}`
> 
> This field DATABASE is the key to letting the Spring choose the active profile.
> 
> And the active profile will choose the DB `driver-class-name` automatically.
> 
> `dolphinscheduler-standalone-server/src/main/bin/start.sh` miss this line.
> 
> So you seted the MySQL URL and other information, but the DB `driver-class-name` is still PostgreSQL, So you can see the error is `Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:postgresql://127.0.0.1:5432/dolphinscheduler`
> 
> And the more detailed information about why we don't need to define URL in YAML file, you can see [#10103 (comment)](https://github.com/apache/dolphinscheduler/issues/10103#issuecomment-1131238019)

Still a little bit confused. After I encountered that `...not accept...` error, I stopped standalone-server, then reran `bash upgrade-schema.sh` in `tools/bin` and still got that error. Was it caused by cache or anything else?

**Comment by qingwli** [comment]
My understanding has some problems. I'll try locally and talk later

**Comment by EricGao888** [comment]
> My understanding has some problems. I'll try locally and talk later

Sure, thx for the explanation : )

**Comment by kezhenxu94** [comment]
> > If we set database to mysql in dolphinscheduler_env.sh, when running upgrade-schema.sh in tools, will get errors like Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:postgresql://127.0.0.1:5432/dolphinscheduler
> 
> 
> 
> Does it means we should also set `SPRING_DATASOURCE_URL` in `dolphinscheduler_env.sh`. you adding in this PR only a default value of database connection, if user database not in the same mechine of dolphinscheduler service it will throw error too.

We don't need to set that. What we want in the yaml is indeed default value. So before and after this PR when users set up in their production environment they are expected to set `SPRING_DATASOURCE_URL`. This PR is just for convenience that some users/developers want to test locally and the MYSQL url happens to be localhost. 

P.S. the reason why I write `export SPRING_DATASOURCE_URL` without a value is that, users might just set the variable without exporting it, that might not work in Spring so we just export it with the value users set. 

```shell
SPRING_DATASOURCE_URL=xxxx # note no "export"
daemon.sh start standalone-server
```

**Review by kezhenxu94 — APPROVED** [review]

**Comment by EricGao888** [comment]
> > > If we set database to mysql in dolphinscheduler_env.sh, when running upgrade-schema.sh in tools, will get errors like Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:postgresql://127.0.0.1:5432/dolphinscheduler
> > 
> > 
> > Does it means we should also set `SPRING_DATASOURCE_URL` in `dolphinscheduler_env.sh`. you adding in this PR only a default value of database connection, if user database not in the same mechine of dolphinscheduler service it will throw error too.
> 
> We don't need to set that. What we want in the yaml is indeed default value. So before and after this PR when users set up in their production environment they are expected to set `SPRING_DATASOURCE_URL`. This PR is just for convenience that some users/developers want to test locally and the MYSQL url happens to be localhost.
> 
> P.S. the reason why I write `export SPRING_DATASOURCE_URL` without a value is that, users might just set the variable without exporting it, that might not work in Spring so we just export it with the value users set.
> 
> ```shell
> SPRING_DATASOURCE_URL=xxxx # note no "export"
> daemon.sh start standalone-server
> ```

This makes sense to me. `username` and `password` are easily kept in mind, but `jdbc:mysql://127.0.0.1:3306/dolphinscheduler?useUnicode=true&characterEncoding=UTF-8` is hardly possible. Adding this default value in application.yaml will save the trouble copying pasting every time.

**Comment by zhongjiajie** [comment]
And did we still need this if only work for someone who run database service in the same host with tools script running?

**Comment by kezhenxu94** [comment]
> And did we still need this if only work for someone who run database service in the same host with tools script running?

Hi, as I said in https://github.com/apache/dolphinscheduler/pull/10399#issuecomment-1153797154 we can have this default value for the sake of convenience, and can be referenced if users want to configure their own database address (copy this by replacing the IP/host).

**Pull request merged**
