### PR TITLE
[Improvement][Plugin] Hide plugin instance password

### PR DESCRIPTION
**Pull request by ruanwenjun**
Hide plugin instance password param.

More detail see #5370

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
if converted to MD5 here, when it needs to be decrypted when using it.

**Comment by CalvinKirs** [comment]
I didn't look into detail, but there are some points that need extra attention. Some queries need to be provided to the backend, and some are for the UI. In addition, additional attention is required to update. Ignoring these will cause some errors

**Comment by ruanwenjun** [comment]
> I didn't look into detail, but there are some points that need extra attention. Some queries need to be provided to the backend, and some are for the UI. In addition, additional attention is required to update. Ignoring these will cause some errors

Got you, There is a problem with this method. It is better to use a symmetric algorithm to encryption the password.

**Comment by ruanwenjun** [comment]
I think we can return an empty password to front-end, this implementation is as same as query `Datasource` and `User`. This will not modify the existing data in the database.

**Comment by CalvinKirs** [comment]
> I think we can return an empty password to front-end, this implementation is as same as query `Datasource` and `User`. This will not modify the existing data in the database.

It's okay

**Comment by ruanwenjun** [comment]
> > I think we can return an empty password to front-end, this implementation is as same as query `Datasource` and `User`. This will not modify the existing data in the database.
> 
> It's okay

Done

**Review by CalvinKirs — COMMENTED** [review]
If you do this, the PWD parameters will be lost when updating.

**Comment by ruanwenjun** [comment]
> If you do this, the PWD parameters will be lost when updating.

Yeal, you are right. This implementation is the same with datasource, when we update datasource the password is a required param, but password seems not a required param here :sob:

**Comment by echohlne** [comment]
Hi @ruanwenjun  @CalvinKirs , this pr seems to try to solve the plaintext password of alert-plugin  can be viewd in the log. I solved a similar problem in the PR #5638 
Could you please tell me about how to reproduce the scene mentioned above ?
maybe I can help to confirm whether the problem has been solved or not 😀

**Comment by ruanwenjun** [comment]
@kyoty Thanks, this pr is want to solve the password transmission problem. Right now, the password or other secret information of a plugin instance is stored in database by plaintext. When someone queries the plugin instance, he will get the password, this is not safe. And you can see the discussion above, I don't have a good way to solve.

**Comment by ruanwenjun** [comment]
Closed, due to the current solution is not good.

**Pull request closed without merging**
