### PR TITLE
[1.3.6-prepare][Improvement][Docker/K8s] Support more configs, more service access, skywalking configs, improve image for python, update faq and add support matrix

### LINKED ISSUE #402: master/worker configuration file comments need to be detailed(master/worker配置文件注释需要详细)
image

### LINKED ISSUE #403: [Feature]The memory of worker, master, and other services does not need to be the same.(worker、master和其他服务的内存不需要是一样的)
The memory of worker, master, and other services does not need to be the same.

---
worker、master和其他服务的内存不需要是一样的

### LINKED ISSUE #4837: Docker & K8s Improvement Plan
### 1.3.5-release

Docker Improvement Plan

- [x] Reduce image size
- [x] Remove frontend/nginx
- [x] Remove stdout log in properties
- [x] improve compose/swarm deployment
- [x] Fix random PSQLException
- [x] Sync docker conf templates to the latest conf properties
- [x] Update outdated readme

K8s Improvement Plan

- [x] Remove frontend/nginx
- [x] Remove redundant configs
- [x] Support resource storage when fs.defaultFS=file:///
- [x] Fix task log disappear after recreating or upgrading helm release
- [x] Improve long host display in K8s
- [x] Update outdated readme

### dev & 1.3.6-release

Docker Improvement Plan

- [x] Reduce image size
- [x] Remove frontend/nginx
- [x] Remove stdout log in properties
- [x] improve compose/swarm deployment
- [x] Fix random PSQLException
- [x] Sync docker conf templates to the latest conf properties
- [x] Update outdated readme
- [x] Rename `WORKER_GROUP` to `WORKER_GROUPS` (#4843)
- [x] Add FAQ support about MySQL and Oracle in readme (#4732 #4871)
- [x] Add default login username and password in readme (#4881)
- [x] Check compatibility in Windows (#4804)
- [x] Fix invalid volume specification in Windows (#4886)
- [x] Support supervisor management (#2687)
- [x] Optimize log stdout with supervisor (#4897)
- [x] Fix that can not build a docker image on Windows (#3124)
- [x] Support docker compose file 3.1+ version
- [x] Add tenant tip for quick start
- [x] Sync the latest configs in master.properties and worker.properties
- [x] Support all configs in common.properties
- [x] Improve the environment variables and reduce the duplication configs
- [x] Fix mysql check
- [x] Add config.env.sh for docker compose and swarm
- [x] Add `MASTER_SERVER_OPTS`, `WORKER_SERVER_OPTS`, `ALERT_SERVER_OPTS`, `API_SERVER_OPTS`, `LOGGER_SERVER_OPTS`
- [x] Support skywalking config in docker
- [x] Replace alpine with debian:slim (#5155)
- [x] Remove redundant postgresql-client and mysql-client
- [x] Add faq for python, spark, hadoop, flink and datax
- [x] Add docs for support matrix on docker (#5068)
- [x] Support task scalability on Docker such as Spark, Flink and DataX (#5100)

K8s Improvement Plan

- [x] Remove frontend/nginx
- [x] Remove redundant configs
- [x] Support resource storage when fs.defaultFS=file:///
- [x] Fix task log disappear after recreating or upgrading helm release
- [x] Improve long host display in K8s
- [x] Adapt to the latest alert-server with updated config and port 50052
- [x] Update outdated readme
- [x] Rename `WORKER_GROUP` to `WORKER_GROUPS` (#4843)
- [x] Add FAQ support about MySQL and Oracle in readme (#2584)
- [x] Add FAQ support to use namespace, access ui and delete pv in readme
- [x] Incorrect host problem in minikube (#4905)
- [x] Check compatibility in all Kubernetes 1.12+
- [x] Support local docker image
- [x] Optimize image pull secret
- [x] Optimize fullname
- [x] Optimize metadata name
- [x] Sync the latest configs in master.properties and worker.properties
- [x] Support all configs in common.properties
- [x] Improve the environment variables and reduce the duplication configs
- [x] Support skywalking config in k8s
- [x] Unify annotations, affinity, nodeSelector, tolerations, resources and probe in K8s
- [x] Support more service access like ClusterIP, NodePort and LoadBalancer
- [x] Improve https tip in k8s
- [x] Add `MASTER_SERVER_OPTS`, `WORKER_SERVER_OPTS`, `ALERT_SERVER_OPTS`, `API_SERVER_OPTS`, `LOGGER_SERVER_OPTS`
- [x] Add faq for python, spark, hadoop, flink and datax
- [x] Add docs for support matrix on k8s (#5068)
- [x] Support task scalability on K8s such as Spark, Flink and DataX (#5100)
- [x] Fix quartz cron task cannot take effect in K8s (#5351)
- [x] Reduce long host and improve long host display on K8s

### LINKED ISSUE #5068: [Improvement][Docker/K8s] Task support matrix and solution on docker/k8s
**Describe the question**

**Task support matrix and solution on docker/k8s**

In initial docker/kubernetes deployment, some tasks cannot be directly supported like flink in issue #5065.

So we should give a task support matrix and solution on docker/k8s, such as hadoop (hdfs/yarn), spark, flink, hive ant etc.

**What are the current deficiencies and the benefits of improvement**

- A clear task support matrix on docker/k8s
- A clear additional steps to support tasks that cannot be directly supported

**Which version of DolphinScheduler:**
 -[1.3.x]
 -[dev]

### LINKED ISSUE #5141: [Bug][Master] Typo in  MasterConfig
**Describe the bug**
Can't use `MasterConfig` to parse `masterDispatchTaskNumber` from `master.properties`, cause of typo.

**To Reproduce**
Steps to reproduce the behavior, for example:

Edit `master.dispatch.task.num` in `master.properties` and Start master by debug mode and see `masterConfig`.

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.3.6]
 -[dev]

### LINKED ISSUE #5155: A Linux distribution for docker-compose
As I know，the image of  apache/dolphinscheduler was base on the Alpine image。But when I install Python dependencies，It takes a lot of time，at least an hour。What's more，It will need more any other  dependencies，for example

`apk update && apk add --no-cache gcc g++ python3-dev libffi-dev librdkafka librdkafka-dev mariadb-connector-c-dev musl-dev libxml2-utils libxslt  libxslt-dev py3-numpy py3-pandas`

But in the end, I fail to install python dependencies，because of the pandas。

So can you build another version based on other Linux，such as slim。 [constrast](https://cloud.tencent.com/developer/news/600722)

Thank you very much ！

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

*[1.3.6-prepare][Improvement][Docker/K8s] Support more configs, more service access, skywalking configs, improve image for python, update faq and add support matrix*

This closes #4837, closes #5155, closes #5068, closes #5141, closes #402, closes #403

## Brief change log

  - *Sync all `master`, `worker` and `common` config for the properties, template, ambari, docker and k8s*
  - *Add `master.dispatch.task.num`, `master.host.selector`*
  - *Remove redundant `MASTER_LISTEN_PORT` and `WORKER_LISTEN_PORT`*
  - *Add `HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE`, `JAVA_SECURITY_KRB5_CONF_PATH`, `LOGIN_USER_KEYTAB_USERNAME`, `LOGIN_USER_KEYTAB_PATH`, `KERBEROS_EXPIRE_TIME`, `HDFS_ROOT_USER`, `YARN_RESOURCEMANAGER_HA_RM_IDS`, `YARN_APPLICATION_STATUS_ADDRESS` for common properties*
  - *Add `SKYWALKING_ENABLE `, `SW_AGENT_COLLECTOR_BACKEND_SERVICES`, `SW_GRPC_LOG_SERVER_HOST`, `SW_GRPC_LOG_SERVER_PORT` for skywalking*
  - *Add `MASTER_SERVER_OPTS`, `WORKER_SERVER_OPTS`, `ALERT_SERVER_OPTS`, `API_SERVER_OPTS`, `LOGGER_SERVER_OPTS`*
  - *Fix mysql check*
  - *Improve the environment variables and reduce the duplication config*
  - *Unify annotations, affinity, nodeSelector, tolerations, resources and probe in K8s*
  - *Support more service access like ClusterIP, NodePort and LoadBalancer*
  - *Improve https tip in k8s*
  - *Replace alpine with debian:slim*
  - *Remove redundant  postgresql-client and mysql-client*
  - *Add faq for python, spark, hadoop, flink and datax*
  - *Add docs for support matrix on docker/k8s*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by chengshiwen** [comment]
@dailidong @CalvinKirs @chenxingchun Done, please review

**Review by davidzollo — APPROVED** [review]
+1
great job

**Comment by davidzollo** [comment]
@xingchun-chen , please test this PR when you are free, thx

**Comment by chengshiwen** [comment]
This closes #402 and closes #403

**Pull request merged**
