### PR TITLE
Take over task instance in master failover

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by caishunfeng** [comment]
@ruanwenjun need to update the doc too.

**Comment by ruanwenjun** [comment]
> @ruanwenjun need to update the doc too.

I find in the doc the master will `takeover` the task in master failover.

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
rerun the fail CI case

**Pull request merged**
