### PR TITLE
[Improvement-4988][docs] Uppercase the first letter the state of Process Instance

### LINKED ISSUE #4988: [Improvement][docs] For unified style, uppercase the first letter
**Describe the question**
For unified style, uppercase the first letter of the state of Process Instance.
image

**What are the current deficiencies and the benefits of improvement**
- Unified style, improvement user experience
- Doesn't make people feel weird

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**
Use uppercase the first letter or all lowercase the letter

### PR DESCRIPTION
**Pull request by chenshuai1995**
## What is the purpose of the pull request

*Uppercase the first letter the state of Process Instance*

this closes #4988

## Brief change log

  - *Uppercase the first letter the state of Process Instance*

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@break60 PTAL,Thx

**Comment by break60** [comment]
image
Are these fields changed on the page?

**Comment by chenshuai1995** [comment]
> image
> Are these fields changed on the page?

I just modify the state of Process Instance. The others i cannot confirm need to modify.

**Comment by break60** [comment]
> > image
> > Are these fields changed on the page?
> 
> I just modify the state of Process Instance. The others i cannot confirm need to modify.

image
You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.

**Comment by break60** [comment]
> > > image
> > > Are these fields changed on the page?
> > 
> > 
> > I just modify the state of Process Instance. The others i cannot confirm need to modify.
> 
> image
> You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.

**Comment by chenshuai1995** [comment]
> > > image
> > > Are these fields changed on the page?
> > 
> > 
> > I just modify the state of Process Instance. The others i cannot confirm need to modify.
> 
> image
> You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.

I get it. I will fix this soon!

**Comment by chenshuai1995** [comment]
> Are these fields changed on the page?
> 
> I just modify the state of Process Instance. The others i cannot confirm need to modify.
> 
> 
> You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.

I have fix this. Please take a look. Thanks!

**Comment by break60** [comment]
> > > > image
> > > > Are these fields changed on the page?
> > > 
> > > 
> > > I just modify the state of Process Instance. The others i cannot confirm need to modify.
> > 
> > 
> > image
> > You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.
> 
> I get it. I will fix this soon!

1.zh_cn.js文件需要改
2.en_US.js文件需要改
3.所有全局页面有用到的全部要改

**Comment by chenshuai1995** [comment]
> > > > > image
> > > > > Are these fields changed on the page?
> > > > 
> > > > 
> > > > I just modify the state of Process Instance. The others i cannot confirm need to modify.
> > > 
> > > 
> > > image
> > > You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.
> > 
> > 
> > I get it. I will fix this soon!
> 
> 1.zh_cn.js文件需要改
> 2.en_US.js文件需要改
> 3.所有全局页面有用到的全部要改

我修改了en_US.js文件中的value值，key不用改吧，这样，你的其他js里，都是通过key调用的，就都不用改动了。这个只是改国际化展示的时候首字母大写。

**Comment by break60** [comment]
> > > > > > image
> > > > > > Are these fields changed on the page?
> > > > > 
> > > > > 
> > > > > I just modify the state of Process Instance. The others i cannot confirm need to modify.
> > > > 
> > > > 
> > > > image
> > > > You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.
> > > 
> > > 
> > > I get it. I will fix this soon!
> > 
> > 
> > 1.zh_cn.js文件需要改
> > 2.en_US.js文件需要改
> > 3.所有全局页面有用到的全部要改
> 
> 我修改了en_US.js文件中的value值，key不用改吧，这样，你的其他js里，都是通过key调用的，就都不用改动了。这个只是改国际化展示的时候首字母大写。

那你这个pr相当于只改了一半，并没有改完整

**Comment by chenshuai1995** [comment]
> > > > > > > image
> > > > > > > Are these fields changed on the page?
> > > > > > 
> > > > > > 
> > > > > > I just modify the state of Process Instance. The others i cannot confirm need to modify.
> > > > > 
> > > > > 
> > > > > image
> > > > > You have only changed the Chinese version, the English version has not been changed, and there are other modules on the page. It is recommended to search and change it globally.
> > > > 
> > > > 
> > > > I get it. I will fix this soon!
> > > 
> > > 
> > > 1.zh_cn.js文件需要改
> > > 2.en_US.js文件需要改
> > > 3.所有全局页面有用到的全部要改
> > 
> > 
> > 我修改了en_US.js文件中的value值，key不用改吧，这样，你的其他js里，都是通过key调用的，就都不用改动了。这个只是改国际化展示的时候首字母大写。
> 
> 那你这个pr相当于只改了一半，并没有改完整

嗯，也可以这么理解。我当时提issue的本意是，在英文的时候，显示的流程状态，部分开头是大写，部分开头是小写。是指的，显示的不统一。没想去改里面的js代码

**Comment by CalvinKirs** [comment]
For better communication, it is recommended not to use Chinese. Thx

**Comment by CalvinKirs** [comment]
hi, has this PR been completed?

**Comment by break60** [comment]
Please complete the pr, someone will give you a review, thank you

**Review by break60 — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
