### PR TITLE
[Improvement][E2E + API Tests] Refactor UI test and API test modules

### PR DESCRIPTION
**Pull request by SnowMoon-Dev**
## Purpose of the pull request

This is a relatively complete sample test module

## Brief change log

ref [10778](https://github.com/apache/dolphinscheduler/issues/10778)
## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@SnowMoon-Dev do you want to add a base test module to keep the same part of api and e2e tests? If so we already discuss in https://github.com/apache/dolphinscheduler/pull/10442#issuecomment-1155921777 and think there are not the same

**Comment by SnowMoon-Dev** [comment]
> @SnowMoon-Dev do you want to add a base test module to keep the same part of api and e2e tests? If so we already discuss in [#10442 (comment)](https://github.com/apache/dolphinscheduler/pull/10442#issuecomment-1155921777) and think there are not the same


No, I integrated the api + e2e modules and wrote a test framework for UI testing, which improved the maintainability of UI testing and lowered the threshold for writing UI tests. I also did some secondary encapsulation for API testing.

**Comment by zhongjiajie** [comment]
> > @SnowMoon-Dev do you want to add a base test module to keep the same part of api and e2e tests? If so we already discuss in [#10442 (comment)](https://github.com/apache/dolphinscheduler/pull/10442#issuecomment-1155921777) and think there are not the same
> 
> No, I integrated the api + e2e modules and wrote a test framework for UI testing, which improved the maintainability of UI testing and lowered the threshold for writing UI tests. I also did some secondary encapsulation for API testing.

According to your describution, I think it is part of my comment above, the different is you do more thing in your PR, am I right?

**Comment by SnowMoon-Dev** [comment]
> 



> > > @SnowMoon-Dev do you want to add a base test module to keep the same part of api and e2e tests? If so we already discuss in [#10442 (comment)](https://github.com/apache/dolphinscheduler/pull/10442#issuecomment-1155921777) and think there are not the same
> > 
> > 
> > No, I integrated the api + e2e modules and wrote a test framework for UI testing, which improved the maintainability of UI testing and lowered the threshold for writing UI tests. I also did some secondary encapsulation for API testing.
> 
> According to your describution, I think it is part of my comment above, the different is you do more thing in your PR, am I right?

Sorry, I didn't describe enough details. In this PR, I re-encapsulated the page objects used in UI testing, refactored the e2e-core module, and redesigned the API testing module, and added These two modules are integrated together, please see the readme.md I submitted PR for details

**Comment by SnowMoon-Dev** [comment]
@zhongjiajie 

[README.md](https://github.com/apache/dolphinscheduler/files/9042793/README.md)

**Pull request closed without merging**
