### PR TITLE
ci: Require up to date before merging

### LINKED ISSUE #14412: [Improvement][CI] CI of unmerged PRs should rerun if a new PR gets merged
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Suppose we have two PR A and B. A or B could pass CI but A and B together cause bugs and fail CI.

If the CI of A and B both had passed on 8 a.m. and A got merged on 9 a.m., in current settings, CI of B still looked good and could be merged. As a result, A and B together cause new bugs and PRs after them will fail the CI.

Therefore, we need to force the CI of unmerged PRs to rerun once a new PR gets merged.

Personally I have seen this kind of bugs happen in DS repo several times.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
closed #14412

We can do that by turn on update to date for each PR ref https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch but it will take our maintainer much time and ci workflow more crowded

### CODE REVIEW

**Comment by zhongjiajie** [comment]
please take a look if you guys have time

**Review by EricGao888 — APPROVED** [review]

**Comment by zhongjiajie** [comment]
I will wait for less three approval to merge this pr

**Review by SbloodyS — APPROVED** [review]
I'm big +1 on this. 👍🏻

**Review by kezhenxu94 — APPROVED** [review]

**Review by rickchengx — APPROVED** [review]

**Comment by kezhenxu94** [comment]
This had been set from day one when the .asf.yaml file is added, and then removed, now it’s added back again. I don’t care who made this decision, but please make sure this is a community consensus and it won’t be changed back and forth.

**Review by Radeity — APPROVED** [review]

**Comment by zhongjiajie** [comment]
> This had been set from day one when the .asf.yaml file is added, and then removed, now it’s added back again. I don’t care who made this decision, but please make sure this is a community consensus and it won’t be changed back and forth.

The last modification was also made by me. At that time, I felt that each pr update to date will task many times, also there were some non-technical reasons.

> it won’t be changed back and forth

Yes, this is why I ping some currently active committers. I hope that as many people as possible know that, to avoid any of us being inactive anymore and remove it in the further

**Comment by zhongjiajie** [comment]
merging, and thanks

**Comment by EricGao888** [comment]
Thanks @zhongjiajie .
I believe this is a step towards stability and robustness : )

**Comment by Radeity** [comment]
Hi all, to avoid frequently updating branch, how about setting `ready-to-merge` label first, and then update branch, finally, merge PR until all CI pass :D

**Comment by EricGao888** [comment]
> Hi all, to avoid frequently updating branch, how about setting `ready-to-merge` label first, and then update branch, finally, merge PR until all CI pass :D

+1, sounds good to me.

**Comment by SbloodyS** [comment]
> Hi all, to avoid frequently updating branch, how about setting `ready-to-merge` label first, and then update branch, finally, merge PR until all CI pass :D

+1

**Comment by zhongjiajie** [comment]
> Hi all, to avoid frequently updating branch, how about setting `ready-to-merge` label first, and then update branch, finally, merge PR until all CI pass :D

FYI, I have raise a new mail thread to discuss it https://lists.apache.org/thread/7qyltrpr163do7s5z0lrszjd42xt028d

**Pull request merged**
