### PR TITLE
[fixed-11437]: date parse pattern match error

### LINKED ISSUE #11437: [Bug] [Task] ParameterUtils#convertParameterPlaceholders replace JSON In SQL error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

My python script contains SQL:
`select JSON_EXTRACT(json_value, CONCAT('$[', id - 1, '].input1') from test`
The python script SQL generated when ds is replaced
:
`select JSON_EXTRACT(json_val, CONCAT(', id - 1, .input1') from test`

### What you expected to happen

SQL should keep original:
`select JSON_EXTRACT(json_value, CONCAT('$[', id - 1, '].input1') from test`

### How to reproduce

- add UT for org.apache.dolphinscheduler.plugin.task.api.parser.ParameterUtilsTest#convertParameterPlaceholders
`String sql = "select JSON_EXTRACT(json_val, CONCAT('$[', id - 1, '].input1') from test";`
  `String sqlScript = ParameterUtils.convertParameterPlaceholders(sql, params);`
  `Assert.assertEquals("select JSON_EXTRACT(json_val, CONCAT(', id - 1, input1') from test", sqlScript);`
- run UT

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pinkhello**
## Purpose of the pull request

closed #11437 

## Brief change log
- modify *dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtils.java#DATE_PARSE_PATTERN*

## Verify this pull request

This change added tests and can be verified as follows:

*dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtilsTest.java*
- *Added testBasicBuiltInParameterPlaceholders to verify the change.*
- *Added testExtendedBuiltInParameterPlaceholders to verify the change.*
- *Added testExtendedBuiltInParameterPlaceholdersToBenchmarkVariable to verify the change.*
- *Added testExtendedBuiltInParameterPlaceholders4 to verify the change.*

### CODE REVIEW

**Review by zhuangchong — DISMISSED** [review]
LGTM.

**Comment by caishunfeng** [comment]
> Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=11438)
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=11438&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=11438&metric=coverage&view=list) No Coverage information [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=11438&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=11438&metric=new_duplicated_lines_density&view=list)

Hi @pinkhello please check the sonar result about the security hotspot.

**Comment by ruanwenjun** [comment]
I have find a lots error with the regex, and this PR seems doesn't fix all the problem.

I just test with the below and get an exception.
```java
Map<String, String> params = new HashMap<>();
        String sql = "select JSON_EXTRACT(json_val, CONCAT('$[aaa', id - 1, '].input1')) from test";
        String sqlScript = ParameterUtils.convertParameterPlaceholders(sql, params);
        Assert.assertEquals("select JSON_EXTRACT(json_val, CONCAT('$[aaa', id - 1, '].input1')) from test",
                sqlScript);
```

Can we have a better way to fix all these problem?

**Comment by pinkhello** [comment]
> ```java
> Map<String, String> params = new HashMap<>();
>         String sql = "select JSON_EXTRACT(json_val, CONCAT('$[aaa', id - 1, '].input1')) from test";
>         String sqlScript = ParameterUtils.convertParameterPlaceholders(sql, params);
>         Assert.assertEquals("select JSON_EXTRACT(json_val, CONCAT('$[aaa', id - 1, '].input1')) from test",
>                 sqlScript);
> ```

DATETIME FORMAT:
`yyyyMMddHHmmss`
`yyyy-MM-dd HH:mm:ss`
`yyyy-MM-dd'T'HH:mm:ss`
`yyyy MM dd HH mm ss`
`yyyy/MM/dd HH mm ss`
......
`\$\[([^\$\]]+)]` don't check format

**Comment by EricGao888** [comment]
@pinkhello May I ask whether there is any update / follow-up for this PR? Thanks

**Pull request closed without merging**
