### PR TITLE
[Improvement][Helm] using helm-docs to generate docs automatically

### LINKED ISSUE #14720: [Improvement][Helm] using helm-docs to generate docs automatically
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We can use some tools like [helm-docs](github.com/norwoodj/helm-docs) to generate README automatically. Manual maintenance of [this document](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/installation/kubernetes.md#appendix-configuration) should be avoided as it can easily lead to omissions or inconsistencies.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gallardot**
## Purpose of the pull request

- close #14720

Generate the chart's README.md file using [helm-docs](https://github.com/norwoodj/helm-docs). When the `values.yaml` file is modified, the README.md file needs to be regenerated.

```bash
./mvnw validate -P helm-doc -pl :dolphinscheduler
```

CI validation has also been added.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by Gallardot** [comment]
I noticed that a deadline check CI has failed. However, I believe this error can be ignored because it's checking the newly added helm charts' `README.md` file.

**Comment by Gallardot** [comment]
I don't know why the OWASP Dependency Check has failed.

**Comment by zhongjiajie** [comment]
> I don't know why the OWASP Dependency Check has failed.

Cause we have security issue and we do not handle it, it is unrelated to you patch

**Comment by zhongjiajie** [comment]
> I noticed that a deadline check CI has failed. However, I believe this error can be ignored because it's checking the newly added helm charts' `README.md` file.

Yeah, you are right, but we have to pass the docs check to merge the patch into the dev branch. So can we try to add disable for current line

```md
[DolphinScheduler Helm Charts](https://github.com/apache/dolphinscheduler/blob/dev/deploy/kubernetes/dolphinscheduler/README.md) <!-- markdown-link-check-disable-line -->
```

**Comment by zhongjiajie** [comment]
others LGTM

**Comment by Gallardot** [comment]
> > I noticed that a deadline check CI has failed. However, I believe this error can be ignored because it's checking the newly added helm charts' `README.md` file.
> 
> Yeah, you are right, but we have to pass the docs check to merge the patch into the dev branch. So can we try to add disable for current line
> 
> ```
> [DolphinScheduler Helm Charts](https://github.com/apache/dolphinscheduler/blob/dev/deploy/kubernetes/dolphinscheduler/README.md) 
> ```

Done. @zhongjiajie

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Pull request merged**
