### PR TITLE
[python] Add autoflake to auto rm unused import

### LINKED ISSUE #8592: [Feature][python] Add CI auto remove unused package
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We need a package to auto remove unused package instead of remove by hand
this issue started when issue #8591 is done

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Add a new commit hook to pre-commit, to auto
  remove unused imports
* Remove all unused pass statements
* Add autoflake to tox and out CI

close: #8592

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend @jieguangzhou

**Review by devosend — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks for reviewing

**Pull request merged**
