### PR TITLE
[task-flink][docs] Corrected name

### PR DESCRIPTION
**Pull request by mans2singh**
## Brief change log

The upload main package section indicates <code>...Resource **Centre** for...</code>, changed to <code>...Resource **Center**...</code>`. 

## Verify this pull request

This pull request is docs cleanup without any test coverage.

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM. Thanks for your contribution.

**Comment by zhongjiajie** [comment]
Actually, `Centre` is English in UK, and `Center` is English in US

**Comment by SbloodyS** [comment]
> Actually, `Centre` is English in UK, and `Center` is English in US

What??? OMG....

**Comment by mans2singh** [comment]
Thanks @SbloodyS  and @zhongjiajie for your support and fun facts.

**Pull request merged**
