### PR TITLE
[Fix-8098] [UI] fix resource manage modal bug

### LINKED ISSUE #8098: [Bug] [UI] udf sub resource manage edit modal can't close
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I renamed the UDF sub resource, I clicked the Cancel Modal, but it didn't respond. as follows:
image

### What you expected to happen

Modal close.

### How to reproduce

Open `UDF manage` -> `resource manage`, click resources to enter the list of sub-resources. click sub-resource edit operate and then click cancel button.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by devosend**
close #8098

### CODE REVIEW

**Comment by devosend** [comment]
PTAL @songjianet @labbomb

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by devosend** [comment]
PTAL @zhongjiajie

**Review by zhongjiajie — APPROVED** [review]
Looking good, thanks @devosend

**Comment by zhongjiajie** [comment]
should we cherry-pick to 203? @janeHe13 @caishunfeng

**Comment by caishunfeng** [comment]
> a77b0ef

I will do it.

**Comment by caishunfeng** [comment]
> #8098

I had cherry-pick into 2.0.3

**Pull request merged**
