### PR TITLE
[FIX-8135] [Bug] [DataSource] jdbc connect parameters can not input '@' 

### PR DESCRIPTION
**Pull request by JYInMyHeart**
## Purpose of the pull request

This pr fix bug 8135

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@JYInMyHeart Do you mind to solve the conflicts

**Comment by zhongjiajie** [comment]
I found out we already fix this bug in #8293, I prefect to close it.

**Comment by zhongjiajie** [comment]
@caishunfeng do you mind to make a double check here?

**Comment by JYInMyHeart** [comment]
> @JYInMyHeart Do you mind to solve the conflicts

Oh. It's too late.

**Comment by zhongjiajie** [comment]
@JYInMyHeart  It does not matter, we still have many works to do, which you can see in #5689

**Pull request closed without merging**
