### PR TITLE
[Improvement][Datasource]refactor the function of parsing other parameters and transforming other parameters

### PR DESCRIPTION
**Pull request by jon-qj**
## Purpose of the pull request
parsing other parameters and transforming other parameters in datasource module aim to decreased redundant code

## Verify this pull request

This pull request is already covered by existing tests

### CODE REVIEW

**Comment by caishunfeng** [comment]
> ## Purpose of the pull request
> ## Brief change log
> ## Verify this pull request

@jon-qj please add some pr detail description

**Comment by jon-qj** [comment]
> > ## Purpose of the pull request
> > ## Brief change log
> > ## Verify this pull request
> 
> @jon-qj please add some pr detail description

Yep

**Comment by zhuangchong** [comment]
As for other parameters of the data source, I have different ideas. At present, the other parameters of each data source may be different. There may be problems in the assembly in the system. I have encountered problems caused by assembly errors several times. I suggest to assemble other parameters and put them on the page to be filled in by the user.

**Comment by kezhenxu94** [comment]
No update for half a year, feel free to reopen if desired

**Pull request closed without merging**
