### PR TITLE
[Fix-7717] [UI Next] Prettier config name error

### LINKED ISSUE #7717: [Bug] [UI Next] ESLint errors
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I get some problems and errors when I run `npm run lint` in dolphinscheduler-ui-next. as follows:
image

It seems to be because of the eslint rules is not effect. 
image

### What you expected to happen

`npm run lint` not errors.

### How to reproduce

`npm run lint` in dolphinscheduler-ui-next.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by devosend**
close #7717

### CODE REVIEW

**Comment by devosend** [comment]
PTAL @songjianet @labbomb

**Review by labbomb — DISMISSED** [review]
LGTM

**Comment by zhongjiajie** [comment]
It seems we have conflict here

**Review by zhongjiajie — APPROVED** [review]
LGTM, thank

**Pull request merged**
