### PR TITLE
Add new version 2.0.1 to issue bug template

### PR DESCRIPTION
**Pull request by zhongjiajie**
Add new version 2.0.1 for github issue template and remove versions not LTS

### CODE REVIEW

**Review by kezhenxu94 — DISMISSED** [review]
We can consider to remove some old versions that we don't recommend users to use, also, I don't think we have capacity to resolve problems reported from those versions

**Comment by zhongjiajie** [comment]
@kezhenxu94  You are right. BTW, does it have some way auto-update github issue version base on git tag or release version? I search and could not found it

**Comment by kezhenxu94** [comment]
> @kezhenxu94 You are right. BTW, does it have some way auto-update github issue version base on git tag or release version? I search and could not found it

We can do that via GitHub Action , will do some investigation

**Comment by zhongjiajie** [comment]
I thinks we could delete and do no accept issue in below version, WDYT @lenboo @CalvinKirs @caishunfeng @kezhenxu94 @dailidong 

```markdown
- 2.0.0-alpha
- 1.3.4
- 1.3.4
- 1.3.3
- 1.3.2
- 1.3.1
- 1.2.1
- 1.2.0
- 1.1.0(Not Apache Release)
```

In other word , we only accept bug report in version

```markdown
- dev
- 2.0.1
- 2.0.0
- 1.3.9
- 1.3.8
- 1.3.6
```

**Comment by zhongjiajie** [comment]
> I thinks we could delete and do no accept issue in below version, WDYT @lenboo @CalvinKirs @caishunfeng @kezhenxu94 @dailidong
> 
> ```gfm
> - 2.0.0-alpha
> - 1.3.4
> - 1.3.4
> - 1.3.3
> - 1.3.2
> - 1.3.1
> - 1.2.1
> - 1.2.0
> - 1.1.0(Not Apache Release)
> ```
> 
> In other word , we only accept bug report in version
> 
> ```gfm
> - dev
> - 2.0.1
> - 2.0.0
> - 1.3.9
> - 1.3.8
> - 1.3.6
> ```

If we agree and do that, we should upgrade our doc, and point out to user which version is our LTS project

**Comment by lenboo** [comment]
> I thinks we could delete and do no accept issue in below version, WDYT @lenboo @CalvinKirs @caishunfeng @kezhenxu94 @dailidong
> 
> ```gfm
> - 2.0.0-alpha
> - 1.3.4
> - 1.3.4
> - 1.3.3
> - 1.3.2
> - 1.3.1
> - 1.2.1
> - 1.2.0
> - 1.1.0(Not Apache Release)
> ```
> 
> In other word , we only accept bug report in version
> 
> ```gfm
> - dev
> - 2.0.1
> - 2.0.0
> - 1.3.9
> - 1.3.8
> - 1.3.6
> ```

+1

**Comment by a5833488** [comment]
manifest for apache/dolphinscheduler:2.0.1 not found:

**Comment by kezhenxu94** [comment]
> manifest for apache/dolphinscheduler:2.0.1 not found:

We need some time to push the Docker images, and next time please don't mix the issue, your questions I nothing to do with this pull request

**Comment by a5833488** [comment]
> 

sorry

**Comment by kezhenxu94** [comment]
@a5833488 Docker images for 2.0.1 are pushed

**Review by kezhenxu94 — APPROVED** [review]
nice

**Pull request merged**
