### PR TITLE
[fix#12243] Fixed the issue of permission to create task-related files during Python task execution

### LINKED ISSUE #12243: [Question] [Kubernetes] After deploying DolphinScheduler with kubernetes, some problems are encountered in the use process.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Problem 1: Problem 1: I ran a very simple Python task and reported a permission error. Even if I set the tenant as root, the problem still cannot be solved. The official website documentation is too simple, and I did not find a solution to the problem.

### What you expected to happen

1) Better support and stricter testing for DolphinScheduler on Kubernetes;
2) Now the Python task version is python 2, and I hope to directly support python 3.

### How to reproduce

The problem can be found by deploying DolphinScheduler with Kubernetes, setting up tenants, binding tenants to users, and running a simple Python task.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pandong2011**
## Purpose of the pull request

close #12243 
related issue #11544
related issue #11913
## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by pandong2011** [comment]
@kezhenxu94 @caishunfeng

**Comment by fhygh** [comment]
@pandong2011  hello, i cherry-pick this pr but found it does not work, can you help check again?

**Comment by pandong2011** [comment]
@fhygh Okay, sure

**Comment by EricGao888** [comment]
The commit history of this PR looks pretty wired, could u plz fix it? Thx 
image

**Pull request closed without merging**
