### PR TITLE
[fix] update queue and tenant with same code error

### PR DESCRIPTION
**Pull request by zhongjiajie**
in ae6aa53f I use the same logic test create or update
tenant and queue which failed create with same value,
this patch will fix it. and also I use constructor to reduce
the new object logic here

### CODE REVIEW

**Comment by zhongjiajie** [comment]
cc @SnowMoon-Dev

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
I chang to 3.1.0 release because the dependent PR #10792 with milestone `3.1.0-release`

**Comment by zhongjiajie** [comment]
> cc @SnowMoon-Dev

this patch is merged to dev now @SnowMoon-Dev

**Comment by SnowMoon-Dev** [comment]
> > cc @SnowMoon-Dev
> 
> this patch is merged to dev now @SnowMoon-Dev

ok

**Pull request merged**
