### PR TITLE
[improvement]Add Set cluster name

### PR DESCRIPTION
**Pull request by jackfanwan**
Backend Add Set cluster name

#12032

### CODE REVIEW

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
Hi @qianli2022 do you have time to review this pr?

**Comment by caishunfeng** [comment]
image
Hi @jackfanwan I found that the UI still show error, should change UI together.

**Comment by caishunfeng** [comment]
> image Hi @jackfanwan I found that the UI still show error, should change UI together.

OK, I found another pr #12074 of the UI part, thxs~  
But it's better to fix it in one pr next time.

**Comment by jackfanwan** [comment]
> > image Hi @jackfanwan I found that the UI still show error, should change UI together.
> 
> OK, I found another pr #12074 of the UI part, thxs~ But it's better to fix it in one pr next time.

ok

**Pull request merged**
