### PR TITLE
[Improvement-9609][Worker]The resource download method is selected according to the configurati…

### LINKED ISSUE #9609: [Feature][resource] More specific log to users who miss config resource center in worker-server
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After version 3.0.0-alpha, when using resource center with HDFS or S3, we have to configure in both `api-server/conf/common.properties` and `worker-server/conf/common.properties`. When users only config in `api-server` but not `worker-server`, they could upload and download resources, but could not use the resource file in task, like shell task or SQL task. 

The worst things is `worker-server` logs only show we have NPE in the resource operator. Maybe we should add a pre verify before worker run task, and raise the error about config is invalid in the resource center, show more specific information to the users.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
…on and the service startup verification is added.

## Purpose of the pull request

The resource download method is selected according to the configuration and the service startup verification is added.

## Brief change log

close #9609 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by songjianet** [comment]
I restarted ci, and I will see the effect later.

**Comment by caishunfeng** [comment]
I had rerun the CI

**Comment by WangJPLeo** [comment]
I should find the problem, I will pr again later.

**Comment by caishunfeng** [comment]
image
Please check the e2e test.

**Review by caishunfeng — APPROVED** [review]
LGTM

**Pull request merged**
