### PR TITLE
[Fix-16046][SqlTask] Fix Sql task use time type is incorrect

### PR DESCRIPTION
**Pull request by yinxiaolog**
## Purpose of the pull request
If SQL specifies a user-defined parameter of the TIME type, set it to the java.sql.Time type when setting the PreparedStatement parameter.

SQL使用自定义参数为TIME类型，设置PreparedStatement执行参数时，会设置为java.sql.Time，原来是String类型。

## Brief change log

change set PreparedStatement to org.apache.dolphinscheduler.plugin.task.api.utils.ParameterUtils .

修改ParameterUtils.setInParameter方法设置DataType类型为TIME，设置为java.sql.Time。

## Verify this pull request

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — COMMENTED** [review]
+1

**Comment by SbloodyS** [comment]
Please link this pr to your issue. @yinxiaolog

**Review by Radeity — APPROVED** [review]

**Review by rickchengx — APPROVED** [review]
LGTM

**Pull request merged**
