### PR TITLE
[Fix-10863] Command execution result data statistics remove userId condition.

### LINKED ISSUE #10863: [BUG-BE][Statistics Module] The number of failed commands is incorrectly counted
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The number of failed commands is incorrectly counted

### What you expected to happen

display correctly

### How to reproduce

The data in the database is inconsistent with the page data display.

### Anything else

No

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

Command execution result data statistics remove userId condition.

## Brief change log

close #10863 
## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by caishunfeng** [comment]
Hi @WangJPLeo I can't get the point of the `The number of failed commands is incorrectly counted`, please add some details for it, thanks.
BTW, I think the userId condition is necessary because the user can only see the data they have.

**Comment by lenboo** [comment]
> Hi @WangJPLeo I can't get the point of the `The number of failed commands is incorrectly counted`, please add some details for it, thanks. BTW, I think the userId condition is necessary because the user can only see the data they have.

Yes, I think the login user can only see the processes with permissions.

**Comment by WangJPLeo** [comment]
> Hi @WangJPLeo I can't get the point of the `The number of failed commands is incorrectly counted`, please add some details for it, thanks. BTW, I think the userId condition is necessary because the user can only see the data they have.

After the resource permissions are refactored, the user-related projects are uniformly obtained in the getProjectIds method, so it is not necessary to use the user ID to query after obtaining the user-related projects. The displayed error command statistics are inaccurate because the user ID association is added. @caishunfeng @lenboo

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
