### PR TITLE
[Improvement-13558][Resources Project] Improve details page return to the previous list page after returning to the list page #13558 

### LINKED ISSUE #13558: [Improvement][Resources Project] The details page does not return to the previous list page after returning to the list page
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description
version 3.x
**Current Problems**
图片
图片
图片
When you come to the task or workflow list interface(Figure 1), click the task edit button on the specified page to enter the task details page(Figure 2). When you return, you will jump to the first page instead of the page where the original task is located(Figure 3). Very unfriendly to the user's experience.

图片
图片
图片
When you come to the list interface of the resource file, click the edit button of the resource file on the specified page to enter the details page of the resource file. When you return or save, you will jump to the first page instead of the page where the original resource file is located. It is also very unfriendly to the user's experience.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhutong6688**
## Purpose of the pull request

Current Problem Is fix #13558 in any version of 3.1.x
The purpose of this modification is that when we are in the resource list, we click into the resource details page, and then return to the resource list, we can still return to the original resource list。

## Brief change log
base on dev branch
add enum.ts in common directory
add storage.ts、isEmpty.ts in utils directory
add main code in types.ts of common directory
add main improve code in dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
add main improve code in dolphinscheduler-ui/src/views/resource/components/resource/table/use-table.ts
add main improve code dolphinscheduler-ui/src/views/resource/components/resource/index.tsx

## Verify this pull request

This is the test verification of this improvement for problem #13558, as follows：
1、Query resource list unconditionally
图片
图片
图片
图片

2、Query resource list conditionally
图片
图片
图片
图片
图片

As can be seen from the above, whether in the case of conditional or unconditional query of resource files, when you enter the corresponding resource details page and click Save or Return, you can smoothly return to the previous resource list, greatly improving the development efficiency. Otherwise, you will return to the home page every time and lose the query conditions, which greatly reduces the development efficiency。

### CODE REVIEW

**Comment by zhutong6688** [comment]
Thanks for Peiwen Zhu's participating in for this solvement

**Comment by zhutong6688** [comment]
Our company has been using dolphinscheduler. After such a long time of use, we found that if we optimize the resource paging part like me, the development efficiency will increase by an order of magnitude, because it saves a lot of repeated searches and page jumps, especially when modifying the same type of resource files in large quantities.

**Comment by zhutong6688** [comment]
I have applied this optimization to the dolphin scheduling used by our company, which has greatly improved the development efficiency and user experience.

**Comment by zhutong6688** [comment]
Current Problem Is https://github.com/apache/dolphinscheduler/issues/13558 in any version of 3.1.x ，It is necessary to solve this bad experience。

**Comment by yanghongwei655** [comment]
improment is great for the user experience and greatly improves development efficiency

**Comment by devosend** [comment]
Good job, Thank you for your contribution, but you should use `pinia` to store data instead of using localStorage directly. @zhutong6688

**Comment by davidzollo** [comment]
please solve conflicts,
image

**Comment by zhutong6688** [comment]
I will change this conflict as soon as possible and replace localStorage with the pinia component. Thank you for acknowledging my contribution to this open source community code.

从 Windows 版邮件发送

发件人: David Zollo
发送时间: 2023年7月6日 11:07
收件人: apache/dolphinscheduler
抄送: 朱通通; Mention
主题: Re: [apache/dolphinscheduler] [Improvement-13558][Resources Project]Improve details page return to the previous list page after returning to thelist page #13558 (PR #13731)

please solve conflicts,

**Comment by zhutong6688** [comment]
I use pinia to store data instead of using localStorage directly in new PR（#14954），please please take a look at my new PR

**Review by songjianet — COMMENTED** [review]
Please resolve the conflict.

**Comment by zhutong6688** [comment]
This PR has been replaced by a new one(#14954), which has been merged into the main branch. Let me close this PR.

**Pull request closed without merging**
