### PR TITLE
[Feature-15146][dolphinscheduler-task-sqoop] add sqoop source/target type

### PR DESCRIPTION
**Pull request by xujiaqiang**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by songjianet — DISMISSED** [review]

**Comment by songjianet** [comment]
Please add the license header to the winning file

**Review by songjianet — DISMISSED** [review]

**Comment by xujiaqiang** [comment]
> ## Purpose of the pull request
> ## Brief change log
> ## Verify this pull request
> This pull request is code cleanup without any test coverage.
> 
> _(or)_
> 
> This pull request is already covered by existing tests, such as _(please describe tests)_.
> 
> (or)
> 
> This change added tests and can be verified as follows:
> 
> (or)
> 
> If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

>[Feature][dolphinscheduler-task-sqoop] add sqoop source/target type #15146 #15178

**Comment by xujiaqiang** [comment]
> ## Purpose of the pull request
> ## Brief change log
> ## Verify this pull request
> This pull request is code cleanup without any test coverage.
> 
> _(or)_
> 
> This pull request is already covered by existing tests, such as _(please describe tests)_.
> 
> (or)
> 
> This change added tests and can be verified as follows:
> 
> (or)
> 
> If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

> [Feature][dolphinscheduler-task-sqoop] add sqoop source/target type #15178

**Comment by davidzollo** [comment]
I'm not sure whether this hana jar license can use or not. the license of `com.sap.cloud.db.jdbc` url is https://tools.hana.ondemand.com/developer-license-3_1.txt . is there anybody can help to check?  

apache compatible license https://apache.org/legal/resolved.html#highlevel

**Comment by xujiaqiang** [comment]
> 我不确定这个hana jar许可证是否可以使用。url的许可证`com.sap.cloud.db.jdbc`是https://tools.hana.ondemand.com/developer-license-3_1.txt。有没有人可以帮忙检查一下？
> 
> apache 兼容许可证https://apache.org/legal/resolved.html#highlevel
> ngdbc-2.5.52.jar cannot be used

**Review by davidzollo — APPROVED** [review]
+1
LGTM

**Pull request merged**
