### PR TITLE
[Fix#5496][master]NPE occurs in complement operation

### PR DESCRIPTION
**Pull request by caoping6**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by brave-lee — COMMENTED** [review]
Before committing to dev, make sure that dev has this problem. BTW, for better communication, please use English

**Comment by CalvinKirs** [comment]
code style check fails, can you resolve it? you can refer to this doc https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html

**Comment by CalvinKirs** [comment]
@ruanwenjun PTAL.Thx

**Comment by ruanwenjun** [comment]
@caoping6 Hi, there are nothing changed?
image

**Pull request closed without merging**
