### PR TITLE
[Improvement-11880][Hivecli] Improve the UI of HiveCli

### LINKED ISSUE #11880: [Improvement][Hivecli] Improve the UI of HiveCli
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Improve the UI of HiveCli

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

close: #11880 

if the user selects the type "FROM_FILE", he doesn't need to write sql statements in the `HIVE SQL SCRIPT`

## Verify this pull request

manually tested

截屏2022-09-09 15 49 36

截屏2022-09-09 15 49 27

### CODE REVIEW

**Review by EricGao888 — COMMENTED** [review]
May I ask whether it is possible to make `Resources` mandatory if users choose `FROM_FILE`?

**Comment by EricGao888** [comment]
> May I ask whether it is possible to make `Resources` mandatory if users choose `FROM_FILE`?

BTW, we could also make `HIVE SQL SCRIPT` mandatory, I mean add a red star on UI for notice, if users choose `FROM_SCRIPT`.

**Comment by EricGao888** [comment]
Overall, this is a good feature. It improves the interactions and I like it : )

**Comment by rickchengx** [comment]
> > May I ask whether it is possible to make `Resources` mandatory if users choose `FROM_FILE`?
> 
> BTW, we could also make `HIVE SQL SCRIPT` mandatory, I mean add a red star on UI for notice, if users choose `FROM_SCRIPT`.

Hi, @EricGao888 , thanks for your suggestions.

I have made `HIVE SQL SCRIPT` mandatary if users choose `FROM_SCRIPT`.

截屏2022-09-13 11 25 31


image

**Comment by EricGao888** [comment]
> > > May I ask whether it is possible to make `Resources` mandatory if users choose `FROM_FILE`?
> > 
> > 
> > BTW, we could also make `HIVE SQL SCRIPT` mandatory, I mean add a red star on UI for notice, if users choose `FROM_SCRIPT`.
> 
> Hi, @EricGao888 , thanks for your suggestions.
> 
> I have made `HIVE SQL SCRIPT` mandatary if users choose `FROM_SCRIPT`.
> 
> 截屏2022-09-13 11 25 31
> 
> and made `Resources` mandatary if users choose `FROM_FILE` (also limit the number of resource file to 1).
> 
> 截屏2022-09-13 11 25 38

Great job!

**Review by EricGao888 — DISMISSED** [review]
LGTM if CI passes.

**Comment by rickchengx** [comment]
Hi, @songjianet , @Amy0104, could you please help me this front-end problem?

It seems that `resourcesRequired.value` will lose the reactivity.
截屏2022-09-23 10 53 03

which means the user's click on the front end does not affect the `required` attribute in `use-resources.ts`

https://github.com/apache/dolphinscheduler/blob/6eb1eb722af06b94027994b2ef8955e84fd97d7f/dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts#L25-L29

https://github.com/apache/dolphinscheduler/blob/6eb1eb722af06b94027994b2ef8955e84fd97d7f/dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts#L74

**Comment by Amy0104** [comment]
> Hi, @songjianet , @Amy0104, could you please help me this front-end problem?
> 
> It seems that `resourcesRequired.value` will lose the reactivity. 截屏2022-09-23 10 53 03
> 
> which means the user's click on the front end does not affect the `required` attribute in `use-resources.ts`
> 
> https://github.com/apache/dolphinscheduler/blob/6eb1eb722af06b94027994b2ef8955e84fd97d7f/dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts#L25-L29
> 
> https://github.com/apache/dolphinscheduler/blob/6eb1eb722af06b94027994b2ef8955e84fd97d7f/dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts#L74

I'll check it.

**Comment by Amy0104** [comment]
Maybe you can try to switch the `useResource` firstly, and then I try to support this by reactive required later. Is that ok? @rickchengx

**Comment by rickchengx** [comment]
> Maybe you can try to switch the `useResource` firstly, and then I try to support this by reactive required later. Is that ok? @rickchengx

@Amy0104 Thanks a lot for the help. I have switched to the `useResources()`.
image

**Comment by Amy0104** [comment]
After this pr merged, I will fix this by #12202 .

**Review by Amy0104 — APPROVED** [review]
LGTM

**Comment by Amy0104** [comment]
I have already set the `required` to be reactive.

**Comment by rickchengx** [comment]
> I have already set the `required` to be reactive.

Thanks a lot, @Amy0104 
* I have made resources of hivecli task to be reactive in #12336

**Pull request merged**
