### PR TITLE
[Fix-10547][data-quality] Fix Table or view not found

### LINKED ISSUE #10547: [Bug] [data-quality] Table or view not found
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I use the data quality module to check the hive table data(hive table:`test`.`t_view_log`), an error is reported when running the task. The error content is:
org.apache.spark.sql.AnalysisException: Table or view not found:`test`.`t_view_log`;line 1 pos 14;
exception

### What you expected to happen

Because I have installed spark2.4.0 and hive3.1.2, started the hive Metastore service, and set hive-site.xml is placed in the conf directory of spark。

### How to reproduce

installed spark2.4.0 and hive3.1.2, started the hive Metastore service, and set hive-site.xml is placed in the conf directory of spark。Then create a new data quality task to check the hive table data。

### Anything else

_No response_

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by feixiameiruhua**
Solve the problem that the data quality module does not support hive table data quality detection

close #10547

### CODE REVIEW

**Comment by feixiameiruhua** [comment]
Solve the problem that the data quality module does not support hive table data quality detection

**Comment by SbloodyS** [comment]
Please associate the issue. @feixiameiruhua

**Comment by feixiameiruhua** [comment]
Solve the problem that the data quality module does not support hive table data quality detection.#10547

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by SbloodyS** [comment]
@zixi0825 PTAL

**Comment by zixi0825** [comment]
LGTM

**Pull request merged**
