### PR TITLE
[Improvement][Task] Datax task add sap hana datasource

### PR DESCRIPTION
**Pull request by dik111**
## Purpose of the pull request
Datax performs ETL operations on the SAP Hana database through RDBMS
closes [#5086 ](https://github.com/apache/dolphinscheduler/pull/5243)

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, thanks for your contribution,code style check fail,you can refer this doc:https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html

**Comment by CalvinKirs** [comment]
https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc
His license seems to be unavailable for Apache

**Comment by dik111** [comment]
> https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc
> His license seems to be unavailable for Apache

**Comment by dik111** [comment]
> https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc
> His license seems to be unavailable for Apache

What should i do for ngdbc dependency unavailable for Apache?

**Comment by CalvinKirs** [comment]
> > https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc
> > His license seems to be unavailable for Apache
> 
> What should i do for ngdbc dependency unavailable for Apache?

Are there other options?

**Comment by dik111** [comment]
> > > https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc
> > > His license seems to be unavailable for Apache
> > 
> > 
> > What should i do for ngdbc dependency unavailable for Apache?
> 
> Are there other options?

i can not find other dependency except ngdbc....

**Comment by CalvinKirs** [comment]
License is indeed a troublesome issue. BTW, when you submit a PR, it is best to thoroughly discuss it first, so as to avoid this happening. I will close it. If you have a new solution, please discuss in the issue. Thanks again for your contribution.

**Pull request closed without merging**
