### PR TITLE
[fix] Simply correct wrong words

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

When review the code, found some wrong words, just correct it.

### CODE REVIEW

**Comment by davidzollo** [comment]
Is there any related issue for this PR?

**Review by davidzollo — DISMISSED** [review]
+1
LGTM

**Comment by DarkAssassinator** [comment]
> Is there any related issue for this PR?

no, because the modification is simple enough and only for comments, do we need add a new issue?

**Comment by ruanwenjun** [comment]
@DarkAssassinator CI failed, please rebase the upstream dev.

**Comment by DarkAssassinator** [comment]
> @DarkAssassinator CI failed, please rebase the upstream dev.

but after rebase the upstream dev, no any more need commit and push, do not find any gap

**Comment by EricGao888** [comment]
> > @DarkAssassinator CI failed, please rebase the upstream dev.
> 
> but after rebase the upstream dev, no any more need commit and push, do not find any gap

That's expected behavior if no conflicts to be resolved. Just do `git push --force`.

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
