### PR TITLE
[Fix][UI Next][V1.0.0-Alpha] Fix build standalone error.

### PR DESCRIPTION
**Pull request by songjianet**
## Purpose of the pull request
[#8508](https://github.com/apache/dolphinscheduler/issues/8580)

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by labbomb — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Comment by zhongjiajie** [comment]
@songjianet  Does this PR fix https://github.com/apache/dolphinscheduler/issues/8580? If so we should close issue #8580

**Comment by songjianet** [comment]
> @songjianet Does this PR fix #8580? If so we should close issue #8580

no need to close.

**Pull request merged**
