### PR TITLE
[Fix][Bug][Dev]Switch version in pom.xml to dev-SNAPSHOT (#9223)

### LINKED ISSUE #9223: [Bug] [dev] version in pom.xml of dev branch confusing
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* `version` in pom.xml of dev branch is confusing. After building the source code, we get apache-dolphinscheduler-2.0.4-SNAPSHOT-xxx.  
* image

### What you expected to happen

* We could change `version` in pom.xml of dev branch to `dev-SNAPSHOT`

### How to reproduce

* Build the src code and `cd dolphin-scheduler/dolphinscheduler/dolphinscheduler-dist/target`, you will see related output stuff all in version `2.0.4-SNAPSHOT`.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Versions in pom.xml files of dev branch is currently set to `2.0.4-SNAPSHOT`, which is confusing. This PR switches the version from `2.0.4-SNAPSHOT` to `dev-SNAPSHOT`.
* This PR closes: #9223 

## Brief change log

* As stated above in Purpose section.

## Verify this pull request

* Compile the code with cmd `mvn -U install package -Prelease -Dmaven.test.skip=true` and related output jars/packages should be of version `dev-SNAPSHOT`

### CODE REVIEW

**Comment by EricGao888** [comment]
Please do not merge this PR at this time. There's still something wrong with it.

**Comment by zhongjiajie** [comment]
> Please do not merge this PR at this time. There's still something wrong with it.

Is there still WIP for this PR?

**Comment by EricGao888** [comment]
> > Please do not merge this PR at this time. There's still something wrong with it.
> 
> Is there still WIP for this PR?

Still WIP, some wired issue with log4j.properties. https://github.com/apache/dolphinscheduler/issues/9223#issuecomment-1080399656

**Comment by zhongjiajie** [comment]
I will test locally in my laptop to try this PR,

**Comment by zhongjiajie** [comment]
@EricGao888 I find out your PR does not change anything. Did you delete your branch? Fix-9223

**Comment by EricGao888** [comment]
> @EricGao888 I find out your PR does not change anything. Did you delete your branch? Fix-9223

@zhongjiajie Sorry I mistakenly delete the branch last night. I will recover it later.

**Comment by EricGao888** [comment]
> > @EricGao888 I find out your PR does not change anything. Did you delete your branch? Fix-9223
> 
> @zhongjiajie Sorry I mistakenly delete the branch last night. I will recover it later.

I reopened the PR here: https://github.com/apache/dolphinscheduler/pull/9299

**Pull request closed without merging**
