### PR TITLE
[Feature] [ALERT-9406]add new properties to alert class

### LINKED ISSUE #9406: [Feature] [ALERT] Add new property to class Alert
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Add new property to class Alert.
projectCode processDefinitionCode  processInstanceId alertType

### What you expected to happen

Add new property to class Alert

### How to reproduce

Add new property to class Alert

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

add new properties to alert class
close https://github.com/apache/dolphinscheduler/issues/9406

## Brief change log

add new properties to alert class
## Verify this pull request

I have tested locally.

### CODE REVIEW

**Comment by Tianqi-Dotes** [comment]
@caishunfeng PTAL , much appreciated.

**Review by caishunfeng — DISMISSED** [review]
LGTM

**Review by lenboo — CHANGES_REQUESTED** [review]
Upgrading SQL also requires updating.

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
