### PR TITLE
[fix-#15176] [sql] If the value of the variable contains $ or / symbols, an error may be reported. 

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

- plz close this issue #15176

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by fuchanghai** [comment]
but when i run ``` mvn spotless:apply ``` I don't see any changes to the file cc @qingwli @EricGao888 
image


image

**Comment by qingwli** [comment]
image

I  have tested and works well.

Did you run this command in the ds root folder?

looks like you in UI folder 

image

**Comment by fuchanghai** [comment]
> image
> 
> I have tested and works well.
> 
> Did you run this command in the ds root folder?
> 
> looks like you in UI folder
> 
> image

thanks for you review,plz help me to run CI

**Comment by fuchanghai** [comment]
@qingwli  @ruanwenjun PTAL

**Comment by qingwli** [comment]
What's your test content was?

**Comment by fuchanghai** [comment]
> What's your test content was?
hi @qingwli you can see #15176

**Comment by qingwli** [comment]
image
No content value

**Comment by fuchanghai** [comment]
> image No content value

content is ``` this is ${a} ```  
output parameter ,you can choose one of follow : 
- ```key ``` :  ```a ```   ```value``` : ```99${aa} ```
- ```key ``` :  ```a ```   ```value``` : ```99$```

**Comment by qingwli** [comment]
image
Works well for me? Any different?

**Comment by fuchanghai** [comment]
i'm sorry ,you can test this content ``` select * from a where a != !{a}```
image

**Comment by ruanwenjun** [comment]
Please add Ut for this, this issue is not clear.

**Comment by fuchanghai** [comment]
> Please add Ut for this, this issue is not clear.

i will add UT, tomorrow

**Comment by fuchanghai** [comment]
> Please add Ut for this, this issue is not clear.

dnoe

**Comment by fuchanghai** [comment]
> image Works well for me? Any different?

hi @qingwli I had add UT,PTAL

**Comment by qingwli** [comment]
@ruanwenjun PTAL

**Comment by fuchanghai** [comment]
@caishunfeng @SbloodyS PTAL

**Pull request closed without merging**
