### PR TITLE
Enable spotless to fix markdown formatting and refactor faq.md as an example

### LINKED ISSUE #11364: [Feature][Style] Format docs automatically
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently, `Spotless` in DS only formats `java` code automatically. 
* `Spotless` does support formatting `markdown`, `json`... We could use it to format DS docs automatically.

image

https://github.com/diffplug/spotless

### Use case

* Already described above.

### Related issues

#6535

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Enable spotless to fix markdown formatting.
* This PR closes: #11364 

## Brief change log

* Enable spotless to fix markdown formatting.
* Refactor faq.md as an example.

## Verify this pull request

* Verified by manual tests.

### CODE REVIEW

**Comment by EricGao888** [comment]
As soon as this one merged, I will start to work on https://github.com/apache/dolphinscheduler/issues/11385

**Comment by zhongjiajie** [comment]
Our FAQ has the html syntax IMG, I think spotless can not auto-fix it, but we should at less find it out, also the other markdown syntax error, or warning. ref https://github.com/apache/dolphinscheduler/issues/11385#issuecomment-1210134097

**Comment by EricGao888** [comment]
> Our FAQ has the html syntax IMG, I think spotless can not auto-fix it, but we should at less find it out, also the other markdown syntax error, or warning. ref [#11385 (comment)](https://github.com/apache/dolphinscheduler/issues/11385#issuecomment-1210134097)

Thx for the information, I will take a look.

**Comment by EricGao888** [comment]
> Our FAQ has the html syntax IMG, I think spotless can not auto-fix it, but we should at less find it out, also the other markdown syntax error, or warning. ref [#11385 (comment)](https://github.com/apache/dolphinscheduler/issues/11385#issuecomment-1210134097)

FYI @zhongjiajie I also submitted an issue for `Spotless` to see if there is anything we could do to fix `http` code formatting in `markdown` by `Spotless`. https://github.com/diffplug/spotless/issues/1272

**Comment by EricGao888** [comment]
I guess the reason why we have `html` code in `markdown` is to resize the images: https://www.markdownguide.org/hacks/#image-size

With `markdown` syntax instead of using `html`, we could insert images but could not resize them. Should we replace those `html` code? @zhongjiajie

**Review by kezhenxu94 — APPROVED** [review]

**Comment by EricGao888** [comment]
@zhongjiajie It would take some more time for me to add several docs checks in CI and I think that is out of the scope of this PR. Therefore, I'm going to merge this one so that markdown files could get well-formatted from now on. For CI checks mentioned in the comments above, I will submit another PR later to issue: #11347 Thanks

**Pull request merged**
