### PR TITLE
[Feature-16264][Task Plugin] Add Aliyun ADB Spark Task Plugin

### LINKED ISSUE #16264: [Feature][Task Plugin] Add Aliyun ADB Spark Task Plugin
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.


### Description

* [`Aliyun ADB Spark`](https://www.alibabacloud.com/help/en/analyticdb-for-mysql/user-guide/spark-app-development/?spm=a2c63.l28256.0.0.7cc67ed0j6gd6b) is a big data solution that separates data computing from data storage, which meets the requirements for online interactive search, stream processing, batch processing, and machine learning. 
* This feature aims to provide the Apache DolphinScheduler community users with a built-in plugin, which is also provided by Apache Airflow. We hope that this plugin will facilitate users in managing Aliyun ADB Spark applications more conveniently.

### Use case

#### Create Datasource

- Click `Datasource -> Create Datasource -> ADBSPARK` to create a datasource.

- Fill in `Datasource Name`, `Aliyun Access Key Id`, `Aliyun Access Key Secret`, `Aliyun Region Id` and click `Confirm`.

#### Create Tasks

- Click `Porject -> Workflow Definition -> Create Workflow` and drag the `ADBSPARK` task to the canvas.

- Fill in the task parameters and click `Confirm` to create the task node.

#### Task Parameters

- Please refer to [DolphinScheduler Task Parameters Appendix](appendix.md) `Default Task Parameters` section for default parameters.

| **Parameters**            | **Description**                                                                                                                                                                                                                                   |
|---------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Datasource types          | The type of datasource the task uses, should be `ADBSPARK`.                                                                                                                                                                                       |
| Datasource instances      | The instance of `ADBSPARK` datasource.                                                                                                                                                                                                            |
| Aliyun ADB Cluster ID     | The ID of the AnalyticDB for MySQL Data Lakehouse Edition (V3.0) cluster.                                                                                                                                                                         |
| Aliyun ADB Resource Group | The name of the job resource group in AnalyticDB for MySQL Data Lakehouse Edition (V3.0) cluster.                                                                                                                                                 |
| Aliyun ADB App Type       | The type of the application. Valid values: Batch(default), SQL.                                                                                                                                                                                   |
| Aliyun ADB Spark Data     | The data of the application template. For information about the application template configuration, see [Spark application configuration guide](https://www.alibabacloud.com/help/en/analyticdb-for-mysql/spark-application-configuration-guide). |

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dcoliversun**
## Purpose of the pull request

This PR aims to add Aliyun ADB Spark Task Plugin, close https://github.com/apache/dolphinscheduler/issues/16264

## Brief change log

* Add adb spark task module to task-all pom.xml
* Add adb spark datasource module to datasource-all pom.xml

## Verify this pull request

This change added tests and can be verified as follows:

- *Added adb spark task tests for unit test.*
- *Added adb spark datasource tests for unit test.*
- *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by dcoliversun** [comment]
cc @SbloodyS could you please review this PR if you have time :)

**Comment by SbloodyS** [comment]
Like #16127, please find a PMC/Committer that is willing to maintain this task plugin on an ongoing basis. Otherwise we won't accept it. @dcoliversun

**Comment by dcoliversun** [comment]
@SbloodyS Thanks for your mention. We will work with @davidzollo to jointly maintain the adb spark plugin. cc @leesf

**Comment by dcoliversun** [comment]
@SbloodyS @davidzollo Conflict and error are solved, maybe we can approve github action

**Pull request closed without merging**
