### PR TITLE
[fix#12114][BUG]check task instance when delete worker group

### PR DESCRIPTION
**Pull request by jackfanwan**
Added task instance criteria

#12114

### CODE REVIEW

**Comment by jackfanwan** [comment]
image
Excuse me, how can I fix this mistake

**Comment by jackfanwan** [comment]
> image Excuse me, how can I fix this mistake

@caishunfeng

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
related pr #12129

Hi @DarkAssassinator do you have time to review this pr?

**Comment by caishunfeng** [comment]
@jackfanwan Please use the correct title.

**Comment by jackfanwan** [comment]
> @jackfanwan Please use the correct title.

Is that right？

**Comment by caishunfeng** [comment]
> Added task instance criteria

The pr logic and issue is abort `taskInstance check when worker group delete`, `Added task instance criteria` is not clear.

**Comment by caishunfeng** [comment]
> > @jackfanwan Please use the correct title.
> 
> Is that right？

`Added task instance criteria` is not clear, this pr and issue is abort `check task instance when delete worker group`

**Comment by jackfanwan** [comment]
> > > @jackfanwan Please use the correct title.
> > 
> > 
> > Is that right？
> 
> `Added task instance criteria` is not clear, this pr and issue is abort `check task instance when delete worker group`

ok

**Comment by DarkAssassinator** [comment]
> related pr #12129
> 
> Hi @DarkAssassinator do you have time to review this pr?

Sure, sorry but it has closed? sorry for push a same PR

**Pull request closed without merging**
