### PR TITLE
Flinksql support standalone deploy mode

### PR DESCRIPTION
**Pull request by shenyun**
## Purpose of the pull request

feature flinksql support standalone deploy mode

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please add some docs.

**Review by Amy0104 — COMMENTED** [review]
The front end part LGTM.

**Review by EricGao888 — APPROVED** [review]
LGTM, it would be better if u could add a UT case to https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java

**Review by ruanwenjun — APPROVED** [review]
+1

**Comment by davidzollo** [comment]
thanks for your first contribution, I'm looking forward to your deep participation.

**Pull request merged**
