### PR TITLE
[FIX-7514] press Enter key get "true" not new line

### LINKED ISSUE #7514: [Bug] [UI] press Enter key get "true" not new line
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In shell task `Script` editbox, when you input some special char(!@#$%...) and you press 'Enter' key to next line.

While you just get `true` str afterwards.

image

### What you expected to happen

Clearly, cursor to new line not `true`.

### How to reproduce

See `What happened`

### Anything else

_No response_

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by devosend**
close #7514 

press Enter key get "true" is not a bug. this is beause `Enter` key is shortcut for autocomplete. I override this shortcut now. However, you can still use the `Tab` shortcut to autocomplete.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@songjianet Do you have time to take a look at this PR?

**Comment by zhongjiajie** [comment]
ping @songjianet again

**Review by songjianet — DISMISSED** [review]
LGTM

**Review by zhongjiajie — DISMISSED** [review]
LGTM, thanks

**Comment by zhongjiajie** [comment]
could you rebase on dev branch? I can not merge due to we need e2e ci context @devosend

**Comment by devosend** [comment]
> could you rebase on dev branch? I can not merge due to we need e2e ci context @devosend

I performed the rebase operation.

**Comment by devosend** [comment]
PTAL @zhongjiajie

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
