### PR TITLE
[1.3.6-prepare][API] Improvement the duration field modify the display to a time-based minute-second format (e.g. 1d 10h 20m 1s) #4752

### PR DESCRIPTION
**Pull request by CalvinKirs**
issue #4751 
pr #4752

### CODE REVIEW

**Comment by zhuangchong** [comment]
+1

**Review by chengshiwen — APPROVED** [review]
+1

**Comment by chengshiwen** [comment]
pr #4752
issue #4751

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
