### PR TITLE
[Fix-14512][BOM] kubernetes-client version conflict

### LINKED ISSUE #14512: [Bug] [K8S] kubernetes-client-api-6.0.0 and spring-cloud-kubernetes-fabric8-config-2.1.3 version conflicts
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Build an image from the latest dev branch and deploy to k8s. All components failed to start with the following error.

```
[INFO] 2023-07-12 09:43:17.819 +0800 com.zaxxer.hikari.HikariDataSource:[352] - DolphinScheduler - Shutdown completed.
[INFO] 2023-07-12 09:43:17.831 +0800 org.eclipse.jetty.server.session:[149] - node0 Stopped scavenging
[INFO] 2023-07-12 09:43:17.838 +0800 org.eclipse.jetty.server.handler.ContextHandler:[1159] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@301e5d23{application,/dolphinscheduler,[file:///tmp/jetty-docbase.12345.1379246485250171406/, jar:file:/opt/dolphinscheduler/libs/swagger-ui-4.11.1.jar!/META-INF/resources],STOPPED}
[INFO] 2023-07-12 09:43:17.865 +0800 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2023-07-12 09:43:17.933 +0800 org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter:[40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector.watch(EventBasedConfigMapChangeDetector.java:81)

The following method did not exist:

    io.fabric8.kubernetes.client.dsl.MixedOperation.watch(Ljava/lang/Object;)Lio/fabric8/kubernetes/client/Watch;

The calling method's class, org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector, was loaded from the following location:

    jar:file:/opt/dolphinscheduler/libs/spring-cloud-kubernetes-fabric8-config-2.1.3.jar!/org/springframework/cloud/kubernetes/fabric8/config/reload/EventBasedConfigMapChangeDetector.class

The called method's class, io.fabric8.kubernetes.client.dsl.MixedOperation, is available from the following locations:

    jar:file:/opt/dolphinscheduler/libs/kubernetes-client-api-6.0.0.jar!/io/fabric8/kubernetes/client/dsl/MixedOperation.class

The called method's class hierarchy was loaded from the following locations:

    io.fabric8.kubernetes.client.dsl.MixedOperation: file:/opt/dolphinscheduler/libs/kubernetes-client-api-6.0.0.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector and io.fabric8.kubernetes.client.dsl.MixedOperation
2023-07-12T01:43:17.933762469Z
```

### What you expected to happen

All components are running normally in k8s

##### build docker image 
```
./mvnw -B clean package  -Dmaven.test.skip  -Dmaven.javadoc.skip  -Dmaven.checkstyle.skip  -Dmaven.deploy.skip -Ddocker.push.skip=true -Ddocker.tag=3.2.0-RC1  -Ddocker.hub=xxx.com/yyy  -Pdocker,release
```
##### deploy by helm
```
helm upgrade --install --create-namespace --namespace dolphinscheduler  dolphinscheduler dolphinscheduler -f helm/values-local.yaml
```

```
cat values-local.yaml
image:
  registry: xxx.com/yyy
  tag: 3.2.0-RC1

minio:
  enabled: false

conf:
  common:
    # resource storage type: HDFS, S3, OSS, GCS, ABS, NONE
    resource.storage.type: NONE
    # The Azure client ID (Azure Application (client) ID)
    resource.azure.client.id: minioadmin
    # The Azure client secret in the Azure application
    resource.azure.client.secret: minioadmin
    # The Azure data factory subscription ID
    resource.azure.subId: minioadmin
    # The Azure tenant id in the Azure Active Directory
    resource.azure.tenant.id: minioadmin
```

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- close #14512 

## Brief change log
SpringCloud often support cloud-native features in two ways, by using native `kubernetes-client` dependency and `fabric8io-kubernetes-client`, including loading properties from ConfigMap in out project.

If we have to use 6.0.0+ version fabric8io-kubernetes-client for pod log watcher and it's incompatible with SpringCloud 2021.x, we can use native `kubernetes-client` for SpringCloud.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> If we have to use 6.0.0+ version fabric8io-kubernetes-client for pod log watcher and it's incompatible with SpringCloud 2021.x, we can use native kubernetes-client for SpringCloud.

This means we will have both kubernetes clients (official one and fabric8 one), unless you want to remove one of them rewrite all the existing related codes  

BTW Spring Boot 2 will be EOL soon (4 months to come) and upgrading is often a preferable choice than downgrading.

**Comment by Radeity** [comment]
Hi @kezhenxu94 , thanks for your comment

> This means we will have both kubernetes clients (official one and fabric8 one).

Yes, can we keep two clients temporarily for quick fix (before release 3.2.0)? I don't find other suitable solutions 😢 

> BTW Spring Boot 2 will be EOL soon (4 months to come) and upgrading is often a preferable choice than downgrading.

Gotcha, I think we can consider upgrading our Spring version to 3.x in the future and then we can unify the kubernetes client, either. WDYT?

**Comment by kezhenxu94** [comment]
> Hi @kezhenxu94 , thanks for your comment
> 
> > This means we will have both kubernetes clients (official one and fabric8 one).
> 
> Yes, can we keep two clients temporarily for quick fix (before release 3.2.0)? I don't find other suitable solutions 😢

I'm -0, but if you insist, please make sure the `kubernetes-client` is only used by Spring, not in our codes, because fabric8 client is already used in our codes, if we want to unify the clients eventually, please minimize the possible changes from now

**Comment by Radeity** [comment]
> I'm -0, but if you insist, please make sure the `kubernetes-client` is only used by Spring, not in our codes.

Thanks for reminding! I will pay more attention to the usage of `kubernetes-client` for future PR, and finally unify to fabric8 when we upgrade to SpringBoot 3.0.

**Review by Gallardot — APPROVED** [review]
I have tested this PR on a K8S cluster v1.22.17, and the k8s task related functions work fine.

**Comment by EricGao888** [comment]
> > I'm -0, but if you insist, please make sure the `kubernetes-client` is only used by Spring, not in our codes.
> 
> Thanks for reminding! I will pay more attention to the usage of `kubernetes-client` for future PR, and finally unify to fabric8 when we upgrade to SpringBoot 3.0.

Maybe you could add a `// TODO: xxxxx` in comment in case we forget this unification stuff.

**Comment by kezhenxu94** [comment]
> > > I'm -0, but if you insist, please make sure the `kubernetes-client` is only used by Spring, not in our codes.
> > 
> > 
> > Thanks for reminding! I will pay more attention to the usage of `kubernetes-client` for future PR, and finally unify to fabric8 when we upgrade to SpringBoot 3.0.
> 
> Maybe you could add a `// TODO: xxxxx` in comment in case we forget this unification stuff.

Filing an issue is preferable to track the issue, and adding a spotless rule to disallow usages of classes from `kubernetes-client` is best

**Comment by zhongjiajie** [comment]
skip merge and wait add spotless rules

**Comment by zhongjiajie** [comment]
rerun ci

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
