### PR TITLE
[Fix-#11942] fix error occurred when copying workflow

### PR DESCRIPTION
**Pull request by wendongdi**
## Purpose of the pull request

fix the bug  #12027 

## Brief change log

set id to null before creating the target

## Verify this pull request

manually

### CODE REVIEW

**Comment by wendongdi** [comment]
@SbloodyS @caishunfeng wait for viewing ~

**Comment by SbloodyS** [comment]
Please associate the issue @wendongdi

**Comment by wendongdi** [comment]
> Please associate the issue @wendongdi

i added it.

**Comment by wendongdi** [comment]
it seems mix other commits , i will close this PR and reopen an other one

**Comment by wendongdi** [comment]
it seems mix other commits , i will close this PR and reopen an other one

**Pull request closed without merging**
