### PR TITLE
[Bug][dep] Bump httpclient version to 4.5.13

### LINKED ISSUE #9538: [Bug] upgrade httpclient due to cve
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

library has cve - https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient

### What you expected to happen

use security libs

### How to reproduce

n/a

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

close #9538 

## Brief change log

close #9538 
## Verify this pull request
tested locally.

### CODE REVIEW

**Comment by Tianqi-Dotes** [comment]
@pjfanning PTAL, much appreciated.

**Comment by zhongjiajie** [comment]
@Tianqi-Dotes It seems CI failed

**Comment by zhongjiajie** [comment]
FYI, still failed

**Review by zhongjiajie — APPROVED** [review]
@Tianqi-Dotes LGTM, but i do not know the detail of dep upgrade, should we wait for @pjfanning to double-check or could we merge directly when one committer is approved?

**Comment by pjfanning** [comment]
I'm not really a dolphinscheduler user - I'm an ASF member with an interest in getting ASF projects to use secure libs. I rely on the CI build to test the lib changes.

**Comment by zhongjiajie** [comment]
> I'm not really a dolphinscheduler user - I'm an ASF member with an interest in getting ASF projects to use secure libs. I rely on the CI build to test the lib changes.

Sound great and thanks for your contribution to all ASF projects  👍

**Pull request merged**
