### PR TITLE
[Bug] Workflow instance can't stop due to doesn't refresh status in master

### PR DESCRIPTION
**Pull request by Dyqer**
## Purpose of the pull request

we can't stop the process instance, because master not refresh the process status from DB

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
Basically LGTM, this should be refactor, all workflow status change should happen in master.

**Comment by Dyqer** [comment]
> Basically LGTM, this should be refactor, all workflow status change should happen in master.

@ruanwenjun Sounds great, but some times, there are many process instance's host is null, which master should duty on this part？

**Comment by ruanwenjun** [comment]
> > Basically LGTM, this should be refactor, all workflow status change should happen in master.
> 
> @ruanwenjun Sounds great, but some times, there are many process instance's host is null, which master should duty on this part？

The workflow instance's host should not be null, the host will be inject when the workflow instance initialized.

**Comment by 2421994771** [comment]
I also encountered the same problem, which is less likely to happen. However, when the master received the state change event, he would refresh the context, but the state was still inconsistent with the database after the refresh. I want to know why the inconsistency occurred. The above submission solves the problem, but does not explain why the state is inconsistent

**Comment by 2421994771** [comment]
> ## Purpose of the pull request
> we can't stop the process instance, because master not refresh the process status from DB
I also encountered the same problem, which is less likely to happen. However, when the master received the state change event, he would refresh the context, but the state was still inconsistent with the database after the refresh. I want to know why the inconsistency occurred. The above submission solves the problem, but does not explain why the state is inconsistent, if you know, can you tell me?

**Pull request merged**
