### PR TITLE
[Fix-13989] Add path validation

### LINKED ISSUE #13989: [Bug] [resource] resource center
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

click resource center and the error message will show

```log
Internal Server Error: The path does not exist. make sure resource path: 
```

### What you expected to happen

should not raise error.

### How to reproduce

start and click resources center

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ly109974**
fix #13989

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Thanks for fixing so fast, and I see you only fix HDFS storage operatior, did you test wether other operator like gcs, oss and s3 work or not? @ly109974

**Comment by rickchengx** [comment]
> Thanks for fixing so fast, and I see you only fix HDFS storage operatior, did you test wether other operator like gcs, oss and s3 work or not? @ly109974

Hi, @zhongjiajie the `listFilesStatus()` in GCS / OSS works well, which has been tested in
* #13562 
* #13435

**Comment by ly109974** [comment]
> 谢谢你修的这么快，我看你只修了HDFS存储operator，你有没有测试其他operator比如gcs、oss和s3能不能用？@ly109974

**Comment by ly109974** [comment]
> Thanks for fixing so fast, and I see you only fix HDFS storage operatior, did you test wether other operator like gcs, oss and s3 work or not? @ly109974

I don't have an environment, is there any other way? @zhongjiajie

**Comment by zhongjiajie** [comment]
approval the ci run

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
