### PR TITLE
[Feature][UI Next] Added the configuration of routes

### LINKED ISSUE #7432: [Feature][UI-Next] Added the configuration of routes
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Automatically generate mappings for files
- Add a new utils folder and some definition methods

Please refer to the main `issue`  [#7332](https://github.com/apache/dolphinscheduler/issues/7332).

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by labbomb**
## Purpose of the pull request

  
close [#7432](https://github.com/apache/dolphinscheduler/issues/7432)

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by songjianet — APPROVED** [review]

**Comment by songjianet** [comment]
LGTM

**Comment by zhongjiajie** [comment]
> LGTM

Hi @songjianet If you see some PR could not run CI and contributor is first time contribute, you could ping committer to allow to run CI

**Comment by songjianet** [comment]
> > LGTM
> 
> Hi @songjianet If you see some PR could not run CI and contributor is first time contribute, you could ping committer to allow to run CI

@zhongjiajie run ci

**Comment by zhongjiajie** [comment]
> @zhongjiajie run ci

Ok, I approval an rerun CI

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Pull request merged**
