### PR TITLE
[11130][refactor] refactor alert-api with lombok

### PR DESCRIPTION
**Pull request by MichaelDeSteven**
## Purpose of the pull request
see #11130

## Brief change log
refactor alert-api with lombok
## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by kezhenxu94 — COMMENTED** [review]
Use `@Data` to replace `@Getter, @Setter, @ToString`

**Comment by MichaelDeSteven** [comment]
> Use `@Data` to replace `@Getter, @Setter, @ToString`

Is that means we need to replace all class with `@Data` or just `AlertData` `AlertInfo` `AlertResult`.
I saw #11074 say that would better to avoid use `@Data`.

**Comment by EricGao888** [comment]
> Use `@Data` to replace `@Getter, @Setter, @ToString`

Hi @kezhenxu94, when I was working on Zeppelin task plugin, I used `@Data` to refactor `ZeppelinParameters` at first and caused `sonar` to fail because of a significant decrease in UT coverage. After checking some materials, I found `@Data` generates some code we do not need here. After replacing it with `@Getter` `@Setter` and `ToString`, the UT coverage recovered. So there might be a trade-off between code briefness and UT coverage. 
Some related materials: 
* https://stackoverflow.com/questions/45569085/sonarqube-bad-coverage-because-of-lombok-data and https://projectlombok.org/features/Data
* https://projectlombok.org/features/Data

WDYT?

**Comment by kezhenxu94** [comment]
> > Use `@Data` to replace `@Getter, @Setter, @ToString`
> 
> 
> 
> Hi @kezhenxu94, when I was working on Zeppelin task plugin, I used `@Data` to refactor `ZeppelinParameters` at first and caused `sonar` to fail because of a significant decrease in UT coverage. After checking some materials, I found `@Data` generates some code we do not need here. After replacing it with `@Getter` `@Setter` and `ToString`, the UT coverage recovered. So there might be a trade-off between code briefness and UT coverage. 
> 
> Some related materials: 
> 
> * https://stackoverflow.com/questions/45569085/sonarqube-bad-coverage-because-of-lombok-data and https://projectlombok.org/features/Data
> 
> * https://projectlombok.org/features/Data
> 
> 
> 
> WDYT?

We should be able to exclude generated codes from Sonar

**Comment by kezhenxu94** [comment]
> > Use `@Data` to replace `@Getter, @Setter, @ToString`
> 
> 
> 
> Hi @kezhenxu94, when I was working on Zeppelin task plugin, I used `@Data` to refactor `ZeppelinParameters` at first and caused `sonar` to fail because of a significant decrease in UT coverage. After checking some materials, I found `@Data` generates some code we do not need here. After replacing it with `@Getter` `@Setter` and `ToString`, the UT coverage recovered. So there might be a trade-off between code briefness and UT coverage. 
> 
> Some related materials: 
> 
> * https://stackoverflow.com/questions/45569085/sonarqube-bad-coverage-because-of-lombok-data and https://projectlombok.org/features/Data
> 
> * https://projectlombok.org/features/Data
> 
> 
> 
> WDYT?

We should be able to exclude generated codes from code coverages

**Review by kezhenxu94 — APPROVED** [review]

**Review by EricGao888 — APPROVED** [review]
Good job! LGTM

**Review by zhuxt2015 — COMMENTED** [review]
LGTM

**Pull request merged**
