### PR TITLE
fixBug('#6172') [UI]Dag node name value judgment error

### PR DESCRIPTION
**Pull request by break60**
issues #6172

### CODE REVIEW

**Review by Technoboy- — DISMISSED** [review]

**Review by CalvinKirs — DISMISSED** [review]
LGTM

**Comment by CalvinKirs** [comment]
please resolve conflicting files.thx

**Comment by break60** [comment]
> please resolve conflicting files.thx

ut seems to be caused by the ut test, and has nothing to do with the front-end code

**Comment by CalvinKirs** [comment]
> > please resolve conflicting files.thx
> 
> ut seems to be caused by the ut test, and has nothing to do with the front-end code

can you update the code?

**Comment by wangyizhi1** [comment]
LGTM

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
