### PR TITLE
[TEST] increase coverage of environment service

### PR DESCRIPTION
**Pull request by abzymeinsjtu**
## Purpose of the pull request

increase coverage of environment service

### CODE REVIEW

**Review by EricGao888 — DISMISSED** [review]

**Review by EricGao888 — DISMISSED** [review]

**Review by qingwli — APPROVED** [review]
+1

**Review by qingwli — CHANGES_REQUESTED** [review]
Please fix code smell
 ```
  assertEquals(
((List<Environment>) result.get(Constants.DATA_LIST)).size(), 0);
```

Swap these 2 arguments so they are in the correct order: expected value, actual value.

**Comment by abzymeinsjtu** [comment]
> Please fix code smell
> 
> ```
>  assertEquals(
> ((List<Environment>) result.get(Constants.DATA_LIST)).size(), 0);
> ```
> 
> Swap these 2 arguments so they are in the correct order: expected value, actual value.

done

**Review by EricGao888 — APPROVED** [review]

**Review by qingwli — APPROVED** [review]
+1

**Pull request merged**
