### PR TITLE
[Improvement-14052][Log] Remove the useless filter in getAppIdsFromLogFile

### LINKED ISSUE #14052: [Improvement][Log] Remove the useless filter in getAppIdsFromLogFile
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Remove the useless filter in getAppIdsFromLogFile

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request
* close: #14052 

## Brief change log

There is no need to perform 2 regular matches on the same line

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by Radeity — COMMENTED** [review]
I'm not sure whether filter first and then forEach aims to avoid branch prediction overhead, but it seems that two regular matches cost a lot, either. cc @ruanwenjun

**Comment by rickchengx** [comment]
> I'm not sure whether filter first and then forEach aims to avoid branch prediction overhead, but it seems that two regular matches cost a lot, either. cc @ruanwenjun

Hi, @Radeity , thanks for you comment
The `filter()` also needs to make regular matches and processing for each line. I am not sure what branch prediction you are referring to.

**Comment by Radeity** [comment]
> I am not sure what branch prediction you are referring to.

I refer to `if (matcher.find())` in forEach

**Comment by rickchengx** [comment]
> > I am not sure what branch prediction you are referring to.
> 
> I refer to `if (matcher.find())` in forEach

If there are a total of `N` lines in the log, and `M` lines have yarn app id.
Then the previous complexity is `O(N+M)`, and now is `O(N)`, WDYT?

**Comment by Radeity** [comment]
> If there are a total of `N` lines in the log, and `M` lines have yarn app id. Then the previous complexity is `O(N+M)`, and now is `O(N)`, WDYT?

For such a streaming execution, i think complexity should be considered `O(N)`. Maybe we should compare the overhead brought from `N` more times regular matches with wrong branch prediction, i have no ideas which one is more efficient...

**Comment by rickchengx** [comment]
> > If there are a total of `N` lines in the log, and `M` lines have yarn app id. Then the previous complexity is `O(N+M)`, and now is `O(N)`, WDYT?
> 
> For such a streaming execution, i think complexity should be considered `O(N)`. Maybe we should compare the overhead brought from `N` more times regular matches with wrong branch prediction, i have no ideas which one is more efficient...

I don't think this question is about branch prediction.
Since in any case, there are a total of N+M times `matcher.find()` before, now it becomes N.

**Comment by Radeity** [comment]
> I don't think this question is about branch prediction.
> Since in any case, there are a total of N+M times `matcher.find()` before, now it becomes N.

If only consider about matching times, i agree that use `forEach` only is more efficient.

**Review by Radeity — APPROVED** [review]

**Pull request merged**
