### PR TITLE
Fix jar path is not correct in java task

### LINKED ISSUE #15902: [Bug] [JAVA TASK] Unable to access jarfile
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[INFO] 2024-04-24 15:40:09.119 +0800 - #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
export JAVA_HOME=/opt/java/openjdk
${JAVA_HOME}/bin/java -classpath .:/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74:/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar -jar /tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar arg1 arg2 
[INFO] 2024-04-24 15:40:09.119 +0800 - ****************************** Script Content *****************************************************************
[INFO] 2024-04-24 15:40:09.119 +0800 - Executing shell command : sudo -u root -i /tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/58_74.sh
[INFO] 2024-04-24 15:40:09.126 +0800 - process start, process id is: 369
[INFO] 2024-04-24 15:40:10.126 +0800 -  -> 
	Error: Unable to access jarfile /tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar
[INFO] 2024-04-24 15:40:10.127 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74, processId:369 ,exitStatusCode:1 ,processWaitForStatus:true ,processExitValue:1

### What you expected to happen

the jar path contains twice `execute path` , it should be once.
- wrong:
/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74//tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar -jar 
- expect:
/tmp/dolphinscheduler/exec/process/root/13364857834464/13374826096608_6/58/74/Test-1.0-SNAPSHOT.jar -jar 

### How to reproduce

1. upload jar to resource center(hfds)
2. create java task (jar type) and select the jar 
3. run task and log error

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/15902

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by Radeity — DISMISSED** [review]
LGTM

**Review by caishunfeng — DISMISSED** [review]

**Review by Radeity — DISMISSED** [review]

**Review by Radeity — APPROVED** [review]
LGTM

**Comment by Radeity** [comment]
Some humble suggestion, next time, can you add additional explanations for the modifications made after PR is approved when performing a force-push?

**Comment by ruanwenjun** [comment]
> Some humble suggestion, next time, can you add additional explanations for the modifications made after PR is approved when performing a force-push?

Thanks for your suggestion, I will add message next time, I'm just worried that these won't be cleaned up in the merger.

**Comment by Radeity** [comment]
> > Some humble suggestion, next time, can you add additional explanations for the modifications made after PR is approved when performing a force-push?
> 
> Thanks for your suggestion, I will add message next time, I'm just worried that these won't be cleaned up in the merger.

Yeah, I can get your point, keep one commit is cleaner. With additional message, review the PR again will be faster :D

**Review by caishunfeng — APPROVED** [review]
LGTM

**Pull request merged**
