### PR TITLE
[Feature-10182][task-datax] datax access kerberos authenticated bigdata cluster

### LINKED ISSUE #10182: [Feature][Task] datax access kerberos authenticated bigdata cluster
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Because Kerberos authentication is added to the big data cluster, when using DATAX to write data to HDFS, you need to use the tenant's KeyTab file to introduce it into json file. Can this file reference use the content of the resource center like a shell? When using, the dataX plug-in downloads the keytab file locally through the resource center runtime, so as to obtain the absolute path and then transfer the parameters into the JSON file, Instead of importing files into the specified server in advance.

### Use case

datax access kerberos authenticated bigdata cluster

### Related issues

datax:
image

shell:
image

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lugela**
In the process of realizing datax synchronization, use custom json for better connection to enable kerberos-authenticated clusters, such as using plug-ins such as hdfs and hbase

## Brief change log
In the process of datax synchronization, use custom json to enable kerberos-authenticated cluster for better connection. For example, if you use plug-ins such as hdfs and hbase us to use related keytab files or xml files, you can use the resource center module

close #10182

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by lugela** [comment]
hi, please tell me if ee2 failed, but after reading the log, I found that it has nothing to do with the change. What should I do here?

**Comment by EricGao888** [comment]
> hi, please tell me if ee2 failed, but after reading the log, I found that it has nothing to do with the change. What should I do here?

You could rebase the code or use `git commit --amend` and push again to force the CI to restart.

**Comment by lugela** [comment]
> > hi, please tell me if e2e failed, but after reading the log, I found that it has nothing to do with the change. What should I do here?
> 
> You could rebase the code or use `git commit --amend` and push again to force the CI to restart.

I expressed a problem, what I mean is that the e2e verification failed, and after reading the reason for the failure, I found that it is not related to the code I submitted

**Comment by lugela** [comment]
hello,
This pr corresponds to 'https://github.com/apache/dolphinscheduler/issues/10182'
Can you help me check what else I should do?

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by Amy0104 — APPROVED** [review]
The front end part LGTM.

**Pull request merged**
