### PR TITLE
fixbug: varPool value is error

### PR DESCRIPTION
**Pull request by Ivan0626**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhuangchong** [comment]
Please create an issue first and associate the PR to the issue.

**Comment by Ivan0626** [comment]
[https://github.com/apache/dolphinscheduler/issues/7746#issue-1091390404](url)

**Comment by Ivan0626** [comment]
> Please create an issue first and associate the PR to the issue.

https://github.com/apache/dolphinscheduler/issues/7746#issue-1091390404

**Review by zhuangchong — COMMENTED** [review]
Please check whether there are spaces. In fact, the best way to get data in this part is to use regular.

**Comment by Ivan0626** [comment]
> 

I improve this PR by regular, Please review this commit

**Review by zhuangchong — DISMISSED** [review]
+1

**Review by zhuangchong — APPROVED** [review]
+1

**Pull request merged**
