### PR TITLE
make alert instance page display more friendly

### PR DESCRIPTION
**Pull request by jon-qj**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Can you provide the final renderings?

**Comment by jon-qj** [comment]
> Can you provide the final renderings?
These are the final renderings.

DingTalk
image

Email
image
Feishu
image

Http
image

Script
image

WeChat
image

**Review by CalvinKirs — APPROVED** [review]
LGTM, btw, this method does not seem to be very suitable for plug-in development, this is a historical issue. But I have no good plan for the time being. Maybe we can open an issue to discuss this.

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
