### PR TITLE
[Fix-13820][alert] Fix bodyParams is empty get error log

### LINKED ISSUE #13820: [Bug] [alert] alert http-plugin `Body` is not necessary but if not input any thing  got error log
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm try to config a alert using `http` 

the config page show the `Body` is not necessary, but if not input any thing , got the error log, and not send the alert message.

image

```shell
[ERROR] 2023-03-29 07:19:32.245 +0000 org.apache.dolphinscheduler.plugin.alert.http.HttpSender:[164] - send http alert msg  exception : null
```

### What you expected to happen

Not input `Body` success.
or change the `Body` is must

### How to reproduce

don not input the  `Body` 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhaifb**
## Purpose of the pull request

initialize a empty  objectNode to save contentField, if bodyParams is empty,will send message only include contentField

close #13820 
If ` bodyParams` is empty ,will get error log. `send http alert msg  exception: null`
```java
    private void setMsgInRequestBody(String msg) {
        try {
            ObjectNode objectNode = JSONUtils.parseObject(bodyParams);
            // set msg content field
            objectNode.put(contentField, msg);
            StringEntity entity = new StringEntity(JSONUtils.toJsonString(objectNode), DEFAULT_CHARSET);
            ((HttpPost) httpRequest).setEntity(entity);
        } catch (Exception e) {
            log.error("send http alert msg  exception : {}", e.getMessage());
        }
    }
```

fix  `ObjectNode objectNode = JSONUtils.createObjectNode();`  initialize a empty  objectNode, `bodyParams` if not input anything , it works
```java
 private void setMsgInRequestBody(String msg) {
        try {
            ObjectNode objectNode = JSONUtils.createObjectNode();
            if(StringUtils.isNotBlank(bodyParams)){
                 objectNode = JSONUtils.parseObject(bodyParams);
            }
            // set msg content field
            objectNode.put(contentField, msg);
            StringEntity entity = new StringEntity(JSONUtils.toJsonString(objectNode), DEFAULT_CHARSET);
            ((HttpPost) httpRequest).setEntity(entity);
        } catch (Exception e) {
            log.error("send http alert msg  exception : {}", e.getMessage());
        }
    }
```

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Please rebase the upstream dev branch.

**Comment by zhaifb** [comment]
> Please rebase the upstream dev branch.

thinks
I've rebase it

**Comment by zhaifb** [comment]
Can this be merged ?  

What else do I need to do

**Comment by fuchanghai** [comment]
@SbloodyS plz run CI

**Comment by SbloodyS** [comment]
> @SbloodyS plz run CI

Done.

**Comment by zhaifb** [comment]
@SbloodyS @fuchanghai  tks.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by SbloodyS** [comment]
Thanks for your contribution. This is a good beginning. Considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(SbloodyS), when mail or added, please tell me who you are. I think I can help to familiar with the Dolphinscheduler if you meet with problems. @kingbabingge

**Pull request merged**
