### PR TITLE
[Doc][ALERT-12555] submit Slack docs

### LINKED ISSUE #12555: [Doc][ALERT] Missing Slack alert doc
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Missing Slack alert doc

### Documentation Links

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/alert/enterprise-webexteams.html

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

submit Slack docs
close https://github.com/apache/dolphinscheduler/issues/12555

## Brief change log

submit Slack docs

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Change LGTM, but Image check failed and it found not to use img with name `/img/new_ui/dev/alert/alert_slack_enable.png`, can you check whether we should use it in our docs, or remove it if not used? @Tianqi-Dotes

**Comment by Tianqi-Dotes** [comment]
> Change LGTM, but Image check failed and it found not to use img with name `/img/new_ui/dev/alert/alert_slack_enable.png`, can you check whether we should use it in our docs, or remove it if not used? @Tianqi-Dotes

Dear Jiajie,
Have added the 'enable' image to the docs. Please help review again.

**Comment by zhongjiajie** [comment]
Restart the failed test

**Review by caishunfeng — APPROVED** [review]
+1

**Pull request merged**
