### PR TITLE
Setting up test for alert-api starting with testing AlertResult Class

### PR DESCRIPTION
**Pull request by netemadi**
## Purpose of the pull request
This pull request will add new test cases to test AlertResult class from alert-api

## Brief change log
No change log

## Verify this pull request
This change is adding new test cases using JUnit, and can be run simply by running tests cases.

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by kezhenxu94 — COMMENTED** [review]
Hi, what's the point to add this test case?

**Comment by netemadi** [comment]
Hi @kezhenxu94 , The purpose of adding these tests is to expand the test coverage in this application and to test different classes for their functionalities.

**Comment by kezhenxu94** [comment]
> Hi @kezhenxu94 , The purpose of adding these tests is to expand the test coverage in this application and to test different classes for their functionalities.

We don't blindly chase test coverage. The test here is basically testing some generated codes (equals, hascode), which I don't think is necessary, if you are interested in adding test, please consider add other meaningful tests

**Comment by SbloodyS** [comment]
> > Hi @kezhenxu94 , The purpose of adding these tests is to expand the test coverage in this application and to test different classes for their functionalities.
> 
> We don't blindly chase test coverage. The test here is basically testing some generated codes (equals, hascode), which I don't think is necessary, if you are interested in adding test, please consider add other meaningful tests

I agreed with @kezhenxu94 . I will close this PR. Looking forward to your new contribution.

**Pull request closed without merging**
