### PR TITLE
[Feature-3649][server/ui] flink sql support for FlinkTask 

### PR DESCRIPTION
**Pull request by CycloneBoy**
## Purpose of the pull request

 flink sql support for FlinkTask   

## Brief change log

- ProgramType.class  add sql type
- FlinkTask.class and FlinkArgsUtils.class add main logical for support flink sql command 
- ResourceInfo.class add the isValid function for check the resource
- Flink.vue  add some logical for support flink sql command 

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, can you add related UT to cover this modification?

**Comment by CycloneBoy** [comment]
> hi, can you add related UT to cover this modification?

yes,i will add later.

**Comment by chengshiwen** [comment]
I will review it later

**Comment by Aer1208** [comment]
Do you want to merge this function into the master version? We also plan to base it on 1.3.8 implements this function. Where can I see all your code, thks.

**Comment by CycloneBoy** [comment]
> Do you want to merge this function into the master version? We also plan to base it on 1.3.8 implements this function. Where can I see all your code, thks.

I see the code conflicts, I will update the code again this weekend

**Comment by songjianet** [comment]
Thank you for your contribution, but since this issue has not been dealt with for a long time, I will close it. If you still have problems in the future, you can re-submit a new issue.

**Pull request closed without merging**
