### PR TITLE
fix: when sudo enable is false, execute command will failed

### LINKED ISSUE #13876: [Bug] [dolphinscheduler-task-api] when sudo enable is false, execute command will failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when sudo enable is false, the tenant doesn't have sudo permission, execute command will failed. The error info is
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization

### What you expected to happen

When the tenant doesn't have sudo permission, execute command will failed.  While set api-server/conf/common.properties and worker-server/conf/common.properties sudo.enable = false,  the execute command should not append "sudo -u" string.

### How to reproduce

When the tenant doesn't have sudo permission, the worker server is stopping cause by some reason， then the worker will disconnected and kill all running tasks

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huangxinan1990**
fix #13876 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Would you please link your PR to your issue? @huangxinan1990

**Comment by huangxinan1990** [comment]
@SbloodyS has already add the issue

**Review by rickchengx — APPROVED** [review]
LGTM, please check the CI

**Comment by huangxinan1990** [comment]
@SbloodyS @caishunfeng @zhuangchong please help to review, thanks

**Review by zhuangchong — APPROVED** [review]

**Pull request merged**
