### PR TITLE
Remove datasource in procedure task

### LINKED ISSUE #13197: [Bug] [ProceducerTask] Remove datasource in procedure task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Right now, we use datasource in procedure task, this will cause we cannot use TEMPORARY TABLE in procedure, since the temporary table will be release after the connection session close. But in datasource the session will not be closed, so the temporary will be share in different task.

### What you expected to happen

xx

### How to reproduce

In different task call the procedure.
```
CREATE PROCEDURE `temporary_table`()
BEGIN
    CREATE TEMPORARY TABLE str_spilt_result
    (
        id BIGINT(20) NOT NULL
    );
    SELECT * from str_spilt_result;
END;
```

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #13197 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by gabry-lab** [comment]
@ruanwenjun  To avoid using connections from thread pool? create a separated connection in each task?

**Comment by caishunfeng** [comment]
> @ruanwenjun To avoid using connections from thread pool? create a separated connection in each task?

Yes, you can see the issue description.

**Comment by caishunfeng** [comment]
@ruanwenjun Can we add this pr as an improvement? Will this change affect the existing usage?

**Comment by gabry-lab** [comment]
> > @ruanwenjun To avoid using connections from thread pool? create a separated connection in each task?
> 
> Yes, you can see the issue description.

Is it possible to create too many connections if there are lots of tasks?

**Comment by ruanwenjun** [comment]
> > > @ruanwenjun To avoid using connections from thread pool? create a separated connection in each task?
> > 
> > 
> > Yes, you can see the issue description.
> 
> Is it possible to create too many connections if there are lots of tasks?

Yes, this will need to create connection for each processdure task, but right now, I don't find other solution. Since the temporary table is bound to the session, if we don't close the session the temporary will always exist.

**Comment by ruanwenjun** [comment]
> @ruanwenjun Can we add this pr as an improvement? Will this change affect the existing usage?

Ok, I add improvement label(But this is more like BUG :) ), this PR will not affect the current usage

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by gabry-lab** [comment]
> > > > @ruanwenjun To avoid using connections from thread pool? create a separated connection in each task?
> > > 
> > > 
> > > Yes, you can see the issue description.
> > 
> > 
> > Is it possible to create too many connections if there are lots of tasks?
> 
> Yes, this will need to create connection for each processdure task, but right now, I don't find other solution. Since the temporary table is bound to the session, if we don't close the session the temporary will always exist.

If we can't find another solution, then current  is the best one. Too many connections for a DB is a disaster absolutely, dropping a temporary table is just a flaw.

**Comment by ruanwenjun** [comment]
> > > > > @ruanwenjun To avoid using connections from thread pool? create a separated connection in each task?
> > > > 
> > > > 
> > > > Yes, you can see the issue description.
> > > 
> > > 
> > > Is it possible to create too many connections if there are lots of tasks?
> > 
> > 
> > Yes, this will need to create connection for each processdure task, but right now, I don't find other solution. Since the temporary table is bound to the session, if we don't close the session the temporary will always exist.
> 
> If we can't find another solution, then current is the best one. Too many connections for a DB is a disaster absolutely, dropping a temporary table is just a flaw.

This is a bug, will cause the procedure task cannot use, the temporary table is shared by multiple task,  if you create a template task in the procedure task, you will get an error, since there might already exist a temporary table with the same name created by another task.

**Comment by gabry-lab** [comment]
If user drop it manually, is it OK?

**Comment by ruanwenjun** [comment]
> If user drop it manually, is it OK?

It's OK for the temporary table if user drop in the end of procedure task, but we cannot make sure all user will drop their temporary table in their procedure task.

**Pull request merged**
