### PR TITLE
[Fix] Parameter values disappear when editing Zeppelin task

### LINKED ISSUE #11102: [Bug] [Task Plugin] Parameter values disappear in UI when editing Zeppelin task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

* If you define a zeppelin task then edit it again later, values disappear in UI.

### What you expected to happen

* The values of zeppelin task parameters such as `noteId`, `paragraphId` shouldn't disappear when editing if you have filled it previously.
* There is probably a bug in the front-end but I couldn't find it, hope someone familiar with the front-end could help.

### How to reproduce

* Create a zeppelin task, save it and edit it again.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pinkhello**
## Purpose of the pull request

closed #11102 

## Brief change log

- * dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts *
- * dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-zeppelin.ts *

## Verify this pull request
This pull request is fix issue without any test coverage.

### CODE REVIEW

**Comment by pinkhello** [comment]
@songjianet @Amy0104  CR， Please

**Comment by EricGao888** [comment]
Hi @pinkhello , thanks for the fix! I'm not familiar with the front-end, just curious, why changing the field name could fix it? Was it because the previous field name too long?

**Comment by pinkhello** [comment]
> Hi @pinkhello , thanks for the fix! I'm not familiar with the front-end, just curious, why changing the field name could fix it? Was it because the previous field name too long?

No, as the case described by Issue, it is because the value-bound field is inconsistent with the display field

**Comment by EricGao888** [comment]
> > Hi @pinkhello , thanks for the fix! I'm not familiar with the front-end, just curious, why changing the field name could fix it? Was it because the previous field name too long?
> 
> No, as the case described by Issue, it is because the value-bound field is inconsistent with the display field

Got it, thx for the explanation.

**Comment by pinkhello** [comment]
> > > Hi @pinkhello , thanks for the fix! I'm not familiar with the front-end, just curious, why changing the field name could fix it? Was it because the previous field name too long?
> > 
> > 
> > No, as the case described by Issue, it is because the value-bound field is inconsistent with the display field
> 
> Got it, thx for the explanation.

YAW

**Comment by pinkhello** [comment]
> > > Hi @pinkhello , thanks for the fix! I'm not familiar with the front-end, just curious, why changing the field name could fix it? Was it because the previous field name too long?
> > 
> > 
> > No, as the case described by Issue, it is because the value-bound field is inconsistent with the display field
> 
> Got it, thx for the explanation.

github action ci always fails

**Comment by EricGao888** [comment]
@pinkhello I've restarted the CI.

**Comment by zhongjiajie** [comment]
@EricGao888 Can we merge this PR? Or we still need @songjianet @Amy0104 to take a look again?

**Review by EricGao888 — APPROVED** [review]
@zhongjiajie I've tested the patch locally and it worked well. Bug fixed. Thx @pinkhello

**Comment by zhongjiajie** [comment]
> @zhongjiajie I've tested the patch locally and it worked well. Bug fixed. Thx @pinkhello

Thanks both @pinkhello and @EricGao888

**Pull request merged**
