### PR TITLE
[API] [bug] dependent task need regenerate up-stream code when import

### LINKED ISSUE #15493: [Bug] [Api] The up-stream process and task is shown error when import a dependent task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When import a dependent task from a Json file in a new environment that export by a old environment, the import operation is success, but you will get error message like "**get task list by process definition id error**", when you open the detail page about the import dependent task.
Following is the error screenshot:

### What you expected to happen

After importing a dependent task from Json file, the up-stream process and task should link properly.

### How to reproduce

Import from the example Json file, and open the detail page of the dependent task of llow3 in the api ui, you will see some error message which show the up-stream process and task not link properly.
[workflow_1705391814549.json](https://github.com/apache/dolphinscheduler/files/13947590/workflow_1705391814549.json)

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xiaolailong**
## Purpose of the pull request

When import a dependent task from json file, the up-stream code of process and task is not re-generated, which cause the import error. (The import operation return success, but when you open the detail of dependend task, it will show many error message like: "can not found process definition")

fix https://github.com/apache/dolphinscheduler/issues/15493

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please link this pr to your issue. @xiaolailong

**Comment by xiaolailong** [comment]
> Please link this pr to your issue. @xiaolailong

Thank you for reminding！There is no relevant issue, should I create one?

**Comment by xiaolailong** [comment]
> Please link this pr to your issue. @xiaolailong

issue is #15493

**Comment by fuchanghai** [comment]
@xiaolailong plz run 'mvn spotless:apply' to fix these violations.

**Comment by fuchanghai** [comment]
hi @SbloodyS  plz check #14956 
image
Importing ```subprocess```, ```condition```, ```switch```, and ```dependcy``` is actually a type of problem. do we need to split it into multiple PRs to do it? . cc @EricGao888 @chenshuai1995 @ruanwenjun

**Comment by SbloodyS** [comment]
> Importing `subprocess`, `condition`, `switch`, and `dependcy` is actually a type of problem.

Thanks. I overlooked some potential issues. I've replyed in https://github.com/apache/dolphinscheduler/pull/14956#issuecomment-1894991875.

**Comment by xiaolailong** [comment]
> @xiaolailong plz run 'mvn spotless:apply' to fix these violations.

Thank you for guideline! already done.

**Comment by rickchengx** [comment]
@xiaolailong Thanks for your contributions. Maybe we should also regenerate the task code when import other task types, such as SUB_PROCESS and CONDITIONS, what do u think? Can this replacement be done in a uniform way?

**Pull request closed without merging**
