### PR TITLE
[Bug] fail-fast for dependent check

### PR DESCRIPTION
**Pull request by Dyqer**
## Purpose of the pull request
Refer  #15229 
If the upstream process instance is failed, the result will be cached and won't be update, so we should return failed immediately and finish the dependent task

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please link this PR to your issue. @Dyqer

**Comment by Dyqer** [comment]
> Please link this PR to your issue. @Dyqer
@SbloodyS link #15229

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by Dyqer** [comment]
@ruanwenjun @zhuangchong can you help review?

**Pull request merged**
