### PR TITLE
[Fix-12425][API] Add rollbackFor setting.

### LINKED ISSUE #12425: [Bug] [API] If Storge exception, ds can create tenant, but show cannot.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we create a new tenant, but storge has some exception such as connect refuse. The UI alert will show create tenant failed, but it will be created in DB and can show in UI. And then use cannot delete this wrong tenant, because cannot delete it in storge.
But due to my PC env, i cannot show the screenshot. But we can check the source code.
**_Create:_** 
image
 **_Delete:_**
image

### What you expected to happen

If db or storge has exception, ds cannot create a tenant.

### How to reproduce

1. Config the `resource.storage.type=HDFS`
2. Create a new tenant
3. Delete this new tenant.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

+ This PR will close: #12425 
Please check the `@Transactional` comment. Becuase `@Transactional` just will rollback on `RuntimeException` and `Error` but not on `checked exceptions`. To roll back checked exception, we need to specify the `rollbackFor`
image

🙋 Next i will double check all the `@Transactional`

## Brief change log

+ Specify the `rollbackFor`
+ Clear some comments.

## Verify this pull request

This pull request is already covered by existing tests

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Good catch, at default the `@Transactional ` will only rollback when meet `unchecked exception and error`, if we set `@Transactional=ExceptionA.class` it will rollback for `ExceptionA`, `unchecked exception` and error.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by ruanwenjun** [comment]
@DarkAssassinator Please rebase the upstream to fix the ci.

**Comment by DarkAssassinator** [comment]
> @DarkAssassinator Please rebase the upstream to fix the ci.

Sure, done, and wait CI finish.

**Review by ruanwenjun — APPROVED** [review]

**Pull request merged**
