### PR TITLE
[fix][UI][bug]Add render to projects-overview table

### PR DESCRIPTION
**Pull request by imizao**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please associate the issue and describe why you want to do that. Thanks.

**Comment by imizao** [comment]
[[fix][Bug] [dolphinscheduler-ui] List number not rendered #13306
](https://github.com/apache/dolphinscheduler/issues/13306)

**Comment by davidzollo** [comment]
@devosend please take a look at this PR, thx

**Review by devosend — APPROVED** [review]
LGTM

**Pull request merged**
