### PR TITLE
[Fix-15644][ui] fix ui Failed to query list after editing file

### LINKED ISSUE #15644: [Bug] [API] edit file in resource center and do nothing exit will recive err
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

i open a file in resource center ,and do nothing ,press exit button,then i will recive an error.
pay attention,the file is not created by me,but the createror 's tenant is same as me,and we are admin in ds
企业微信截图_5a07b441-0f27-4320-9db3-1340d7c79102

### What you expected to happen

the file `s creater is same as me as a admin,and we have same tenant ,so i have right,there is no reason to get this err

### How to reproduce

1.give user A and user B admin right by change database,t_ds_user table ,user_type coulme.
2.give user A and B the same tenant
3.A create a file,and B open it ,do nothing just exit
4.we weill recive a ok msg,and a err msg
企业微信截图_cace0c13-6fdf-40cc-a361-db93d645a0d3

### Anything else

1.i read the source code  and log
2.and i comparison the good request and bad requeest,i find the bug is about fullName
3.the good request is:xxxxxx/dolphinscheduler/resources?fullName=&tenantCode=&type=FILE&searchVal=&pageNo=2&pageSize=10
4.if you do the reproduce step ,you will caughe bad request:xxxxx/dolphinscheduler/resources?fullName=work&tenantCode=&type=FILE&searchVal=&pageNo=1&pageSize=10
5.if u cut the fullName's value in bad request you will get right response
6.i try to debug,but sorry i just can`t,the backed is good i think,probbly is fronted
image

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by bajiaolong**
fix: #15644

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by songjianet — CHANGES_REQUESTED** [review]
image

**Review by songjianet — DISMISSED** [review]

**Review by SbloodyS — DISMISSED** [review]
+1

**Review by rickchengx — DISMISSED** [review]

**Review by rickchengx — COMMENTED** [review]
@bajiaolong please check the CI error

**Comment by bajiaolong** [comment]
> @bajiaolong please check the CI error

Sorry, I don't know which one to solve. can you help me?

**Comment by rickchengx** [comment]
> > @bajiaolong please check the CI error
> 
> Sorry, I don't know which one to solve. can you help me?

image
@bajiaolong 
cc @songjianet @c3Vu @arlendp I am also not familiar with front-end, please help

**Comment by arlendp** [comment]
> > > @bajiaolong please check the CI error
> > 
> > 
> > Sorry, I don't know which one to solve. can you help me?
> 
> image @bajiaolong cc @songjianet @c3Vu @arlendp I am also not familiar with front-end, please help

This CI build error seems to has nothing to do with this commit. It is the execution of eslint --fix in the CI process that caused the code formatting error.

**Comment by SbloodyS** [comment]
This will be fixed after this pr is merged. #15732 @bajiaolong

**Comment by bajiaolong** [comment]
> This will be fixed after this pr is merged. #15732 @bajiaolong

RECD

**Comment by rickchengx** [comment]
@bajiaolong it seems CI cannot pass
image

**Review by SbloodyS — APPROVED** [review]

**Comment by SbloodyS** [comment]
@rickchengx @ruanwenjun @EricGao888 PTAL.

**Comment by EricGao888** [comment]
> @rickchengx @ruanwenjun @EricGao888 PTAL.

I'm not familiar with front-end stuff. Would u plz take a look? @arlendp @c3Vu

**Review by rickchengx — APPROVED** [review]
+1

**Pull request merged**
