### PR TITLE
[fix-10386]LDAP user create with status enable

### LINKED ISSUE #10386: [Bug] [dolphinscheduler-api] When connecting to ldap, ldap users cannot log in
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当配置 conf/application-api.properties 为ldap认证时

```
security.authentication.type=LDAP
ldap.urls=ldap://xx.xx.xx.xx:389
ldap.base.dn=cn=users,cn=accounts,dc=hadoop,dc=com
ldap.username=cn=Directory Manager
ldap.password=xxxx
ldap.user.identity.attribute=uid
ldap.user.email.attribute=mail
```

image

### What you expected to happen

报错是用户停用，查询数据库发现 
```
           id: 2
    user_name: user1
user_password: NULL
    user_type: 1
        email: user1@hadoop.com
        phone: NULL
    tenant_id: 0
  create_time: 2022-06-08 11:01:43
  update_time: 2022-06-08 11:01:43
        queue:
        state: 0
```

state状态为0

代码中创建从ladp读取的用户state默认都是0，这样对接ladp后，ladp中的用户仍然不能登录

### How to reproduce

操作如上，配置任何ladp均会出现上述现象。

### Anything else

_No response_

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qingwli**
close #10386 

~~I'll add LDAP login test later~~ Done

part of #10425

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@lenboo This PR still need to cherry-pick to 2.0.6 too, when you finish cherry pick to 300b2, please change milestone to 2.0.6

**Comment by zhongjiajie** [comment]
LGTM, please take a look @caishunfeng

**Comment by zhongjiajie** [comment]
Is this PR ready to go now? @liqingwang

**Comment by qingwli** [comment]
Yes @zhongjiajie

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by qingwli** [comment]
Hi @zhongjiajie  This PR has cherry-picked to 300b2, and still needs to cherry-pick to 2.0.6 too

**Comment by caishunfeng** [comment]
> Hi @zhongjiajie This PR has cherry-picked to 300b2, and still needs to cherry-pick to 2.0.6 too

@liqingwang can you cherry-pick this pr to 2.0.6? and I will add the milestone for it.

**Comment by zhongjiajie** [comment]
> Hi @zhongjiajie This PR has cherry-picked to 300b2, and still needs to cherry-pick to 2.0.6 too

Thanks for you bring this up

**Comment by qingwli** [comment]
> > Hi @zhongjiajie This PR has cherry-picked to 300b2, and still needs to cherry-pick to 2.0.6 too
> 
> Thanks for you bring this up

I have cherry-picked this pr to #10508 and merged it into the 2.0.6 branch. Thanks @caishunfeng

**Pull request merged**
