### PR TITLE
[Improvement][Test] Remove Powermock in dolphinscheduler-task-plugin

### LINKED ISSUE #12150: [Improvement][Test] Remove Powermock in dolphinscheduler-task-plugin
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Remove `Powermock` in `dolphinscheduler-task-plugin`
- This is a sub-task of #11405

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by stalary**
## Brief change log

Remove Powermock in dolphinscheduler-task-plugin

This pr will close https://github.com/apache/dolphinscheduler/issues/12150

### CODE REVIEW

**Comment by EricGao888** [comment]
@stalary Looks like the errors come from `EmrAddStepsTaskTest`

image

**Comment by stalary** [comment]
> @stalary Looks like the errors come from `EmrAddStepsTaskTest`
> 
> image

done.

**Review by EricGao888 — APPROVED** [review]
LGTM as long as CI passes

**Comment by EricGao888** [comment]
If no more comments, I will proceed to merge this PR : )

**Pull request merged**
