### PR TITLE
[BUG#7086]Fix binary package sql file path error

### LINKED ISSUE #7086: [Bug][Package]  binary package sql file path error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

binary package sql file path error 

image

### What you expected to happen

image

### How to reproduce

package

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CalvinKirs**
image
fix #7086

### CODE REVIEW

**Review by lenboo — APPROVED** [review]
+1

**Comment by kezhenxu94** [comment]
This is actually intentional because we need the same path structure in IDE and in distributed package, in IDE the class path is relative to `src/resource` so we can access these sql files via `classpath:sql/....` but in distributed package, the class path is `download/path/sql`. we can modify the class path to `download/path` in distributed package but that includes too many unnecessary contents

**Comment by CalvinKirs** [comment]
> This is actually intentional because we need the same path structure in IDE and in distributed package, in IDE the class path is relative to `src/resource` so we can access these sql files via `classpath:sql/....` but in distributed package, the class path is `download/path/sql`. we can modify the class path to `download/path` in distributed package but that includes too many unnecessary contents

image
But when I executed sh script/create-dolphinscheduler.sh after the binary package was packaged, he reported an error. Did I do something wrong?

**Comment by kezhenxu94** [comment]
@CalvinKirs do you use 2.0.1-prepare? it is missing 

https://github.com/apache/dolphinscheduler/blob/100a9ba3fc21764158593bd33e2b261b0ef39982/script/create-dolphinscheduler.sh#L31

and 

https://github.com/apache/dolphinscheduler/blob/100a9ba3fc21764158593bd33e2b261b0ef39982/script/create-dolphinscheduler.sh#L38

**Comment by CalvinKirs** [comment]
> @CalvinKirs do you use 2.0.1-prepare? it is missing
> 
> https://github.com/apache/dolphinscheduler/blob/100a9ba3fc21764158593bd33e2b261b0ef39982/script/create-dolphinscheduler.sh#L31
> 
> and
> 
> https://github.com/apache/dolphinscheduler/blob/100a9ba3fc21764158593bd33e2b261b0ef39982/script/create-dolphinscheduler.sh#L38

Sorry i missed this, thank you

**Pull request closed without merging**
