### PR TITLE
[Fix-10095][UI] fulfill missing fields in DataQuality

### LINKED ISSUE #10095: [Bug] [UI] missing some fields in DataQuality task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in `DataQuality` module. different `Rule` has different form fields. some fields are missed to commit. so it can't reload when edit.

92f2b6f4d42d5d23bdf56bbd4a6ee79

f169d7bf61bab78b8e6f41ccb0993d1
1ca00033eaaf4a19ea094253f4f9e5b
14dea22da51026f12e477108ba5efb5
fa4aeeb7615b6aedb611dc219cab182

### What you expected to happen

expect to reload the missed form fields data when edit DataQality task

### How to reproduce

1. create a DataQuality task
2. choose the rule showed above
3. input fields and save.
4. edit the created task again

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rockfang**
## Purpose of the pull request
close [#10095 ](https://github.com/apache/dolphinscheduler/issues/10095)
## Brief change log
add missed fields in DataQuality task
## Verify this pull request
This pull request is code cleanup without any test coverage.
here is one fixed screenshot：
7537a564a6b2f780342420bcbeb8bd5

### CODE REVIEW

**Review by labbomb — APPROVED** [review]
LGTM

**Review by Amy0104 — APPROVED** [review]
LGTM

**Comment by songjianet** [comment]
Please rebase to 3.0.0-beta-prepare branch. @rockfang

**Comment by rockfang** [comment]
> Please rebase to 3.0.0-beta-prepare branch. @rockfang

@songjianet . A new PR is available. I hope I did it in the right way

**Pull request merged**
