### PR TITLE
[Feature][StandaloneServer] Fix some problems exist in Standalone Server 

### LINKED ISSUE #6091: [Bug][dolphinscheduler-standalone-server] StandaloneServer run failed on Windows system
Since the directory separator is not the same for different operating systems, reading the pom.xml file of registry in Windows system fails.
The error message is as follows :
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: ../dolphinscheduler/dolphinscheduler-standalone-server/target/classes/\../../../dolphinscheduler-registry-plugin/dolphinscheduler-registry-zookeeper/pom.xml
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.apache.dolphinscheduler.server.StandaloneServer.main(StandaloneServer.java:75)
```

### LINKED ISSUE #6713: [Feature][StandaloneServer] Ensure that the Standalone Server restarts using the same data file
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Standalone Server is a great idea, but is has two problems can be imporved: 
+ Each time when you start a StandaloneServer, a random temporary directory would be created, which actually has no meaning
llike below, standaloneserver create a directory： dolphinscheduler_1109196593964124306, but the db data file: dolphinscheduler_11091965939641243069.mv.db was not in directory dolphinscheduler_1109196593964124306 
```shell
16:51:05.054 [Standalone-Server] INFO org.apache.dolphinscheduler.server.StandaloneServer - H2 database directory: C:\Users\echoh\AppData\Local\Temp\dolphinscheduler_11091965939641243069
```
image
+ After each time restart, it would import the init-sql script again. As a result, the previously configured data would be loss.
image

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by echohlne**
## Purpose of the pull request
1. normalize the absolute path to ensure the standaloneserver can be run in windows os. close #6091 
2. ensure the h2 db should not update when Standalone restarts. close #6713

## Brief change log
1. normalize the absolute path to ensure the standaloneserver can be run in windows os.  
2. ensure the h2 db should not update when Standalone restarts.

## Verify this pull request

This pull request is already covered by existing tests

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Check my comments in https://github.com/apache/dolphinscheduler/issues/6713

I'm -1 to the changes because reusing in-memory database is not our expected use case.

**Comment by echohlne** [comment]
Thanks @kezhenxu94 
I understand what you said, should we consider that standaloneserver only provides limited functions?
At this stage, if you use standaloneserver with HDFS service, you will be in troubled. After you create a tenant or upload a file, the page is invisible after restarting, which is actually very inconvenient to use.

**Comment by kezhenxu94** [comment]
> At this stage, if you use standaloneserver with HDFS service, you will be in troubled. After you create a tenant or upload a file, the page is invisible after restarting

Hi @huagkunlun thanks for the scenario, can you elaborate why you need to restart standalone server when you  use HDFS service?

**Comment by echohlne** [comment]
I originally wanted to do some function enhancements of the resource center in the webpage based on the standalone server.   

Once it restarted, the HDFS data record  stored in the built-in database was lost, which really troubled me a lot.

At present, standaloneserver  seems is more suitable for debugging some stateless crud functions.....

Thanks @kezhenxu94  I would try to use the traditional way to continue my work.

**Comment by kezhenxu94** [comment]
@huagkunlun I admit that currently standalone server is not full feature because of some historical tech debt and I'm still optimizing to make it full-featured. Sorry for that you have to use a traditional way to continue your work 🙇

**Comment by echohlne** [comment]
Looking forward your great work!
btw is the temporary dir and related data file location works as expected ?
I guess you want to create a random temp dir and the data file stored in the temp dir, but now  the temp dir seems has no meaning.
image

**Comment by kezhenxu94** [comment]
> Looking forward your great work!
> btw is the temporary dir and related data file location works as expected ?
> I guess you want to create a random temp dir and the data file stored in the temp dir, but now the temp dir seems has no meaning.
> image

Yeah good catch, the db file should be inside the temp directory, could you open a pull request to fix this ?

**Comment by echohlne** [comment]
> > Looking forward your great work!
> > btw is the temporary dir and related data file location works as expected ?
> > I guess you want to create a random temp dir and the data file stored in the temp dir, but now the temp dir seems has no meaning.
> > image
> 
> Yeah good catch, the db file should be inside the temp directory, could you open a pull request to fix this ?

I will submit a new pr to fix this.

**Pull request closed without merging**
