### PR TITLE
[Improvement#5741][Worker] Improve task process status log 

### LINKED ISSUE #5741: [Improvement][Worker] Improve task process status log
**Describe the question**
In the AbstractCommandExecutor, after the task process executed, it will log the status.
We need to move the log from line 206 to line 227, the `result.getExitStatusCode()` is always 0, because we did not assign value.
https://github.com/apache/dolphinscheduler/blob/2ba569acd028c00c22f4853de7c58251ac72816c/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java#L157-L206

**Which version of DolphinScheduler:**
 -[1.3.6]
 -[dev]

### PR DESCRIPTION
**Pull request by tanvimoharir**
## Purpose of the pull request

this closes #5741 

<!-Move logger statement*.-->

## Brief change log
- *Move logger statement*

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by tanvimoharir** [comment]
Closes #5741

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
Deeply thanks for your contribution, this is a good beginning, considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by tanvimoharir** [comment]
> Deeply thanks for your contribution, this is a good beginning, considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

Thanks @CalvinKirs I will reach out :)

**Pull request merged**
