### PR TITLE
[1.3.6-prepare][Improvement][Common] Optimize HashMap Initial Capacity #4896

### PR DESCRIPTION
**Pull request by CalvinKirs**
pr :#4896

### CODE REVIEW

**Comment by zhuangchong** [comment]
+1

**Comment by lenboo** [comment]
which  issue does this pr refer to ?

**Comment by chengshiwen** [comment]
> which issue does this pr refer to ?

pr #4896
no issue

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
