### PR TITLE
[1.3.7] Update soft version to 1.3.7

### PR DESCRIPTION
**Pull request by Eights-Li**
## Purpose of the pull request

this pr modify ds version to 1.3.7 deal with when upgrade ds from 1.3.6 to 1.3.7,  the t_ds_version table still 1.3.6

## Brief change log

- *modify soft_version file*

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
ambari also needs to be upgraded, can you complete it?

**Comment by Eights-Li** [comment]
> ambari also needs to be upgraded, can you complete it?

ok

**Comment by chengshiwen** [comment]
@Eights-Li Please refer to https://dolphinscheduler.apache.org/en-us/community/release-prepare.html

**Review by CalvinKirs — APPROVED** [review]
Due to time constraints, I will merge this PR and I will start a new PR for the remaining work

**Pull request merged**
