### PR TITLE
[Doc-16375] change front build command

### LINKED ISSUE #16375: [Doc][UI] The command to build the front in the document ran incorrectly
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

An error was reported when using the npm run build command to build the front end, but the build configuration was not found in the front end's package.json. The build command used in pom is pnpm run build: prod. The documentation should not be modified

### Documentation Links

docs/docs/en/contribute/frontend-development.md
docs/docs/zh/contribute/frontend-development.md

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ThomasTan2002**
## Purpose of the pull request

close #16375

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — CHANGES_REQUESTED** [review]
This is not a Chore. Please follow the pull request notice create an improvement or document issue and link to this PR.

**Comment by ThomasTan2002** [comment]
@EricGao888 @SbloodyS 
Thanks for review it at your convenience.

**Comment by ThomasTan2002** [comment]
> This is not a Chore. Please follow the pull request notice create an improvement or document issue and link to this PR.

OK

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by wangxj3 — APPROVED** [review]
LGTM

**Pull request merged**
