### PR TITLE
[Fix-#6779] add default constructor

### PR DESCRIPTION
**Pull request by zwZjut**
## Purpose of the pull request

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of org.apache.dolphinscheduler.api.utils.PageInfo (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

https://github.com/apache/dolphinscheduler/issues/6779

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zwZjut** [comment]
@licongyang

**Comment by zhongjiajie** [comment]
Good job! Code look good to me, waiting for CI

**Review by CalvinKirs — APPROVED** [review]
Good Job

**Comment by zhongjiajie** [comment]
Hi @zwZjut , thanks for your contribution and welcome to join community 🎉 . If you want contribute but could not find issue, maybe you could start in #5689 or just search our issue list https://github.com/apache/dolphinscheduler/issues. Looking forward to your next contribution

**Pull request merged**
