### PR TITLE
[Fix-5699][UI] Fix update user error in user information

### LINKED ISSUE #5699: [Bug][UI] Update user error in user information
**To Reproduce**

User Infomation Page-> Click Edit Buttom  -> popup Edit User Dalog -> Click Edit Button to finish the edit action.

**Expected behavior**
Bug fixed

**Screenshots**
image

**Which version of Dolphin Scheduler:**
 -[1.3.6]
 -[dev]

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

*[Fix-5699][UI] Fix update user error in user information*

This fixes #5699, and fixes the problem introduced by #5627

## Brief change log

  - *Fix update user error in user information*
  - *Sync user info by `this.setUserInfo(param)`*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by CalvinKirs** [comment]
please take a look,thx @zhuangchong

**Review by myangle1120 — APPROVED** [review]

**Review by myangle1120 — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by echohlne** [comment]
@chengshiwen  @CalvinKirs @myangle1120 Sorry to bother you guys.
+ this PR is supposed to solve the problem introduced in #5627, sorry I'm not sure What problem was introduced in #5627? 
I have tried to reproduce the screenshot menshoned in Issue#5699, but I can't reproduce it, it's a little strange. Can you tell me what problem was introduced @chengshiwen ,I want to know what had happend  so I can avoid similar mistakes in the future。

+ **In addition, I personally think that the current PR introduces a new problem: if we create a new user using admin, such as test, after successfully creating,  the current logged-in user displayed in the top right corner of the page will be updated to the current newly created user,** you can see my screenshot based on the latest code of dev:  

1. try to add a new user named test, now the username of current user is admin.  

image  

2. after the user has been created,  the username of current user changes from admin to test.  

image

**Comment by chengshiwen** [comment]
@kyoty @CalvinKirs Sorry, introducing the second problem is my mistake, and I have submitted a repaired pr #5735

For the 1st problem, the following lines will cause a tenant named `0` to appear, which is not right. So the solution of the previous pr #5627 needs to be reimplemented

https://github.com/apache/dolphinscheduler/blob/0a5670f1958bfca56f84e42c1e11bb3150abcb4b/dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue#L297
https://github.com/apache/dolphinscheduler/blob/0a5670f1958bfca56f84e42c1e11bb3150abcb4b/dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue#L316

A tenant named `0`
image

**Comment by echohlne** [comment]
@chengshiwen Thank you for your repair., I will pay more attention to enhance the test when I submit PR in the future.

**Pull request merged**
