### PR TITLE
[fix-13504] Display the current project name on the left corner of the page

### PR DESCRIPTION
**Pull request by QuantumXiecao**
## Purpose of the pull request

[fix-13504] Display the current project name on the left corner of the page.

Releated PR: #13504 

After fixing, the result would be as follows:
image

## Brief change log

[fix-13504] Display the current project name on the left corner of the page.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by QuantumXiecao** [comment]
image
@songjianet @Amy0104 Could you please do me a favour? This is my first PR. I do not see what this error means.

**Review by SbloodyS — COMMENTED** [review]
I think what this issue #13504 wants to express is to display the project name in the upper left corner of the page. I can't see the meaning of displaying it on the url.

**Comment by QuantumXiecao** [comment]
@SbloodyS I have updated my codes. And could you please help to label this issue for passing CI/CD's label check.
image

**Comment by SbloodyS** [comment]
> @SbloodyS I have updated my codes. And could you please help to label this issue for passing CI/CD's label check.

Done.

**Comment by QuantumXiecao** [comment]
image
@SbloodyS @songjianet @Amy0104 Sorry to disturb and I would like to know why it stuck here. Could you please help me out?

**Comment by Amy0104** [comment]
> 

I have rerun it.

**Review by Amy0104 — APPROVED** [review]
LGTM

**Pull request merged**
