### PR TITLE
[doc] Add the deployment document of kubernetes in non-helm mode 

### LINKED ISSUE #13569: [Doc][k8s-deploy] Add the deployment document of kubernetes in non-helm mode
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

At present, the production environment of many companies does not support helm deployment, because their environment does not allow connection to the external network. At this time, it is necessary to return to the deployment using the original k8s yaml resource, but the deployment documentation for this method is lacking. This is not friendly to the user experience of dolphinscheduler

### Documentation Links

Only the documentation of the helm method：

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/guide/installation/kubernetes

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qindongliang**
close https://github.com/apache/dolphinscheduler/issues/13569

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by EricGao888 — COMMENTED** [review]
CI style checks failed. Could u plz run `mvn spotless:apply` to fix these errors?

**Comment by qindongliang** [comment]
> 

ok let me try

**Comment by qindongliang** [comment]
@EricGao888 Mergeable: milestone-label-check  fail , how to fix it

**Comment by zhongjiajie** [comment]
> @EricGao888 Mergeable: milestone-label-check  fail , how to fix it 

never mind, it is for maintainer

**Review by kezhenxu94 — COMMENTED** [review]
Read through the doc it seems to be a very general-purpose guide to deploy Helm Chart deployments by generating manifests first and apply them. Kubernetes users should learn that from a general way like search engine or other blogs. Putting this guide in DolphinScheduler looks unreasonable, our doc is not Wikipedia to contain all stuffs

**Comment by qindongliang** [comment]
This is indeed part of the requirements, if you think it is unnecessary, I will close the pr

**Pull request closed without merging**
