### PR TITLE
[Improvement-16506][alert] Add retry send mail validAddresses

### PR DESCRIPTION
**Pull request by nelsontech**
## Purpose of the pull request

The content of this commit adjusts the email notification module so that when invalid email addresses are included among multiple recipients, it does not prevent all recipients from receiving emails. Instead, emails will continue to be delivered to the actual valid email addresses.

## Verify this pull request

This change added tests and can be verified as follows:

- email alert to user whose email address is valid, and add other email address which is invalid ,when send email alert, the valid email address will receive the email alert message

### CODE REVIEW

**Comment by SbloodyS** [comment]
Please follow the pull request notice. @nelsontech

**Comment by nelsontech** [comment]
> Please follow the pull request notice. @nelsontech

changed

**Comment by nelsontech** [comment]
@SbloodyS I changed, shoud be there anymore to change?

**Comment by SbloodyS** [comment]
> @SbloodyS I changed, shoud be there anymore to change?

You should create an issue first and link it to your pr and tittle.

**Comment by nelsontech** [comment]
@SbloodyS ok, thank you

**Pull request closed without merging**
