### PR TITLE
[BUG][UI] Flink task display right version and deploy mode

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
Existed flink task can not display the right flink version and deploy mode because the flink version is hard coded.

### Wrong display:
image

### Expected display:
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by luoyize** [comment]
fix use-flink.ts: 
`watchEffect(() => { if(model.programType === 'SQL'){ model.flinkVersion = '>=1.13' }else { if(model.flinkVersion === '>=1.13'){ model.flinkVersion = '<1.10' } } 
// model.flinkVersion = model.programType === 'SQL' ? '>=1.13' : '<1.10' })`

**Comment by devosend** [comment]
You should create an issue to describe this bug.

**Comment by Radeity** [comment]
Hi, @devosend , the description of UI bug is same as https://github.com/apache/dolphinscheduler/issues/13644, i've already added more explanation of this bug in the purpose of this pr, for not creating duplicated issue. Thanks for reminding, next time, i'll create an issue first.

**Comment by Radeity** [comment]
> fix use-flink.ts: `watchEffect(() => { if(model.programType === 'SQL'){ model.flinkVersion = '>=1.13' }else { if(model.flinkVersion === '>=1.13'){ model.flinkVersion = '<1.10' } } // model.flinkVersion = model.programType === 'SQL' ? '>=1.13' : '<1.10' })`

Hi, @chenss-1 , the fix in this pr works.

**Review by devosend — APPROVED** [review]
LGTM

**Pull request merged**
