### PR TITLE
 [Fix-4843] Rename WORKER_GROUP to WORKER_GROUPS (#4843)

### LINKED ISSUE #4843: [Bug][Docker] 1.3.5 release compose file config error WORKER_GROUP
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
The configuration item of compose startup file worker service is wrong, WORKER_GROUP here should be WORKER_GROUPS

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Lā qǔ 1.3.5-Release huòzhě zuìxīn jìngxiàng 2. Dǎkāi xiāngguān de docker-compose wénjiàn 3. Zhǎodào róngqì míng wèi dolphinscheduler-worker 4. Qízhōng de environment zhōng WORKER_GROUP, cǐ chù rúguǒ shì WORKER_GROUP bù qǐ zuòyòng, huì yòng mòrèn zhí. Yīng gǎi wèi WORKER_GROUPS
展开
161 / 5000
翻译结果
1. Pull 1.3.5-release or the latest image
2. Open the relevant docker-compose file
3. Find the container named dolphinscheduler-worker
4. WORKER_GROUP in the environment, if WORKER_GROUP does not work here, the default value will be used. Should be changed to WORKER_GROUPS 

**Expected behavior**

**Screenshots**

358411DB-C676-49bc-BBB2-F9BD89EE60A1

**Which version of Dolphin Scheduler:**
 -[1.3.5-release]

**Additional context**

**Requirement or improvement**
- Here to adjust to WORKER_GROUPS

### PR DESCRIPTION
**Pull request by wangdazhong001**
fix #4843

### CODE REVIEW

**Review by chengshiwen — CHANGES_REQUESTED** [review]
@wangdazhong001 Please search and replace all `WORKER_GROUP` to `WORKER_GROUPS` in `docker` directory, such as `docker/build/startup-init-conf.sh` and `docker/build/conf/dolphinscheduler/worker.properties.tpl` which need to be considered

**Review by chengshiwen — CHANGES_REQUESTED** [review]
@wangdazhong001 Please search and replace globally. There are still some files that have not been updated

**Review by chengshiwen — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Pull request merged**
