### PR TITLE
[Fix-7245] [API] Fix spelEvaluationException: EL1008E: Property or field 'all' cannot be found 

### LINKED ISSUE #7245: [Bug] [API] spelEvaluationException: EL1008E: Property or field 'all' cannot be found
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[ERROR] 2021-12-07 19:02:27.766 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[46] - 查询worker分组失败
org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'all' cannot be found on object of type 'org.springframework.cache.interceptor.CacheExpressionRootObject' - maybe not public or not valid?
  at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:217)
  at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104)
  at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:91)
  at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112)
  at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:272)
  at org.springframework.cache.interceptor.CacheOperationExpressionEvaluator.key(CacheOperationExpressionEvaluator.java:104)
  at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.generateKey(CacheAspectSupport.java:795)
  at org.springframework.cache.interceptor.CacheAspectSupport.generateKey(CacheAspectSupport.java:592)
  at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:379)
  at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
  at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
  at com.sun.proxy.$Proxy152.queryAllWorkerGroup(Unknown Source)
  at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl.getWorkerGroups(WorkerGroupServiceImpl.java:255)
  at org.apache.dolphinscheduler.api.service.impl.WorkerGroupServiceImpl.queryAllGroup(WorkerGroupServiceImpl.java:233)
```

### What you expected to happen

The query is normal

### How to reproduce

Query the list of workers

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this pr close #7245

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhuangchong** [comment]
@caishunfeng Please help review

**Comment by zhuangchong** [comment]
@lenboo

**Review by Narcasserun — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
