### PR TITLE
[Feature][Api] Refactor org.apache.dolphinscheduler.api.controller.QueueController

### LINKED ISSUE #11067: [Feature][Api] Refactor org.apache.dolphinscheduler.api.controller.QueueController
[[DSIP-7] [API] Suggest refactor the backend api](https://github.com/apache/dolphinscheduler/issues/10257#) #10257 

 ### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

 Refactor org.apache.dolphinscheduler.api.controller.QueueController

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tracehh**
Fix: #11067 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by tracehh** [comment]
@SbloodyS @caishunfeng PTAL, thx.

**Comment by tracehh** [comment]
@SbloodyS @caishunfeng  PTAL, thx.

**Comment by SbloodyS** [comment]
Hi @tracehh , please split the service part and the v2 controller/entity part into two PR based on the above conclusions in https://github.com/apache/dolphinscheduler/pull/10998#issuecomment-1207708303. Thanks.

**Comment by tracehh** [comment]
ok,split the service part and the v2 controller/entity @SbloodyS

**Review by caishunfeng — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
