### PR TITLE
[DSIP-66][k8s] Support User-customized K8s YAML Pod

### LINKED ISSUE #16482: [DSIP-66][k8s] YAML Pod for User Customization
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Supporting **user-customized K8s YAML Pod** has the following benefits:

- **Flexibility:** Unlike the existing K8s low-code job with limited functionality, YAML Pod provide users with the flexibility to define sophisticated task instances in DolphinScheduler, similar to how custom JSON does in DataX.

- **Workflow Customization:** Users can integrate operational and maintenance processes into DolphinScheduler using YAML Pod for complex workflows.

In short, by enabling user-customized YAML Pod, *DolphinScheduler* can better support a wide range of Kubernetes-based workflows and operational requirements.

### Frontend Design

The frontend adds support for user-customized k8s YAML Pod while remaining compatible with the original k8s low-code jobs.

1. **The Web UI layouts**

    2-2-1-frontend-design

    When the user switches on the Custom Template, the Low-code k8s Job fields should *hide* and YAML editor should *appear* (or vice versa), similar to the JSON Custom Template in the *DataX* plugin.

    This feature is implemented using the *Vue component span*, which is controlled by *reactive variables* (such as `yamlEditorSpan`) in the file `dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts`.

3. **The Request body**

    When the user switches to Custom Template mode, the request body should include only YAML-related fields (`customConfig` and `yamlContent`), and all previously hidden fields should not be sent.

    This feature is implemented using the `taskParams` in the file `dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts`

4. **i18n/locales**

    Apache DolphinScheduler is an international software and should support multiple languages.

    The text on the Web UI are retrieved from variables defined in the file `dolphinscheduler-ui/src/locales/{en_US, zh_CN}/project.ts`. And for user-customized k8s YAML tasks, there are three key variables to consider:
    - `k8s_custom_template`: the label for the switch to enable user-customized k8s YAML tasks.
    - `k8s_yaml_template`: the label for the text editor used to input user YAML.
    - `k8s_yaml_empty_tips`: the warning message displayed when a user tries to submit empty YAML

    This feature is implemented by invoking `t('project.node.${variable_name}')` (such as `t('project.node.k8s_yaml_template')`) in the file `dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts`.

### Backend Design

The backend design describes the process of how the worker executes user-customized k8s YAML Pod tasks. 

2-3-1-backend-design-overview

After the worker checks the parameters, `K8sYamlTaskExecutor` is loaded for the current user-customized k8s YAML Pod task. Once the YAML is parsed into `HasMetadata`, its `kind` field is used to assign `abstractK8sOperation` as `K8sPodOperation` for executing the YAML Pod task.

1. **K8s Task Executors**

    2-3-2-backend-design-task-executors

    Three k8s task executor are involved:
    - `AbstractK8sTaskExecutor` is an abstract class that represents a k8s task executor.
    - `K8sTaskExecutor` is a concrete class that *extends* `AbstractK8sTaskExecutor` to represent a low-code executor 
    - `K8sYamlTaskExecutor` is a concrete class that *extends* `AbstractK8sTaskExecutor` to represent a user-customized k8s YAML task executor.

2. **K8s Operation handlers**

    2-3-3-backend-design-operation-handlers

    Two operation handlers are involved:
    - `AbstractK8sOperation` is an interface representing all k8s resource operations. 
    - `K8sPodOperation` is a concrete class that implements `AbstractK8sOperation` to handle *Pod* operations

### Usecase Design

A typical use case for a k8s YAML Pod task includes *uploading* YAML, *online* workflows, and *starting* workflows, similar to k8s low-code jobs, unless users switch to the *Custom Template* option to fill in Pod YAML.

2-4-1-usecase-design

1. The user **edits** a k8s Pod YAML node in a workflow
2. If the *Custom Template* is activated and YAML content is not blank, the user may **online** this whole workflow
3. If the workflow is *online*, the user may **start** the workflow and review the logs generated during the execution of the workflow.

### Compatibility, Deprecation, and Migration Plan

The user-customized k8s YAML feature requires only `customConfig` to be activated(1). By default, the value is 0, which applies to the existing k8s low-code jobs.

This DSIP does not propose any deprecation or migration plan, but community feedback is valued.

### Test Plan

The User-customized k8s YAML Pod feature allows users to submit YAML *Pod* to k8s. And this test plan aims to ensure that the feature functions as expected and meets user requirements.

| Test Case #|        Name      |            Action          |               Expectation             |
| :--------: | :----------------| :------------------------- | :------------------------------------ |
|    1       | UI Display       | Edit YAML, save and reopen | The YAML content stays up-to-date.    |
|    2       | UI Validation    | try to submit empty YAML   | The UI modal dialog intercepts empty YAML. |
|    3       | Online Workflow  | Save workflow, and online  | The User successfully brings the workflow online. |
|    4       | Dryrun Workflow  | Run workflow as dryrun mode| The Master successfully dry runs this task. |
|    5       | Test Workflow    | Run workflow as test mode  | The Worker successfully tests this task. |
|    6       | Run Workflow     | Run workflow               | The Worker successfully runs this task. |

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Mighten**
## Purpose of the pull request

This pull request adds user-customized YAML support for Kubernetes Pod task, 
and aims to close: #16482
-  #16482

## Brief change log

- *Added `YamlUtils` with `jackson-dataformat-yaml`(new dependency in `pom.xml`)*
- *Updated `K8sUtils` with default namespace injection*
- *Added user-customized YAML task mode, with frontend and backend*

## Verify this pull request

This change added tests and can be verified as follows:

- *Added `YamlUtilsTest` to verify `YamlUtils`*
- *Added `K8sUtilsTest` to verify updates for `K8sUtils`*
- *Manually verified the user-customized YAML task mode using both the web page and IDE output:*

    1. Switch on the **Custom Template** mode, and paste Kubernetes *YAML* file content:

        1-enable-yaml-mode

        *Conclusion*: The user-customized YAML mode works correctly in the frontend.

    2. **Online**, **Start** the current workflow and *review* the log of the current task instance:

        2-view-pod-log

        *Conclusion*: The user-customized YAML mode works correctly in the backend.

    3. Review the pod output parameters *parsed from the log* in the IDE console (these are not listed in the task instance log window):

        3-get-pod-output-params

        *Conclusion*: The user-customized YAML mode correctly parses the output values from the log.

### CODE REVIEW

**Comment by Gallardot** [comment]
First you need to create a DSIP.

**Comment by fuchanghai** [comment]
#15301

**Comment by ruanwenjun** [comment]
> First you need to create a DSIP.

Yes you need to create a DSIP, and provide detailed design, rather then directly submit a PR.

**Comment by fuchanghai** [comment]
@Mighten Please modify the associated issue number

**Review by songjianet — APPROVED** [review]

**Comment by SbloodyS** [comment]
Closing for no plans to do this.

**Pull request closed without merging**
