### PR TITLE
[1.3.6-prepare][Fix-4843] Rename WORKER_GROUP to WORKER_GROUPS #4856

### PR DESCRIPTION
**Pull request by CalvinKirs**
pr #4856
issue #4843

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@chengshiwen hi, can you help me review?

**Review by chengshiwen — APPROVED** [review]
+1

**Comment by chengshiwen** [comment]
> @chengshiwen hi, can you help me review?

Done

**Comment by chengshiwen** [comment]
pr #4856
issue #4843

**Review by lgcareer — APPROVED** [review]
+1

**Pull request merged**
