### PR TITLE
[Feature][UI Next] Add Workflow Instance

### PR DESCRIPTION
**Pull request by devosend**
## Purpose of the pull request
add workflow instance

## Brief change log

image

## Releated issues
#7928

### CODE REVIEW

**Comment by devosend** [comment]
PTAL @songjianet @labbomb

**Review by labbomb — APPROVED** [review]
LGTM

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Congratulation for your first merge @songjianet

**Pull request merged**
