### PR TITLE
[Bug-12956] fix incorrect java path

### PR DESCRIPTION
**Pull request by zhangfane**
## Purpose of the pull request
Fix the problem reported by this issue #12956。
This pull request  update java path。

## Brief change log
fix incorrect java path

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by EricGao888 — APPROVED** [review]

**Comment by EricGao888** [comment]
@zhangfane You could either run `mvn spotless:apply` or rebase your code on the latest dev branch to pass CI.

**Comment by zhangfane** [comment]
@EricGao888 done

**Comment by EricGao888** [comment]
@zhangfane Something wrong with CI, could u plz rebase on the latest dev branch? It will help make CI pass and I could merge this PR. Thx : )

**Comment by zhangfane** [comment]
@EricGao888 done

**Pull request merged**
