### PR TITLE
Change issue bot mailing list describe from Chinese to English

### PR DESCRIPTION
**Pull request by zhongjiajie**
## Purpose of the pull request

Github issue bot describe change to English page instead of Chinese

## Brief change log

  - *Github issue bot describe change to English page instead of Chinese*

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Can it be removed together with the relevant description in the issue template.

For example: If you feel the description in English is not clear, then you can append description in Chinese, thanks!

**Comment by zhongjiajie** [comment]
Hi @CalvinKirs, this PR it not related I proposal in mailing-list, https://lists.apache.org/thread.html/r0c2e9f9fa8968936884191371592791616bcc609375b9f84a4ec1155%40%3Cdev.dolphinscheduler.apache.org%3E, it just correct the issue bot link.

And about proposal "Do not support not english issue or PR anymore", maybe we should wait more time after community discuss.

**Comment by lenboo** [comment]
> Hi @CalvinKirs, this PR it not related I proposal in mailing-list, https://lists.apache.org/thread.html/r0c2e9f9fa8968936884191371592791616bcc609375b9f84a4ec1155%40%3Cdev.dolphinscheduler.apache.org%3E, it just correct the issue bot link.
> 
> And about proposal "Do not support not english issue or PR anymore", maybe we should wait more time after community discuss.

i find this pr is not associate with the mail ,  and I think our default prompt should be in English, 
so this PR is ok.

**Review by lenboo — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
> > Hi @CalvinKirs, this PR it not related I proposal in mailing-list, https://lists.apache.org/thread.html/r0c2e9f9fa8968936884191371592791616bcc609375b9f84a4ec1155%40%3Cdev.dolphinscheduler.apache.org%3E, it just correct the issue bot link.
> > And about proposal "Do not support not english issue or PR anymore", maybe we should wait more time after community discuss.
> 
> i find this pr is not associate with the mail , and I think our default prompt should be in English, so this PR is ok.

Yes, this PR should be merge due to should show english as default, cc @CalvinKirs

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
