### PR TITLE
 [Fix] [ui] Fixed the re-upload function of the Resource Management menu #8764

### LINKED ISSUE #8764: [Bug] [ui] File resource list and UDF resource list file re-upload error, and the subfolder does not have related functions
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

File resource list and UDF resource list An error occurred during file re-uploading. The subfolder resource list does not have related functions. Procedure
An exception was reported when calling the update resource interface

### What you expected to happen

This issue is not fully fixed in V2.0.5, hopefully it will be fixed in the next release.

### How to reproduce

1. Upload the file in the resource list and click Upload again
2. The subfolder list does not have the re-upload function
3. The uploaded files in the UDF resource list do not have the re-upload function
4. An interface exception is reported when you click re-upload

### Anything else

If the resource file in the workflow instance cannot be updated, the workflow instance will need to be redefined if the resource needs to be upgraded later

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by HuntFalcon**
[Fix] [ui] Fixed the re-upload function of the Resource Management menu
* Modify resource file list and sub-file front-end code
* Modify udF resource file list and subfile front-end code
* Fix modified page does not dynamically update content, added V-if judgment
* Fix duplicate ID problem
* Fixed v2.0.5 UDF resource list re-upload function

### CODE REVIEW

**Comment by HuntFalcon** [comment]
Administrator to help review, thank you

**Comment by songjianet** [comment]
You need to create an issue correspondingly, instead of expressing the problem in the description of this pr

**Comment by HuntFalcon** [comment]
I just submitted a question #8764, do I need to resubmit this PR? I don't know the overall process of the first submission, I hope you can understand.

**Comment by songjianet** [comment]
> I just submitted a question #8764, do I need to resubmit this PR? I don't know the overall process of the first submission, I hope you can understand.

Not needed, usually for new or changed functions, and to fix the problem, create a new issue and associate it with pr.

**Review by songjianet — APPROVED** [review]
LGTM

**Pull request merged**
