### PR TITLE
[Doc][Style] Fix doc format once for all

### LINKED ISSUE #12005: [Doc][Style] Fix the format of all docs once for all
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* Currently we fix doc format incrementally, which causes much noise during PR review. Considering part of the doc  format has been fixed already, it is high time that we fix the rest once for all.
* See https://github.com/apache/dolphinscheduler/pull/11444#issuecomment-1248870320 for details.

### Documentation Links

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* This PR closes: #12005 , for details, see: #12005

## Brief change log

* Fix the format of docs once for all.

## Verify this pull request

* This PR is to fix doc format without test coverage needed.

### CODE REVIEW

**Review by kezhenxu94 — DISMISSED** [review]

**Review by SbloodyS — DISMISSED** [review]
+1

**Comment by kezhenxu94** [comment]
Please fix the dead link

**Comment by ruanwenjun** [comment]
Please cp this PR to 3.1.0-prepare after the ci pass.

**Comment by EricGao888** [comment]
> Please fix the dead link

Sure, thx

**Comment by EricGao888** [comment]
> Please cp this PR to 3.1.0-prepare after the ci pass.

Sure, will do.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
