### PR TITLE
 [Improvement-15183][api] split Api status  #15276 

### LINKED ISSUE #15183: [Improvement][API] Split Status in to sub status.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We maintain all module status in one class, it's very large, we need to split this by submodule.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhengkezhou1**
## Purpose of the pull request

1. split the old status enum and create new child status
2. use new status replace old status enum

this pull request fix https://github.com/apache/dolphinscheduler/issues/15183

## Brief change log

- change **org/apache/dolphinscheduler/api/exceptions/ServiceException** 
- change **org/apache/dolphinscheduler/api/utils/Result**
- change **org/apache/dolphinscheduler/api/service**
- change **org/apache/dolphinscheduler/api/service/impl**
- change **org/apache/dolphinscheduler/api/controller**  
- change **org/apache/dolphinscheduler/api/controller/v2**

## Verify this pull request

This pull request is already covered by existing tests, such as **unit test**

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Good Job

**Comment by caishunfeng** [comment]
- https://github.com/apache/dolphinscheduler/pull/15276

**Comment by zhengkezhou1** [comment]
hi, @caishunfeng @ruanwenjun @SbloodyS  @zhuangchong i have finished this task

**Comment by ruanwenjun** [comment]
Please rebase from the upstream-dev and solve the conflicts.

**Comment by zzzk1** [comment]
Is the problem solved?

**Comment by zzzk1** [comment]
I think, I put all the changes into this PR

**Comment by zzzk1** [comment]
> Please rebase from the upstream-dev and solve the conflicts.

i don't konw how to deal with **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java**
图片
it looks like cant find **FileOperateException**

**Comment by zhengkezhou1** [comment]
> Please rebase from the upstream-dev and solve the conflicts.

@ruanwenjun  can you help me to review this pr ?

**Comment by ruanwenjun** [comment]
> > Please rebase from the upstream-dev and solve the conflicts.
> 
> @ruanwenjun can you help me to review this pr ?

Sorry for reply late, I will review this pr, and #15276 should merge first.

**Pull request closed without merging**
