### PR TITLE
add support to build based on pushing tags

### LINKED ISSUE #12248: [Improvement][Backend] Build Image for Pushing Tag Events
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently the GitHub Actions workflow publish-docker only builds and pushes images on dev branch. There's no automation for release image building & pushing. We need to update the publish-docker workflow to be triggered by pushing tag events and build the corresponding images using the same tags.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by danielfree**
## Purpose of the pull request

closes #12248 

This PR adds support to build images triggered by tag pushing event

## Brief change log

Add a section in publish-docker.yml for Github Actions to run only on tag events.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by kezhenxu94 — COMMENTED** [review]
Released Docker images should be pushed to Docker hub not ghcr.io. And testers can easily find the corresponding commit sha of the tag to find the image in ghcr so there is no need to push them to ghcr.io too.

**Comment by danielfree** [comment]
> Released Docker images should be pushed to Docker hub not ghcr.io. And testers can easily find the corresponding commit sha of the tag to find the image in ghcr so there is no need to push them to ghcr.io too.

how about I change the action to push to docker hub? need someone to setup the user/pwd in secrets.

**Comment by kezhenxu94** [comment]
> > Released Docker images should be pushed to Docker hub not ghcr.io. And testers can easily find the corresponding commit sha of the tag to find the image in ghcr so there is no need to push them to ghcr.io too.
> 
> how about I change the action to push to docker hub? need someone to setup the user/pwd in secrets.

1. That needs Apache Infra team to set this up, you need to open Jira ticket to ask them to set this up.
2. You need to use release event to trigger the publish workflow, tag event happens when voting a new release, at this time the version is not officially released so we cannot publish to Docker hub yet.

**Comment by danielfree** [comment]
> > > Released Docker images should be pushed to Docker hub not ghcr.io. And testers can easily find the corresponding commit sha of the tag to find the image in ghcr so there is no need to push them to ghcr.io too.
> > 
> > 
> > how about I change the action to push to docker hub? need someone to setup the user/pwd in secrets.
> 
> 1. That needs Apache Infra team to set this up, you need to open Jira ticket to ask them to set this up.
> 2. You need to use release event to trigger the publish workflow, tag event happens when voting a new release, at this time the version is not officially released so we cannot publish to Docker hub yet.

is this something we want to do? if so, we can open the jira ticket to setup everything needed.

**Comment by kezhenxu94** [comment]
> > > > Released Docker images should be pushed to Docker hub not ghcr.io. And testers can easily find the corresponding commit sha of the tag to find the image in ghcr so there is no need to push them to ghcr.io too.
> > > 
> > > 
> > > how about I change the action to push to docker hub? need someone to setup the user/pwd in secrets.
> > 
> > 
> > 
> > 1. That needs Apache Infra team to set this up, you need to open Jira ticket to ask them to set this up.
> > 2. You need to use release event to trigger the publish workflow, tag event happens when voting a new release, at this time the version is not officially released so we cannot publish to Docker hub yet.
> 
> is this something we want to do? if so, we can open the jira ticket to setup everything needed.

It's worth doing IMO

**Comment by kezhenxu94** [comment]
This is done recently in #13631

**Pull request closed without merging**
