### PR TITLE
Add bot mergeable to make sql files change synchronize

### LINKED ISSUE #6431: [Feature][dev] Make sure to synchronize change for sql file
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When developer change sql files in https://github.com/apache/dolphinscheduler/tree/dev/sql, sometime they would forgot change `H2` sql file. Standalone server could not start when this happen. Maybe we should

* (better) Add bot ensure those file change synchronize
* Add check list when contributor create PR in [PR template][1]

[1]: https://github.com/apache/dolphinscheduler/blob/dev/.github/PULL_REQUEST_TEMPLATE.md

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
closes: #6431

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I create a demo PR in my repo, https://github.com/zhongjiajie/dolphinscheduler/pull/3. When we not change sql files in then same time bot mergeable would

* failed our CI check, notify maintainer be careful about this PR
* add it would add labels `sql not sync`

If developer fix synchronize problem, mergeable would remove the label `sql not sync` and check pass.

**Comment by zhongjiajie** [comment]
We still have some discuss in [issue](https://github.com/apache/dolphinscheduler/issues/6431#issuecomment-938463234). If we agree with this PR, we have to config mergeable to our repo before in work, you could config in the page https://github.com/apps/mergeable

**Comment by kezhenxu94** [comment]
@zhongjiajie this requires the infra to [install the GitHub App](https://github.com/apps/mergeable/installations/837350) in this repo, otherwise the new file (`.github/mergeable.yml`) takes no effect

**Comment by zhongjiajie** [comment]
Yeah, that what I said in https://github.com/apache/dolphinscheduler/pull/6465#issuecomment-938540798,  do you mean we have to asked infra team to install it? @kezhenxu94

**Comment by kezhenxu94** [comment]
> Yeah, that what I said in https://github.com/apache/dolphinscheduler/pull/6465#issuecomment-938540798,  do you mean we have to asked infra team to install it? @kezhenxu94 
> 
> 
> 
> 

Yes you need to ask infra to install in this repo

**Comment by zhongjiajie** [comment]
Thanks and I would try to ask infra team for help.

**Comment by zhongjiajie** [comment]
PTAL @CalvinKirs @lenboo

**Review by kezhenxu94 — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
Good job~

**Comment by zhongjiajie** [comment]
I would create test PR to test this feature.

**Comment by kezhenxu94** [comment]
Screen Shot 2021-11-10 at 15 06 54

@zhongjiajie it worked

**Comment by zhongjiajie** [comment]
> Screen Shot 2021-11-10 at 15 06 54
> 
> @zhongjiajie it worked

Thanks! Boss Ke, yyds 👍

**Pull request merged**
