### PR TITLE
[Bug][API]Resource Check error

### LINKED ISSUE #6366: [Bug] [API][service] checkResourceExists function use the magic number userId '0'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when the resource exactly exists,but the userId is not '0', the function will not take effect.

### What you expected to happen

the resources should be operate by the loginUser, sow the userId should be the loginUser's id

### How to reproduce

the resources should be operate by the loginUser, sow the userId should be the loginUser's id

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BenjaminWenqiYu**
## Purpose of the pull request
fix the magic number userId '0'

## Brief change log

fix the magic number userId '0'

## Verify this pull request

This pull request is code cleanup without any test coverage.

resolve #6366

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by CalvinKirs** [comment]
CI failure has nothing to do with this PR. I will merge this pr first.

**Comment by BenjaminWenqiYu** [comment]
there is another question


> considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

thank you very much, I will add your wechat later.

**Comment by BenjaminWenqiYu** [comment]
Thank you very much, I will add your wechat later.

**Pull request merged**
