### PR TITLE
[Feature-5087][SqlTask] Add a switch to send mail and print head logs in SqlTask

### LINKED ISSUE #174: The SQL query node selects "no send", and the specified mailbox discovery is sent successfully.(SQL查询节点选择“都不发”，指定邮箱发现是发送成功的)

### LINKED ISSUE #547: sql task alarm configuration, it is recommended to be configurable, optional or not selected(sql任务的告警配置，建议做成可配置的，可选可不选)
The current log alarm policy is that when the alarm fails, the task is reported incorrectly. In fact, the task is executed OK. Only the email alarm needs to be blocked.

---
目前的日志告警策略是告警失败就会任务报错，其实任务是执行OK了的，只需要屏蔽邮件告警，就OK

### LINKED ISSUE #5087: [Feature][SqlTask] Add a switch to send mail and print head logs in SqlTask
**Describe the feature**

**Add the switch to send mail and print head logs in SqlTask**

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

**[Feature-5087][SqlTask] Add a switch to send mail and print head logs in SqlTask*

This closes #174 closes #547 closes #5087

## Brief change log

  - *Add a switch to send mail in SqlTask*
  - *Print head logs in SqlTask*
  - *Compatible with historical versions*

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.

(and)

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

## Snapshots

**Configure SQLTask**:

Picture 1:
image

Picture 2:
image

Picture 3:
image

**Send email but failed**

image

**Turn off sending email**

image

@dailidong  @CalvinKirs @chenxingchun

### CODE REVIEW

**Comment by chengshiwen** [comment]
@CalvinKirs I have tried to improve the unit test coverage to `22.2%` from `0%`. But the db is more difficult to mock, so the `SqlTaskTest` also has never been enabled to test.

**Review by CalvinKirs — APPROVED** [review]
LGTM.backend

**Comment by CalvinKirs** [comment]
btw, send email default value should is true. please reviewers notice.

**Review by break60 — APPROVED** [review]
+1

**Pull request merged**
