### PR TITLE
Fix docs style is incorrect by CI pass

### PR DESCRIPTION
**Pull request by zhongjiajie**
test ci conflict, seems our ci do not correct in https://github.com/apache/dolphinscheduler/pull/15145

### CODE REVIEW

**Comment by EricGao888** [comment]
I've made it `ready for review` so that we could figure out whether CI will block merging once finished.

**Review by ruanwenjun — DISMISSED** [review]
test approve

**Comment by ruanwenjun** [comment]
The pr can still merged although the doc style check failed.
image

**Comment by zhongjiajie** [comment]
it work in https://github.com/apache/dolphinscheduler/actions/runs/6986642056/job/19012384537

**Review by ruanwenjun — APPROVED** [review]

**Pull request merged**
