### PR TITLE
[python] Add flake8 and black for code style and integrated to GA

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Add describe and configure for code style
* Add CI integrated to GitHub action, separator pydolphinscheduler directory in single CI process
* Add some documentation about Github action and local run
* Change pydolphinscheduler codebase for conform to code style check

### CODE REVIEW

**Review by davidzollo — APPROVED** [review]
great job
+1

**Review by CalvinKirs — APPROVED** [review]
Good Job~

**Comment by zhongjiajie** [comment]
Thanks

**Comment by zhongjiajie** [comment]
ref: #6407

**Pull request merged**
