### PR TITLE
[Improvement][Deployment] deployment tutorial has security risks

### PR DESCRIPTION
**Pull request by xinxingi**
## Purpose of the pull request
#15869 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
I think this is unnessnary.

**Comment by xinxingi** [comment]
> I think this is unnessnary.

I also don't think it's a problem, just an improvement.

**Comment by ruanwenjun** [comment]
I am -1 to this PR, my concern is `openssl` might not be pre-installed in all linux distribution. This might cause user need to pre install other tools.

**Comment by xinxingi** [comment]
ok i will close this PR

**Pull request closed without merging**
