### PR TITLE
[Fix][UI]Fix UI adaptation problem and semantic error

### PR DESCRIPTION
**Pull request by zekai-li**

### CODE REVIEW

**Comment by zekai-li** [comment]
- UI adaptaion problem：
TypeError: Cannot read properties of undefined (reading 'replace')
    at e.template (index.7d7b65c.js?482c934e226363298844:2)
    at a.u [as $t] (index.7d7b65c.js?482c934e226363298844:2)
    at a.i (index.7d7b65c.js?482c934e226363298844:2)
    at a.t._render (index.7d7b65c.js?482c934e226363298844:2)
    at a.i (index.7d7b65c.js?482c934e226363298844:2)
    at fn.get (index.7d7b65c.js?482c934e226363298844:2)
    at fn.run (index.7d7b65c.js?482c934e226363298844:2)
    at dn (index.7d7b65c.js?482c934e226363298844:2)
    at Array.<anonymous> (index.7d7b65c.js?482c934e226363298844:2)
    at Kt (index.7d7b65c.js?482c934e226363298844:2)

**Review by zhuangchong — APPROVED** [review]
+1 very good

**Comment by zekai-li** [comment]
@ke4qqq Please help review.

**Review by CalvinKirs — APPROVED** [review]

**Comment by zhuangchong** [comment]
@zekai-li 
considering that it's your first contribution, I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Pull request merged**
