### PR TITLE
[Fix-11087] [Oracle] Add oracle dependency and fix datasource chinese doc link error

### LINKED ISSUE #11087: [Bug] [Data Source] Can not create oracle data source.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

"Failed to load driver class oracle.jdbc.OracleDriver in either of HikariConfig class loader or Thread context classloader" is prompted when I build a oracle data source  connection. I have already copyed ojdbc6.jar or ojdbc8.jar file to all libs directories，and restarted servers .The jdbc file worked well in version 1.x.
(By the way ,there is no oracle datasource description in lastest DOC?)
### What you expected to happen

create oracle data source properly

### How to reproduce

Just create oracle data source. 

### Anything else

_No response_

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

Fix #11087

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
LGTM once CI passed

**Review by EricGao888 — APPROVED** [review]

**Comment by xyzhh** [comment]
Is the bug really fix in release 3.0.0 ? I can't create oracle datasource still with the version(not beta version).

**Comment by SbloodyS** [comment]
> Is the bug really fix in release 3.0.0 ? I can't create oracle datasource still with the version(not beta version).

Yes. Feel free to open an issue if you have any further problems.

**Comment by JIEX888** [comment]
The problem has not been resolved, and I have encountered the same problem

**Pull request merged**
