### PR TITLE
[DSIP-32][Master] Add command fetcher strategy for master fetch command

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #https://github.com/apache/dolphinscheduler/issues/15897

## Brief change log

- Change the master loop command strategy, and support fetch discontinuous orders commands .

## Verify this pull request

Test by UT and E2E

### CODE REVIEW

**Review by Radeity — DISMISSED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
> ## Purpose of the pull request
> close ##15897
> 
> ## Brief change log
> ## Verify this pull request
> This pull request is code cleanup without any test coverage.
> 
> _(or)_
> 
> This pull request is already covered by existing tests, such as _(please describe tests)_.
> 
> (or)
> 
> This change added tests and can be verified as follows:
> 
> (or)
> 
> If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

Please improve the pr description.

**Review by Radeity — APPROVED** [review]
LGTM

**Pull request merged**
