### PR TITLE
[Improvement][ExecutorServiceImpl] remove some unnecessary

### LINKED ISSUE #11118: [Improvement][ExecutorServiceImpl] remove some unnecessary
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

image
Do you mind if I delete the part marked in red, I don't think these lines of code are necessary

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

remove some unnecessary

## Brief change log
remove some unnecessary in ExecutorServiceImpl

## Verify this pull request

This pull request is code cleanup without any test coverage.
close #11118

### CODE REVIEW

**Comment by fuchanghai** [comment]
@SbloodyS @caishunfeng What snoar detects should be the content that needs to be tested that is not fully covered by the test unit. This should have nothing to do with the code I modified. What do you think?

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by caishunfeng** [comment]
I rerun the fail CI jobs.

**Comment by fuchanghai** [comment]
@caishunfeng It's still wrong now, but it doesn't seem to be related to the code I submitted，PTAL

**Pull request merged**
