### PR TITLE
[Fix-8696][server]add comments for the repeated record on granting project

### PR DESCRIPTION
**Pull request by yanmushi**
添加注释：在2.0.5中，授权项目时，重复记录BUG

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by SbloodyS** [comment]
Is this nessessary?

**Comment by SbloodyS** [comment]
Is this nessessary?

**Comment by yanmushi** [comment]
I think it is. The Bug has been fixed in dev branch. But it is not a UI BUG.

**Comment by SbloodyS** [comment]
> I think it is. The Bug has been fixed in dev branch. But it is not a UI BUG.

Since it has been fixed in dev branch. I think this comment is redundant.

**Comment by zhongjiajie** [comment]
Hi @yanmushi I agree with @SbloodyS, If this is already fix in dev, we should not add any comment on it

**Comment by caishunfeng** [comment]
> > I think it is. The Bug has been fixed in dev branch. But it is not a UI BUG.
> 
> Since it has been fixed in dev branch. I think this comment is redundant.

Agree with @SbloodyS , and I will close this pr.
@yanmushi Thanks for your submitting and looking forward to your next pr.

**Pull request closed without merging**
