### PR TITLE
[Fix-14231][api] Align execution status enum

### LINKED ISSUE #14231: [Bug] [Master]  WorkflowExecutionStatus is incompatible with TaskExecutionStatus
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

version : 3.1.7
SubProcessor 133 lines, use WorkflowExecutionStatus. Code conversion TaskExecutionStatus. Because TaskExecutionStatus does not have a corresponding value, the transition will fail and the SubProcessor will not be able to update the state properly
 

SubProcessor.updateTaskState

 taskInstance.setState(TaskExecutionStatus.of(subProcessInstance.getState().getCode()));

### What you expected to happen

The SubProcessor can be updated normally

### How to reproduce

SubProcessInstance.status=4

### Anything else

Partial Log

[INFO] 2023-05-29 16:56:29.966 +0800 - set work flow 31156 task 191582 running
[INFO] 2023-05-29 16:56:29.967 +0800 - work flow 31156 task 191582, sub work flow: 31158 state: WorkflowExecutionStatus{code=4, desc='ready stop'}
[INFO] 2023-05-29 16:56:34.971 +0800 - set work flow 31156 task 191582 running
[INFO] 2023-05-29 16:56:34.972 +0800 - work flow 31156 task 191582, sub work flow: 31158 state: WorkflowExecutionStatus{code=4, desc='ready stop'}
[INFO] 2023-05-29 16:56:39.975 +0800 - set work flow 31156 task 191582 running
[INFO] 2023-05-29 16:56:39.977 +0800 - work flow 31156 task 191582, sub work flow: 31158 state: WorkflowExecutionStatus{code=4, desc='ready stop'}
[INFO] 2023-05-29 16:56:44.980 +0800 - set work flow 31156 task 191582 running
[INFO] 2023-05-29 16:56:44.981 +0800 - work flow 31156 task 191582, sub work flow: 31158 state: WorkflowExecutionStatus{code=4, desc='ready stop'}

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zichen-fei**
## Purpose of the pull request
fix #14231 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please link this pr to your issue.

**Comment by zichen-fei** [comment]
#14231

**Comment by zichen-fei** [comment]
> Please link this pr to your issue.

done

**Comment by fuchanghai** [comment]
@SbloodyS plz rerun the fail part
image

**Pull request closed without merging**
