### PR TITLE
[improve-#13678] add filter in method of ``` setMainJarName ```

### LINKED ISSUE #13678: [Bug] [flink sql] flink sql  "The jar for the task is required."
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

env:
    dolphinscheduler 3.1.4
    flink 1.14.2
problem:
    cannot run flink sql task
    
image
image
error log :
image
some body can help me?

### What you expected to happen

sql tasks should not prompt for jar package issues

### How to reproduce

See the picture above (What happened)

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request
- this close #13678 
add filter in method of ``` setMainJarName ```

## Brief change log

this close : #13678

### CODE REVIEW

**Review by zhuangchong — APPROVED** [review]
LGTM.

**Review by EricGao888 — APPROVED** [review]

**Comment by EricGao888** [comment]
@fuchanghai Have u submitted a PR to dev branch?

**Comment by Radeity** [comment]
> @fuchanghai Have u submitted a PR to dev branch?

Hi, @EricGao888, i think it's unnecessary to submit to dev, ref https://github.com/apache/dolphinscheduler/issues/13678#issuecomment-1457546588, WDYT?

**Comment by EricGao888** [comment]
> > @fuchanghai Have u submitted a PR to dev branch?
> 
> Hi, @EricGao888, i think it's unnecessary to submit to dev, ref [#13678 (comment)](https://github.com/apache/dolphinscheduler/issues/13678#issuecomment-1457546588), WDYT?

Got it.

**Comment by fuchanghai** [comment]
> > @fuchanghai Have u submitted a PR to dev branch?
> 
> Hi, @EricGao888, i think it's unnecessary to submit to dev, ref [#13678 (comment)](https://github.com/apache/dolphinscheduler/issues/13678#issuecomment-1457546588), WDYT?

You recommend me before I submitted it , so this branch copy from 3.1.5 ,
image

**Comment by fuchanghai** [comment]
> > @fuchanghai Have u submitted a PR to dev branch?
> 
> Hi, @EricGao888, i think it's unnecessary to submit to dev, ref [#13678 (comment)](https://github.com/apache/dolphinscheduler/issues/13678#issuecomment-1457546588), WDYT?

Thanks again

**Pull request merged**
