### PR TITLE
Refactor code, add class import.

### PR DESCRIPTION
**Pull request by dongzl**
Refactor code, add class import.

### CODE REVIEW

**Review by kezhenxu94 — COMMENTED** [review]
There are many other places with the same issue, could you replace them all? (you can search globally in IDE)

**Comment by dongzl** [comment]
> There are many other places with the same issue, could you replace them all? (you can search globally in IDE)

@kezhenxu94 , OK, I will check other classes.  Please give me some time.

**Review by davidzollo — APPROVED** [review]
+1
good job

**Comment by davidzollo** [comment]
> > There are many other places with the same issue, could you replace them all? (you can search globally in IDE)
> 
> @kezhenxu94 , OK, I will check other classes. Please give me some time.

Nice to see you again in a year or more

**Pull request merged**
