### PR TITLE
[2.0.1-cherrypick] SPI(Task ,Alert ,DataSource)

### PR DESCRIPTION
**Pull request by CalvinKirs**
PR: #6723 #6828 #6361
Issue：#6712 #6792 #6490 #6071

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Since these PRs are related, I merged them into one PR

**Comment by zhongjiajie** [comment]
Good job, and thanks for your work! 👍

**Comment by davidzollo** [comment]
A hard work!

I think it would be a better choice to submit the basic implementation of SPI, alert SPI, task SPI, and datasource SPI separately.

I have a suggestion that a PR solves a problem. For example, the PR of Alert SPI only solves Alert and task SPI only solves Task Plugin. It is not a good practice to mix them together.

**Comment by CalvinKirs** [comment]
> A hard work!
> 
> I think it would be a better choice to submit the basic implementation of SPI, alert SPI, task SPI, and datasource SPI separately.
> 
> I have a suggestion that a PR solves a problem. For example, the PR of Alert SPI only solves Alert and task SPI only solves Task Plugin. It is not a good practice to mix them together.

I plan to do this, but because of the correlation between these PRs, it is difficult for me to make them into multiple PRs separately.

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
