### PR TITLE
[Feature-7428][UI] display the full name of the node in DAG workflow when mouseover

### LINKED ISSUE #7428: [Feature][UI] display the full name of the node in DAG workflow page
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

the node should expand or display the full name while the mouse is moved up.

We have many tasks with serial nodes in DS 2.0.0 now. Sometimes I want to find a certain node, but I have to double-click  them then open and view one by one to find it. It is not as convenient as the old version~
image

In the version 1.3.x, the node name can be displayed completely.
image

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mgduoduo**
close: #7428. customize a tooltip for the node to display the full task name of the node in DAG workflow when mouseover.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@songjianet Do you have time to take a look at this PR?

**Comment by caishunfeng** [comment]
PTAL @songjianet @Wangyizhi1

**Review by wangyizhi1 — APPROVED** [review]
LGTM

**Review by songjianet — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Comment by songjianet** [comment]
Thank you for your contribution, this has already been handled by others.

**Pull request closed without merging**
