### PR TITLE
[improvement-#14005] configurable scala version

### LINKED ISSUE #14005: [Improvement][Bom] In the ```pom file``` of the ```bom module```, the ```scala version``` is best also configured in the properties tag
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

hi @zhuangchong Please tag good first issue

image

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mashangyuanmeng**
## Purpose of the pull request
this close #14005 
configurable scala version

## Brief change log

configurable scala version

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by mashangyuanmeng** [comment]
@caishunfeng @EricGao888 plz runCI

**Review by fuchanghai — APPROVED** [review]
LGTM

**Review by SbloodyS — COMMENTED** [review]
Please check failed UT.

**Comment by EricGao888** [comment]
> @caishunfeng @EricGao888 plz runCI

Could u plz fix this case?

image

**Comment by fuchanghai** [comment]
hi @EricGao888 @SbloodyS It works fine on my local test
image

**Comment by SbloodyS** [comment]
> hi @EricGao888 @SbloodyS It works fine on my local test.

Are you running on jdk11? The failed UT is running on jdk11.

**Comment by fuchanghai** [comment]
> > hi @EricGao888 @SbloodyS It works fine on my local test.
> 
> Are you running on jdk11? The failed UT is running on jdk11.

My local scala version is 2.12.15，jdk version is 1.8,
This error seems to be caused by scala

**Comment by fuchanghai** [comment]
image

**Pull request closed without merging**
