### PR TITLE
feat: Unify mysql insert value queto

### PR DESCRIPTION
**Pull request by boy-xiaozhang**
## Purpose of the pull request
fix bug

## Brief change log
fix mysql initialize sql file
## Verify this pull request

bash create-dolphinscheduler.sh

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I think double quotes should also work in this SQL, it related on your database configuration. So maybe it is not a bug

**Comment by boy-xiaozhang** [comment]
> 

I'll test other database versions

**Comment by boy-xiaozhang** [comment]
hi @zhongjiajie After my verification, I found that when the metastore of dolphinscheduler uses mysql, and the sql mode of mysql contains ANSI QUOTES, double quotes are not allowed,"" would be interpreted as `` Below is the official explanation
image
Strictly speaking, this is not a bug, but it is still a relatively unfriendly behavior, because it is inevitable that students may use this SQL mode

**Comment by zhongjiajie** [comment]
Thanks for the clarification, I think we should merge it

**Review by zhongjiajie — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks @boy-xiaozhang

**Pull request merged**
