### PR TITLE
[Feature][Monitoring] Added disk available capacity monitoring

### LINKED ISSUE #10190: [Bug] [E2E] The front-end page changes failed the E2E test
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

relevance   https://github.com/apache/dolphinscheduler/pull/10186

https://github.com/apache/dolphinscheduler/runs/6548541522?check_suite_focus=true
image

### What you expected to happen

pass

### How to reproduce

pass

### Anything else

_No response_

### Version

3.0.0-alpha

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by retime123**
## Purpose of the pull request
This method is added because the available disk capacity cannot be monitored  
before  https://github.com/apache/dolphinscheduler/pull/10186
close [#10190](https://github.com/apache/dolphinscheduler/issues/10190)

## Brief change log

Change dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
Change dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HeartBeat.java
Change dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
Change dolphinscheduler-ui/src/views/monitor/servers/master/index.tsx
Change dolphinscheduler-ui/src/views/monitor/servers/worker/index.tsx
Change dolphinscheduler-ui/src/locales/en_US/monitor.ts
Change dolphinscheduler-ui/src/locales/zh_CN/monitor.ts

unit testing
Change dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/os/OSUtilsTest.java
Change dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/HeartBeatTest.java

## Verify this pull request

retry

image

### CODE REVIEW

**Comment by retime123** [comment]
Hi @caishunfeng     I have resubmitted the code.  if OK, Merge!

**Comment by retime123** [comment]
image
It's always a surprise!
You can add this feature. I'm getting a little upset

**Comment by retime123** [comment]
Can it be merged?

**Review by zhuangchong — APPROVED** [review]
+1

**Review by Amy0104 — APPROVED** [review]
The font end part LGTM.

**Review by caishunfeng — APPROVED** [review]
+1, thanks for your contribution.

**Pull request merged**
