### PR TITLE
[Fix-7902] The default registration plug-in is missing parameters

### LINKED ISSUE #7902: [Bug] [Registry] The default registration plug-in is missing parameters
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The default registration plug-in is missing parameters

### What you expected to happen

The default registration plug-in is missing parameters

### How to reproduce

The default registration plug-in is missing parameters

### Anything else

_No response_

### Version

2.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

This pr will close #7902

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
Do we also need to add below config?
```properties
registry.namespace=
registry.block.until.connected.wait=600

**Comment by SbloodyS** [comment]
> Do we also need to add below config?
> 
> ```ini
> registry.namespace=
> registry.block.until.connected.wait=600
> ```

registry.namespace is already included.
I'll add registry.block.until.connected.wait.
thx.

**Comment by ruanwenjun** [comment]
@SbloodyS Sorry, it's a typo. I mean `registry.digest`

**Comment by SbloodyS** [comment]
@ruanwenjun Sorry. I missed some parameters referring to the document of 1.3.X. Please review again. Thx.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Pull request merged**
