### PR TITLE
[DSIP-39][parameter] Improvement startup parameters/global parameters/project parameters data type

### PR DESCRIPTION
**Pull request by sdhzwc**
#15936
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by sdhzwc** [comment]
Due to my misuse I turned off #15967 and redid the pull request, sorry for the trouble you guys are in god operation, the conflict I have solved it @ruanwenjun @SbloodyS @songjianet

**Comment by sdhzwc** [comment]
Historical Discussion PR #15945

**Comment by ruanwenjun** [comment]
Closed this PR, you should continue on https://github.com/apache/dolphinscheduler/pull/15967

**Comment by sdhzwc** [comment]
> Closed this PR, you should continue on https://github.com/apache/dolphinscheduler/pull/15967

I couldn't resolve the conflict using the previous method, because my dev is identical to the DS dev. I made a basic mistake here. I should have created a new branch, and then merged any conflicting code to my branch for resolution. So I had to restart for this.

**Pull request closed without merging**
