### PR TITLE
[bug] [dolphinscheduler-ui] UI timed scheduler Improvement

### LINKED ISSUE #15623: [Bug] [dolphinscheduler-ui]  UI timed scheduler Improvement
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/issues/15449

https://github.com/apache/dolphinscheduler/assets/26395835/6251f961-b426-451f-a6d4-a7207aa771db

### What you expected to happen

在工作流定义中，上线一个已经存在定时配置的任务时，执行update逻辑。
In the workflow definition, the update logic is executed when a task already has a scheduled configuration.

### How to reproduce

在工作流定义中，上线一个已经存在定时配置的任务时，会错误的执行create逻辑。
In the workflow definition, the create logic will be executed incorrectly when a task already has a scheduled configuration.

### Anything else

pass

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cqutwangyu**
## Purpose of the pull request
fix https://github.com/apache/dolphinscheduler/issues/15623

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by cqutwangyu** [comment]
@songjianet @Amy0104 
please cc

**Comment by Gallardot** [comment]
@cqutwangyu 
Thanks for your contribution, can you upload a page snapshot at the same time?

**Comment by cqutwangyu** [comment]
@Gallardot 
ok,I recorded the video

this is error

https://github.com/apache/dolphinscheduler/assets/26395835/6e70c8ce-89aa-41eb-85f9-1296968d3996

this is fix

https://github.com/apache/dolphinscheduler/assets/26395835/daa2213e-33bf-4567-84cb-7b0bb80d03df

**Review by songjianet — DISMISSED** [review]

**Comment by songjianet** [comment]
image

**Comment by cqutwangyu** [comment]
Hello, I checked the error message and I found that the error message is not related to the content I modified. I then executed the pnpm run build:prod command on my computer, and the package was successful.




---Original---
From: ***@***.***&gt;
Date: Mon, Feb 26, 2024 08:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] [Bug] [dolphinscheduler-ui] UI timed scheduler Improvement (PR #15624)




 
image.png (view on web)

**Comment by rickchengx** [comment]
cc @c3Vu @arlendp

**Comment by Gallardot** [comment]
I have tested this PR in my dev cluster, it works well and the issue has been fixed. Thanks @cqutwangyu .

What should be the next step to proceed with this PR?

@songjianet @cqutwangyu @rickchengx

**Comment by rickchengx** [comment]
> I have tested this PR in my dev cluster, it works well and the issue has been fixed. Thanks @cqutwangyu .
> 
> What should be the next step to proceed with this PR?
> 
> @songjianet @cqutwangyu @rickchengx

@cqutwangyu please fix the failed CI

**Comment by cqutwangyu** [comment]
> > I have tested this PR in my dev cluster, it works well and the issue has been fixed. Thanks @cqutwangyu .
> > What should be the next step to proceed with this PR?
> > @songjianet @cqutwangyu @rickchengx
> 
> @cqutwangyu please fix the failed CI

OK, FIXED

**Comment by arlendp** [comment]
> cc @c3Vu @arlendp

i test the pr in local dev environment, it works as expected and did solve https://github.com/apache/dolphinscheduler/issues/15623 @rickchengx

**Review by rickchengx — APPROVED** [review]
LGTM

**Pull request merged**
