### PR TITLE
Split the components into individual package, refactor configurations to use Spring properties

### PR DESCRIPTION
**Pull request by kezhenxu94**
Now only `common.properties` is still using the old configuration, I'll open another PR to refactor it to also use Spring properties

### CODE REVIEW

**Review by CalvinKirs — DISMISSED** [review]

**Review by lenboo — DISMISSED** [review]
+1

**Review by CalvinKirs — DISMISSED** [review]

**Review by CalvinKirs — DISMISSED** [review]
LGTM,

**Comment by CalvinKirs** [comment]
Let us provide a separate PR to fix e2e's errors.

**Comment by kezhenxu94** [comment]
@CalvinKirs @lenboo OK this is good to go now

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
