### PR TITLE
[fix-#14086]The subprocess type node is always in the ready stop state

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

this close:
- #14086

### CODE REVIEW

**Comment by fuchanghai** [comment]
@ruanwenjun @zhuangchong PTAL

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
does it exists in dev branch?

**Comment by fuchanghai** [comment]
> does it exists in dev branch?

> As far as I know, first of all, the latest code branch structure has changed, and it does not judge whether the sub-process instance is finished before stopping the task in the parent workflow
image


image

**Comment by fuchanghai** [comment]
BTW ，I think we should stop the remote execution of the task first. Then judge the status of the remote task, and finally update the task status in the parent process  WDYT@zhongjiajie @ruanwenjun 

```
killRemoteSubprocessInstanc()
if(subprocessInstance.getState.typeisFinish){
currentTask.setState(subprocessInstance.getState)
updateCurrentTaskById
}
```
>或者我们在调用远程任务有返回信息之后，再根据subprocessinstance 的状态来判断是否更新父流程中的task状态
>Or we can judge whether to update the task state in the parent process according to the state of the subprocess instance after calling the remote task and returning information

**Comment by fuchanghai** [comment]
@zhuangchong @zhongjiajie PTAL

**Review by zhuangchong — APPROVED** [review]

**Comment by zhongjiajie** [comment]
@fuchanghai  BTW, next time you can use `close #14086`to let pr close references issue when pr merged

**Comment by fuchanghai** [comment]
> @fuchanghai BTW, next time you can use `close #14086`to let pr close references issue when pr merged

thanks for your reminder

**Pull request merged**
