### PR TITLE
[fix-#13999] add some dependent version

### LINKED ISSUE #13999: [Bug] [bom] some dependent version configurations are missing
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
image
image

### What you expected to happen

add version

### How to reproduce

add version

### Anything else

_No response_

### Version

3.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

add some dependent version
 this close #13999 

## Brief change log

add some dependent version

### CODE REVIEW

**Comment by fuchanghai** [comment]
@zhuangchong

**Comment by zhongjiajie** [comment]
Hello @fuchanghai , thanks for your contribution, but version 3.0.x is prepare to end of life, and I check missing version in bom module will not throw error because they may have version in these module itself, such as https://github.com/apache/dolphinscheduler/blob/dc3c9651342529fcfde47dd0949a0ced18ce9e4a/dolphinscheduler-data-quality/pom.xml#L32, So maybe this pr will not accept for version 3.0.x

**Comment by fuchanghai** [comment]
hi @zhongjiajie If there is a next version of 3.0.x.
I think the bom module should have the function of version management, maybe we should introduce the version of bom in other modules. if 3.0.x ha

**Comment by zhongjiajie** [comment]
> hi @zhongjiajie If there is a next version of 3.0.x.
> I think the bom module should have the function of version management, maybe we should introduce the version of bom in other modules. if 3.0.x ha

do you mean all module versions should be dependent on `dolphinscheduler-bom`? yeah, we should do it, but should not in bugfix version, should be correct the dependent in dev version

**Comment by SbloodyS** [comment]
> do you mean all module versions should be dependent on `dolphinscheduler-bom`? yeah, we should do it, but should not in bugfix version, should be correct the dependent in dev version

Agreed with @zhongjiajie. Closing this PR.

**Pull request closed without merging**
