### PR TITLE
[Fix-7236][common] Fix bug of the host cannot be recognized when the endpoint uses the domain name

### LINKED ISSUE #7236: [Bug] [2.0.0-release]  Failed to create tenant using S3a Minio
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I failed to create tenant when using store as S3a Minio。
The following is my configuration。
```bash
# cat conf/config/install_config.conf |egrep -v "^#|^$"
ips="survey-cdh01,survey-cdh02,survey-cdh03"
sshPort="22"
masters="survey-cdh01,survey-cdh02"
workers="survey-cdh01,survey-cdh02,survey-cdh03"
alertServer="survey-cdh01"
apiServers="survey-cdh01"
installPath="/data/apache-dolphinscheduler-1.3.9/dolphinscheduler"
deployUser="root"
dataBasedirPath="/tmp/dolphinscheduler"
javaHome="/usr/java/jdk1.8.0_181-cloudera"
apiServerPort="12345"
dbtype="mysql"
dbhost="survey-cdh01:3306"
username="dolphinscheduler"
password="dolphinscheduler"
dbname="dolphinscheduler"
registryPluginDir="lib/plugin/registry/zookeeper"
registryPluginName="zookeeper"
registryServers="survey-cdh01:2181,survey-cdh02:2181,survey-cdh03:2181"
zkRoot="/dolphinscheduler"
alertPluginDir="lib/plugin/alert"
taskPluginDir="lib/plugin/task"

resourceStorageType="S3"
resourceUploadPath="/dolphinscheduler"
defaultFS="s3a://dolphinscheduler"
s3Endpoint="http://survey-minio.xxx.com"
s3AccessKey="root"
s3SecretKey="rootroot"

resourceManagerHttpAddressPort="8088"
yarnHaIps="192.168.xx.xx,192.168.xx.xx"
singleYarnIp="yarnIp1"
hdfsRootUser="root"
kerberosStartUp="false"
krb5ConfPath="$installPath/conf/krb5.conf"
keytabUserName="hdfs-mycluster\\@ESZ.COM"
keytabPath="$installPath/conf/hdfs.headless.keytab"
kerberosExpireTime="2"
sudoEnable="false"
workerTenantAutoCreate="true"
```
Survey-minio.xxx.com is my Minio server API address,The bucket and directory exist on the Minio server.

image

An error occurs when I create a tenant on the console。
image

dolphinscheduler-api.log The error information is as follows
```bash
# tail -200 logs/dolphinscheduler-api.log
[INFO] 2021-12-07 16:07:05.645 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:e5437c60-1991-4da7-8c39-6246bec365e3, LOGIN_USER:admin, URI:/dolphinscheduler/queues/list, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.QueueController.queryList, ARGS:{}
[INFO] 2021-12-07 16:07:09.564 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:278cfb2f-67d3-4342-aba6-3c5ba47bd625, LOGIN_USER:admin, URI:/dolphinscheduler/tenants/verify-code, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.verifyTenantCode, ARGS:{tenantCode=root}
[INFO] 2021-12-07 16:07:09.668 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[76] - REQUEST TRANCE_ID:3ef77ec2-d16e-4e35-b347-17e60dbbe5f9, LOGIN_USER:admin, URI:/dolphinscheduler/tenants, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.TenantController.createTenant, ARGS:{queueId=1, description=, tenantCode=root}
[ERROR] 2021-12-07 16:07:09.673 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[46] - 创建租户错误
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.mkdir(HadoopUtils.java:277)
	at org.apache.dolphinscheduler.api.service.impl.BaseServiceImpl.createTenantDirIfNotExists(BaseServiceImpl.java:135)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl.createTenant(TenantServiceImpl.java:116)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$FastClassBySpringCGLIB$$fcc8d845.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:752)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.apache.dolphinscheduler.api.service.impl.TenantServiceImpl$$EnhancerBySpringCGLIB$$89fb9fab.createTenant(<generated>)
	at org.apache.dolphinscheduler.api.controller.TenantController.createTenant(TenantController.java:91)
	at org.apache.dolphinscheduler.api.controller.TenantController$$FastClassBySpringCGLIB$$24aaa089.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:752)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.apache.dolphinscheduler.api.aspect.AccessLogAspect.doAround(AccessLogAspect.java:87)
	at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.apache.dolphinscheduler.api.controller.TenantController$$EnhancerBySpringCGLIB$$527efca8.createTenant(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1633)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:561)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

I failed to create tenant when using store as S3a Minio。

### How to reproduce

I failed to create tenant when using store as S3a Minio。

### Anything else

_No response_

### Version

2.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liqiquan**
## Purpose of the pull request
fix: #7236

## Brief change log
1. Upgrade hadoop version to 2.8.5
2. Added fs.s3a.path.style.access configuration, default false
3. Contains the jar packages and related licenses that hadoop 2.8.5 depends on

## Verify this pull request

There are no test cases for now. Our company's internal dolphin scheduler version also upgraded hadoop to 2.8.5, which solved this problem and ran normally after going online.

### CODE REVIEW

**Comment by liqiquan** [comment]
@caishunfeng @BaoLiang 
Help take a look at the submission. The hadoop official has revised this problem (https://issues.apache.org/jira/browse/HADOOP-12963), to solve this problem, you need to upgrade the hadoop version to 2.8.x. Considering the usage, the hadoop 2.8.5 version was chosen
帮忙看一下提交。 hadoop官方已修改此问题(),解决这个问题需要把hadoop版本升级到2.8.x。考虑到使用量，选择了hadoop 2.8.5版本

**Comment by caishunfeng** [comment]
> ## Purpose of the pull request
> fix bug：#7236
> 
> ## Brief change log
> ## Verify this pull request
> This pull request is code cleanup without any test coverage.
> 
> _(or)_
> 
> This pull request is already covered by existing tests, such as _(please describe tests)_.
> 
> (or)
> 
> This change added tests and can be verified as follows:

Please describe the brief change log and any test for this pr.

**Comment by liqiquan** [comment]
> brief change
I added brief change. There are no test cases for now, but the relevant code modifications have passed the internal test of our company and have been launched.

**Comment by caishunfeng** [comment]
I had approve to run the CI test.

**Comment by SbloodyS** [comment]
There is a certain conflict between this pr and #8367. @caishunfeng

**Comment by caishunfeng** [comment]
> There is a certain conflict between this pr and #8367. @caishunfeng

@SbloodyS Thanks your feedback, but the #8367 is about COMPLEMENT_DATA bugfix, and this pr is about s3a, it seems no conflict.

**Comment by caishunfeng** [comment]
> SonarCloud Quality Gate failed.    Quality Gate failed
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [C](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [29 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [9 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL) [462 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_coverage&view=list) [1.2% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_duplicated_lines_density&view=list)

@liqiquan Please check the sonar and CI check.

**Comment by SbloodyS** [comment]
> > There is a certain conflict between this pr and #8367. @caishunfeng
> 
> @SbloodyS Thanks your feedback, but the #8367 is about COMPLEMENT_DATA bugfix, and this pr is about s3a, it seems no conflict.

Sorry for my mistake. It's #8637.

**Comment by caishunfeng** [comment]
> Sorry for my mistake. It's #8637.

Thanks, they all about s3a. I am not familiar about s3a, so PTAL @nobolity @SbloodyS

**Comment by liqiquan** [comment]
> > SonarCloud Quality Gate failed.    Quality Gate failed
> > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [C](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [29 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [9 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL) [462 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_coverage&view=list) [1.2% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_duplicated_lines_density&view=list)
> 
> @liqiquan Please check the sonar and CI check.



> > SonarCloud Quality Gate failed.    Quality Gate failed
> > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [C](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [29 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [9 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL) [462 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=8547&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_coverage&view=list) [1.2% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=8547&metric=new_duplicated_lines_density&view=list)
> 
> @liqiquan Please check the sonar and CI check.
The error reported by sonar is basically the problem of the js code of the dolphinscheduler-ui module, but my submission does not involve this module

**Comment by liqiquan** [comment]
@caishunfeng
Ask a question, the code I submitted does not involve the dolphinscheduler-ui module, why is there a large number of errors in the js code of the dolphinscheduler-ui module in the sonar report?

**Comment by caishunfeng** [comment]
> @caishunfeng Ask a question, the code I submitted does not involve the dolphinscheduler-ui module, why is there a large number of errors in the js code of the dolphinscheduler-ui module in the sonar report?

It seems the sonar will check all the project files, not only the change files. You can skip the UI errors if you don't update the UI module. 
But you have to check the CI build fail. see https://dolphinscheduler.apache.org/en-us/community/development/DS-License.html.
PTAL again @nobolity @lenboo

**Comment by liqiquan** [comment]
@caishunfeng 
Can you help to run the ci test again?

**Comment by caishunfeng** [comment]
> @caishunfeng Can you help to run the ci test again?

Of course, I had approved it.

**Comment by liqiquan** [comment]
@caishunfeng 
Please help to run the ci test again, thx

**Pull request closed without merging**
