### PR TITLE
[WIP][fix] Database init error in dev branch

### LINKED ISSUE #10120: [Bug] [db] Raise database object duplicate when build and create-ds.sh in branch dev
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When i build binary tarball from branch dev, then change database connection type to pg or mysql. It will raise duplicate object, such as duplicate index or column, it because we do not change the version in table `t_ds_version` and will upgrade when we finish the database init

### What you expected to happen

ATT

### How to reproduce

ATT

### Anything else

ATT

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
close: #10120

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I will add some tests on it after version 3.0.0-beta-1 released

**Comment by SbloodyS** [comment]
I think we should create a more elegant way to initialize ```t_ds_version``` instead of modifying it before each release. Just as #9484

**Comment by zhongjiajie** [comment]
you're right. we should do that

**Comment by davidzollo** [comment]
is this pr still in WIP?

**Comment by davidzollo** [comment]
is this pr still in WIP?

**Comment by caishunfeng** [comment]
Will close this pr due to no update for a long time.

**Pull request closed without merging**
