### PR TITLE
[Feat]Restore presto and spark sql datasource in datasource plugin module

### PR DESCRIPTION
**Pull request by sparklezzz**
## Purpose of the pull request

Restore presto sql and spark sql datasource in datasource plugin module, which were removed during refactor in v2.0.1 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by lenboo** [comment]
@sparklezzz 
Is there an issue that can be associated with this PR?

**Comment by mgduoduo** [comment]
Looking forward to an early merger. we can't config the presto connection now after upgrading to version 2.0.3,  
error: "datasource plugin 'presto' is not found"
however it works fine in 2.0.0.

**Comment by Narcasserun** [comment]
Maybe we can expose the jdbcUrl parameter without ds assembling it by ourselves, which can reduce a lot of repetitive code, and can reuse the same logic like hive, presto, spark, etc.

**Review by Narcasserun — COMMENTED** [review]
There are a lot of duplicate codes in hive, Presto and spark data sources. Maybe we should reuse logic

**Comment by EricJoy2048** [comment]
Hi @sparklezzz  I have the same problem. When can you come back？

**Review by caishunfeng — APPROVED** [review]
LGTM

**Pull request merged**
