### PR TITLE
[Fix-10895][standalone] fix standalone-server view task log

### PR DESCRIPTION
**Pull request by liguotian**
* add logger server to StandaloneServer
* add logback-standalone.xml file for StandaloneServer
* add log.config param to dolphinscheduler-daemon.sh start func

### CODE REVIEW

**Comment by liguotian** [comment]
#10912   I have recreate a PR  ,and modify usage of LoggerServer  @caishunfeng . please approve

**Comment by liguotian** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=10933)
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [E](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [53 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [B](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [6 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [11 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [1333 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [19.0% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list) [4.6% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list)

I have no idea ，i guess because of this PR is my FIRST ANALYSIS for Sornar 。see [Sornar Lastest ANALYSIS](https://sonarcloud.io/project/overview?id=apache-dolphinscheduler) 🤷🏻‍♀️。

**Comment by ruanwenjun** [comment]
> > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=10933)
> > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [E](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [53 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [B](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [6 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [11 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [1333 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [19.0% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list) [4.6% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list)
> 
> I have no idea ，i guess because of this PR is my FIRST ANALYSIS for Sornar 。see [Sornar Lastest ANALYSIS](https://sonarcloud.io/project/overview?id=apache-dolphinscheduler) 🤷🏻‍♀️。

This is caused by the image 2.0.6 doesn't release :).

**Comment by liguotian** [comment]
> 

These two checks can be skipped ？ or what we should do next?

**Comment by liguotian** [comment]
> > > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=10933)
> > > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [E](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [53 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [B](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [6 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [11 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [1333 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL)
> > > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [19.0% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list) [4.6% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list)
> > 
> > 
> > I have no idea ，i guess because of this PR is my FIRST ANALYSIS for Sornar 。see [Sornar Lastest ANALYSIS](https://sonarcloud.io/project/overview?id=apache-dolphinscheduler) 🤷🏻‍♀️。
> 
> This is caused by the image 2.0.6 doesn't release :).

These two checks can be skipped ？ or what we should do next?

**Comment by ruanwenjun** [comment]
> > > > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=10933)
> > > > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [E](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [53 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [B](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [6 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [11 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [1333 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL)
> > > > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [19.0% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list) [4.6% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list)
> > > 
> > > 
> > > I have no idea ，i guess because of this PR is my FIRST ANALYSIS for Sornar 。see [Sornar Lastest ANALYSIS](https://sonarcloud.io/project/overview?id=apache-dolphinscheduler) 🤷🏻‍♀️。
> > 
> > 
> > This is caused by the image 2.0.6 doesn't release :).
> 
> These two checks can be skipped ？ or what we should do next?

Sorry, the sornar check faild is caused by the code smell, need to change the code.

**Comment by liguotian** [comment]
> > > > > SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=10933)
> > > > > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [E](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [53 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [B](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [6 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [11 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL) [1333 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10933&resolved=false&types=CODE_SMELL)
> > > > > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [19.0% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list) [4.6% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10933&metric=new_duplicated_lines_density&view=list)
> > > > 
> > > > 
> > > > I have no idea ，i guess because of this PR is my FIRST ANALYSIS for Sornar 。see [Sornar Lastest ANALYSIS](https://sonarcloud.io/project/overview?id=apache-dolphinscheduler) 🤷🏻‍♀️。
> > > 
> > > 
> > > This is caused by the image 2.0.6 doesn't release :).
> > 
> > 
> > These two checks can be skipped ？ or what we should do next?
> 
> Sorry, the sornar check faild is caused by the code smell, need to change the code.

It's OK , If you need me to do anything, please let me know

**Pull request closed without merging**
