### PR TITLE
[fix-#11689] change replaceAll to replace in method of tryExecuteSqlResolveColumnNames

### LINKED ISSUE #11689: [Bug] [DataX] change replaceAll to replace
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
if use replaceAll which parses a regular expression .so create_time be changed to crea_me

### What you expected to happen

be right

### How to reproduce

change to replace

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
…SqlResolveColumnNames

## Brief change log

change replaceAll to replace in method of tryExecuteSqlResolveColumnNames
## Verify this pull request

This pull request is code cleanup without any test coverage.

this close  #11689

### CODE REVIEW

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
Could you please add UT for this, in fact, `replace` is the same as `replaceAll`, will replace all matched.

**Review by ruanwenjun — APPROVED** [review]
Sorry, I missunstanderstand, this bug is caused by we didn't translate `.`

**Comment by fuchanghai** [comment]
> Could you please add UT for this, in fact, `replace` is the same as `replaceAll`, will replace all matched.

you can see the issue #11689

**Comment by fuchanghai** [comment]
> Sorry, I missunstanderstand, this bug is caused by we didn't translate `.`

thanks for your review

**Pull request merged**
