### PR TITLE
[1.3.6-prepare][Improvement][UI] Update the column name of the duration field on the instance UI page

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

Update the column name of the duration field on the instance UI page1.3.6 imp UI duration 1

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhuangchong** [comment]
@chenxingchun

**Comment by xingchun-chen** [comment]
Pull the latest code, E2E has been closed

**Comment by xingchun-chen** [comment]
In the Chinese version, the s of the task instance page is not removed?

**Comment by zhuangchong** [comment]
> In the Chinese version, the s of the task instance page is not removed?

The S logo was written in the VUE file, and both Chinese and English were changed

**Comment by zhuangchong** [comment]
> Pull the latest code, E2E has been closed

An update has been made, but it is still an exception

**Pull request merged**
