### PR TITLE
[python] Add param workgroup to process definition

### PR DESCRIPTION
**Pull request by zhongjiajie**
## Purpose of the pull request

This patch add work group to process definition. ref #6407

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Hi @caishunfeng maybe you could use this PR for template test

**Comment by caishunfeng** [comment]
> Hi @caishunfeng maybe you could use this PR for template test

Well done. Thanks ~

**Comment by zhongjiajie** [comment]
I think is good to go now, PTAL @CalvinKirs @lenboo

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by lenboo — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
