### PR TITLE
[Fix-13413][Master]Empty dependency operation causes Master null pointer exception

### LINKED ISSUE #13413: [Improvement] [Master] Empty dependency operation causes Master null pointer exception
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建一个空的依赖，运行后工作流一直处于"正在执行"状态

### What you expected to happen

空的依赖应该运行成功

### How to reproduce

image
创建一个依赖节点，但是不添加依赖，点击保存
image
点击运行，依赖节点一直处于”正在执行“状态。

### Anything else

image
MasterServer报空指针异常

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lsy1072915121**
## Purpose of the pull request
Improve #13413 

## Brief change log

Assign a default value to an empty dependency

## Verify this pull request
image

 empty dependency run successfully

### CODE REVIEW

**Review by EricGao888 — COMMENTED** [review]
@JinyLeeChina Looks like this PR targets `2.0.8-prepare`, could u plz take a look? thanks

**Comment by EricGao888** [comment]
@lsy1072915121 Could u plz fix the PR title and keep it in one line? Thx

**Comment by lsy1072915121** [comment]
> @lsy1072915121 Could u plz fix the PR title and keep it in one line? Thx

OK,I fixed

**Comment by JinyLeeChina** [comment]
Hi @lsy1072915121 , I think if there is no specific dependency, it should not be saved successfully. You can modify like this
image

**Comment by brave-lee** [comment]
Hi @lsy1072915121 , I think if there is no specific dependency, it should not be saved successfully. You can modify like this
image

**Comment by lsy1072915121** [comment]
@JinyLeeChina Hi,It's also a good way.But I think it is better to add verification when saving dependency node rather than when saving workflow

**Comment by brave-lee** [comment]
> @JinyLeeChina Hi,It's also a good way.But I think it is better to add verification when saving dependency node rather than when saving workflow

I don't think so, many people do not use ui, but use the rest api.

**Review by brave-lee — APPROVED** [review]
+1

**Pull request merged**
