### PR TITLE
[Fix-16410] wrong env in values.yaml

### LINKED ISSUE #16410: [Bug] [Helm] env `DEFAULT_TENANT_ENABLED` is not taking effect.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The env variable for worker "DEFAULT_TENANT_ENABLED" is not taking effect.
Worker 的 env 配置 "DEFAULT_TENANT_ENABLED" 不生效。

https://github.com/apache/dolphinscheduler/blob/aabda868daabe938e4894f1886d56def9401651c/deploy/kubernetes/dolphinscheduler/values.yaml#L691
https://github.com/apache/dolphinscheduler/blob/aabda868daabe938e4894f1886d56def9401651c/deploy/kubernetes/dolphinscheduler/README.md?plain=1#L310

### What you expected to happen

The Bootstrap User is used as the execution user.
启动用户会被用作执行用户。

### How to reproduce

When deploying via Helm, set worker.env.DEFAULT_TENANT_ENABLED to true, and use 'default' as the tenant to trigger the workflow, then observe whether the Bootstrap User is used as the execution user.
在通过 Helm 部署时设置 worker.env.DEFAULT_TENANT_ENABLED 为 true，并使用 default 作为租户触发工作流，观察是否使用 Bootstrap User 作为执行用户。

### Anything else

The purpose of this environment variable configuration is to override the Spring configuration item at https://github.com/apache/dolphinscheduler/blob/aabda868daabe938e4894f1886d56def9401651c/dolphinscheduler-worker/src/main/resources/application.yaml#L70. 
该环境变量配置的目的是覆盖 /dolphinscheduler-worker/src/main/resources/application.yaml#L70 的 Spring 配置项。

According to the Spring Externalized Configuration documentation, the environment variable should be named WORKER_TENANT_CONFIG_DEFAULT_TENANT_ENABLED rather than the current DEFAULT_TENANT_ENABLED.
根据 Spring Externalized Configuration 文档的说明，该环境变量应该命名为 `WORKER_TENANT_CONFIG_DEFAULT_TENANT_ENABLED` 而非目前的 `DEFAULT_TENANT_ENABLED`。

ref:
https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yelijing18**
## Purpose of the pull request

fix #16410

## Brief change log

fix wrong env in values.yaml and Readme for K8s deploy.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by Gallardot** [comment]
Thank you for your contribution. LGTM. But please make CI happy first.

Please execute `./mvnw validate -P helm-doc -pl :dolphinscheduler` in your fork

**Comment by yelijing18** [comment]
> Thank you for your contribution. LGTM. But please make CI happy first.
> 
> Please execute `./mvnw validate -P helm-doc -pl :dolphinscheduler` in your fork

Already done. 
Thanks for your guidance.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by Gallardot — APPROVED** [review]
LGTM.
But it looks like there are some issues with the docker version. @SbloodyS  is working on it.

**Pull request merged**
