### PR TITLE
[Feature][Github] Add stale mechanism to auto mark issues and PRs as stale

### LINKED ISSUE #8074: [Feature][Github] Add stale mechanism to auto mark issues and PRs as stale
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We should add stale mechanism to auto mark issues and PRs as stale status to control the number, which can also remind us which need to be picked up again.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of the pull request

Fixes #8074

### CODE REVIEW

**Comment by davidzollo** [comment]
good job

**Review by davidzollo — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
@asdf2014 We already have stale GA in https://github.com/apache/dolphinscheduler/blob/dev/.github/workflows/stale.yml, I am not sure what would be going on with multiple stale configuration

**Comment by kezhenxu94** [comment]
This PR should not be merged. The configuration file `stale.yml` is for GitHub App https://github.com/apps/stale and we never ask infra to enable it in our repo. What's more, as @zhongjiajie pointed out, we already have workflow to mark stale issues, there is no point to add another duplicate one... @zhongjiajie do you mind reverting this?

**Comment by zhongjiajie** [comment]
> This PR should not be merged. The configuration file `stale.yml` is for GitHub App https://github.com/apps/stale and we never ask infra to enable it in our repo. What's more, as @zhongjiajie pointed out, we already have workflow to mark stale issues, there is no point to add another duplicate one... @zhongjiajie do you mind reverting this?

Thanks @kezhenxu94 to point it out. I have forget about we have stale Github App

**Pull request merged**
