### PR TITLE
[Fix-11376][task plugin]Seatunnel Task cannot save successfully when …

### LINKED ISSUE #11376: [Bug] [Task Plugin] Seatunnel Task cannot save successfully when select spark engine
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
image

### What you expected to happen

I can save Seatunnel task successfully.

### How to reproduce

Above

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shangeyao**
## Purpose of the pull request

close #11376

### CODE REVIEW

**Review by zhuangchong — CHANGES_REQUESTED** [review]
After the modification, there is still a logical problem this time. I understand that it is to verify some parameters under specified conditions. 
It is recommended to modify it like this: 

```
        boolean result = super.checkParameters() && Objects.nonNull(deployMode);
        if (result && DeployModeEnum.local != deployMode) {
            result = Objects.nonNull(master);
            if (result && (MasterTypeEnum.SPARK == master || MasterTypeEnum.MESOS == master)) {
                result = StringUtils.isNotBlank(masterUrl);
            }
        }
        return result;
```

**Comment by shangeyao** [comment]
> After the modification, there is still a logical problem this time. I understand that it is to verify some parameters under specified conditions. It is recommended to modify it like this:
> 
> ```
>         boolean result = super.checkParameters() && Objects.nonNull(deployMode);
>         if (result && DeployModeEnum.local != deployMode) {
>             result = Objects.nonNull(master);
>             if (result && (MasterTypeEnum.SPARK == master || MasterTypeEnum.MESOS == master)) {
>                 result = StringUtils.isNotBlank(masterUrl);
>             }
>         }
>         return result;
> ```

After my test, I found that the two code segments have the same effect.

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhuangchong** [comment]
It has been merged into the 3.1.0 branch.

**Pull request merged**
