### PR TITLE
[Improvement] Remove redundant and security vulnerable code

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Remove redundant and potentially risky code.
* Users could use `K8S connection` in `Connection(Datasource) Center` to submit task to K8S clusters. There is absolutely no need to have a K8S cluster management console in Dolphin, which only leads to potential vulnerabilities.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM.

**Comment by kezhenxu94** [comment]
Do we have any related docs to remove?

**Comment by EricGao888** [comment]
> Do we have any related docs to remove?

Good catch, on the way : )

**Review by kezhenxu94 — DISMISSED** [review]

**Review by kezhenxu94 — COMMENTED** [review]
Let's also remove the mapper and sql definitions

**Comment by EricGao888** [comment]
Just figured out in spark / flink tasks, there are still places using cluster management stuff. I need to refactor related code to completely get rid of k8s management stuff.

**Comment by ruanwenjun** [comment]
Thanks for cleaning this kind of code.

**Comment by EricGao888** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity for 120 days. It will be closed in 7 days if no further activity occurs.

NO stale

**Pull request closed without merging**
