### PR TITLE
[Improvement][API] the ProcessDefinitionServiceImpl defineIdList collection traversal code optimization.

### PR DESCRIPTION
**Pull request by zhuangchong**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds checkstyle plugin.)*

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Review by chengshiwen — CHANGES_REQUESTED** [review]
This change is too little, can you find and replace the global magic number with the `Constants`?

**Comment by zhuangchong** [comment]
> This change is too little, can you find and replace the global magic number with the `Constants`?

The main optimization is in collection traversal

image

**Comment by chengshiwen** [comment]
> > This change is too little, can you find and replace the global magic number with the `Constants`?
> 
> The main optimization is in collection traversal
> 
> image

Also too small. Don't submit pr for pr

**Comment by zhuangchong** [comment]
> Also too small. Don't submit pr for pr

Small code change, just for PR?

You can think the part I changed is not reasonable, or I can close it, but this is to submit PR for PR?

**Comment by chengshiwen** [comment]
You are already a senior contributor, you can try to solve more difficult problems, such as the issues that have not been resolved for a long time. These simple problem or improvements can be used as issues and left to contributors who are just getting started

**Comment by chengshiwen** [comment]
As senior contributors, we can try to solve more difficult problems, such as the issues that have not been resolved for a long time. These simple problems or improvements can be used as issues and left to contributors who are just getting started

**Comment by CalvinKirs** [comment]
> As senior contributors, we can try to solve more difficult problems, such as the issues that have not been resolved for a long time. These simple problems or improvements can be used as issues and left to contributors who are just getting started

If it belongs to the BUG type and is very urgent, you can do it yourself, and you can leave it to new contributors for other types. You can help guide and provide help as a mentor.

**Pull request closed without merging**
