### PR TITLE
[Improvement][UI] Hot fix for timeout when uploading large files to resource center

### LINKED ISSUE #10340: [Bug] [dolphinscheduler-api] HDFS failed to upload large file
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在配置HDFS之后使用资源中心上传过大的文件（90MB）失败，小文件可以。猜想：不能上传超过HDFS数据块大小（64MB）的文件，查看日志错误信息：没有合适的分解器。
image

### What you expected to happen

在之前版本（2.0.5）中，该功能正常可以使用，升级版本3.0.0-alpha，3.0.0-beta-1均不能正常使用。

### How to reproduce

集群部署完成后，配置HDFS，使用的Hadoop 集群 NameNode 配置了 HA ，完成之后上传一个128MB（超过HDFS数据块）以上的文件

### Anything else

问题每次都出现，相关的日志再安装目录下面的api-server/logs下的最新文件中

### Version

3.0.0-beta-1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xingnull**
## Purpose of the pull request

Fix #10340

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by EricGao888** [comment]
@xingnull Great job! Thanks for submitting this PR. It is a hot fix for #10340 which blocks a few users as stated in https://github.com/apache/dolphinscheduler/issues/10340#issuecomment-1223456773

@songjianet @Amy0104 Please take a look when available. Thanks!

@xingnull BTW you could add a short description for your PR and use `related: #10340` to make this PR linked to the related issue.

**Review by EricGao888 — APPROVED** [review]

**Comment by songjianet** [comment]
Is there any way to resolve this interface from backend or hardware resources. Whether it can be optimized in the form of data stream sharding. @xingnull

**Comment by fuchanghai** [comment]
@songjianet @xingnull @EricGao888 For the file upload part, I recommend cutting large files into small files for upload. After all the files are uploaded, the backend merges the small files into large files

**Comment by zhongjiajie** [comment]
So is there any update here? can we release this into version 3.0.x?

**Comment by LiJie20190102** [comment]
It seems that I have encountered the same problem. When there are a large number of taskInstances (for example, 1715952 records), the interface request will report an error. Is this the same question? If yes, can this time parameter be changed to configurable。
image

**Comment by zhongjiajie** [comment]
> It seems that I have encountered the same problem. When there are a large number of taskInstances (for example, 1715952 records), the interface request will report an error. Is this the same question? If yes, can this time parameter be changed to configurable。
> image

@LiJie20190102 not the same, this is because upload file too large cause too many time, and your just because too may history data, you can delete some of history data in your metadata to make it quick

**Pull request closed without merging**
