### PR TITLE
[Improvement-6151] Performance optimization of DEPENDENT task

### PR DESCRIPTION
**Pull request by wangyizhi1**
#6151

### CODE REVIEW

**Review by songjianet — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
FYI @Wangyizhi1 @caishunfeng @songjianet , this PR does not target #6151 , it causes issue #6151 still open. It would make our issue hard to maintain, please take care of this next time, thanks

**Comment by zhongjiajie** [comment]
We should use keyword `fix #6151` or `close: #6151` to target issue in PR

**Comment by wangyizhi1** [comment]
> We should use keyword `fix #6151` or `close: #6151` to target issue in PR

@zhongjiajie  Sorry, i will take care of this next time

**Pull request merged**
