### PR TITLE
[Improvement] Optimize ServerLoadProtection.

### PR DESCRIPTION
**Pull request by Zzih**
## Purpose of the pull request

- Fix the issue where configurations couldn't load properly due to case sensitivity
- add configuration validation
- and modify error log messages.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Are you sure there will exist `case sensitivity` problem? add configuration LGTM, some change should already exist in https://github.com/apache/dolphinscheduler/pull/15803

**Comment by ruanwenjun** [comment]
Please resolve the conflicts.

**Comment by Zzih** [comment]
> LGTM

In the Kubernetes environment, I couldn't inject **MASTER_SERVER_LOAD_PROTECTION_MAX_JVM_MEMORY_USAGE_PERCENTAGE_THRESHOLDS** into`maxJVMMemoryUsagePercentageThresholds` as configured. However, modifying it to`maxJvmMemoryUsagePercentageThresholds` does allow successful injection. I suspect this might be related to the getters and setters generated by Lombok.

**Comment by Zzih96** [comment]
> 请解决冲突。

LGTM

> 请解决冲突。



> Please resolve the conflicts.



> Please resolve the conflicts.

I'll give it a try.

**Comment by Zzih** [comment]
> Please resolve the conflicts.

I'll give it a try.

**Pull request closed without merging**
