### PR TITLE
fix dependent task when the dependent on process have forbidden tasks

### LINKED ISSUE #10899: [Bug] [dependent task] dependent task failed when the process to be dependent on that have forbidden to run task
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

a process PA contain any forbidden to run task , when process PB have task TB dependent on PA, then TB will fail.
But in dolphin2.0.5 this scenario will work.

### What you expected to happen

work as before

### How to reproduce

a process PA contain any forbidden to run task , when process PB have task TB dependent on PA, then TB will fail.

### Anything else

_No response_

### Version

2.0.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lordk911**
close [#10899](https://github.com/apache/dolphinscheduler/issues/10899)

### CODE REVIEW

**Review by brave-lee — COMMENTED** [review]
Depending on a single task will also have this bug, please fix it

**Comment by brave-lee** [comment]
> Depending on a single task will also have this bug, please fix it
Can refer to
`    private DependResult getDependTaskResult(ProcessInstance processInstance, long taskCode, DateInterval dateInterval) {
        TaskInstance taskInstance = processService.findLastTaskInstanceInterval(taskCode, dateInterval);
        if (taskInstance == null) {
            TaskDefinition taskDefinition = processService.findTaskDefinitionByCode(taskCode);
            if (taskDefinition == null) {
                logger.error("Cannot find the task definition, something error, taskCode: {}", taskCode);
                return DependResult.FAILED;
            }
            if (taskDefinition.getFlag() == Flag.NO) {
                logger.warn("Cannot find the task instance, but the task is forbidden, so dependent success, taskCode: {}, taskName: {}", taskCode, taskDefinition.getName());
                return DependResult.SUCCESS;
            }
            if (!processInstance.getState().typeIsFinished()) {
                logger.info("Wait for the dependent workflow to complete, taskCode:{}, processInstanceId:{}, processInstance state:{}",
                        taskCode, processInstance.getId(), processInstance.getState());
                return DependResult.WAITING;
            }
            logger.warn("Cannot find the task in the process instance when the ProcessInstance is finish, taskCode: {}, taskName: {}", taskCode, taskDefinition.getName());
            return DependResult.FAILED;
        } else {
            logger.info("The running task, taskId:{}, taskCode:{}, taskName:{}", taskInstance.getId(), taskInstance.getTaskCode(), taskInstance.getName());
            return getDependResultByState(taskInstance.getState());
        }
    }`

**Comment by lordk911** [comment]
> > Depending on a single task will also have this bug, please fix it
> > Can refer to
> > `    private DependResult getDependTaskResult(ProcessInstance processInstance, long taskCode, DateInterval dateInterval) {         TaskInstance taskInstance = processService.findLastTaskInstanceInterval(taskCode, dateInterval);         if (taskInstance == null) {             TaskDefinition taskDefinition = processService.findTaskDefinitionByCode(taskCode);             if (taskDefinition == null) {                 logger.error("Cannot find the task definition, something error, taskCode: {}", taskCode);                 return DependResult.FAILED;             }             if (taskDefinition.getFlag() == Flag.NO) {                 logger.warn("Cannot find the task instance, but the task is forbidden, so dependent success, taskCode: {}, taskName: {}", taskCode, taskDefinition.getName());                 return DependResult.SUCCESS;             }             if (!processInstance.getState().typeIsFinished()) {                 logger.info("Wait for the dependent workflow to complete, taskCode:{}, processInstanceId:{}, processInstance state:{}",                         taskCode, processInstance.getId(), processInstance.getState());                 return DependResult.WAITING;             }             logger.warn("Cannot find the task in the process instance when the ProcessInstance is finish, taskCode: {}, taskName: {}", taskCode, taskDefinition.getName());             return DependResult.FAILED;         } else {             logger.info("The running task, taskId:{}, taskCode:{}, taskName:{}", taskInstance.getId(), taskInstance.getTaskCode(), taskInstance.getName());             return getDependResultByState(taskInstance.getState());         }     }`

thanks, I've just reuse your code @JinyLeeChina

**Review by brave-lee — APPROVED** [review]
+1

**Pull request merged**
