### PR TITLE
[Fix-#4840][worker] fix master fault tolerance when startup

### LINKED ISSUE #4840: [Bug][Master] Master cannot fault tolerant when multiple Masters start at the same time
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
If multiple Masters are started at the same time, it will cause global fault tolerance logic errors. Multiple Masters that are online at the same time are recognized, fault tolerant will be skipped
多个Master同时启动，会导致全局容错逻辑错误，识别到多个同时在线的Master，会跳过容错
image
image
image

**Expected behavior**
Master registration Zookeeper and start fault tolerance at the same time
Master 注册Zookeeper和启动容错同时进行

**Which version of Dolphin Scheduler:**
 -[1.3.*]

### PR DESCRIPTION
**Pull request by vimacro**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

This closes #4840 

## Brief change log

- Fix  master fault tolerance when startup

## Verify this pull request

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by chengshiwen — COMMENTED** [review]
Is it better to move `this.masterRegistry.unRegistry()` in `this.zkMasterClient.close()` as well?

**Comment by zhanguohao** [comment]
> Is it better to move `this.masterRegistry.unRegistry()` in `this.zkMasterClient.close()` as well?
Here is still needed, need to cancel the registration in time when the program exits

**Comment by vimacro** [comment]
> Is it better to move `this.masterRegistry.unRegistry()` in `this.zkMasterClient.close()` as well?

good idea !

**Review by chengshiwen — APPROVED** [review]
+1

**Pull request merged**
