### PR TITLE
[Feature-11129] [API] Refactor org.apache.dolphinscheduler.api.controller.ProcessDefinitionController

### LINKED ISSUE #11129: [API] Refactor org.apache.dolphinscheduler.api.controller.ProcessDefinitionController
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

accroding to [DSIP-7] [API] Suggest refactor the backend api https://github.com/apache/dolphinscheduler/issues/10257

**Suggested optimization**
* Content-Type change to `application/json`
* Add more example to api doc
* Improve the accuracy of error reporting
* The input and output parameters of API should use entity
* Rename all `process` to `workflow` in interface

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MichaelDeSteven**
## Purpose of the pull request
close #11129 

## change log
* refactor ProcessDefinitionService interface：use `Result` to replace `Map<String, Object>`
* add WorkflowDefinitionController

### CODE REVIEW

**Comment by MichaelDeSteven** [comment]
@caishunfeng @SbloodyS this pr is ready to review. plz take a look.

**Comment by SbloodyS** [comment]
I haven't seen any v2 controller in this PR. Is there something missing? @MichaelDeSteven

**Comment by MichaelDeSteven** [comment]
> I haven't seen any v2 controller in this PR. Is there something missing? @MichaelDeSteven

@SbloodyS the refactor work is so huge. I want to split the refactor task as small as possible. Hoping this way can make refactor task going well.  
this pr is first step. After that, I will continue v2 controller task.

**Comment by SbloodyS** [comment]
> > I haven't seen any v2 controller in this PR. Is there something missing? @MichaelDeSteven
> 
> @SbloodyS the refactor work is so huge. I want to split the refactor task as small as possible. Hoping this way can make refactor task going well. this pr is first step. After that, I will continue v2 controller task.

So we split the refactor task to a single function. Each pr should contain at least one refactor function and its related modifications. It is not recommended to submit irrelevant things in advance.

**Comment by MichaelDeSteven** [comment]
> > > I haven't seen any v2 controller in this PR. Is there something missing? @MichaelDeSteven
> > 
> > 
> > @SbloodyS the refactor work is so huge. I want to split the refactor task as small as possible. Hoping this way can make refactor task going well. this pr is first step. After that, I will continue v2 controller task.
> 
> So we split the refactor task to a single function. Each pr should contain at least one refactor function and its related modifications. It is not recommended to submit irrelevant things in advance.


how about this,  I will add some interface in v2 controller base on this pr. after the pr is merged, I will continue pr #11148 to finish the rest of interface？

**Comment by SbloodyS** [comment]
If you think the refactor work is too large. You can submit a PR for each refactor method. @MichaelDeSteven

**Comment by MichaelDeSteven** [comment]
> If you think the refactor work is too large. You can submit a PR for each refactor method. @MichaelDeSteven

the tough part is solved in this pr. I will complete v2 controller task in this pr. code review may take some time. but that would be all right.

**Comment by SbloodyS** [comment]
> > If you think the refactor work is too large. You can submit a PR for each refactor method. @MichaelDeSteven
> 
> the tough part is solved in this pr. I will complete v2 controller task in this pr. code review may take some time. but that would be all right.

In the mean time, you can convert this pr to draft. And mark it as ready to review after you finish your work.

**Pull request closed without merging**
