### PR TITLE
[Improvement-11013][dolphinscheduler-common] YarnHAAdminUtils#getActiveRMName function Add HTTPS Hadoop environment support 

### LINKED ISSUE #11013: [Improvement][Common] YarnHAAdminUtils#getActiveRMName function can not supported HTTPS Hadoop environment
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

HTTP requests are hard-coded in this place, and HTTPS Hadoop environment cannot be supported
 
image

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liyangyang-12138**
## Purpose of the pull request

**YarnHAAdminUtils#getActiveRMName function Add HTTPS Hadoop environment support**

This closes #11013

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @liyangyang-12138 , please associate the issue.

**Comment by SbloodyS** [comment]
@liyangyang-12138 Please fix the checkstyle error.

**Comment by liyangyang-12138** [comment]
@SbloodyS trouble to help me retry check process ,thanks ~~~

**Comment by SbloodyS** [comment]
> @SbloodyS trouble to help me retry check process ,thanks ~~~

Done.

**Comment by liyangyang-12138** [comment]
@SbloodyS ask for advice,what tools can help me check in advance to avoid multiple errors,thanks~~~

**Comment by SbloodyS** [comment]
> @SbloodyS ask for advice,what tools can help me check in advance to avoid multiple errors,thanks~~~

You can take a look at the checkstyle part in `https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html` and check it locally.

**Comment by liyangyang-12138** [comment]
@SbloodyS I have seen this address and configured it,But he can't check the Test-class code, If it's not my configuration error, I'll try to modify check-style.xml. please  help me click check-process for me again,thanks~~

**Comment by liyangyang-12138** [comment]
> > @SbloodyS trouble to help me retry check process ,thanks ~~~
> 
> Done.

tanks~~

**Comment by liyangyang-12138** [comment]
> > @SbloodyS trouble to help me retry check process ,thanks ~~~
> 
> Done.

tanks~~

**Comment by liyangyang-12138** [comment]
> > @SbloodyS ask for advice,what tools can help me check in advance to avoid multiple errors,thanks~~~
> 
> You can take a look at the checkstyle part in `https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html` and check it locally.

I have seen this address and configured it,But he can't check the Test-class code, If it's not my configuration error, I'll try to modify check-style.xml. please help me click check-process for me again,thanks~~

**Comment by SbloodyS** [comment]
> I have seen this address and configured it,But he can't check the Test-class code, If it's not my configuration error, I'll try to modify check-style.xml. please help me click check-process for me again,thanks~~

You can add the inspection scope of idea checkstyle to the test module. You should not modify the `check-style.xml`.

**Comment by liyangyang-12138** [comment]
@SbloodyS Oo,thanks for your advice,I reconfigured it and checked it again,no problem was found.please help me retry check-process,hope it will succeed this time,sorry for the trouble~~~ : )

**Comment by SbloodyS** [comment]
> @SbloodyS Oo,thanks for your advice,I reconfigured it and checked it again,no problem was found.please help me retry check-process,hope it will succeed this time,sorry for the trouble~~~ : )

It seems you did not push your changes successfully.

**Comment by liyangyang-12138** [comment]
> > @SbloodyS Oo,thanks for your advice,I reconfigured it and checked it again,no problem was found.please help me retry check-process,hope it will succeed this time,sorry for the trouble~~~ : )
> 
> It seems you did not push your changes successfully.

Sorry, there's something wrong with the network. I didn't push it successfully. I've pushed it again~~

**Comment by liyangyang-12138** [comment]
@SbloodyS I’m sorry to bother you. Now that I have the code format and test coverage all right, what should I do when I encounter this problem.
image

**Comment by SbloodyS** [comment]
I had restarted the failed CI. The E2E test has some flaky.  @liyangyang-12138

**Comment by liyangyang-12138** [comment]
> 

Thank you very much. After more than ten commits, this PR has finally passed~~~ : )

**Comment by liyangyang-12138** [comment]
trouble @chengshiwen  teacher help me review the code when have time,thanks for @SbloodyS  teacher's guidance,I was not very clear about the PR process in the first. I hope the subsequent commit can go smoothly,thank you again to both teachers~~~~

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by chengshiwen — APPROVED** [review]
+1

**Pull request merged**
