### PR TITLE
[Bug] [ui] fix cannot edit project

### LINKED ISSUE #6193: [Bug] [ui] cannot edit process definition name
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

on dev, It cannot be modified process definition name on the page

在dev分支上,页面不能修改工作流定义的名字

### What you expected to happen

above

### How to reproduce

open process definition editing page

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tandoy**
fix cannot edit project

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
LGTM, but there still exist a problem when update a project, could you please fix it together.

When we edit the project, if we don't change the projectName, it will throw an project already exist error.

You can find the code in ProjectServiceImpl#update
https://github.com/apache/dolphinscheduler/blob/07d6542febe1b4ad3f4ca3e69af654b2f6538933/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java#L285-L318

**Comment by Tandoy** [comment]
> LGTM, but there still exist a problem when update a project, could you please fix it together.
> 
> When we edit the project, if we don't change the projectName, it will throw an project already exist error.
> 
> You can find the code in ProjectServiceImpl#update
> https://github.com/apache/dolphinscheduler/blob/07d6542febe1b4ad3f4ca3e69af654b2f6538933/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java#L285-L318

already fixed

**Review by ruanwenjun — APPROVED** [review]
@Tandoy OK, but it seems this pr fixed the project edit issue, not process definition edit issue. 
It should not close 
- #6193

And for project name, it's better to set the unique restriction in database instead of in program, since concurrent modified may break this rule. This can be discussed in the future.

**Review by brave-lee — COMMENTED** [review]
+1

**Comment by Tandoy** [comment]
@ruanwenjun I see. It's my fault. And #6193 I will try to fix it.

**Comment by ruanwenjun** [comment]
@Tandoy Np, it's a good job, I have removed the `close #6193 `.

**Pull request merged**
