### PR TITLE
[BUG-7962] Fix global params cannot transport into sub_process

### PR DESCRIPTION
**Pull request by ruanwenjun**
related issue #7962

### CODE REVIEW

**Comment by ruanwenjun** [comment]
This pr also need to cherry-pick into dev.

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
@ruanwenjun Do you need to fix it on dev too?

**Comment by davidzollo** [comment]
good job

**Comment by ruanwenjun** [comment]
> 

OK, I will submit a pr to dev.

**Pull request merged**
