### PR TITLE
[Fix-7083] [UI] The switch task is missing the else branch

### LINKED ISSUE #7083: [Bug] [UI] The switch task is missing the else branch
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The switch task is missing the else branch:
image

### What you expected to happen

should be as follows: 
image

### How to reproduce

Create a switch task on the DAG page.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangyizhi1**
fix #7083

### CODE REVIEW

**Review by songjianet — APPROVED** [review]

**Comment by songjianet** [comment]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM, I think it could be merged to dev. cc: @lenboo @CalvinKirs @ruanwenjun

**Review by caishunfeng — APPROVED** [review]
LGTM

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
