### PR TITLE
[Improvement-16122][Authentication] Improvement k8s resource center statement

### LINKED ISSUE #16122: [Improvement][Authentication] Improvement k8s resource center statement
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Due to [[DSIP-42] Add dolphinscheduler-aws-authentication module](https://github.com/apache/dolphinscheduler/pull/16043/files#top), resource center statement is outdated.
will directly link to related to avoid inconsistency.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pegasas**
## Purpose of the pull request

fix: #16122
## Brief change log

Due to [[DSIP-42] Add dolphinscheduler-aws-authentication module](https://github.com/apache/dolphinscheduler/pull/16043/files#top), resource center statement is outdated.
will directly link to related to avoid inconsistency.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — COMMENTED** [review]
Please create an issue and link to this PR, and correct the title.

**Comment by pegasas** [comment]
> Please create an issue and link to this PR, and correct the title.

It was related to
https://github.com/apache/dolphinscheduler/issues/16122, 
for somehow reason it can not be tagged.
request for reopening this issue.

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
