### PR TITLE
[fix] [ui] Fixed the re-upload function of the Resource Management menu

### PR DESCRIPTION
**Pull request by HuntFalcon**
* Modify resource file list and sub-file front-end code
* Modify udF resource file list and subfile front-end code
* Fix modified page does not dynamically update content, added V-if judgment

### CODE REVIEW

**Comment by HuntFalcon** [comment]
Resource file re-upload function

**Comment by songjianet** [comment]
Is there an issue related to this issue?

**Comment by HuntFalcon** [comment]
邮件已收到，我会尽快给您回复！

**Comment by HuntFalcon** [comment]
The problem is not open. This bug was found in the application process of our company. The file re-upload function cannot be used in the version above V2.0.

**Comment by songjianet** [comment]
> The problem is not open. This bug was found in the application process of our company. The file re-upload function cannot be used in the version above V2.0.

You need to create an issue accordingly.

**Pull request closed without merging**
