### PR TITLE
[Feature-4725][server] preSql support sql of Query type

### PR DESCRIPTION
**Pull request by coding-now**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

preSql support query type,  return value as params

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by davidzollo** [comment]
good beginning， please submit a corresponding issue and add Unit Test for new code

**Review by coding-now — COMMENTED** [review]
add test case done

**Comment by chengshiwen** [comment]
@coding-now Please pass the **SonarCloud Code Analysis** and check the [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=4720&resolved=false&types=CODE_SMELL)

**Comment by coding-now** [comment]
@dailidong @chengshiwen @CalvinKirs   test case add done, but it failed again,what can i do now...

**Comment by caishunfeng** [comment]
Hi @coding-now this pr has not updated in a long time. So it will be closed.
BTW, the preSql feature has been implemeted in the newest code. You can check it.
If you have other questions, you can re-open this pr or create a new one. Thxs.
close #4725

**Pull request closed without merging**
