### PR TITLE
[Feature-8591][Python] Add pre-commit to run basic test before commit

### LINKED ISSUE #8591: [Feature][python] Add pre-commit to run basic test before commit
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some of the tests could be run locally before users submit to the remote branch. I think [pre-commit](https://pre-commit.com) is a good component to do that, it will make our workflow more easier

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jim-parsons**
## Purpose of the pull request

Add pre-commit to run basic test before commit

## Brief change log

  1. add `.pre-commit-config.yaml` in the pydolphinscheduler module and configured basic check rules like `isort`, `black`, `flake8`
  2. add some instructions in `DEVELOP.MD`

this close #8591

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Thanks for your contribution, I will take a look at Monday

**Comment by zhongjiajie** [comment]
Hi @tangchunbo , I test locally and find some missing config, so I add a new commit df8d4943 to fix it, holp you don't mind.And you could take a look on it.

**Review by zhongjiajie — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks @tangchunbo for the contribution

**Comment by jim-parsons** [comment]
> 

not at all。 thx big old~

**Comment by zhongjiajie** [comment]
@tangchunbo  You are welcome, do you interested in Python API and joining its developer team with us?

**Pull request merged**
