### PR TITLE
[Cherry-Pick][3.1.0-Prepare] Cherry pick docs format fix for 3.1.0

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Cherry-pick #12006

## Verify this pull request

* This pull request is docs format fix.

### CODE REVIEW

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
Hi @EricGao888 please check the fail CI.

**Comment by EricGao888** [comment]
> Hi @EricGao888 please check the fail CI.

@caishunfeng I've fixed the dead links and restarted CI.

**Comment by caishunfeng** [comment]
> > Hi @EricGao888 please check the fail CI.
> 
> @caishunfeng I've fixed the dead links and restarted CI.

Thanks~

**Pull request merged**
