### PR TITLE
[1.3.6-prepare][Feature-5062][*] Create/Edit/Delete Worker Group in Web UI #5113

### LINKED ISSUE #5175: [Improvement][Server] Optimize and reduce worker group queries of database and zookeeper
**Describe the question**

`HostManager.select()` will call `workerGroupMapper.queryAllWorkerGroup()` or `workerGroupMapper.queryWorkerGroupByName(workerGroupName)` from database, and call `registryCenter.getRegisterOperator().get(workerGroupPath + "/" + node)` from zookeeper.

They will cause more queries, even if these queries rarely change.

**What are the current deficiencies and the benefits of improvement**
- Optimize and reduce worker group queries of database and zookeeper 

**Which version of DolphinScheduler:**
 -[1.3.5]
 -[dev]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

### LINKED ISSUE #5176: [Bug][Server] Wrong excludeFilters cause the worker server to start the master's beans and threads like LowerWeightHostManager and RefreshResourceTask
**To Reproduce**
Steps to reproduce the behavior, for example:
1. Add one line `logger.info("RefreshResourceTask: {}", workerHostWeights);` in `RefreshResourceTask#run` (Picture 1)
2. Re-run `MasterServer` and `WorkerServer`
3. See log of `MasterServer` and `WorkerServer`
4. The `LowerWeightHostManager` and `RefreshResourceTask` logs of master appear in the`WorkerServer` log (Picture 2)
5. **Other master's beans and threads will also appear in the`WorkerServer` like `MasterRegistry`, `ZookeeperNodeManager` and etc**

**Picture 1**
image

**Picture 2**
image

**Expected behavior**
Bug fixed

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

### PR DESCRIPTION
**Pull request by chengshiwen**
pr: #5113 #5182
issue: #5062 #5175 #5176

This also closes #5175 and closes #5176

### CODE REVIEW

**Comment by lenboo** [comment]
i think we have some differences of opinion on this feature
so we can put this feature on the next version.

**Comment by chengshiwen** [comment]
After testing, this pr will not cause any performance problems, so I decide to reopen this pr. Because submitting this pr is not an easy work, I don’t plan to submit it again later. So I can have more time to solve many other problems of DolphinScheduler.

**Comment by chengshiwen** [comment]
@dailidong @lenboo @gaojun2048 @CalvinKirs
I made optimization to reduce the database and zookeeper queries by `ServerNodeManager`, which is evolved from `ZooKeeperNodeManager`. Please review, thanks a lot.

`ServerNodeManager` is responsible for:
- `WorkerNodeInfoAndGroupDbSyncTask`: Schedule worker node info (heartbeat info) and worker group db sync task every 10s
- `WorkerGroupNodeListener` & `MasterNodeListener`: Listen worker group node and master node and sync nodes

image

**Comment by EricJoy2048** [comment]
+1
Why test coverage in SonarCloud Code Analysis  is 0%?

**Comment by chengshiwen** [comment]
> +1
> Why test coverage in SonarCloud Code Analysis is 0%?

The unit test is skipped.

image

**Comment by EricJoy2048** [comment]
> > +1
> > Why test coverage in SonarCloud Code Analysis is 0%?
> 
> The unit test is skipped.
> 
> image

ok

**Review by EricJoy2048 — APPROVED** [review]
+1

**Comment by chengshiwen** [comment]
I add a new commit to replace worker address input with multiple-select as follow:

image

**Comment by EricJoy2048** [comment]
> I add a new commit to replace worker address input with multiple-select as follow:
> 
> image

good job !

**Pull request merged**
