### PR TITLE
Add end-to-end test framework and some basic cases

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@CalvinKirs this is good to go now

**Comment by CalvinKirs** [comment]
> @CalvinKirs this is good to go now

Very cool! Can you provide the documentation to guide us to follow up on the e2e additions and development?

**Comment by kezhenxu94** [comment]
> > @CalvinKirs this is good to go now
> 
> 
> 
> Very cool! Can you provide the documentation to guide us to follow up on the e2e additions and development?

Added.

**Review by CalvinKirs — APPROVED** [review]
LGTM @dailidong  PTAL

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
