### PR TITLE
[Improvement][UI] Improve monaco-editor component in ts.

### LINKED ISSUE #11270: [Improvement][UI] Improve monaco-editor component.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Amy0104**
## Purpose of the pull request

This pull request  improves monaco-editor component in ts.

## Related Issue

close #11270

### CODE REVIEW

**Review by songjianet — APPROVED** [review]
LGTM

**Review by labbomb — APPROVED** [review]
LGTM

**Review by devosend — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
@songjianet  already cherry pick to 3.0.0-prepare

**Pull request merged**
