### PR TITLE
Add Github Actions stale bot

### LINKED ISSUE #6467: [Feature][CI] Add stale bot for issues and PR
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add stale bot for issues and PR, which for issues and PR has not recent activity for a long time, allow bot to automatically mark issues and PRs as stale or event close them. It could reduce maintenance time for our community

### Use case

Automatically mark issues and PRs as stale or event close them

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
closes: https://github.com/apache/dolphinscheduler/issues/6467

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Add "new feature" as exempt labels for issue. But we still have discuss in https://lists.apache.org/thread.html/r1b45dcec6fa9167fe6f2c9cfc06e0cd1002cf0c51cef069ed3c74f08%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by zhongjiajie** [comment]
PTAL @CalvinKirs @lenboo

**Comment by zhongjiajie** [comment]
Since we merged #6601 , the discuss in https://lists.apache.org/thread.html/r1b45dcec6fa9167fe6f2c9cfc06e0cd1002cf0c51cef069ed3c74f08%40%3Cdev.dolphinscheduler.apache.org%3E is done. Add I think this PR is good to go now. ping @CalvinKirs @lenboo @ruanwenjun @zhuangchong

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks for merging.

**Pull request merged**
