### PR TITLE
[Feature-8222][python] move examples into the scope of source package

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

- [Feature-8222][python]move examples into the scope of source package so that examples will get installed along with the pydolphinscheduler package when running `pip install`

## Brief change log

- move `dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/examples/` folder into `dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/`
- add `__init__.py` file under folder `dolphinscheduler/dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/` 

## Verify this pull request

This change added tests and can be verified as follows:

- create a conda env for testing and activate it
- run `cd dolphinscheduler/dolphinscheduler-python/pydolphinscheduler`
- run `pip install .`
- go to the conda env you created above and find the pydolphinscheduler package you just installed, folder `examples` should be there

### CODE REVIEW

**Comment by zhongjiajie** [comment]
You forget add apache license hander in `dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/__init__.py`

**Comment by zhongjiajie** [comment]
Also have to and docstring into `./src/pydolphinscheduler/examples/__init__.py`, otherwise it would failed fake8 test `./src/pydolphinscheduler/examples/__init__.py:1:1: D104 Missing docstring in public package`

**Comment by EricGao888** [comment]
> Also have to and docstring into `./src/pydolphinscheduler/examples/__init__.py`, otherwise it would failed fake8 test `./src/pydolphinscheduler/examples/__init__.py:1:1: D104 Missing docstring in public package`

Thx for the comment, will fix it

**Comment by zhongjiajie** [comment]
@EricGao888  CI failed,  I comment in original issue https://github.com/apache/dolphinscheduler/issues/8222#issuecomment-1035729364

**Comment by EricGao888** [comment]
> @EricGao888 CI failed, I comment in original issue [#8222 (comment)](https://github.com/apache/dolphinscheduler/issues/8222#issuecomment-1035729364)

It seems the path change of folder `examples` caused  the test case to fail. I fixed the test case in the latest commit and ran pytest locally successfully. 

Not sure what the code in the screenshot below does, do I need to change it?
image

**Comment by zhongjiajie** [comment]
I restart CI just now

**Comment by zhongjiajie** [comment]
Python api doc build failed. because we use `examples/tutorial.py`'s source to generate document connect. you should also change content in https://github.com/apache/dolphinscheduler/blob/35578efd08905d30a1c56a5741f689590249c8ce/dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst#overview-of-tutorial

```diff
- .. literalinclude:: ../../examples/tutorial.py
+ .. literalinclude:: ../../src/pydolphinscheduler/examples/tutorial.py
   :start-after: [start tutorial]
   :end-before: [end tutorial]
```

**Comment by EricGao888** [comment]
> Python api doc build failed. because we use `examples/tutorial.py`'s source to generate document connect. you should also change content in https://github.com/apache/dolphinscheduler/blob/35578efd08905d30a1c56a5741f689590249c8ce/dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst#overview-of-tutorial
> 
> ```diff
> - .. literalinclude:: ../../examples/tutorial.py
> + .. literalinclude:: ../../src/pydolphinscheduler/examples/tutorial.py
>    :start-after: [start tutorial]
>    :end-before: [end tutorial]
> ```

Thanks for the comment! I'm working on it. BTW, maybe we can add run cmd `make clean && make html` into DEVELOP.md so that developers could make sure the doc building is fine by running the cmd locally ahead.

**Comment by zhongjiajie** [comment]
Good suggest! But please separate in different PR to do that.

**Comment by EricGao888** [comment]
> Good suggest! But please separate in different PR to do that.

@zhongjiajie Could you please restart the CI? This time it should work. thx

**Comment by zhongjiajie** [comment]
I restart it. I missing this PR, my bad

**Comment by EricGao888** [comment]
> I restart it. I missing this PR, my bad

No worries. Seems SonarCloud Code Analysis failed, test coverage needs to be over 33%. Do I need to add more tests to cover those examples? BTW is there anyway I can run this CI by myself so that I could trigger it every time after I make a change?

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks @EricGao888

**Comment by EricGao888** [comment]
> LGTM, thanks @EricGao888

Coooooool, thx @zhongjiajie for helping me with my first contribution. Really good experience!

**Comment by zhongjiajie** [comment]
@EricGao888  One more thing, issue #8222 still open due to you do not target it in your PR, next time maybe you could use keyword `close: ##8222` or `fix: ##8222` in https://github.com/apache/dolphinscheduler/pull/8340#issue-845276708. In this case, the related issue would be close when PR is be merged

**Comment by zhongjiajie** [comment]
And, we still have an existing task in https://github.com/apache/dolphinscheduler/pull/8340#issuecomment-1035976404, which we should add some content to hint users about how to test doc build locally

**Comment by EricGao888** [comment]
> > Good suggest! But please separate in different PR to do that.
> 
> @zhongjiajie Could you please restart the CI? This time it should work. thx

@zhongjiajie Fixed in https://github.com/apache/dolphinscheduler/pull/8693

**Pull request merged**
