### PR TITLE
[typo] Modify the comment of 'deployMode'.

### PR DESCRIPTION
**Pull request by FlechazoW**
## Purpose of the pull request

This pull request modify the comment of 'deployMode', which is not clear for truly meanings.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by caishunfeng** [comment]
I rerun the fail CI

**Review by EricGao888 — DISMISSED** [review]

**Comment by EricGao888** [comment]
@FlechazoW Could u plz pull the latest dev code and rebase your code? That will get CI pass.

**Comment by FlechazoW** [comment]
> @FlechazoW Could u plz pull the latest dev code and rebase your code? That will get CI pass.

Done.

**Review by EricGao888 — APPROVED** [review]

**Review by EricGao888 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
