### PR TITLE
[Fix-16211] Remove ExecutePath in buildJarCommand to fix Java Task in Jar Mode

### LINKED ISSUE #16211: [Bug] [dolphinscheduler-task-java] 3.2.1-release version Java Task not working, need remove the ExecutePath and only use the absolute path in shell script
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

3.2.1-release version java tasks always failed. 
javac and java command cannot find the correct jar file and .java file
After check the shell script file, I found out that the path to the jar file and .java file is not correct, the execution path appears twice and the javac and java cannot find the file correctly
Looks like the code to generate the command is adding the ExecutePath and AbsolutePathInLocal, and the path is not correct
I make some change in my local branch(remove the ExecutionPath when generate the jar command, the log related code is for my local debugging) and fix both Jar Model Java Task and Java Model Java Task

### What you expected to happen

Create the Shell script to run the Java Task correctly

### How to reproduce
For 3.2.1-RELEASE Version
Create any simple Process with a Simple JavaTask and run the Process

### Anything else

Looks like the dev branch is fixing this problem, but I think the test code need to be improved to prevent such problem in a RELEASE Version

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lanxing2**
# Pull Request Branch
Issue-16211

# Pull Request Content
## Purpose of the pull request
Fix [issue 16211](https://github.com/apache/dolphinscheduler/issues/16211)   
The comment says "duplicated with https://github.com/apache/dolphinscheduler/issues/15902"
And should be fixed by pr [15906](https://github.com/apache/dolphinscheduler/pull/15906)   
But I have tested and I think PR 15906 only fix the JavaTask Java Mode, Jar Mode still have bug  
ResourceAbsolutePathInLocal already have the ExecutePath, need remove it in buildJarCommand() method  
Also update the UnitTest  
Please check my reply in [issue 16211](https://github.com/apache/dolphinscheduler/issues/16211)  
I deployed the latest code in apache/dolphinscheduler dev branch in my own cluster and run JavaTask in Jar Mode and it failed  
After deployed my code in my own cluster, run JavaTask in Jar Mode and it succeed 

## Brief change log
[Fix issue 16211] Remove ExecutePath in buildJarCommand() to fix Java Task in Jar Mode

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.
- *Updated JavaTaskTest to verify the change.*
- *Build dolphinscheduler-task-java and deployed to my own cluster and tested end to end, please check the comment in [issue 16211](https://github.com/apache/dolphinscheduler/issues/16211) about the log before and after this pull request  *
- *Run mvn spotless:apply and check the code format*

(or)

# Pull Request Code Style
Already run the mvn spotless:apply and checked no problem with the code style

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by lanxing2** [comment]
Changed the branch name and requested a new PR

**Comment by ruanwenjun** [comment]
Good catch, sorry for missing this, we can use directly abosolute path is enough.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
