### PR TITLE
[Improvement][CI] Update github mergeable label regex

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request

* Currently we have both `3.0.x` and `3.1.x` ongoing, some bug fixes may need to be cherry-picked to both `3.0.x` and `3.1.x`. However, we could not use milestone for two versions. We could use labels to track those bug fixes in case we miss them when doing cherry-pick. For features or improvements, we label them with `3.2.0`.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by EricGao888** [comment]
@zhongjiajie Could u plz take a look when available? Thanks.

**Review by davidzollo — APPROVED** [review]
+1
good job

**Comment by davidzollo** [comment]
@EricGao888  label 3.0.x and 3.1.x should be the required fields,  if the pr has `improvement`, this CI will run successfully, it seems not right

**Comment by EricGao888** [comment]
@davidzollo Thanks, I will have a double-check tomorrow.

**Pull request merged**
