### PR TITLE
[Bug-9793] [Script] dolphinscheduler-daemon.sh overwrite_server_env may causing standalone server start failed

### LINKED ISSUE #9793: [Bug] [Script] dolphinscheduler-daemon.sh overwrite_server_env may causing standalone server start failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If the user modifies the ```dolphinscheduler_env.sh``` and then start standalone server by ```dolphinscheduler-daemon.sh 
 start standalone-server```. Then ```overwrite_server_env``` may causing standalone server start failed.

### What you expected to happen

running successfully.

### How to reproduce

above.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

This pr will close #9793

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> If the user modifies the dolphinscheduler_env.sh and then start standalone server by dolphinscheduler-daemon.sh start standalone-server. Then overwrite_server_env may causing standalone server start failed.

Can you elaborate the details?

**Comment by SbloodyS** [comment]
If the user modifies the ```dolphinscheduler_env.sh``` and using ```start-all.sh``` to start the cluster. After a period of time, the user wants to start standalone-server for testing through ```dolphinscheduler-daemon.sh start standalone-server```. Then it may failed. I don't know if this is the right way. Or should we just put this special case in the document to remind users? @kezhenxu94

**Comment by kezhenxu94** [comment]
I think `dolphinscheduler_env.sh` should take effect for all components including the standalone server. Do you mean users run the pseudo cluster as well as the standalone server simultaneously? If so I don't think that's feasible and users should not do that.

**Comment by SbloodyS** [comment]
> I think `dolphinscheduler_env.sh` should take effect for all components including the standalone server. Do you mean users run the pseudo cluster as well as the standalone server simultaneously? If so I don't think that's feasible and users should not do that.

Yes. Maybe I think too much. I will close this pr and issue for now. Thanks. @kezhenxu94

**Pull request closed without merging**
