### PR TITLE
[Improvement][*] Define version with revision globally and update version to 1.3.6-SNAPSHOT

### PR DESCRIPTION
**Pull request by chengshiwen**
## What is the purpose of the pull request

*Define version with `revision` globally and update version to 1.3.6-SNAPSHOT*

## Brief change log

*(for example:)*
  - *Define version with `revision` globally*
  - *Update version to `1.3.6-SNAPSHOT` from `1.3.4-SNAPSHOT`*
  - *Update tab to space in `dolphinscheduler-common/pom.xml` and `dolphinscheduler-dao/pom.xml` for checkstyle with space required*

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.

### CODE REVIEW

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
It is recommended to manage the version number globally. The cost of this change is small.

**Comment by chengshiwen** [comment]
> It is recommended to manage the version number globally. The cost of this change is small.

Now updating the property `revision` is just ok!
```
<properties>
    <revision>1.4.0-SNAPSHOT</revision>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
...
```

**Comment by CalvinKirs** [comment]
The next version should be 1.3.6

**Comment by chengshiwen** [comment]
> The next version should be 1.3.6

Done

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by chengshiwen** [comment]
@lgcareer @dailidong @lenboo Spring Boot is also based on this solution, see [https://github.com/spring-projects/spring-boot/blob/2.2.x/pom.xml](https://github.com/spring-projects/spring-boot/blob/2.2.x/pom.xml) for details

**Review by lgcareer — APPROVED** [review]
+1

**Review by davidzollo — APPROVED** [review]
+1
good job

**Pull request merged**
