### PR TITLE
[Improvement][Alert] Replace HSSFWorkbook

### LINKED ISSUE #5367: Toolbox SQL use "select SQL result"  support excel-2007(xlsx)  attach file in mail
**Feature request describe**
Toolbox SQL when I use "select SQL result" s a excel attach file in mail,but email received,the attach excel file is excel-2003, whicle is xls file format，but the now is 2021,the  excel-2003(xls to early),can dolphinscheduler in furture both to support excel-2003(xls) and above excel-2007(xlsx)? whice add a check buttle in two file format,thanks; 

**Which version of Dolphin Scheduler**
-[1.3.5-preview]

### LINKED ISSUE #5369: [Bug][Plugin-Alert-Email] UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed;
**Describe the bug**
When I send an email with attach file, there will be an error in `alert-server`.
```java
23:21:37.649 [pool-7-thread-1] ERROR org.apache.dolphinscheduler.plugin.alert.email.MailSender - Send email to [bestruanwenjun@gmail.com] failed
javax.mail.MessagingException: IOException while sending message
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1365)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.dolphinscheduler.plugin.alert.email.MailSender.attachContent(MailSender.java:358)
	at org.apache.dolphinscheduler.plugin.alert.email.MailSender.attachment(MailSender.java:261)
	at org.apache.dolphinscheduler.plugin.alert.email.MailSender.sendMails(MailSender.java:211)
	at org.apache.dolphinscheduler.plugin.alert.email.MailSender.sendMails(MailSender.java:147)
	at org.apache.dolphinscheduler.plugin.alert.email.EmailAlertChannel.process(EmailAlertChannel.java:45)
	at org.apache.dolphinscheduler.alert.runner.AlertSender.alertResultHandler(AlertSender.java:162)
	at org.apache.dolphinscheduler.alert.runner.AlertSender.syncHandler(AlertSender.java:126)
	at org.apache.dolphinscheduler.alert.processor.AlertRequestProcessor.process(AlertRequestProcessor.java:60)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler.lambda$processReceived$0(NettyServerHandler.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed; 
	boundary="----=_Part_0_2080677060.1619191291188"
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:896)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1694)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1913)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1315)
	... 17 common frames omitted
```

After set `Thread.currentThread().setContextClassLoader(getClass().getClassLoader());` this problem can be fixed. I'm not sure if this is a common problem. 
https://stackoverflow.com/questions/21856211/javax-activation-unsupporteddatatypeexception-no-object-dch-for-mime-type-multi

**To Reproduce**
1.  Execute a sql task
2. Send email with attachment

**Which version of Dolphin Scheduler:**
 -[1.3.6]
 -[dev]

### LINKED ISSUE #5397: [Improvement][Alert]  Replace HSSFWorkbook
**Lift the limit on the number of rows in excel files**
When we Lifted the limit of 10,000 lines and dealt with more than 65535 rows of sql data and . HSSFWorkbook is not suitable for this situation. It is recommended to upgrade to SXSSFWorkbook or XSSFWorkbook。It is not recommended to convert ResultSet into a big json，that will waste a lot of memory space。

**Which version of DolphinScheduler:**
 -[1.3.5]

### PR DESCRIPTION
**Pull request by ruanwenjun**
New Jar Vote Thread:
https://lists.apache.org/thread.html/rcfe376eb7dab07b4ee977fdd60cd2b0b5e04af8400363b5776d62cc6%40%3Cdev.dolphinscheduler.apache.org%3E

close #5397 close #5369 close #5367 close #5400

### CODE REVIEW

**Comment by CalvinKirs** [comment]
+SparseBitSet-1.2.jar

+commons-compress-1.19.jar

+commons-math3-3.6.1.jar

+curvesapi-1.06.jar

+xmlbeans-3.1.0.jar

You lost the license of these jars

**Comment by CalvinKirs** [comment]
I noticed that you have added a new jar. Please refer to this document and ask PMC for suggestions in the dev mailing list. They will check the license.
https://dolphinscheduler.apache.org/en-us/community/development/DS-License.html

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
Because a new jar is involved, more people are needed to check it.

**Comment by ruanwenjun** [comment]
@CalvinKirs Thanks a lot.

**Pull request merged**
