### PR TITLE
[Bug] [UI] UI miss machine learning task group 

### LINKED ISSUE #12171: [Bug] [UI] UI miss machine learning task group
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

image

### What you expected to happen

image

### How to reproduce

empty

### Anything else

empty

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jieguangzhou**
## Purpose of the pull request

close: #12171

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

### CODE REVIEW

**Comment by jieguangzhou** [comment]
@labbomb @Amy0104  PTAL, thanks.

**Review by labbomb — APPROVED** [review]
LGTM

**Comment by jieguangzhou** [comment]
> LGTM

Thanks

**Review by Amy0104 — APPROVED** [review]
LGTM

**Pull request merged**
