### PR TITLE
[FIX] Fix failure to recover stopped instance

### PR DESCRIPTION
**Pull request by privking**
## Purpose of the pull request
Fix failure to recover stopped instance
error

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by rickchengx — DISMISSED** [review]
LGTM

**Comment by rickchengx** [comment]
@privking please run 'mvn spotless:apply' to fix the code style

**Comment by privking** [comment]
fixed

**Review by ruanwenjun — APPROVED** [review]
LGTM, thanks for your patch.

**Pull request merged**
