### PR TITLE
[Improvement-6715][Schedule] Add release schedule option when update or release process definition (#6715)

### LINKED ISSUE #6715: [Improvement][Schedule] set timing schedule when save process definition
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

at 1.3.x version, we set process definition timing schedule   :
1.  save process definition
2.  set process online
3.  add timing of process definition
4. set timing schedule status to online

To simplify operation， we can set the timing schedule  (include online/offline) on the process definition save page. 

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by linyanbin666**
## Purpose of the pull request

close #6715 

## Brief change log
- Add release schedule option when update process definition.
- Add release schedule popover when release process definition.

## Verify this pull request
Manually verified the change by testing locally.

### CODE REVIEW

**Comment by brave-lee** [comment]
In the dev version of ProcessDefinition, there is already an interface for online workflow and timing at the same time. Please use this interface

**Comment by linyanbin666** [comment]
@JinyLeeChina Sorry to reply you later. I see that the current interface（org.apache.dolphinscheduler.api.service.ProcessDefinitionService#releaseWorkflowAndSchedule） will fail if the timing is not set, but some scenarios just need to go online workflow. It seems to me that user should be able to choose whether to go online workflow and timing at the same time.

**Comment by brave-lee** [comment]
> 

This method is to realize both online and offline workflow and timing

**Comment by linyanbin666** [comment]
> > 
> 
> This method is to realize both online and offline workflow and timing

They're both at the same time, but sometimes it just need to online workflow without timing. In my opinion, timing should be optional, not mandatory.

**Comment by brave-lee** [comment]
I don't agree with the back-end modification. Why can't you use these two methods selectively on the front-end?What's opinion @lenboo @Wangyizhi1

**Comment by linyanbin666** [comment]
> I don't agree with the back-end modification. Why can't you use these two methods selectively on the front-end?What's opinion @lenboo @Wangyizhi1

I agree with using ProcessDefinitionController#releaseProcessDefinition and ProcessDefinitionController#releaseWorkflowAndSchedule selectively on the front-end. I will change that. And Do you have any suggestions for ProcessDefinitionController#updateProcessDefinition, it also has timing option.

**Comment by songjianet** [comment]
Thank you for your contribution, but it is currently in the switching period between the new and the old UI, and this function will not be implemented in the old UI.

**Pull request closed without merging**
