### PR TITLE
[Improvement][doc] correct error in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by davidzollo**
this file is too old and has some error. The content of the official website is complete

### CODE REVIEW

**Review by gabry-lab — APPROVED** [review]
+1

**Review by gabry-lab — CHANGES_REQUESTED** [review]
Please refer to the contribution document [here](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/contribute/join/contribute.html)

**Comment by davidzollo** [comment]
> Please refer to the contribution document [here](https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/contribute/join/contribute.html)

has updated

**Review by EricGao888 — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
I think we should keep the developer-related doc in file `contributing.md` instead of the website only.

**Comment by davidzollo** [comment]
> I think we should keep the developer-related doc in file `contributing.md` instead of the website only.

can you do this?

**Comment by gabry-lab** [comment]
> I think we should keep the developer-related doc in file `contributing.md` instead of the website only.

Then there are two places to maintain, and we should avoid conflicts between them.

**Review by gabry-lab — APPROVED** [review]

**Pull request merged**
