### PR TITLE
[Fix] [SQL] sql script upgrade exception

### LINKED ISSUE #6461: [Bug] [SQL] sql script upgrade exception
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE t_ds_task_definition drop INDEX `task_unique`;     END IF; END' at line 1

### What you expected to happen

sql script

### How to reproduce

sql script upgrade

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this PR close #6461 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
LGTM

**Review by CalvinKirs — COMMENTED** [review]
We do not have version 1.4.0, maybe it should be removed temporarily

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
