### PR TITLE
[Feature-10905][API] Add CURD to the project/tenant/user section of the API and add its tests.

### PR DESCRIPTION
**Pull request by ly1ex**
## Purpose of the pull request

Add CURD to the project/tenant/user section of the API and add its tests.

## Brief change log

* add queryProjectByName/updateProject/deleteProject and it's test

* add queryTenantList/updateTenant/deleteTenantById and it's test

* add queryUser/updateUser/deleteUser and it's test

## Verify this pull request

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by SbloodyS** [comment]
Hi @lyleshaw , I think the title should be feature instead of fix.

**Comment by ly1ex** [comment]
PTAL @zhongjiajie

**Comment by zhongjiajie** [comment]
> Hi @lyleshaw , I think the title should be feature instead of fix.

Agree with that

**Comment by ly1ex** [comment]
> Hi @lyleshaw , I think the title should be feature instead of fix.

I'm sorry I just saw it, it's been changed.

**Comment by ly1ex** [comment]
@zhongjiajie Hi jiajie I have finished the java side of the code, but I found a problem with the ci detection.

image

It seems  I import the IO Exception in the wrong order, but I don't know what's wrong (tried using IDEA's fix import order but it didn't change)

Maybe you can help me look at it.

**Comment by zhongjiajie** [comment]
> @zhongjiajie Hi jiajie I have finished the java side of the code, but I found a problem with the ci detection.
> 
> image
> 
> It seems I import the IO Exception in the wrong order, but I don't know what's wrong (tried using IDEA's fix import order but it didn't change)
> 
> Maybe you can help me look at it.

Good to see you finish the change we told about 🎉 . And for the Java import issue, you can see more detail in https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html section "Pull Request Code Style" to solve it, with that config it will tell you the detail wrong order is it

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Pull request merged**
