### PR TITLE
Update dolphinscheduler_ddl.sql - for PostgreSQL

### PR DESCRIPTION
**Pull request by darrkz**
https://github.com/apache/dolphinscheduler/pull/12826 for this pr

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by DarkAssassinator** [comment]
hi @darkz1984 , same as #13080 ?

**Comment by darrkz** [comment]
> hi @darkz1984 , same as #13080 ?

[# 13080](https://github.com/apache/dolphinscheduler/pull/13080) is for  MySQL database

**Review by davidzollo — APPROVED** [review]
+1

**Comment by EricGao888** [comment]
Same comment here as https://github.com/apache/dolphinscheduler/pull/12826#issuecomment-1336167856

**Pull request merged**
