### PR TITLE
[1.3.6-prepare][Mail] Fix send mail failed instead of execute sql error #4739

### PR DESCRIPTION
**Pull request by CalvinKirs**
Fix send mail failed instead of execute sql error #4739

### CODE REVIEW

**Review by chengshiwen — APPROVED** [review]
+1

**Comment by chengshiwen** [comment]
pr #4739
issue #4738

**Review by lenboo — APPROVED** [review]
+1

**Comment by chengshiwen** [comment]
pr #4739
issue #4738 #4710 #4621

**Pull request merged**
