### PR TITLE
[Feature-13052][Task Plugin] Support Apache Seatunnel Connector-V2

### LINKED ISSUE #13052: [Feature][Task Plugin] Support Apache Seatunnel Connector-V2
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

_No response_

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shangeyao**
## Purpose of the pull request

close #13052 

## Brief change log

support flink-v2, spark-v2, seatunnel-engine

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by caishunfeng** [comment]
Hi @zhuangchong @CalvinKirs Do you have time to review this pr?

**Comment by CalvinKirs** [comment]
Could you provide a test? or your local running screenshot?

**Review by chaplinthink — CHANGES_REQUESTED** [review]
I have  view and test the code.  Find  a bug need to fix, when save seatunnel process definition.

Class `SeatunnelParameters `need add follow code for json parse.
```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, visible = true, property = "engine")
@JsonSubTypes({
        @JsonSubTypes.Type(value = SeatunnelFlinkParameters.class, name = "FLINK"),
        @JsonSubTypes.Type(value = SeatunnelFlinkParameters.class, name = "FLINK_V2"),
        @JsonSubTypes.Type(value = SeatunnelSparkParameters.class, name = "SPARK"),
        @JsonSubTypes.Type(value = SeatunnelSparkParameters.class, name = "SPARK_V2"),
        @JsonSubTypes.Type(value = SeatunnelEngineParameters.class, name = "SEATUNNEL_ENGINE")
})
```

**Comment by chaplinthink** [comment]
The screenshot  that i run in my  machine.  It can work for seatunnel engine to run ETL job. @CalvinKirs 
 
image

image

**Comment by chaplinthink** [comment]
@caishunfeng @CalvinKirs  Hi,  This PR hasn't been merged for a long time, is there any consideration?  I would be happy to help with anything.

**Comment by jobmission** [comment]
@shangeyao This is a great PR, very useful. Can you continue to complete it？

**Comment by jobmission** [comment]
@shangeyao 你好，我在使用的时候，我用的seatunnel、flink版本不支持run-mode参数，可否在创建任务页面及构造job 配置的任务增加一个run-mode枚举none ，不拼加run-mode参数，这样使用范围更广一些，感谢

image

image

**Comment by jobmission** [comment]
@shangeyao @caishunfeng @CalvinKirs @chaplinthink Hi ,生成seatunnel 脚本的时候，是否可以加上任务名称，现在提交到fink的job名字都是默认的seatunnel 看着很难受，seatunnel可以接受--name参数，可以把工作流的名称拼接上

**Review by davidzollo — APPROVED** [review]
+1 
LGTM

**Comment by davidzollo** [comment]
@chaplinthink, considering this PR hasn't been merged for a long time, I merged it and you can submit a new PR to fix it, thx
@jobmission, you can continue to submit a PR to complete what you said.

**Pull request merged**
