### PR TITLE
fix work oom when task logs's size is very large

### LINKED ISSUE #11214: [Improvement][Worker] Avoid worker oom when you find appid from task logs
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We deploy app on yarn by spark or flink , if you need to check app status on yarn , you must know appid. In dolphin, the appid is  from worker's task logs. when task logs's size is very large, worker's memory will occuted by task logs.
eg...
98b6e379d63b718e6aef3612eba1b79

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by microeastcowboy**
## Purpose of the pull request
close #11214 
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by MichaelDeSteven — COMMENTED** [review]
LGTM

**Review by zhuangchong — APPROVED** [review]
LGTM.

**Comment by zhuangchong** [comment]
@microeastcowboy 
Thank you very much for your contribution, this PR is very good. I think we can get deep communiction, you can contact me through mail or add wechat(KerwinZhuang), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.

**Comment by Radeity** [comment]
@microeastcowboy @zhuangchong  
Hi, I don't think it's a good fix. 

This code only considers the situation when a yarn job is done and collect its appId. However, when killing a running yarn job, there will be a remote network call to get all logs in `LogClientService`. If log size is large, this method maybe not a good solution.

In addition, I'm working on a new way to handle this which replace current way to collect appIds, and I am willing to submit a PR when I finish it!

**Comment by zhuangchong** [comment]
@Radeity 
You are right, this pr only optimizes this part of the code, very much looking forward to your contribution.

**Pull request merged**
