### PR TITLE
[Fix-9938] exists task set environment config again

### LINKED ISSUE #9938: [Bug] [server master] need fault tolerance task environment_config is null
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

need fault tolerance task  environment_config is null task execute failed
image

### What you expected to happen

image

### How to reproduce

1

### Anything else

_No response_

### Version

2.0.5

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by someorz**
## Purpose of the pull request
query from table  t_ds_task_instance don't select  environment_config field，and I found that sometimes environment_code 
exist but  environment_config  is null,so fix it by query environment and set to taskInstance

## Brief change log
close https://github.com/apache/dolphinscheduler/issues/9938

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by someorz** [comment]
what should i do to pass check?

**Comment by SbloodyS** [comment]
@caishunfeng Could you take a look at this PR?

**Comment by caishunfeng** [comment]
Hi @someorz please resolve the conflict

**Comment by kezhenxu94** [comment]
I don't think this is a valid PR and it notifies too many people for noise, please open another one PR

**Pull request closed without merging**
