### PR TITLE
【Bug】 OracleSouce edited again, ConnectionType is null

### PR DESCRIPTION
**Pull request by AliceXiaoLu**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by AliceXiaoLu** [comment]
@caishunfeng please review

**Comment by rickchengx** [comment]
Hi, @AliceXiaoLu , thanks for your work. Could you please update the related UT?

**Comment by AliceXiaoLu** [comment]
> Hi, @AliceXiaoLu , thanks for your work. Could you please update the related UT?

What exactly is UT? For example???

**Comment by rickchengx** [comment]
> > Hi, @AliceXiaoLu , thanks for your work. Could you please update the related UT?
> 
> What exactly is UT? For example???

Maybe you could check and update the `OracleDataSourceProcessorTest` to test the case of this PR :)

**Comment by AliceXiaoLu** [comment]
> > > Hi, @AliceXiaoLu , thanks for your work. Could you please update the related UT?
> > 
> > 
> > What exactly is UT? For example???
> 
> Maybe you could check and update the `OracleDataSourceProcessorTest` to test the case of this PR :)

Yes， OracleDataSourceProcessorTest has this case. and is right。

**Comment by AliceXiaoLu** [comment]
@caishunfeng  Please help me to add Label,Thank you. Lable must include one of the following: feature, bug, improvement, document, chore AND Label must include one or more version numbers.

**Comment by AliceXiaoLu** [comment]
@caishunfeng +1

**Comment by AliceXiaoLu** [comment]
@rickchengx Please help to review

**Comment by rickchengx** [comment]
> @rickchengx Please help to review

* LGTM, please check the failed CI
* And could you please add the related issue link in the PR, E.g., `close: #issue`

cc @caishunfeng

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
