### PR TITLE
the name should equals, then assure the resource exists

### LINKED ISSUE #6373: [Bug] [API] the logical judgement for file existing or not may be error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the logical judgement for file existing or not may be error 

### What you expected to happen

the logical judgement for file existing or not may be error 

### How to reproduce

the logical judgement for file existing or not may be error 

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BenjaminWenqiYu**
## Purpose of the pull request
the logical judgement for file existing or not may be error

## Brief change log
the name should equals, then assure the resource exists
## Verify this pull request

This pull request is code cleanup without any test coverage.

resolve #6373

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, thx for contribution, please resolve conflicting files

**Comment by BenjaminWenqiYu** [comment]
thank you, I will resolve conflicting files soon.

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
The resource name must be globally unique

**Comment by BenjaminWenqiYu** [comment]
I got that 'The resource name must be globally unique',  but I have a question. The table 't_ds_user' have not a user with the id is '0', and then the exists function will take effect or not?

**Comment by BenjaminWenqiYu** [comment]
The resource was upload by user, so it's userId was the user's id who uploaded it. The the checkResourceExists will not take effect when user the 'userId 0'.

**Comment by CalvinKirs** [comment]
> The resource was upload by user, so it's userId was the user's id who uploaded it. The the checkResourceExists will not take effect when user the 'userId 0'.

I didn't look at it, but userId is not needed in this、. There is a problem with the design of this method. Maybe you can try to modify it.

**Comment by BenjaminWenqiYu** [comment]
I will look on it, I think we can check the resource exists or not without the useeid condition.





---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 11:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/dolphinscheduler] the name should equals, then assure the resource exists (#6374)




  
The resource was upload by user, so it's userId was the user's id who uploaded it. The the checkResourceExists will not take effect when user the 'userId 0'.
  
I didn't look at it, but userId is not needed in this、. There is a problem with the design of this method. Maybe you can try to modify it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CalvinKirs** [comment]
cloose by #6409

**Pull request closed without merging**
