### PR TITLE
[python] Auto location when create process definition

### LINKED ISSUE #8254: [Feature][python] Find a way to add attr location to process definition
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Separate from #6407
**Beautify workflow DAG graphic**: when workflow create by Python API, we set default location as `{"x": 0, "y": 0}` in [this PR change][task-location] which means all of tasks in the same place when we open it in UI. we certainly have `format` button in UI, but just a javascript lib and could not call in backend. IMO, I thinks we should also add attribute `graph` or others name to show the view of DAG

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
close: #8254

### CODE REVIEW

**Comment by zhongjiajie** [comment]
related: #11535 thanks @labbomb

**Comment by zhongjiajie** [comment]
PTAL @jieguangzhou @hiSandog if you have time, thanks

**Comment by jieguangzhou** [comment]
LGTM

**Review by SbloodyS — COMMENTED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks all~

**Pull request merged**
