### PR TITLE
Merging general settings to faq

### PR DESCRIPTION
**Pull request by sneh-wha**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
waiting for CI, and for @SbloodyS , we just migrate `how to` doc to another place and I know you working on adding some content to `howto`

**Comment by SbloodyS** [comment]
> waiting for CI, and for @SbloodyS , we just migrate `how to` doc to another place and I know you working on adding some content to `howto`

Got it. I'll revise it after this pr is merged.

**Comment by SbloodyS** [comment]
merging...

**Comment by zhongjiajie** [comment]
> > waiting for CI, and for @SbloodyS , we just migrate `how to` doc to another place and I know you working on adding some content to `howto`
> 
> Got it. I'll revise it after this pr is merged.

thanks

**Pull request merged**
