### PR TITLE
Correct typo in English README

### PR DESCRIPTION
**Pull request by brnnnfx**
## Purpose of the pull request

This corrects a minor typo to make the README file a little more clear for readers.

## Brief change log

Change the following line...

`Please referer the official website document...`

...to appear as...

`Please refer to the official website document...`

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by zhuangchong — DISMISSED** [review]
LGTM.

**Comment by brnnnfx** [comment]
> SonarCloud Quality Gate failed.    Quality Gate failed
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=CODE_SMELL) [14 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_coverage&view=list) [30.8% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_duplicated_lines_density&view=list)

Hi @zhuangchong , thanks for the approval. Does my change still  need to be bound by this :arrow_up: ? 

The lacking code coverage level is in files I didn't touch / are not affected by my change.

**Comment by lenboo** [comment]
> > SonarCloud Quality Gate failed.    Quality Gate failed
> > [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=CODE_SMELL) [14 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=7695&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_coverage&view=list) [30.8% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=7695&metric=new_duplicated_lines_density&view=list)
> 
> Hi @zhuangchong , thanks for the approval. Does my change still need to be bound by this ⬆️ ?
> 
> The lacking code coverage level is in files I didn't touch / are not affected by my change.

hi @brnnnfx:
   Thanks for your contribution.  Because of changes of checklist(we added e2e checklist in last month), I'm afraid you need to rebase the latest dev branch to your branch 'patch-1'.

**Comment by zhongjiajie** [comment]
> 

I do not thinks it is related to this point. It keeps waiting cause we have a confilc setting about it. I would submit a PR to correct it

**Comment by zhongjiajie** [comment]
> > 
> 
> I do not thinks it is related to this point. It keeps waiting cause we have a confilc setting about it. I would submit a PR to correct it

I submit PR #7807 to correct our CI workflow. @brnnnfx you could rebase after PR #7807 merged

**Comment by zhongjiajie** [comment]
> I submit PR #7807 to correct our CI workflow. @brnnnfx  you could rebase after PR #7807 merged

@brnnnfx Now you could rebase to dev and force push to restart CI

**Comment by zhongjiajie** [comment]
I approval to run CI just now, we would waiting CI result

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Hi @brnnnfx , thanks for your contribution and welcome to join the community 🎉 . If you want to contribute but could not find issues, maybe you could start in #5689 or just search our issue list https://github.com/apache/dolphinscheduler/issues. Looking forward to your next contribution.

**Pull request merged**
