### PR TITLE
[Doc-16555] Add note of Alert Script Plugin

### PR DESCRIPTION
**Pull request by wangxj3**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by caishunfeng — DISMISSED** [review]

**Review by Gallardot — DISMISSED** [review]

**Review by SbloodyS — DISMISSED** [review]
+1

**Comment by davidzollo** [comment]
Please run this command ` mvn spotless:apply` before submitting the PR

**Comment by wangxj3** [comment]
> Please run this command ` mvn spotless:apply` before submitting the PR

fix it

**Review by davidzollo — APPROVED** [review]
+1

**Review by Gallardot — APPROVED** [review]

**Pull request merged**
