### PR TITLE
[Improvement][API] Make the return value clearer #5015

### LINKED ISSUE #5015: [Improvement][API] Make the return value clearer
**Describe the question**
The return value of some interfaces is not clear, such as you see in xxController.

**What are the current deficiencies and the benefits of improvement**
Clarifying the type of the method's return value can make the code read better.

**Which version of DolphinScheduler:**
 -[1.3.x]
 -[dev]

### PR DESCRIPTION
**Pull request by ruanwenjun**
* Refactor the Api code to make the method return typed parameters

## Purpose of the pull request

Most methods in the current API module do not have a clear return value, but return Object or Map<String, Object>. These makes it difficult to develop a new feature and maintain old code. It is strongly recommended using a specific type class as the return value of method, rather than Object or Map<String, Object>.

This closes #5015

## Brief change log

Change the method return value of API model.

## Verify this pull request

This pull request is already covered by existing tests.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
please resolve  vulnerabilities(Security Rating on New Code (is worse than A))

**Comment by ruanwenjun** [comment]
> please resolve vulnerabilities(Security Rating on New Code (is worse than A))

Thanks, resolved.

**Comment by ruanwenjun** [comment]
> please resolve vulnerabilities(Security Rating on New Code (is worse than A))

Thanks, resolved.

**Comment by chengshiwen** [comment]
@ruanwenjun Hi, sorry for too late review, could you resolve the conflicts and the `32 Code Smells` at first? Thanks so much!

**Pull request closed without merging**
