### PR TITLE
[Bug][dolphinscheduler-task-seatunnel] script resource file path error

### LINKED ISSUE #15156: [Bug] [seatunnel job ] When executing the local seatunneljob, an error message is displayed indicating that the file cannot be found
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`将资源中心配置在本地时，对于上传到资源中的脚本文件，在执行seatunnel任务脚本，显示找不到脚本文件。因为在`dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java`文件的代码中，对ResourceName进行切分时，只切割了1个字符，代码如下
```
    protected List<String> buildOptions() throws Exception {
        List<String> args = new ArrayList<>();
        if (BooleanUtils.isTrue(seatunnelParameters.getUseCustom())) {
            args.add(CONFIG_OPTIONS);
            args.add(buildCustomConfigCommand());
        } else {
            seatunnelParameters.getResourceList().forEach(resourceInfo -> {
                args.add(CONFIG_OPTIONS);
                // TODO: Need further check for refactored resource center
                // TODO Currently resourceName is `/xxx.sh`, it has more `/` and needs to be optimized
                args.add(resourceInfo.getResourceName().substring(1));
            });
        }
        return args;
    }
```
所以在初始化时，生成的脚本文件路径字符串前缀是`file:`，只切割掉1个字符，会导致文件路径包含`ile:` ,进而生成错误的路径字符串`ile:/tmp/dolphinscheduler`

所以实际应该切割掉5个字符。只切割掉一个字符会报如下的错误：
Snipaste_2023-11-13_15-54-11
Snipaste_2023-11-13_15-55-40

希望可以尽快处理一下，只需要在 `args.add(resourceInfo.getResourceName().substring(1));`改为`args.add(resourceInfo.getResourceName().substring(5));`
希望在下个版本中可以进行修复，谢谢！

### What you expected to happen

Snipaste_2023-11-13_15-54-11
Snipaste_2023-11-13_15-55-40

### How to reproduce

向资源中心上传seatunnel的作业文件，进行调度执行，会报错 找不到作业文件

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cqutwangyu**
## Purpose of the pull request
fix https://github.com/apache/dolphinscheduler/issues/15156
fix script resource file path error
image
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by cqutwangyu** [comment]
@caishunfeng @SbloodyS @zhuangchong 
please cc

**Review by SbloodyS — COMMENTED** [review]
Please link this pr to your issue. @cqutwangyu

**Comment by cqutwangyu** [comment]
> Please link this pr to your issue. @cqutwangyu

ok, link to https://github.com/apache/dolphinscheduler/issues/15156

**Review by rickchengx — APPROVED** [review]
LGTM

**Comment by maxiangmin** [comment]
包含子任务的工作流，子工作流中有个别任务失败，重跑失败任务时，子工作流中的任务会全部重跑，这个bug会在这个版本修复吗？

**Review by SbloodyS — APPROVED** [review]
+1

**Pull request merged**
