### PR TITLE
datasource test and sql task Remove connection pool issues is #14179

### LINKED ISSUE #14179: Driver does not support get/set network timeout for connections. (Method not supported)
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I I updated Dolphin 3.1.6 and tested the Hive data source connection and found 5 more long links in the HiveServer2 service that did not close。
Dolphin：
image

hiveservice2：
image

api-log：
image

### What you expected to happen

I expected hive datasource wiil be close

### How to reproduce

you just test hive datasource

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xuhui1231**
close: #14179

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
hi @xuhui1231 I am very sorry. I understand the problem #14183 that this PR is currently trying to solve. I think our content has been repeated. After the communication in the weekly meeting, I will discuss and decide to remove the connection pool under daatasource, so I am still working on it Currently this works.

**Comment by zhaohehuhu** [comment]
> hi @xuhui1231 I am very sorry. I understand the problem #14183 that this PR is currently trying to solve. I think our content has been repeated. After the communication in the weekly meeting, I will discuss and decide to remove the connection pool under daatasource, so I am still working on it Currently this works.

haha. I also made a PR that wound like to remove connection pool in Kyuubi datasource #14190

**Comment by MonsterChenzhuo** [comment]
I suggest creating an "issues" or task breakdown to handle the multiple data sources. Everyone can choose the sources they are interested in and make modifications for testing purposes.
What do you all think about this suggestion?

**Comment by xuhui1231** [comment]
> I suggest creating an "issues" or task breakdown to handle the multiple data sources. Everyone can choose the sources they are interested in and make modifications for testing purposes. What do you all think about this suggestion?

OH，That's a good idea，After I test I will create Issues

**Comment by zhongjiajie** [comment]
@xuhui1231 Hi, please run command `mvn spotless:apply` to format our code and docs please

**Comment by zhongjiajie** [comment]
https://github.com/apache/dolphinscheduler/actions/runs/5607655761/jobs/10259960705?pr=14193 it seems some UT error currently, do you have time to correct the fail CI

**Comment by xuhui1231** [comment]
> https://github.com/apache/dolphinscheduler/actions/runs/5607655761/jobs/10259960705?pr=14193 it seems some UT error currently, do you have time to correct the fail CI
I modified ut and submitted the code Just now

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Comment by zhongjiajie** [comment]
thanks @SbloodyS , I will cherry pick to 3.1.8 prepare

**Comment by ruanwenjun** [comment]
This PR will introduce new bug, the datasource client will only keep one connection.

**Pull request merged**
