### PR TITLE
[Fix-9420][doc] fix url wrong in zh doc

### LINKED ISSUE #9420: [Bug] [doc] There is something wrong about the zh docs.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
there is something wrong about the zh docs.

### What you expected to happen

it should be [http://localhost:12345/dolphinscheduler](http://localhost:12345/dolphinscheduler) instead of [http://localhost:12345/dolphinscheduler，如果有需要请修改成对应的](http://localhost:12345/dolphinscheduler，如果有需要请修改成对应的)

### How to reproduce

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/installation/docker.html

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ly1ex**
## Purpose of the pull request

fix #9420 
 
## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by caishunfeng** [comment]
I had approve and run CI.  
But it seems do not need to run CI test if just change doc files.

**Comment by SbloodyS** [comment]
> I had approve and run CI. But it seems do not need to run CI test if just change doc files.

There is a filter condition that does not take effect in CI. I'll fix it.

**Review by lenboo — APPROVED** [review]
+1

**Review by zhongjiajie — APPROVED** [review]

**Comment by zhongjiajie** [comment]
@songjianet I find UI failed to build twice today, is there any bad commit currently?

**Comment by songjianet** [comment]
> @songjianet I find UI failed to build twice today, is there any bad commit currently?

Please check https://github.com/apache/dolphinscheduler/pull/9431, It may be due to the problem of not using pnpm's package manager, because pnpm is recommended for new front-end projects, but our back-end packaging tool does not seem to support it, so we can only temporarily do compatibility processing.

**Comment by kezhenxu94** [comment]
> > @songjianet I find UI failed to build twice today, is there any bad commit currently?
> 
> Please check #9431, It may be due to the problem of not using pnpm's package manager, because pnpm is recommended for new front-end projects, but our back-end packaging tool does not seem to support it, so we can only temporarily do compatibility processing.

@songjianet Please check that PR #9431, I've migrated from npm to pnpm in the CI build

**Comment by zhongjiajie** [comment]
Thank @songjianet for the clarification, and @lyleshaw please rebase on branch dev after #9431 merged.

**Comment by ly1ex** [comment]
> Thank @songjianet for the clarification, and @lyleshaw please rebase on branch dev after #9431 merged.

Done.

Waiting for approval to run CI~

**Comment by SbloodyS** [comment]
I had approved to run ci~

**Comment by zhongjiajie** [comment]
@caishunfeng 🚀 so fast~

**Pull request merged**
