### PR TITLE
[BUG] Missing metadata fields caused by version upgrade

### LINKED ISSUE #13897: Unknown column 'execution_type' in 'field list'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After updating from 2.0 to 3.1.5, the following problems occurred:

截屏2023-04-10 11 22 18

### What you expected to happen

I expect the workflow definition to be loaded correctly
截屏2023-04-10 11 24 39

### How to reproduce

1.39 -> 2.0 -> 3.1.5

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xinxingi**
## Purpose of the pull request
close #13897

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by SbloodyS** [comment]
PTAL @zhongjiajie

**Comment by zhongjiajie** [comment]
I check branch dev, and found column `exception_type` already exists in https://github.com/apache/dolphinscheduler/blob/8c43e71adf3d98ad1e63711abfdf1d125e262c76/dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/mysql/dolphinscheduler_ddl.sql#L444 and https://github.com/apache/dolphinscheduler/blob/8c43e71adf3d98ad1e63711abfdf1d125e262c76/dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/postgresql/dolphinscheduler_ddl.sql#L79

which mean some already fix in, and I deep into mysql ddl find we have fix in https://github.com/apache/dolphinscheduler/pull/11619

**Comment by zhongjiajie** [comment]
I check detail and found some error here.
* in 2.0.8(latest version of 2.0.x): only postgresql update ddl have `execution_type` in `2.0.0_schema` updating
* in 3.0.5(latest version of 3.0.): both postgresql have `execution_type` in `2.0.0_schema` updating, 3.0.x already EOF
* in 3.1.5(latest version of 3.1.x): only postgresql update ddl have `execution_type` in `2.0.0_schema` updating

This make a little complex, mean we should add this column adding in both branch `2.0.9-prepare` and `3.1.6-prepare`, but we should not add directly to `dev` branch, because it already have https://github.com/apache/dolphinscheduler/pull/13901#issuecomment-1521069953

**Comment by zhongjiajie** [comment]
@xinxingi you should add new directory named `3.1.6_schema` in https://github.com/apache/dolphinscheduler/tree/ecfdebebaee6cae98156ae1140fcd4205fa55ad9/dolphinscheduler-dao/src/main/resources/sql/upgrade and move your code in PR into `mysql/dolphinscheduler_ddl.sql` to fix the further version of 3.1.x

**Comment by zhongjiajie** [comment]
> I check detail and found some error here.
> 
> * in 2.0.8(latest version of 2.0.x): only postgresql update ddl have `execution_type` in `2.0.0_schema` updating
> * in 3.0.5(latest version of 3.0.): both postgresql have `execution_type` in `2.0.0_schema` updating, 3.0.x already EOF
> * in 3.1.5(latest version of 3.1.x): only postgresql update ddl have `execution_type` in `2.0.0_schema` updating
> 
> This make a little complex, mean we should add this column adding in both branch `2.0.9-prepare` and `3.1.6-prepare`, but we should not add directly to `dev` branch, because it already have [#13901 (comment)](https://github.com/apache/dolphinscheduler/pull/13901#issuecomment-1521069953)

FYI @zhuangchong we should add this in 3.1.6-prepare after is merged

**Comment by zhongjiajie** [comment]
already fix in next version in 2.0.x in 7c73e3f

**Comment by zhongjiajie** [comment]
fix in next version in 3.1.x in ca10898, cc: @zhuangchong

**Comment by zhongjiajie** [comment]
I think maybe we should close this pr, due to dev branch already have

**Comment by xinxingi** [comment]
@zhongjiajie LGTM，But I have a question, if only the latest version is submitted, if the user uses a version before 3.1.6, won't this problem still occur?

**Comment by zhongjiajie** [comment]
> @zhongjiajie LGTM，But I have a question, if only the latest version is submitted, if the user uses a version before 3.1.6, won't this problem still occur?

Will still have a bug, but the version before 3.1.6 is been already release, we should not change then anymore but can notice users to upgrade to 3.1.6 instead of version between 3.0.0 - 3.1.5

**Pull request closed without merging**
