### PR TITLE
[doc] Delete SPRING_DATASOURCE_DRIVER_CLASS_NAME in doc

### LINKED ISSUE #10226: [Doc][Docker] Update Docker Doc
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Due [this](https://github.com/apache/dolphinscheduler/issues/10103#issuecomment-1132668573)

We don't need to config -e `SPRING_DATASOURCE_DRIVER_CLASS_NAME="org.postgresql.Driver" \` when we run Docker Image

I will update the Docker doc 

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qingwli**
close #10226

### CODE REVIEW

**Comment by qingwli** [comment]
PTAL @kezhenxu94

**Comment by zhongjiajie** [comment]
Seem we missing some change in 
* https://github.com/apache/dolphinscheduler/blob/baf654cb47d60a753dd6372698ebb9230fca4859/.github/workflows/cluster-test/mysql/dolphinscheduler_env.sh#L24
* https://github.com/apache/dolphinscheduler/blob/2423fa50f7d08538630929fee004a858c95ed38d/.github/workflows/cluster-test/postgresql/dolphinscheduler_env.sh#L24
* https://github.com/apache/dolphinscheduler/blob/7a8f3f1810ec283fc5acd66077d46db88b0400af/docs/docs/en/architecture/configuration.md#L453 and the zh document

**Comment by zhongjiajie** [comment]
Seem we missing some change in 
* https://github.com/apache/dolphinscheduler/blob/baf654cb47d60a753dd6372698ebb9230fca4859/.github/workflows/cluster-test/mysql/dolphinscheduler_env.sh#L24
* https://github.com/apache/dolphinscheduler/blob/2423fa50f7d08538630929fee004a858c95ed38d/.github/workflows/cluster-test/postgresql/dolphinscheduler_env.sh#L24
* https://github.com/apache/dolphinscheduler/blob/7a8f3f1810ec283fc5acd66077d46db88b0400af/docs/docs/en/architecture/configuration.md#L453 and the zh document

**Comment by zhongjiajie** [comment]
I restart the failed CI

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Pull request merged**
