### PR TITLE
[Fix-#6854][dao] fix "ResourceMapper.xml -> queryResourcePaging" sql bug

### PR DESCRIPTION
**Pull request by yangqiyu0306**
## Purpose of the pull request

fix issue #6854 ， The reason is that there is a problem with SQL writing

## Brief change log

update ResourceMapper.xml -> queryResourcePaging sql

## Verify this pull request

it's will open the resource list normally；

### CODE REVIEW

**Comment by davidzollo** [comment]
Please solve the conflicts locally and then re-submit PR, thx

**Comment by yangqiyu0306** [comment]
hi @lenboo , If you have time, Please review and merge the code，ths

**Comment by davidzollo** [comment]
closes #6854

**Review by davidzollo — APPROVED** [review]
+1

**Comment by davidzollo** [comment]
@janeHe13  please check this PR when you're free

**Pull request merged**
