### PR TITLE
[Fix-5549][WorkerServer] SqlTask NullPointerException #5549

### LINKED ISSUE #5549: [Bug][WorkerServer] SqlTask NullPointerException
**Describe the bug**

The "printReplacedSql" method, before sqlParamsMap iterates, check null,
and sqlParamsMap.get(i) check null.

**Expected behavior**
When sqlParamsMap is null, no NullPointerException should be thrown.

**Which version of Dolphin Scheduler:**
 -[dev]

### PR DESCRIPTION
**Pull request by didiaode18**
## Purpose of the pull request

This close #5549.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@didiaode18 
The main problem in this issue #5549 might be that the value in the `sqlParamsMap` may be null.
And there is a same pr #5556

**Comment by CalvinKirs** [comment]
Sorry, someone submitted PR before you.
 If the original PR has not been updated for a long time (usually two weeks), 
we will accept the new PR.

**Comment by didiaode18** [comment]
Thank you for your reminder, how to deal with the pr that has not been merged under the consultation will not affect my next submission @ruanwenjun @CalvinKirs

**Comment by CalvinKirs** [comment]
Deeply thanks for your contribution to this. 
According to the open-source culture, `who submit first, who get merged, if it is good enough.`, 
Therefore, I will close this PR. I am very sorry for that. I look forward to your continued contribution. If you encounter any problems, please feel free to communicate with me.

**Comment by CalvinKirs** [comment]
> Thank you for your reminder, how to deal with the pr that has not been merged under the consultation will not affect my next submission @ruanwenjun @CalvinKirs

It is best to check if someone has submitted a PR before submitting it.

**Pull request closed without merging**
