### PR TITLE
[Improvement-4375][api] cannot delete yarn queue

### LINKED ISSUE #4375: [Improvement][api] Queues can only be created and edited, not deleted
**Describe the question**
Queues can only be created and edited, not deleted
Looking at the current Dev development branch, there is no API for deleting queues

**What are the current deficiencies and the benefits of improvement**
-  Consider adding the ability and API to delete queues？

**Which version of DolphinScheduler:**
 - [1.2.1]

### PR DESCRIPTION
**Pull request by amaoisnb**
[Improvement-4375][api] cannot delete yarn queue
Improvements for unable to delete queues
have delete button to delete the queue

close #4375

### CODE REVIEW

**Comment by davidzollo** [comment]
good job, can you add Unit Test for this PR?

**Comment by amaoisnb** [comment]
> good job, can you add Unit Test for this PR?

OK, I'll try

**Comment by amaoisnb** [comment]
> good job, can you add Unit Test for this PR?

I added it as well, can you look at it

**Comment by amaoisnb** [comment]
I need some review

**Review by SbloodyS — COMMENTED** [review]
Please resolve conflicts.

**Review by songjianet — DISMISSED** [review]

**Review by SbloodyS — DISMISSED** [review]
+1

**Comment by SbloodyS** [comment]
@amaoisnb Hi, please check the failed CI.

**Comment by amaoisnb** [comment]
> @amaoisnb Hi, please check the failed CI.

OK， I'll try

**Comment by SbloodyS** [comment]
Please check failed UT. @amaoisnb

**Review by SbloodyS — APPROVED** [review]

**Comment by Radeity** [comment]
Hi @SbloodyS @amaoisnb , FYI, we plan to remove yarn queue management https://github.com/apache/dolphinscheduler/pull/14310#issuecomment-1624817040, do you have any different idea about it?

**Pull request merged**
