### PR TITLE
Update ZKMasterClient.java

### PR DESCRIPTION
**Pull request by whw02**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds checkstyle plugin.)*

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by chengshiwen** [comment]
@whw02 Please review [pull-request](https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html) and rename the title, and pass the **Backend / Compile-chec**k and  **Unit Test / Check code style**

**Comment by davidzollo** [comment]
@whw02 ,  thanks for your first contribution,  please contact me(wechat: 510570367 or mail : lidongdai@apache.org), I think I can help you if you need any help

**Comment by whw02** [comment]
thanks,this debug(#4757) is&nbsp; closed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dailidong"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 下午2:50
收件人: "apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;; 
抄送: "王汉文"<1029312668@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/incubator-dolphinscheduler] Update ZKMasterClient.java (#4745)





 
@whw02 ,  thanks for your first contribution,  please contact me(wechat: 510570367 or mail : lidongdai@apache.org), I think I can help you if you need any help

**Comment by davidzollo** [comment]
> thanks,this debug(#4757) is&nbsp; closed.
> […](#)

@whw02 , thanks for again, though this pr is not been merged into dev, I think maybe next time, I'm still looking forward to your participation,  please contact me(wechat: 510570367 or mail : lidongdai@apache.org), I want to make friends with you, when added, please tell me your github id, thx

By the way , the issue has been solved, I will close this PR

remember contact me, ^^

**Pull request closed without merging**
