### PR TITLE
[Feature][JsonSplit] fix processDefinitionService ut and bug

### PR DESCRIPTION
**Pull request by simon824**
fix ut and bug #4417

### CODE REVIEW

**Review by chengshiwen — CHANGES_REQUESTED** [review]
There are still some test failures

image

**Comment by simon824** [comment]
> There are still some test failures
> 
> image

This pr is just about dolphinscheduler-api module,i will fix dao module next pr.

**Comment by brave-lee** [comment]
+1

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
