### PR TITLE
[Feature] Optimizing data source centers

### PR DESCRIPTION
**Pull request by labbomb**
## Purpose of the pull request
Add data source type page

## Brief change log

- Added a dialog box for selecting the data source type
- Delete the original data source type drop-down selection

image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by songjianet — DISMISSED** [review]
LGTM

**Review by devosend — DISMISSED** [review]
LGTM

**Comment by caishunfeng** [comment]
@labbomb Please add some pr description, thanks~

**Comment by labbomb** [comment]
> @labbomb Please add some pr description, thanks~

down

**Review by devosend — APPROVED** [review]
LGTM

**Review by Amy0104 — APPROVED** [review]
The front end part LGTM.

**Pull request merged**
