### PR TITLE
[Improvement][Master] Add master explicit overload control

### LINKED ISSUE #16032: [Improvement][Master] Add master explicit overload control like worker
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now master/worker are all based on cpu/memory control in protection. see https://github.com/apache/dolphinscheduler/blob/5463d0255a71212668606588c10189c2fb0185d2/dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/BaseServerLoadProtection.java#L38
When deployed in k8s, it will get cpu/memory from pod node instead of pod JVM.
Add a explicit overload control like worker.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pegasas**
## Purpose of the pull request

resolve: https://github.com/apache/dolphinscheduler/issues/16032

## Brief change log

Now master/worker are all based on cpu/memory control in protection. see https://github.com/apache/dolphinscheduler/blob/5463d0255a71212668606588c10189c2fb0185d2/dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/BaseServerLoadProtection.java#L38
When deployed in k8s, it will get cpu/memory from pod node instead of pod JVM.
Add a explicit overload control like worker.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
We shouldn't add control here, once a workflow is be loaded means it has get all resource.

**Comment by pegasas** [comment]
> We shouldn't add control here, once a workflow is be loaded means it has get all resource.

https://github.com/apache/dolphinscheduler/blob/5463d0255a71212668606588c10189c2fb0185d2/dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutorThreadPool.java#L55-L66 
I saw worker control workload like this.

**Comment by pegasas** [comment]
aligned with worker like https://github.com/apache/dolphinscheduler/pull/16027/files

**Comment by pegasas** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity for 120 days. It will be closed in 7 days if no further activity occurs.

remove

**Pull request closed without merging**
