### PR TITLE
[community] Add version selection for issue bug selection

### LINKED ISSUE #6620: [Feature][community] Add version selection button for our bug template
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I find out we do not have version selection bottom in our bug report template. It will save maintainer time to have version selection, unless their have to ask reporter, such as https://github.com/apache/dolphinscheduler/issues/6613#issuecomment-952944539

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
closes: #6620

Add version selection when bug issue create

image

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @kezhenxu94 @CalvinKirs @lenboo .I have test in my fork and it work, you could try in https://github.com/zhongjiajie/dolphinscheduler/issues/new/choose

**Comment by kezhenxu94** [comment]
LGTM

**Review by CalvinKirs — APPROVED** [review]
Good job

**Comment by zhongjiajie** [comment]
Thanks 🎉

**Pull request merged**
