### PR TITLE
[python] Add config mechanism and cli subcommand config

### LINKED ISSUE #8344: [Feature][python] Support read configuration in env variable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After https://github.com/apache/dolphinscheduler/issues/8249 is merged, our cli could read config in local file, but in some case, user prefer to set config to env variable, so we should also support read config in env variable

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Add configuration.py mechanism for more easy change config
  and move some configs to it. It mechanism including
  configuration.py module and default_config.yaml file
* Add `config` for cli subcommand allow users initialize, get,
  set configs

close: #8344

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @devosend @jieguangzhou thanks

**Comment by devosend** [comment]
LGTM

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks

**Comment by zhongjiajie** [comment]
This PR target to the wrong issue, is should close issue #8249 instead of https://github.com/apache/dolphinscheduler/issues/8344

**Pull request merged**
