### PR TITLE
[Improvement][Flink] Change Flink command into FLINK_HOME

### LINKED ISSUE #16003: [Improvement][Flink] Change Flink command into FLINK_HOME
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

configure flink into ${FLINK_HOME}/bin/flink to make ds env configration work.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pegasas**
## Purpose of the pull request

fix: https://github.com/apache/dolphinscheduler/issues/16003

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by Radeity — DISMISSED** [review]

**Comment by Radeity** [comment]
Hi @pegasas, please fix UT.

**Comment by pegasas** [comment]
> Hi @pegasas, please fix UT.

Thanks, Done.
image

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by Radeity — DISMISSED** [review]
LGTM

**Comment by Radeity** [comment]
Please run `mvn spotless:apply` @pegasas

**Comment by pegasas** [comment]
> Please run `mvn spotless:apply` @pegasas

Weired, 
it seems my change has not been posted. 
Thanks
image

**Review by SbloodyS — COMMENTED** [review]
Please fix UT. @pegasas

**Review by rickchengx — DISMISSED** [review]
LGTM, please fix the UT

**Comment by pegasas** [comment]
> LGTM, please fix the UT

image
image

Sorry I missed test in `flink-stream`.
Done and pass spotless check on my local machine.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by rickchengx — APPROVED** [review]
LGTM

**Pull request merged**
