### PR TITLE
[python] Make the logs look better

### LINKED ISSUE #8258: [Feature][python] Custom log for meanful an easier log formatter
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

ATT, for now we just use logging and it should be confgire each file we want to add log, maybe we should add a custom logger to do it

maybe we could just add 

```py
log = logging.getLogger(__name__)
```

in each place wo call `logging`

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jieguangzhou**
Make the logs look better

* Change logging.warning to logger.warning
* Add testing for logging about task code already in process definition

close: #8258

### CODE REVIEW

**Comment by jieguangzhou** [comment]
PTAL @zhongjiajie thanks

**Comment by zhongjiajie** [comment]
Hi @jieguangzhou, it seem CI lint failed. you could run and check it in your local env by `pre-commit`, which your could see in https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-python/pydolphinscheduler/DEVELOP.md#code-style

**Comment by jieguangzhou** [comment]
> Hi @jieguangzhou, it seem CI lint failed. you could run and check it in your local env by `pre-commit`, which your could see in https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-python/pydolphinscheduler/DEVELOP.md#code-style


I've fixed it，PTAL @zhongjiajie thanks

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Comment by zhongjiajie** [comment]
Thanks ~

**Comment by zhongjiajie** [comment]
BTW, good test writing!

**Pull request merged**
