### PR TITLE
[Improvement] Rename variable QUEUE_MAX_SIZE to QUEUE_INITIAL_SIZE

### LINKED ISSUE #16039: [Improvement][Master] The variables in the code are incorrect and there are ambiguity
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The variable `org.apache.dolphinscheduler.service.queue.StandByTaskInstancePriorityQueue#QUEUE_MAX_SIZE` in the code needs to be changed to `QUEUE_INITIAL_SIZE`, because the meaning of this variable is the initial capacity of the queue, not the maximum capacity.  The `java.util.PriorityQueue`is an unbounded queue.
image

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shilei-ly**
## Purpose of the pull request
fix #16039  Modify the name of the variable, reduce the ambiguity

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
It's better to remove the initialize size, most workflow doesn't have 3000 tasks.

**Comment by shilei-ly** [comment]
> It's better to remove the initialize size, most workflow doesn't have 3000 tasks.

Sure，3000 is too big。Now I have removed the initial capacity

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by rickchengx — COMMENTED** [review]
LGTM, @alei1206  please  run 'mvn spotless:apply' to fix the code style

**Comment by shilei-ly** [comment]
> LGTM, @alei1206 please run 'mvn spotless:apply' to fix the code style

@rickchengx  Thank you for reminding. Code has been submitted again

**Review by rickchengx — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Pull request merged**
