### PR TITLE
[Feature-7451][Worker]remove date+1 when the data is supplemented

### LINKED ISSUE #7451: [Improvement][Worker] Remove '+1' (day) in the date of the complement data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When the data is supplemented, the date is always +1.
This often misleads users.
So I think we should remove this.

### Use case

The date is always the same as user selected in ui when the data is supplemented.

### Related issues

#5979

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

close #7451 

## Brief change log

remove date+1 when the data is supplemented.

### CODE REVIEW

**Review by lenboo — CHANGES_REQUESTED** [review]
Suppose today is December 18, and the timing time is 01:00 on December 18. 
The business data of yesterday executed in the task script should be December 17.

Therefore, if we remove this + 1 and make up the number on December 17, you will make up the data on December 16.

**Comment by SbloodyS** [comment]
The dates of the process instance and the actual complement are inconsistent. After the complement is selected, the date of the selected complement is displayed in the process instance instead of the actual date.So that we should remove date+1 when the data is supplemented.@lenboo

**Comment by lenboo** [comment]
> The dates of the process instance and the actual complement are inconsistent. After the complement is selected, the date of the selected complement is displayed in the process instance instead of the actual date.So that we should remove date+1 when the data is supplemented.@lenboo

yes, you are right! well done!

**Review by lenboo — APPROVED** [review]
+1

**Pull request merged**
