### PR TITLE
[Feature][PyDolphinScheduler] Add Sagemaker YAML example define in pyds

### LINKED ISSUE #11921: [Feature][PyDolphinScheduler] Support SageMaker task in pyds
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

part of https://github.com/apache/dolphinscheduler/issues/11906

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jieguangzhou**
## Purpose of the pull request

close: #11921

## Brief change log

- [x] add YAML example
- [x] Add the document

```yaml
#Define the workflow
workflow:
  name: "Sagemaker"
  release_state: "offline"

# Define the tasks under the process
tasks:
  - name: sagemaker
    task_type: Sagemaker
    sagemaker_request_json: $FILE{"example_sagemaker_params.json"}
```

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

### CODE REVIEW

**Comment by jieguangzhou** [comment]
@zhongjiajie PTAL, thanks

**Review by zhongjiajie — DISMISSED** [review]
LGTM overall

**Comment by zhongjiajie** [comment]
waiting for CI

**Comment by jieguangzhou** [comment]
@zhongjiajie PTAL, thanks

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
