### PR TITLE
[Bug-15215][Api] non-admin should not modify tenantId and queue

### LINKED ISSUE #15215: [Bug] [API] Users are not allowed to modify the default tenant and queue through the update API
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Users can modify the default tenant and queue through the update api. I think this should not be allowed because it cannot be modified through the UI. This should be consistent.

### What you expected to happen

Users are not allowed to modify the default tenant and queue through the update API

### How to reproduce

https://lists.apache.org/thread/89tkm3lmqlzbtm86kx3xnk8cc1smfm83

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhanqian0609**
## Purpose of the pull request

fix: #15215

## Brief change log

Users are not allowed to modify the default tenant and queue through the update API

### CODE REVIEW

**Review by brave-lee — DISMISSED** [review]
+1

**Comment by zhongjiajie** [comment]
@zhanqian-1993 could you run command `./mvnw spotless:check` to format the code?

**Comment by zhanqian0609** [comment]
Hi @zhongjiajie , thanks for your solution, it works.
But now I've another problem that "milestone-label-check" is always fail, I've no idea how to do. I've tried to push another commit that comment content contains "bug" and "#PR-ID" label, It seem doesn't work.(as a freshman, sorry for bothering you with the simple question)

**Review by zhongjiajie — APPROVED** [review]
👍 thanks for you contribution, I add label to pass CI process

**Pull request merged**
